### PR TITLE
HDDS-8816. Removed duplicate declaration of mockito-core in rocksdb-checkpoint-differ

### PR DESCRIPTION
**Pull request by hemantk-12**
## What changes were proposed in this pull request?
Removed duplicate declaration of `mockito-core` in `rocksdb-checkpoint-differ`

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-8816

### CODE REVIEW

**Review by ayushtkn — APPROVED** [review]
Have approved the run.

If the build comes clean then changes LGTM

**Comment by adoroszlai** [comment]
Thanks @ayushtkn for the review.  `NoClassDefFoundError` also started happening on `master`, independently from this PR:

```
Tests run: 12, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 2.868 s <<< FAILURE! - in org.apache.ozone.rocksdb.util.TestManagedSstFileReader
Error:  org.apache.ozone.rocksdb.util.TestManagedSstFileReader.testGetKeyStreamWithTombstone(int)[2]  Time elapsed: 0.036 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/eclipse/jetty/io/RuntimeIOException
```

https://github.com/apache/ozone/actions/runs/5250198253/jobs/9483885952#step:6:942

However, we should postpone merging this until `master` is in clean state.

**Review by adoroszlai — APPROVED** [review]
Thanks @hemantk-12 for the fix.

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by ayushtkn** [comment]
Thanx @hemantk-12 for the contribution & @adoroszlai for the review!!!

**Comment by adoroszlai** [comment]
Thanks @ayushtkn for reviewing and merging it.

**Pull request merged**
