### PR TITLE
HDDS-9531. Prepare requires admin user rights.

### PR DESCRIPTION
**Pull request by z-bb**
## What changes were proposed in this pull request?

prepare requires an administrator account to be executed

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-9531

### CODE REVIEW

**Comment by adoroszlai** [comment]
Thanks @z-bb for the patch.

Please check [compile error](https://github.com/z-bb/ozone/actions/runs/6638240586/job/18034198778#step:6:2096) (seems to be missing import).

**Comment by z-bb** [comment]
> Thanks @z-bb for the patch.
> 
> Please check [compile error](https://github.com/z-bb/ozone/actions/runs/6638240586/job/18034198778#step:6:2096) (seems to be missing import).

okey， I have fixed this

**Comment by errose28** [comment]
@z-bb Prepare should already be restricted to administrators, but please test to verify. We do this in in [`OzoneManagerStateMachine#preAppendTransaction`](https://github.com/apache/ozone/blob/84fb0b442dcbb8e3e242ac5b43dc769cc087657a/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java#L288) because that is where prepare first takes effect to block incoming write requests. I see this isn't clear from the current code, so if you want to update this patch with a comment explaining this instead that may be helpful.

**Comment by z-bb** [comment]
> @z-bb Prepare should already be restricted to administrators, but please test to verify. We do this in in [`OzoneManagerStateMachine#preAppendTransaction`](https://github.com/apache/ozone/blob/84fb0b442dcbb8e3e242ac5b43dc769cc087657a/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java#L288) because that is where prepare first takes effect to block incoming write requests. I see this isn't clear from the current code, so if you want to update this patch with a comment explaining this instead that may be helpful.

Thanks review, I have some question, whether prepare can be executed in non-high-availability mode. If it can be executed, OzoneManagerStateMachine#preAppendTransaction will not be executed, and admin will not be checked.
If prepare cannot be executed in non-ha mode, do you need to judge isRatisEnabled? If it is true, an exception will be thrown. Otherwise, the following problems will occur.
https://issues.apache.org/jira/browse/HDDS-9532

**Comment by errose28** [comment]
We don't need prepare in non-HA (1 Ratis enabled OM), or non-Ratis (1 non-Ratis enabled OM). The 1 OM and 3 OM Ratis cases should work the same if prepare is run though. For the non-Ratis case, I think we can fix it in the Jira you linked to just make it a no-op. I have commented on that Jira.

**Comment by adoroszlai** [comment]
@errose28 @z-bb what's the next step for this PR?  Based on the last two comments, this could be closed in favor of HDDS-9532, but #5532 (PR for that task) was closed.

**Comment by z-bb** [comment]
> @errose28 @z-bb what's the next step for this PR? Based on the last two comments, this could be closed in favor of [HDDS-9532](https://issues.apache.org/jira/browse/HDDS-9532), but #5532 (PR for that task) was closed.

Sorry, I will close this and HDDS-9532 will reopen

**Pull request closed without merging**
