### PR TITLE
HDDS-7964. Enable ratis pre-vote in Ozone by default.

### PR DESCRIPTION
**Pull request by ChenSammi**
https://issues.apache.org/jira/browse/HDDS-7964

### CODE REVIEW

**Comment by Galsza** [comment]
Looking good to me.

**Review by kaijchen — APPROVED** [review]
LGTM

**Comment by adoroszlai** [comment]
@ChenSammi Can you please include information on how the change was tested?  Also, a link in Jira to the Ratis issue where pre-vote was introduced, may be useful.

**Comment by ChenSammi** [comment]
> @ChenSammi Can you please include information on how the change was tested? Also, a link in Jira to the Ratis issue where pre-vote was introduced, may be useful.

@adoroszlai , the pre-vote feature in Ratis is RATIS-993.  Pre-vote is on by default in Ratis for a long time.  So I believe it's safe to make the change.  There is no special test for this change. It's covered by all existing Ozone and Ratis tests who create ratis group.

**Comment by ChenSammi** [comment]
Thanks @kaijchen and @adoroszlai for the code review.

**Pull request merged**
