### PR TITLE
HDDS-5652. Introduce an Integration test for ContainerBalancer.

### PR DESCRIPTION
**Pull request by siddhantsangwan**
## What changes were proposed in this pull request?

Integration test for ContainerBalancer should verify that balancing is performed in an unbalanced cluster. Also, balancing should not cause loss of container replicas. 

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5652

## How was this patch tested?

### CODE REVIEW

**Comment by siddhantsangwan** [comment]
@lokeshj1703 @JacksonYao287 please take a look at the TestContainerBalancer integration test and the related changes in MiniOzoneCluster. If the logic seems fine, I can clean this up and finalize it. We can have separate a Jira for the changes in MiniOzoneCluster. The test is currently passing.

**Comment by lokeshj1703** [comment]
@siddhantsangwan Thanks for working on this! The draft changes look good.

**Comment by JacksonYao287** [comment]
@siddhantsangwan Thanks for this work! The draft looks good. please continue this work

**Comment by adoroszlai** [comment]
@siddhantsangwan can you please resolve conflicts?

**Comment by siddhantsangwan** [comment]
Yeah @adoroszlai I'm debugging why this test always fails CI and trying to make it work.

**Pull request closed without merging**
