### PR TITLE
HDDS-11349. Add NullPointer handling when volume/bucket tables are not initialized

### PR DESCRIPTION
**Pull request by devabhishekpal**
## What changes were proposed in this pull request?
HDDS-11349. Add NullPointer handling when volume/bucket tables are not initialized

Please describe your PR in detail:
* Currently if we call the /volumes API while the Volumes table is being initialized it returns a 500 error.
* This PR will add the handling of this scenario
* After this change, if we call `/volumes` or `/buckets` endpoint before the table is completely initialized, it will return
```
{
  totalCount: 0,
  volumes: []
}
```
```
{
buckets: []
totalCount: 0
}
```

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-11349

## How was this patch tested?
It was tested using unit tests and also manually verifying the response is properly returned.
Screenshot 2024-08-21 at 12 45 17

Screenshot 2024-08-21 at 12 45 26

### CODE REVIEW

**Review by devmadhuu — APPROVED** [review]
Thanks @devabhishekpal . Changes LGTM +1

**Review by tanvipenumudy — APPROVED** [review]
Thank you @devabhishekpal for the patch, LGTM.

**Comment by tanvipenumudy** [comment]
Thank you @devabhishekpal for the patch, @devmadhuu for the review.

**Comment by devmadhuu** [comment]
@tanvipenumudy when you merge the PR, kindly also resolve the associated JIRA by mentioning the fixed version as 1.5.0 (current one)

**Comment by tanvipenumudy** [comment]
Resolved the ticket: [HDDS-11349](https://issues.apache.org/jira/browse/HDDS-11349), thank you @devmadhuu!

**Pull request merged**
