### PR TITLE
HDDS-4561: We should support suggested Ratis Server Leader in OM HA.

### PR DESCRIPTION
**Pull request by qizhu-lucas**
## What changes were proposed in this pull request?

Now the OM HA not support suggested Leader, we should support it.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-4561

## How was this patch tested?

Later will add unit test.

### CODE REVIEW

**Comment by ChenSammi** [comment]
@qizhu-lucas , thanks for this improvement.  I have following general questions,
1. Is Ratis Leader hint supported in ratis now?
2. If Ratis Leader hint is supported, what's the use case that "ozone.om.ratis.suggested.leader.enable" should be set as false?

**Comment by qizhu-lucas** [comment]
@ChenSammi  
1. Ratis Leader suggested,  supported in ratis .
2. I just added false option for test, if we need roll back to original retry OMs based.

**Comment by hanishakoneru** [comment]
We had previously removed failover to suggested leader because the nodeId is guaranteed consistency across servers and clients. For example, in server `nodeId1` could point to `OM1` and in client `nodeId1` could be pointing to `OM2`. In this scenario, when the client is told to failover to `nodeId1`, it will keep retrying the request on `OM2` and never reach the actual leader `OM1`. 
So instead of using the nodeId to failover, I think we should utilize the OM address to decide which node to failover to.

**Comment by adoroszlai** [comment]
/pending "instead of using the nodeId to failover, I think we should utilize the OM address to decide which node to failover to"

**Pull request closed without merging**
