### PR TITLE
HDDS-5502. [OFS] URI parser throws URISyntaxException when path contains space

### PR DESCRIPTION
**Pull request by smengcl**
https://issues.apache.org/jira/browse/HDDS-5502

`java.net.URI(String)` rejects parsing unescaped space characters (probably others as well) in the given String, raising `URISyntaxException` when the input path has such characters.

~~Added a custom parser to work around the limitation.~~ Use `hadoop.fs.Path` to parse the input path string (which uses URI internally but normalizes input) instead.

### CODE REVIEW

**Review by vivekratnavel — APPROVED** [review]
+1 LGTM

**Comment by vivekratnavel** [comment]
@smengcl I am unable to re-run CI workflow. Can you please re-trigger CI by pushing an empty commit?

**Comment by smengcl** [comment]
> @smengcl I am unable to re-run CI workflow. Can you please re-trigger CI by pushing an empty commit?

Yes.

It turns out there **is** a valid corner case caught by the acceptance misc test.

```
hdfs dfs -ls ofs://om/volume1/bucket1 2>&1

${output} = -ls: Can not create a Path from an empty string
```

Working on the fix.

**Review by vivekratnavel — APPROVED** [review]

**Comment by smengcl** [comment]
Thanks @vivekratnavel for reviewing and merging this patch!

**Pull request merged**
