### PR TITLE
[DO NOT MERGE] Backport some fixes from `master` to `ozone-1.4`

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Backport the following fixes from `master` to `ozone-1.4` for 1.4.1.

- HDDS-10009. Bump commons-lang3 to 3.14.0 (#5869)
- HDDS-10014. Fixed internal error on generating S3 secret via HTTP (#5887)
- HDDS-10040. Bump commons-compress to 1.25.0 (#5897)
- HDDS-10106. Bump aws-java-sdk to 1.12.632 (#5952)
- HDDS-10128. Bump commons-configuration2 to 2.8.0, commons-text to 1.11.0 (#5996)
- HDDS-10194. Upgrade Bouncy Castle to 1.77 (#6077)
- HDDS-10199. Node.js 16 actions are deprecated (#6087)
- HDDS-10200. OM may terminate due to NPE in `S3SecretValue` proto conversion (#6089)
- HDDS-10202. OmMetadataManagerImpl creates new S3Batcher for each operation (#6088)
- HDDS-10204. TypedTable.putWithBatch may leak if conversion of value throws (#6097)
- HDDS-10294. Actual client configuration ignored in ECReconstructionCoordinator (#6163)
- HDDS-10401. Bump commons-compress to 1.26.0 (#6240)
- HDDS-10406. Bump aws-java-sdk to 1.12.661 (#6249)

If approved, I'll push to the `ozone-1.4` branch directly.

## How was this patch tested?

CI:
https://github.com/adoroszlai/ozone/actions/runs/8000506651

### CODE REVIEW

**Comment by adoroszlai** [comment]
Thanks @ivandika3 for the reminder.

**Comment by adoroszlai** [comment]
@myskov please review https://github.com/apache/ozone/pull/6252/commits/1a235b6350baad8167a6429d5adcd68317a1ef63

@hemantk-12 please review https://github.com/apache/ozone/pull/6252/commits/9954d41eb72e22aa0dfb1f5e07f134fea9a28391 and https://github.com/apache/ozone/pull/6252/commits/b6a122623ebfe91a64ef2bb9d43729d0ea9fba0f

**Comment by ferhui** [comment]
Thanks for backporting it. Do we have a release plan for 1.4.1?

**Comment by adoroszlai** [comment]
@hemantk-12 this backport includes two snapshot-related patches (https://github.com/apache/ozone/pull/6252/commits/9954d41eb72e22aa0dfb1f5e07f134fea9a28391 and https://github.com/apache/ozone/pull/6252/commits/b6a122623ebfe91a64ef2bb9d43729d0ea9fba0f), would you like to take a look?

**Review by hemantk-12 — APPROVED** [review]
Thanks @adoroszlai for the back porting this fixes. And sorry for the delayed review somehow I missed it earlier.

LGTM.

**Comment by adoroszlai** [comment]
Thanks @hemantk-12, @myskov for the review.

> sorry for the delayed review somehow I missed it earlier.

No problem, I just wanted to merge this during the weekend because CI is less busy then.

> Do we have a release plan for 1.4.1?

@ferhui no plan yet, we can discuss this on dev@ mailing list.

**Pull request merged**
