### PR TITLE
HDDS-4671. Use mvn to get ozone.version instead of complex shell commands (addendum)

### PR DESCRIPTION
**Pull request by ferhui**
…ands (addendum)

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## What is the link to the Apache JIRA

(Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HDDS-XXXX. Fix a typo in YYY.)

Please replace this section with the link to the Apache JIRA)

## How was this patch tested?

(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

### CODE REVIEW

**Comment by ferhui** [comment]
@elek Sorry, i miss a sh script as @adoroszlai mentioned

**Review by adoroszlai — APPROVED** [review]
Thanks @ferhui for the addendum.  I have verified version number in the docs is correct.

**Comment by ferhui** [comment]
@adoroszlai Thanks for review!

**Comment by ferhui** [comment]
Failed UT is unrelated, i file a new jira to track it. https://issues.apache.org/jira/browse/HDDS-4694

**Comment by adoroszlai** [comment]
Thanks @ferhui for the contribution.

**Pull request merged**
