### PR TITLE
HDDS-4957. Fix flaky test TestSCMInstallSnapshotWithHA#testInstallCorruptedCheckpointFailure

### PR DESCRIPTION
**Pull request by bshashikant**
## What changes were proposed in this pull request?
The test assumes that a follower node must be behind the leader during the final validation assertions. Fix is to not start the follower server itself , so that it always lags behind the leader at any point of time.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4957

## How was this patch tested?
Fixed UT

### CODE REVIEW

**Comment by bshashikant** [comment]
@GlenGeng , can you please take a look?

**Comment by bshashikant** [comment]
Retriggering the CI check again after a clean CI run , to ensure its not flaky.

**Review by amaliujia — APPROVED** [review]
LGTM

**Comment by amaliujia** [comment]
retrigger CI test third time so ensure it is not flaky. After this time I can merge this PR.

**Comment by amaliujia** [comment]
@bshashikant thanks for this fix!

**Comment by GlenGeng** [comment]
Thanks @bshashikant for the fix, and @amaliujia for the review and verification in CI.

**Comment by adoroszlai** [comment]
FYI, it is possible to repeat a single test several times, see @elek's guide at https://cwiki.apache.org/confluence/display/HADOOP/Github+Actions+tips+and+tricks

Additionally, with JUnit 5 it's as simple as changing `@Test` to `@RepeatedTest(10)` (adjust repetitions as needed) for the flaky test case.  Fork timeout also needs to be increased.

Ran the test 2x10 times without issues:

https://github.com/adoroszlai/hadoop-ozone/runs/2080365955#step:4:3826
https://github.com/adoroszlai/hadoop-ozone/runs/2080365955#step:4:3931

Here's my change for reference:
https://github.com/adoroszlai/hadoop-ozone/commit/73bea4db8bf4826f7f31eb24d1951e853197ae22

**Pull request merged**
