### PR TITLE
HDDS-5920. [Merge rocksdb in datanode] Allow to add ColumnFamilyOptions to tables.

### PR DESCRIPTION
**Pull request by guihecheng**
## What changes were proposed in this pull request?

Allow to add ColumnFamilyOptions to tables.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5920

## How was this patch tested?

a new ut.

### CODE REVIEW

**Comment by nandakumar131** [comment]
@guihecheng can we do the S3 related changes in a separate PR?

**Comment by guihecheng** [comment]
@nandakumar131 Oh, actually I'm trying to push only the last commit, those s3 related PRs are not related to rocksdb merge.
But on the first push, I set the push target to the wrong remote branch(master), and after I switched to the right branch(HDDS-3630), there are extra commits added automatically, I think I shall close these and make new PRs, thanks~

**Comment by guihecheng** [comment]
Hi @nandakumar131 I just did a force push, and the unrelated commits are gone and I do the same for the other PRs too, thanks~

**Review by nandakumar131 — APPROVED** [review]

**Comment by nandakumar131** [comment]
Thanks @guihecheng  for the contribution.

**Pull request merged**
