### PR TITLE
HDDS-4695. Support encode and decode ArrayList and Long.

### PR DESCRIPTION
**Pull request by nandakumar131**
## What changes were proposed in this pull request?
Support encode and decode ArrayList and Long

## What is the link to the Apache JIRA
HDDS-4695

## How was this patch tested?
New unit test added

### CODE REVIEW

**Comment by runzhiwang** [comment]
@nandakumar131 LGTM.  I think this patch is almost similar to my previous pr: https://github.com/apache/ozone/pull/1797.

**Comment by GlenGeng** [comment]
Thanks for the work! The support of Long is a surprise.

**Review by amaliujia — COMMENTED** [review]
+1 LGTM

**Comment by GlenGeng** [comment]
@runzhiwang  Please merge it and rebase the delete block log PR with latest HDDS-2823. Thanks!

**Pull request merged**
