### PR TITLE
HDDS-4752. TestOzoneFileSystem is not picking the configured 'Parameters'

### PR DESCRIPTION
**Pull request by rakeshadr**
## What changes were proposed in this pull request?
TestOzoneFileSystem all 4 parameterized iterations are running always with enabledFileSystemPaths=false and omRatisEnabled=false, which is basically due to the wrong init function using @BeforeClass.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4752

## How was this patch tested?

Modified TestOzoneFileSystem and verified using this test. 

With this changes, `TestOzoneFileSystem#testTrash` is expected to fail as this case was not running earlier in the build. HDDS-4751 issue is raised to handle the TestOzoneFileSystem#testTrash failure.

### CODE REVIEW

**Comment by rakeshadr** [comment]
Like I mentioned in the description, with this changes it is expected that TestOzoneFileSystem#testTrash will be failed as this case(`enabledFileSystemPaths=true and enableOMRatis=false`) was not running earlier in the build. HDDS-4751 issue is raised to handle the TestOzoneFileSystem#testTrash failure.

Please help me to review the changes, thanks!

**Review by ayushtkn — APPROVED** [review]
Thanx @rakeshadr for the fix, changes LGTM. I observed same problem in `TestRootedOzoneFileSystem` also sometime back while chasing an issue with delete. May be we can fix that too similarly, if it exists/still exists :-)

Should hold merging this till the test gets fixed, or disable for time being else other folks might get blocked.

**Comment by mukul1987** [comment]
Thanks for the PR @rakeshadr , can you please rebase the PR, as @sadanand48 had recently pushed in a fix for this issue.

**Comment by rakeshadr** [comment]
> Thanks for the PR @rakeshadr , can you please rebase the PR, as @sadanand48 had recently pushed in a fix for this issue.

Thanks @ayushtkn and @mukul1987 for the reviews. I've rebased the PR to latest master code base and kick started the build.

**Comment by rakeshadr** [comment]
> Thanx @rakeshadr for the fix, changes LGTM. I observed same problem in `TestRootedOzoneFileSystem` also sometime back while chasing an issue with delete. May be we can fix that too similarly, if it exists/still exists :-)
> 
> Should hold merging this till the test gets fixed, or disable for time being else other folks might get blocked.

@ayushtkn 
I've modified `TestRootedOzoneFileSystem`, but I could see few test case failures. I feel to raise separate jira to analyse that failures and fix it. Does that make sense to you?

**Comment by ayushtkn** [comment]
Thanx @rakeshadr, Sure. We can go ahead here and track that separately
The build is green now. 
+1

**Comment by rakeshadr** [comment]
Thanks @mukul1987 , @ayushtkn for the reviews. I've merged it. Will raise followup jira to track TestRootedOzoneFileSystem changes.

**Pull request merged**
