### PR TITLE
HDDS-4424. Update README with information how to report security issues

### PR DESCRIPTION
**Pull request by elek**
## What changes were proposed in this pull request?

security@ozone.apache.org is created, we can add tn to the README.md and we can create the SECURITY.md file (Github naming convention)

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4424

## How was this patch tested?

:eyes:

### CODE REVIEW

**Comment by elek** [comment]
GIthub suggests clarifying which versions are supported. Can we say that only 1.0 is supported? (cc @arp7 @ChenSammi)

**Comment by dineshchitlangia** [comment]
@elek I think it is safe to say only 1.0 is supported (by supported I mean for production). 
Let's wait to hear from others.

**Comment by elek** [comment]
Discussed on last community meeting and everybody was happy with marking only 1.0 as security-supported. Will rebase this patch soon

**Review by arp7 — APPROVED** [review]

**Comment by elek** [comment]
Merging it now. Thanks the review @arp7

**Pull request merged**
