### PR TITLE
HDDS-7117. Consider reading chunk files using MappedByteBuffer.

### PR DESCRIPTION
**Pull request by szetszwo**
## What changes were proposed in this pull request?

From @jojochuang 
> Running Impala TPC-DS which stresses Ozone DN read path.
> BufferUtils#assignByteBuffers stands out as one of the offender.
> We can experiment with MappedByteBuffer and see if it makes performance better.

## What is the link to the Apache JIRA

HDDS-7117

## How was this patch tested?

New unit test.

### CODE REVIEW

**Review by jojochuang — COMMENTED** [review]
Thanks @szetszwo for the PR!
The PR makes sense to me. I'll need to verify the performance difference in the cluster.

**Review by jojochuang — COMMENTED** [review]
TODO: I hope this patch can better leverage OS cache, get rid of the temporary heap buffer. Will verify and benchmark in a real cluster.

**Comment by szetszwo** [comment]
@jojochuang , thanks a lot for testing this!

**Comment by jojochuang** [comment]
Please hold the merge as I am still doing a few more perf benchmarks. Thanks.

**Comment by szetszwo** [comment]
@jojochuang , sure.  Will wait for your test results.  Thanks a lot!

**Comment by swamirishi** [comment]
@jojochuang Can this be merged? Are the test results out?

**Comment by ChenSammi** [comment]
@szetszwo , thanks for working on this. Do you have time to do a patch rebase? 

I did a micro performance test, comparing the on heap buffer, off heap buffer and memory mapped buffer, here is the result.
image

By default, DN will use 1MB(bytes.per.checksum) as the buffer size. So using memory mapped buffer can increase at least micro level performance a lot.

**Comment by ChenSammi** [comment]
@szetszwo , there is another your PR #3730 which aims to improve the read performance too.  I didn't have time to closely look at #3730 yet. Not sure is there overlap between this one and #3730?

**Comment by szetszwo** [comment]
@ChenSammi , this PR is to change reading the local files using java `MappedByteBuffer` while https://github.com/apache/ozone/pull/3730 uses Netty `ChunkedNioFile`.

**Review by ChenSammi — APPROVED** [review]
The last patch LGTM +1.

**Pull request merged**
