### PR TITLE
HDDS-8580. Reduce memory usage in ContainerKeyMapperTask#reprocess - addendum: fix compile error

### PR DESCRIPTION
**Pull request by ivandika3**
## What changes were proposed in this pull request?

This is a patch for [HDDS-8580](https://issues.apache.org/jira/browse/HDDS-8580) with addition to resolve compile issue with [HDDS-8733](https://issues.apache.org/jira/browse/HDDS-8733)

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8580

## How was this patch tested?

CI tests.

### CODE REVIEW

**Comment by ivandika3** [comment]
Hi @dombizita @szetszwo, there was a compilation issue due to conflict with HDDS-8733. Could you help to resolve the conflict? Sorry for the inconvenience.

**Review by dombizita — APPROVED** [review]
thanks for the quick fix @ivandika3! +1, pending CI

**Review by adoroszlai — APPROVED** [review]
Thanks @ivandika3 for the fix.

**Comment by szetszwo** [comment]
@ivandika3 , thanks a lot for fixing this!

**Pull request merged**
