### PR TITLE
HDDS-4530. Add authorization check for SCM

### PR DESCRIPTION
**Pull request by wycccccc**
## What changes were proposed in this pull request?

Add authorization check about stopReplicationManager, forceExitSafeMode, startReplicationManager, deactivatePipeline, closePipeline in `SCMClientProtocolServer` .

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4530

Please replace this section with the link to the Apache JIRA)

## How was this patch tested?

Add unit test.

### CODE REVIEW

**Comment by vivekratnavel** [comment]
@wycccccc Can you please check if this integration test failure is related to this change?

```
Error:  Failures: 
Error:    TestDecommissionAndMaintenance.testContainerIsReplicatedWhenAllNodesGotoMaintenance:394 expected:<5> but was:<6>
[INFO] 
Error:  Tests run: 213, Failures: 1, Errors: 0, Skipped: 15
```

**Comment by wycccccc** [comment]
@vivekratnavel I passed this test, no failure like this.So I think the failure is not related to this change.

**Comment by elek** [comment]
> I passed this test, no failure like this.So I think the failure is not related to this change.

We prefer to commit only green builds.  If it's an intermittent test, there are two options:

 1. Add an empty commit and have a green build
 2. Disable the test with a simple commit on master and create a JIRA with the log which proves the intermittency.

Let me re-trigger this build...

**Review by elek — APPROVED** [review]
+1, thanks the patch @wycccccc 

LGTM

Might be interesting to create unit (or acceptance tests?) for it in the future. But it can be a more complex task, can do it in follow-ups.

**Comment by wycccccc** [comment]
Thax @elek review, I will try to create a jira to solve it.

**Pull request merged**
