### PR TITLE
HDDS-10782. Replace GSON with Jackson in EventQueue

### PR DESCRIPTION
**Pull request by weimingdiit**
## What changes were proposed in this pull request?

Replace GSON with Jackson in EventQueue, which converts protobuf messages to JSON when trace level logging is enabled.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-10782

## How was this patch tested?
unit tests, manual tests

### CODE REVIEW

**Comment by weimingdiit** [comment]
@adoroszlai  Could you review this pr?

**Comment by adoroszlai** [comment]
Thanks @weimingdiit for the patch.

Getting two kinds of errors:

```
ERROR events.EventQueue: Error serializing payload: No serializer found for class com.google.protobuf.UnknownFieldSet$Parser and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.apache.hadoop.hdds.scm.server.SCMDatanodeHeartbeatDispatcher$ContainerReportFromDatanode["report"]->org.apache.hadoop.hdds.protocol.proto.StorageContainerDatanodeProtocolProtos$ContainerReportsProto["unknownFields"]->com.google.protobuf.UnknownFieldSet["parserForType"])
```

Solved this by setting:

```
.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS)
```

on `TRACING_SERIALIZER`.

```
ERROR events.EventQueue: Error serializing payload: Direct self-reference leading to cycle (through reference chain: org.apache.hadoop.hdds.scm.server.SCMDatanodeHeartbeatDispatcher$PipelineReportFromDatanode["report"]->org.apache.hadoop.hdds.protocol.proto.StorageContainerDatanodeProtocolProtos$PipelineReportsProto["unknownFields"]->com.google.protobuf.UnknownFieldSet["defaultInstanceForType"])
```

I haven't found a quick solution for this.

Please also see https://github.com/apache/ozone/pull/6500#discussion_r1556974844 for previous attempt to replace GSON in `EventQueue`.

**Comment by weimingdiit** [comment]
@adoroszlai Thanks for your comment, I will try to solve the second question

**Comment by adoroszlai** [comment]
@weimingdiit as far as I see "Direct self-reference leading to cycle" is still a problem, so I converted the PR to draft to indicate this is still WIP.

Also, please try to avoid force-push when updating the PR.  Here are some great articles that explain why:

https://developers.mattermost.com/blog/submitting-great-prs/#4-avoid-force-pushing
https://www.freecodecamp.org/news/optimize-pull-requests-for-reviewer-happiness#request-a-review

**Comment by weimingdiit** [comment]
> @weimingdiit as far as I see "Direct self-reference leading to cycle" is still a problem, so I converted the PR to draft to indicate this is still WIP.
> 
> Also, please try to avoid force-push when updating the PR. Here are some great articles that explain why:
> 
> https://developers.mattermost.com/blog/submitting-great-prs/#4-avoid-force-pushing https://www.freecodecamp.org/news/optimize-pull-requests-for-reviewer-happiness#request-a-review

@adoroszlai Thanks for your reminder, I will pay attention to this.

**Pull request closed without merging**
