### PR TITLE
HDDS-7301. Cleanup of org.apache.hadoop.ozone.OmUtils

### PR DESCRIPTION
**Pull request by myskov**
## What changes were proposed in this pull request?

Removed dead code and code smells reported by Sonar.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7301

## How was this patch tested?

unit tests

### CODE REVIEW

**Review by kaijchen — COMMENTED** [review]
The change is correct, however, some public static methods such as `getOmRpcPort` might be useful in the future (they are used only once and the patch has inlined them). What do you think @adoroszlai?

**Review by adoroszlai — COMMENTED** [review]
Thanks @myskov for the patch.

> some public static methods such as `getOmRpcPort` might be useful in the future (they are used only once and the patch has inlined them)

Not only that, but it is possible that user code may call these public methods.  I think it's better to deprecate them first, to be removed in some future release.

**Comment by DaveTeng0** [comment]
> Thanks @myskov for the patch.
> 
> > some public static methods such as `getOmRpcPort` might be useful in the future (they are used only once and the patch has inlined them)
> 
> Not only that, but it is possible that user code may call these public methods. I think it's better to deprecate them first, to be removed in some future release.

hey @myskov ~ would you mind marking those methods deprecated for now and creating ticket(s) for the removal in the future?

**Review by adoroszlai — APPROVED** [review]

**Comment by adoroszlai** [comment]
Thanks @myskov for the patch, @kaijchen for the review.

**Pull request merged**
