### PR TITLE
HDDS-4681. SCM webui display wrong Node counts.

### PR DESCRIPTION
**Pull request by flirmnave**
## What changes were proposed in this pull request?

Fix SCM webui Node Counts display.
The order is follow [hdds.proto#NodeState](https://github.com/apache/ozone/blob/984cf668a6f3e89dfbba659414de5749390723a6/hadoop-hdds/interface-client/src/main/proto/hdds.proto#L130) and [hdds.proto#NodeOperationalState](https://github.com/apache/ozone/blob/984cf668a6f3e89dfbba659414de5749390723a6/hadoop-hdds/interface-client/src/main/proto/hdds.proto#L136).

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4681

Please replace this section with the link to the Apache JIRA)

Test on docker-compose.
Screenshot from 2021-01-13 15-28-30

### CODE REVIEW

**Comment by smengcl** [comment]
+1 pending CI. Looks like a small missing piece in the UI as a result of the addition of [`NodeOperationalState`](https://github.com/apache/ozone/commit/92369fcfaedfee29f212b8998ef33915a249d6fd#diff-d8f3555e167ab79b883cad8cc5deae1e61bd328a72b56a7d3b85190291d742dbR136-R142). Thanks for the patch.

CC @sodonnel

**Review by smengcl — APPROVED** [review]

**Comment by lamber-ken** [comment]
+1

**Review by cku328 — APPROVED** [review]
LGTM. Thanks @flirmnave for working on this.

**Comment by smengcl** [comment]
Thanks @flirmnave for the patch. Thanks @lamber-ken @cku328 for reviewing this. Merged.

**Comment by flirmnave** [comment]
Thanks @smengcl @lamber-ken @cku328 for reviewing.

**Comment by sodonnel** [comment]
Thanks for this change - this was on the "todo list" for decommission, but I never got it - HDDS-2641. I think I can resolve that one now as a duplicate of this one.

**Comment by sodonnel** [comment]
Actually, HDDS-2641 was to show the actual nodes decommissioning and their pending replication stats, similar to how the Namenode WebUI does in HDFS. I will leave HDDS-2641 open for now as something we can add in the future. Feel free to take that one if you like, as I won't have time for it in the near future.

**Pull request merged**
