### PR TITLE
[DO NOT MERGE] Backport some fixes and compatibility commits from master to ozone-1.4 

### PR DESCRIPTION
**Pull request by xichen01**
## What changes were proposed in this pull request?

Backport the following commit from master to ozone-1.4 for 1.4.1. Including some bug fixes and Ratis upgrade and necessary dependencies.

HDDS-11333. Avoid hard-coded current version in upgrade/xcompat tests (#7089)
HDDS-10168. Add Ozone 1.4.0 to compatibility acceptance tests (#6040)
HDDS-11414. Key listing for FSO buckets fails with forward client (#7161)
HDDS-11570. Fix HDDS Docs build failure with Hugo v0.135.0 (#7337)
HDDS-11498. Improve SCM deletion efficiency. (#7249)
HDDS-11482. EC Checksum throws IllegalArgumentException because the buffer limit is negative (#7230)
HDDS-10465. Change ozone.client.bytes.per.checksum default to 16KB (#6331)
HDDS-10480. Avoid proto2 ByteString.toByteArray() calls. (#6342)
HDDS-11536. Bump macOS runner version to macos-13 (#7279)
HDDS-11504. Update Ratis to 3.1.1. (#7257)
HDDS-11472. Avoid recreating external access authorizer on OM state reload (#7238)
HDDS-11436. Minor update in Recon API handling. (#7178)
HDDS-11223. Fix iteration over ChunkBufferImplWithByteBufferList (#6999)
HDDS-11136. Some containers affected by HDDS-8129 may still be in the DELETING state incorrectly (#6967)
HDDS-10918. NPE in OM when leader transfers (#6735)
HDDS-10777. S3 Gateway error when parsing XML concurrently (#6609)
HDDS-10780. NullPointerException in watchForCommit (#6627)

## How was this patch tested?
https://github.com/xichen01/ozone/actions/runs/11445199314

### CODE REVIEW

**Comment by xichen01** [comment]
For https://issues.apache.org/jira/browse/HDDS-11414, `ListStatusLight` is disabled in ozone-1.4 due to compatibility issues discussed in https://github.com/apache/ozone/pull/7326
cc: @adoroszlai @sumitagrawl @tanvipenumudy

**Comment by xichen01** [comment]
@duongkame, @guohao-rosicky @ChenSammi @siddhantsangwan @Cyrill @ArafatKhan2198 @devabhishekpal @jojochuang @adoroszlai @szetszwo @aswinshakil @slfan1989 @scolley31 @tanvipenumudy
please check that your commits are correctly cherry-picked.

**Review by adoroszlai — APPROVED** [review]

**Review by devabhishekpal — APPROVED** [review]
Thanks for the effort @xichen01 .
My changes look good. +1

**Review by ArafatKhan2198 — APPROVED** [review]
My change look good +1

**Review by tanvipenumudy — APPROVED** [review]
> For https://issues.apache.org/jira/browse/HDDS-11414, ListStatusLight is disabled in ozone-1.4 due to compatibility issues discussed in https://github.com/apache/ozone/pull/7326

Thank you @xichen01, the changes LGTM +1

**Comment by adoroszlai** [comment]
@xichen01 can you please cherry-pick the following two commits (in this order)?

* dcdc47ec8d HDDS-10168. Add Ozone 1.4.0 to compatibility acceptance tests (#6040)
* 5b32c7dd6c HDDS-11333. Avoid hard-coded current version in upgrade/xcompat tests (#7089)

**Comment by xichen01** [comment]
https://issues.apache.org/jira/browse/HDDS-11368
@devabhishekpal @szetszwo @adoroszlai Is this need to be backport? ASF's policy on obtaining MIT licenses appears to be inconclusive.

**Comment by adoroszlai** [comment]
> https://issues.apache.org/jira/browse/HDDS-11368
> Is this need to be backport?

Let's try to include in next batch.

**Comment by adoroszlai** [comment]
Thanks @xichen01 for the backports, @ArafatKhan2198, @devabhishekpal, @tanvipenumudy for the review.

**Pull request merged**
