### PR TITLE
HDDS-117. Add convenience methods for port management in DatanodeDetails

### PR DESCRIPTION
**Pull request by ptlrs**
## What changes were proposed in this pull request?
This change adds convenience methods for port management in DatanodeDetails

Please describe your PR in detail:
* Added `newRatisPort`, `newRestPort`, `newStandalonePort` to create new ports
* Added `getRatisPort`, `getRestPort`, `getStandalonePort` to get ports
* Added `setRatisPort`, `setRestPort`, `setStandalonePort` to set ports
* Removed recursion and reduced an extra method call from getPort 
* Updated files to use the new helper methods

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-117

## How was this patch tested?
CI: https://github.com/ptlrs/ozone/actions/runs/11733186419

### CODE REVIEW

**Comment by ptlrs** [comment]
Thanks @adoroszlai. I have resolved the conflicts.

**Comment by nandakumar131** [comment]
@adoroszlai, I will take a look at this today. Thanks for the tag.
@ptlrs, thanks for resolving the conflicts.

**Review by nandakumar131 — APPROVED** [review]
+1, LGTM.

**Comment by adoroszlai** [comment]
Thanks @ptlrs for the patch, @nandakumar131 for the review.

**Pull request merged**
