### PR TITLE
[DO NOT MERGE] Backport some fixes and compatibility commits from master to ozone-1.4

### PR DESCRIPTION
**Pull request by xichen01**
## What changes were proposed in this pull request?

HDDS-9503. Migrate simple misc. integration tests to JUnit5 (#5854)
HDDS-11608. Client should not retry invalid protobuf request (#7354)
HDDS-11132. Revert client version bump done as part of HDDS-10983 (#7348)
HDDS-11368. Remove dependency on Babel in Vite (#7119)
HDDS-11635. Memory leak when using Ozone FS via Hadoop FileContext API (#7382)

## How was this patch tested?

https://github.com/xichen01/ozone/actions/runs/11534716378

### CODE REVIEW

**Comment by xichen01** [comment]
@swamirishi, @hanishakoneru
please check that your commits are correctly cherry-picked.

**Comment by xichen01** [comment]
After this PR merge, so that the necessary PRs have been merged to ozone-1.4, So I will release ozone-1.4.1-RC2

**Comment by xichen01** [comment]
Backport HDDS-9503 make the Junit5 Annotation `Flaky` added in HDDS-8900 take effect, current branch  `Flaky` doesn't work on junit4.

**Comment by swamirishi** [comment]
thanks for the patch @xichen01 for HDDS-11132

**Comment by adoroszlai** [comment]
@devabhishekpal please review 07cb23f1efd6a90c108fcde009784c81bb2d42aa (backport of HDDS-11368)

**Comment by xichen01** [comment]
@adoroszlai @devabhishekpal Any review suggestions? If not, I will merge this PR and release ozone-1.4-rc2

**Review by devabhishekpal — APPROVED** [review]
This looks good to me, thanks for the backport @xichen01

**Pull request merged**
