### PR TITLE
HDDS-11150. Recon Overview page crashes due to failed API Calls

### PR DESCRIPTION
**Pull request by devabhishekpal**
## What changes were proposed in this pull request?

HDDS-11150. Shift Axios.all to Promise.allSettled and add fallback for error in failed requests

Please describe your PR in detail:

- Currently Axios.all() uses Promise.all() in the background, but this causes all further promises to reject if one request is rejected
- So we have migrated to Promise.allSettled() which allows to wait for all requests to complete instead of immediately rejecting
- Along with this new fallbacks have been added to allow data to be shown even if there is an error while fetching the data
- Scope of fallback scenario
   - When the API is unreachable, say because of an API timeout or the backend is not able to respond
   - When the network might go down and the call to the backend fails
   - If the API returns any error (like 500, or 404 etc.) where the data is not present

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-11150

## How was this patch tested?
Patch was tested manually
| Screenshot | Description |
|------------|-------------|
|Screenshot 2024-07-15 at 21 56 03 | Fallback when clusterState request fails |
|Screenshot 2024-07-18 at 12 35 26| Fallback when open keys summary fails |
|Screenshot 2024-07-18 at 12 35 06 | Fallback when deletePending keys summary fails |
| Screenshot 2024-07-18 at 12 36 01 | Fallback when File Size Distribution API fails |
|Screenshot 2024-07-18 at 12 35 46| Fallback when Container Size Distribution API fails |

### CODE REVIEW

**Comment by devabhishekpal** [comment]
@ArafatKhan2198 @devmadhuu @smitajoshi12 Could you please take a look?
Also please do suggest if you have any alternatives to the `??` that I am displaying when the clusterState endpoint fails

**Comment by devmadhuu** [comment]
@devabhishekpal Can you pls define clear scope and clear boundaries this PR will cover ?

**Comment by dombizita** [comment]
> @ArafatKhan2198 @devmadhuu @smitajoshi12 Could you please take a look? Also please do suggest if you have any alternatives to the `??` that I am displaying when the clusterState endpoint fails

I'd suggest to go with `N/A`, as that describes maybe better that we were not able to get the necessary data to display. Let me know what you think of this!

**Comment by devabhishekpal** [comment]
Message displayed when we are hovering over the data in case of fallback.
Screenshot 2024-07-15 at 22 00 55

**Comment by smitajoshi12** [comment]
@devabhishekpal 
Can we do same fall back for Open keys Summary and Pending Deleted Keys Summary for NA instead of 0.

**Comment by smitajoshi12** [comment]
@devabhishekpal 

Can we handle null check before reduce
image

**Comment by devabhishekpal** [comment]
Hi @smitajoshi12 , thanks for your review.
Addressed the issues you pointed out in the latest commit

**Comment by smitajoshi12** [comment]
@devabhishekpal 

This condition should be in orr
esp.status === 'rejected' || resp.reason.toString().includes('CanceledError')

**Comment by devabhishekpal** [comment]
Extending on the above, if we use `||` it means the error would be thrown in either if it gets rejected, or if it is cancelled.
But this is not correct, as there might be scenarios where the API might reject the Promise, but the error is not cancellation.

In that scenario we do not want to throw the error, but fallback to the default values.
We want to throw the error only when the request is rejected as the call was cancelled.

**Comment by smitajoshi12** [comment]
@ArafatKhan2198 @devmadhuu 

Can you review as this pr needs to get merged in OZONE-719.3.x as we have already completed all recent changes cherry picks for ECharts and other upstream Jiras.

**Comment by smitajoshi12** [comment]
> Extending on the above, if we use `||` it means the error would be thrown in either if it gets rejected, or if it is cancelled. But this is not correct, as there might be scenarios where the API might reject the Promise, but the error is not cancellation.
> 
> In that scenario we do not want to throw the error, but fallback to the default values. We want to throw the error only when the request is rejected as the call was cancelled.

If one api fails because Internal server error or any other issue response is blank but UI looks this way It should catch error or throw error

image

**Comment by devabhishekpal** [comment]
Thanks @smitajoshi12 for pointing this out.
Addressed this in the latest PR.

In case the request is cancelled, we go to catch.
Else we initialize with the default values and display a popup to notify the user something is going wrong.

Can you take another look?
Thanks

**Comment by smitajoshi12** [comment]
It looks good to me

**Review by smitajoshi12 — APPROVED** [review]
All changes looks good to me

**Comment by ArafatKhan2198** [comment]
Thanks for the patch @devabhishekpal and thanks for the review @smitajoshi12

**Pull request merged**
