### PR TITLE
HDDS-4462. Add --frozen-lockfile to pnpm install to prevent ozone-recon-web/pnpm-lock.yaml from being updated automatically

### PR DESCRIPTION
**Pull request by smengcl**
Trivial fix.
~~Update `ozone-recon-web/pnpm-lock.yaml` as Git is reporting not clean after a maven build.~~

Add --frozen-lockfile to pnpm install to prevent ozone-recon-web/pnpm-lock.yaml from being updated automatically.

### CODE REVIEW

**Comment by vivekratnavel** [comment]
This shouldn't be happening. I am curious to know which maven build command did you use?

**Comment by smengcl** [comment]
> This shouldn't be happening. I am curious to know which maven build command did you use?

`mvn clean install -DskipTests -Dmaven.javadoc.skip`

I found this issue on both my Mac and in a Ubuntu VM.

**Comment by vivekratnavel** [comment]
Thanks, @smengcl! I am unable to reproduce this lock file update on my machine.

Can you please try `<arguments>pnpm install --frozen-lockfile</arguments>` in https://github.com/apache/ozone/blob/master/hadoop-ozone/recon/pom.xml#L121 ? You can then run the same mvn command inside `hadoop-ozone/recon` directory to build only recon and quickly test. Before the test, don't forget to checkout ozone-recon-web/pnpm-lock.yaml if there are any local changes. This time it should not update the lock file and your git tree should be clean. Please let me know the results. Thanks!

**Comment by smengcl** [comment]
> Thanks, @smengcl! I am unable to reproduce this lock file update on my machine.
> 
> Can you please try `<arguments>pnpm install --frozen-lockfile</arguments>` in https://github.com/apache/ozone/blob/master/hadoop-ozone/recon/pom.xml#L121 ? You can then run the same mvn command inside `hadoop-ozone/recon` directory to build only recon and quickly test. Before the test, don't forget to checkout ozone-recon-web/pnpm-lock.yaml if there are any local changes. This time it should not update the lock file and your git tree should be clean. Please let me know the results. Thanks!

I tested that adding `--frozen-lockfile` to the argument works. `ozone-recon-web/pnpm-lock.yaml` is clean after the same mvn command.

I will change this jira to adding `--frozen-lockfile` instead.

**Comment by vivekratnavel** [comment]
Thanks @smengcl! Patch looks good to me. +1

**Review by vivekratnavel — APPROVED** [review]

**Pull request merged**
