### PR TITLE
HDDS-5616. Document how to run ozone sample cluster with FSO-enabled

### PR DESCRIPTION
**Pull request by yuangu002**
## What changes were proposed in this pull request?

Add a shell script to automate docker-up with FSO enabled.
Update README instructions.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5616

## How was this patch tested?
Tested on clusters.

cc @avijayanhwx @smengcl

### CODE REVIEW

**Review by adoroszlai — CHANGES_REQUESTED** [review]
Thanks @yuangu002 for thinking about improving developer experience.

I don't think we need a separate script for such logic.  It definitely does not belong to the root directory and README, since it is specific to the `ozone` compose environment.

Instead of adding the new script, we can define these variables in existing `run.sh` for documentation purpose.  We may also consider enabling FSO as default in `run.sh`.

https://github.com/apache/ozone/blob/master/hadoop-ozone/dist/src/main/compose/ozone/run.sh

**Comment by yuangu002** [comment]
> Thanks @yuangu002 for thinking about improving developer experience.
> 
> I don't think we need a separate script for such logic. It definitely does not belong to the root directory and README, since it is specific to the `ozone` compose environment.
> 
> Instead of adding the new script, we can define these variables in existing `run.sh` for documentation purpose. We may also consider enabling FSO as default in `run.sh`.
> 
> https://github.com/apache/ozone/blob/master/hadoop-ozone/dist/src/main/compose/ozone/run.sh

Thanks @adoroszlai for taking a look. I have reverted back all root directory level changes. Could you take another look?

**Review by adoroszlai — APPROVED** [review]
Thanks @yuangu002 for updating the patch.

**Comment by avijayanhwx** [comment]
Thanks for the patch @yuangu002, and the review @adoroszlai.

**Pull request merged**
