### PR TITLE
HDDS-6982. EC: Attempt to cleanup the RECOVERING container when reconstruction failed at coordinator.

### PR DESCRIPTION
**Pull request by umamaheswararao**
## What changes were proposed in this pull request?

Coordinator created recovering containers would be deleted if there is failure.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-6982

## How was this patch tested?

Will be adding tests.

### CODE REVIEW

**Review by JacksonYao287 — COMMENTED** [review]
thanks @umamaheswararao for the patch , the changes overall looks good.
so now, we have to ways to cleanup stale recovering containers.
1 if coordinator encounters any exception when reconstructing the EC container group, it will try to delete the all the recovering containers. this is just the work of this patch.
2 when datanode startup, it will scan all the containers and delete the recovering ones. this will be done in [HDDS-6978](https://issues.apache.org/jira/browse/HDDS-6978)

so , a question, what if the coordinator crashes when trying to delete the recovering containers in other target datanode and those target datanode never restarts? there will be no trigger to complete this task.

should we have some other approaches to make sure that those recovering container will be deleted ultimately?  maybe we can assign this work to containerDataScanner, then another question comes, for a certain recovering container, how the datanode itself know this container is being written by coordinator, or just a stale recovering container with a lost coordinator.

**Comment by umamaheswararao** [comment]
HI @JacksonYao287, Thank you for the comments. 
Yeah, we have discussed about this point. I have just filed a JIRA for the same https://issues.apache.org/jira/browse/HDDS-6987 (please see the description in this JIRA).

I think we can go with some longer timeout. Let's 20mins? If reconstruction does not happen in 20mins, I would consider that reconstruction tasks is facing some really slow issues or intermittently failed. Let't keep that as dev tunable param and as we learn the time needed, we may update it accordingly. But Let's not expose that to users to avoid some too much internal configs.

**Review by JacksonYao287 — APPROVED** [review]
LGTM +1！

**Comment by umamaheswararao** [comment]
Oops, I had a test for this one but forgot to add in this PR. Anyway, since we got +1, I moved ahead to commit and filed the followup for adding the test. HDDS-6989

Thanks a lot @JacksonYao287 for the reviews!

**Comment by JacksonYao287** [comment]
thanks @umamaheswararao for the review!

**Pull request merged**
