### PR TITLE
HDDS-5774. Fix missing parameter slot for exception on container close.

### PR DESCRIPTION
**Pull request by guihecheng**
## What changes were proposed in this pull request?

Fix missing parameter slot for exception on container close.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5774

## How was this patch tested?

no need.

### CODE REVIEW

**Review by jojochuang — APPROVED** [review]

**Comment by jojochuang** [comment]
+1 pending precommit job.

**Review by JacksonYao287 — APPROVED** [review]
LGTM +1

**Review by adoroszlai — CHANGES_REQUESTED** [review]
Thanks @guihecheng for the patch.  Adding a placeholder for the exception is not necessary.  Logger methods are available with extra `Throwable` last parameter.

Here's an example without `{}`:

```
2020-07-22 12:32:13,723 [Command processor thread] ERROR commandhandler.CloseContainerCommandHandler (CloseContainerCommandHandler.java:handle(129)) - Can't close container #1
java.io.IOException
	at org.apache.hadoop.ozone.container.common.transport.server.ratis.XceiverServerRatis.submitRequest(XceiverServerRatis.java:534)
	at org.apache.hadoop.ozone.container.common.statemachine.commandhandler.CloseContainerCommandHandler.handle(CloseContainerCommandHandler.java:103)
	at org.apache.hadoop.ozone.container.common.statemachine.commandhandler.CommandDispatcher.handle(CommandDispatcher.java:99)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$initCommandHandlerThread$1(DatanodeStateMachine.java:465)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.apache.hadoop.ozone.container.common.transport.server.ratis.XceiverServerRatis.submitRequest(XceiverServerRatis.java:532)
	... 4 more
```

And some other code with unnecessary `{}`:

```
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerState.java
143:        LOG.info("{} was interrupted: {}", this, e);
```

```
2021-09-22 01:52:35,103 [f7bb455a-760e-4a0c-9ebd-bcc6783f1b45@group-32853C645470-FollowerState] INFO  impl.FollowerState (FollowerState.java:run(143)) - f7bb455a-760e-4a0c-9ebd-bcc6783f1b45@group-32853C645470-FollowerState was interrupted: {}
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at org.apache.ratis.util.TimeDuration.sleep(TimeDuration.java:324)
	at org.apache.ratis.util.TimeDuration.sleep(TimeDuration.java:309)
	at org.apache.ratis.server.impl.FollowerState.run(FollowerState.java:118)
```

**Comment by guihecheng** [comment]
@adoroszlai hmmm, that is interesting, I remember encountering a problem with one exception shown during one of my test, but I'm not using the master branch anyway.
Confirmed manually that this is not a problem for the master branch. I shall close it, thanks~
```
2021-09-22 13:14:42,022 ERROR org.apache.hadoop.ozone.container.common.statemachine.commandhandler.CloseContainerCommandHandler: Can't close container #20
org.apache.hadoop.hdds.scm.container.common.helpers.StorageContainerException: Error while creating/ updating .container file. ContainerID: 20
        at org.apache.hadoop.ozone.container.keyvalue.KeyValueContainer.writeToContainerFile(KeyValueContainer.java:235)
        at org.apache.hadoop.ozone.container.keyvalue.KeyValueContainer.updateContainerFile(KeyValueContainer.java:255)
        at org.apache.hadoop.ozone.container.keyvalue.KeyValueContainer.updateContainerData(KeyValueContainer.java:366)
        at org.apache.hadoop.ozone.container.keyvalue.KeyValueContainer.markContainerForClose(KeyValueContainer.java:286)
        at org.apache.hadoop.ozone.container.keyvalue.KeyValueHandler.markContainerForClose(KeyValueHandler.java:961)
        at org.apache.hadoop.ozone.container.ozoneimpl.ContainerController.markContainerForClose(ContainerController.java:101)
        at org.apache.hadoop.ozone.container.common.statemachine.commandhandler.CloseContainerCommandHandler.handle(CloseContainerCommandHandler.java:91)
        at org.apache.hadoop.ozone.container.common.statemachine.commandhandler.CommandDispatcher.handle(CommandDispatcher.java:99)
        at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$initCommandHandlerThread$24(DatanodeStateMachine.java:556)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Permission denied
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at org.apache.hadoop.ozone.container.keyvalue.KeyValueContainer.createTempFile(KeyValueContainer.java:774)
        at org.apache.hadoop.ozone.container.keyvalue.KeyValueContainer.writeToContainerFile(KeyValueContainer.java:219)
        ... 9 more
```

**Pull request closed without merging**
