### PR TITLE
HDDS-11052. HttpFS fails to start when compiled for Java 17

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

HttpFS fails to start when compiled by and for Java 17:

```
JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 \
  ./hadoop-ozone/dev-support/checks/build.sh -Djavac.version=17
```

Excerpt from HttpFS log:

```
java.lang.IllegalArgumentException
	at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
	...
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577)
	...
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:774)
	...
	at org.apache.hadoop.http.HttpServer2.start(HttpServer2.java:1301)
	at org.apache.ozone.fs.http.server.HttpFSServerWebServer.start(HttpFSServerWebServer.java:153)
	at org.apache.ozone.fs.http.server.HttpFSServerWebServer.main(HttpFSServerWebServer.java:185)
```

1. Change HttpFS to use `HttpServer2` from HDDS instead of Hadoop.
2. Migrate `HttpServer2` and HttpFS to Jersey 2, which Ozone already uses in S3 Gateway.  Parts of this change are taken from https://github.com/apache/hadoop/pull/763, thanks @aajisaka, since these components were originally adapted from Hadoop.

https://issues.apache.org/jira/browse/HDDS-11052

## How was this patch tested?

Compiled with and for Java 17:
https://github.com/adoroszlai/ozone/actions/runs/9741132878/job/26879699266#step:7:1

and ran HA-unsecure acceptance test, including HttpFS tests, with Java 17:
https://github.com/adoroszlai/ozone/actions/runs/9741132878/job/26880396757#step:6:1084

Regular CI:
https://github.com/adoroszlai/ozone/actions/runs/9746424125

### CODE REVIEW

**Review by smengcl — APPROVED** [review]
Thanks @adoroszlai . lgtm

**Comment by adoroszlai** [comment]
@dombizita @fapifta would you like to take a look?

**Review by dombizita — APPROVED** [review]
Thanks for fixing this @adoroszlai! I checked some basic functionalities with the HttpFS gateway in a docker cluster with your changes and they're working fine.

**Comment by adoroszlai** [comment]
Thanks @dombizita, @smengcl for the review.

**Pull request merged**
