### PR TITLE
HDDS-11695. SCM follower should not log NotLeaderException during Pipeline Report processing.

### PR DESCRIPTION
**Pull request by nandakumar131**
## What changes were proposed in this pull request?
SCM follower should not log NotLeaderException during Pipeline Report processing.

While processing Pipeline Report, SCM follower might log `NotLeaderException` when the follower tries to move the Pipeline from ALLOCATED state to OPEN state.

This exception can be ignored as this is expected to happen in follower SCM.

We can optionally add `scmContext.isLeader()` check before calling `pipelineManager.openPipeline(pipelineID)` this will avoid the exception in the first place.
But, we can still end up with `NotLeaderException` as leader can change after `scmContext.isLeader()` check is done.

`scmContext.isLeader()` is an optimization which is not required here.

## What is the link to the Apache JIRA
HDDS-11695.

## How was this patch tested?
This is logging change and doesn't affect any functionality.
The code refactoring is tested with existing unit test.

### CODE REVIEW

**Review by chungen0126 — CHANGES_REQUESTED** [review]
Thanks @nandakumar131 for the patch. Overall, the change looks good. Just a nit.

**Review by chungen0126 — APPROVED** [review]
+1 LGTM

**Comment by adoroszlai** [comment]
Thanks @nandakumar131 for the patch, @chungen0126 for the review.

**Comment by nandakumar131** [comment]
Thanks @chungen0126  for the review and @adoroszlai for the merge!

**Pull request merged**
