### PR TITLE
HDDS-11911. Return consistent error code when snapshot is not found in the DB or Snapshot Chain.

### PR DESCRIPTION
**Pull request by sadanand48**
## What changes were proposed in this pull request?
When the snapshot is deleted/purged , and it is removed either from DB or from the snapshot chain the exceptions thrown are not consistent.
If a snapshot is not found in table/chain, it should throw OMException with result code FILE_NOT_FOUND
Please check details in HDDS-11911

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-11911

## How was this patch tested?
Unit test

### CODE REVIEW

**Review by hemantk-12 — COMMENTED** [review]
Thanks @sadanand48 for the patch.

I had the same point in https://github.com/apache/ozone/pull/7112#discussion_r1735272547 earlier but forgot to create a follow-up task.

 There are two more places ([1](https://github.com/apache/ozone/blob/189a9fe42013e82f93becaede627e509322c38f6/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotUtils.java#L166) and [2](https://github.com/apache/ozone/blob/189a9fe42013e82f93becaede627e509322c38f6/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotUtils.java#L203)) where we throw INVALID_SNAPSHOT_ERROR. These helper functions are only for internal APIs and background services, but do we need to change them as well?
 
Other than the above point, changes look good to me.

**Comment by sadanand48** [comment]
> but do we need to change them as well?

sure, lets change it.

**Review by hemantk-12 — APPROVED** [review]
Thanks @sadanand48 for addressing the review comments.

LGTM.

**Comment by sadanand48** [comment]
Thanks @hemantk-12 for the review.

**Pull request merged**
