### PR TITLE
HDDS-1997. Support copy-source-if-(un)modified-since headers for MPU …

### PR DESCRIPTION
**Pull request by symious**
…key creation with copy

## What changes were proposed in this pull request?

- Add the header check of copy-source-if-(un)modified-since.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-1997

## How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by symious** [comment]
@elek Could you help to review this PR?

**Review by elek — CHANGES_REQUESTED** [review]
Thanks the patch @symious (and sorry for the late review). I tested it with aws cli, and I think the headers can be strings not just longs:

```
aws s3api --endpoint=http://localhost:9878 create-bucket --bucket bucket1
aws --endpoint=http://localhost:9878  s3api put-object --bucket bucket1 --key key1 --body /tmp/qwe

aws s3api --endpoint=http://localhost:9878 create-multipart-upload --bucket bucket1 --key mptest
export UPLOAD_ID=ec6856e9-0c44-4b94-8055-67cf4f33f51e-105622884754849793
201364  aws s3api --endpoint=http://localhost:9878 upload-part-copy --bucket bucket1 --key mptest --upload-id $UPLOAD_ID --part-number 1 --copy-source bucket1/key1 --copy-source-if-modified-since 2020-01-27 
```

Last command is failed and the exception is visible in the log:

```
s3g_1       | Caused by: java.lang.NumberFormatException: For input string: "Mon, 27 Jan 2020 00:00:00 GMT"
s3g_1       | 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
s3g_1       | 	at java.base/java.lang.Long.parseLong(Long.java:692)
s3g_1       | 	at java.base/java.lang.Long.valueOf(Long.java:1144)
s3g_1       | 	at org.apache.hadoop.ozone.s3.endpoint.ObjectEndpoint.checkCopySourceModificationTime(ObjectEndpoint.java:860)
s3g_1       | 	at org.apache.hadoop.ozone.s3.endpoint.ObjectEndpoint.createMultipartKey(ObjectEndpoint.java:596)
```

I think the content of the headers should be parsed.

Did you test it with another AWS tool? We may need to support both long and date.

Other parts looks good. The error message was too generic for me, but I found that AWS throws the same generic message ;-)

**Comment by symious** [comment]
@elek Thanks for the comment.
I think I was doing the test with s3api too, but I was testing with Long only. Will update the patch to support String also.
For the error message, I used the error message from AWS, I will add more details in the patch.

**Comment by elek** [comment]
>  I used the error message from AWS, 

Yes, I just learned it. It's fine to keep the current message to mimic the behavior of AWS.

Just FYI: You can create command line compatibility test (Test which executes AWS CLI and checks results) with modifying this file:

https://github.com/apache/ozone/blob/master/hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot

(And executing `./test.sh` from `compose/ozone` folder from the build).

It's more like a good to have, not a must-have (IMHO), but if you are interested, you can check, and create other Jira/patch with improving acceptance tests.

**Comment by symious** [comment]
Sure, thanks for the suggestions. 
I'm a little confused here, I have tried different typs of date format with was s3api, like "01-12-2020", "13-01-2020" and Long type timestamp, I found AWS is handling them all well. 
I am trying to use parseDate from common-lang3 which can parse date according to a list of format, but seems a little hard to list all possible DateFormat, do you have any suggestions on this?

**Comment by symious** [comment]
Fixed the patch to check the date from the header.
Will raise another commit for the robot test. Not familiar with the robot test, need some time to work on it.

**Comment by symious** [comment]
@elek The robot script is updated, could you have a check?

**Review by elek — APPROVED** [review]
+1 thanks for the update @symious 

Tested with the same method as before (using aws cli) and works well. (And it's already tested by robot tests, thanks for that...)

**Comment by symious** [comment]
My pleasure.

**Pull request merged**
