### PR TITLE
HDDS-5997 Centralize string based replication config validation via ReplicationConfigValidator

### PR DESCRIPTION
**Pull request by fapifta**
## What changes were proposed in this pull request?
We are having a property called ozone.replication.allowed-configs.
In this PR I propose to use the validation in the creator methods of ReplicationConfig class, and use this as a central
place to implement the parsing and validation logic of ReplicationConfigs.
It is out of scope to adjust the server side validation in this PR, I filed a separate JIRA for that.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-5997

## How was this patch tested?
Adjusted JUnit tests around the changes.

### CODE REVIEW

**Comment by sodonnel** [comment]
I haven't looked at this in detail yet, but the change `fromTypeAndFactor` to `fromProtoTypeAndFactor` that goes through a lot of files - I think this needs to be made on master as a separate change, and then merge master back to the branch.

We introduced this method onto master first to ease any merging pains later, so if we are going to rename it, then we probably should do that on master to keep this part consistent.

Hopefully it is relatively easy to do, but using the "refactor" tool in Intellij to just rename all occurrences of it.

**Comment by sodonnel** [comment]
Sorry, I just realised this commit is going to master. I just assumed it was going to the EC branch from the earlier discussions we had.

**Comment by sodonnel** [comment]
I think this change looks good, but I am not sure about the new interface name `CopyingReplicationConfig`. I wonder if either `ReplicationConfigWithFactor` or `ReplicatedReplicationConfig` would be better? The EC one will be called ECReplicationConfig, so perhaps ReplicatedReplicationConfig is similar. Having `Copying` in the name immediately made me think the interface was related the copying the ReplicationConfig object, which is not the case at all.

**Comment by sodonnel** [comment]
Yea, while it sounds strange I think `ReplicatedReplicationConfig` better describes what it is, and goes better with `ECReplciationConfig` which we have on the EC branch.

**Comment by fapifta** [comment]
Thank you for the suggestion @sodonnel, I have renamed the interface, let me know if you have spotted anything else that we should address here.

**Review by sodonnel — APPROVED** [review]
+1 LGTM

**Pull request merged**
