### PR TITLE
HDDS-4786. Disable Ratis pre-vote feature in SCM HA

### PR DESCRIPTION
**Pull request by amaliujia**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4786

## How was this patch tested?

UT

### CODE REVIEW

**Comment by amaliujia** [comment]
R: @bshashikant

**Comment by GlenGeng** [comment]
overall LGTM.

My concern is, preVote may do no harm to SCM HA.

**Comment by bshashikant** [comment]
> overall LGTM.
> 
> My concern is, preVote may do no harm to SCM HA. How about make it a configurable choice ?

I think , its ok to test it with Ratis and Ozone first befor emaking it ON. We can definitely make it configurable and this can be done post some perf/stability test results as well.

**Comment by amaliujia** [comment]
I guess at this moment we can just be aligned with master branch. And in master branch turned new features in Ozone off was a requirement for the Ozone next release.

I have rebased this PR.

**Comment by amaliujia** [comment]
@bshashikant PR rabased

**Review by bshashikant — APPROVED** [review]

**Comment by bshashikant** [comment]
Thanks @amaliujia for the work.

**Pull request merged**
