### PR TITLE
HDDS-9886. `hadoop fs -checksum` fails with `NoClassDefFoundError` on Hadoop 2

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

`hadoop fs -checksum` (or `hdfs dfs -checksum`) fails with `NoClassDefFoundError: CompositeCrcFileChecksum` when using Hadoop 2.  `CompositeCrcFileChecksum` was added by HDFS-13056 only in Hadoop 3.2.0 (and backported to 3.1.1).  (Thus it may also fail with Hadoop 3.1.0 and Hadoop 3.0.x, but I haven't tried those.)

This PR fixes it by copying code from Hadoop.

https://issues.apache.org/jira/browse/HDDS-9886

## How was this patch tested?

Added execution of `hdfs dfs -checksum` in Robot tests.

CI:
https://github.com/adoroszlai/ozone/actions/runs/7221000684/job/19675627539

### CODE REVIEW

**Review by jojochuang — COMMENTED** [review]
I am not against this approach, but I do know that downstream applications such as Cloudera Manager inspects class path and will abort when it finds that Hadoop and Ozone have the same classpath. Do you think we can do it but with a different classpath?

**Review by jojochuang — COMMENTED** [review]
Or can this be moved under hadoop-ozone/ozonefs-hadoop2 module? Cloudera Manager does not include ozonefs-hadoop2 jar

**Comment by adoroszlai** [comment]
> Hadoop and Ozone have the same classpath.

We already have code with the same FQCN as the corresponding class in Hadoop, e.g. `LeaseRecoverable` (added in b97d943d5cee11933d4aed0665607c97c9be92ce).  I'm sure there are other examples as well.

> Do you think we can do it but with a different classpath?

I can try.

**Review by jojochuang — COMMENTED** [review]
Looks good!

**Comment by adoroszlai** [comment]
Thanks @jojochuang, @szetszwo for the review.

**Pull request merged**
