### PR TITLE
HDDS-9392. Streaming write pipeline should pick the nearest datanode as primary node

### PR DESCRIPTION
**Pull request by ivandika3**
## What changes were proposed in this pull request?

In `BlockDataStreamOutput#setupStream`, if pipeline mode is enabled, we pass the Pipeline object to the `RatisHelper#getRoutingTable`.

In `RatisHelper#getRoutingTable`, we pick the first datanode in the pipeline as the primary, which from my understanding should be the Datanode closest to the client. However, I'm unable to find the logic that sort the datanodes in the pipeline.

To get the nearest datanode, when we open the stream key and request SCM to allocate the block (`OMKeyRequest#allocateBlock`), we need to also pass the clientMachineString so that so that nearest datanodes will be used instead. This should improve the performance of the stream pipeline mode. For normal Write Pipeline V1 (Async mode), the clientMachineString will be default to empty and datanodes won't be sorted to avoid incurring unnecesary overhead. 

Edit: The logic to pass the client address to be sorted in SCM has been done in https://github.com/apache/ozone/pull/5666. This patch focuses on the integration of the datastream API:

1. `setSortDatanodesInPipeline(true)` to the `KeyArgs` passed in Streaming write pipeline API (e.g. `createStreamKey`, `createStreamFile`, `BlockDataStreamOutputEntryPool`)
2. Switch from `Pipeline#getFirstNode` to `Pipeline#getClosestNode` in `RatisHelper` to build the `RoutingTable` and `RaftClient` with the correct pipeline topology.
3. Set `topologyAware` flag in `XceiverClientManager#acquireClient` in `BlockDataStreamOutput` so that the correct client is chosen based on the topology
    - This requires changing unifying the cache key of both Ratis and EC client to have suffix `host:port` which is explained in the comment.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-9392

## How was this patch tested?

Existing tests.

Edit: (Clean CI: https://github.com/ivandika3/ozone/actions/runs/7138521827)

### CODE REVIEW

**Comment by szetszwo** [comment]
@ivandika3 , please feel free to let me know when this is ready.  Thanks!

**Comment by ivandika3** [comment]
Hi @szetszwo , might be slightly unrelated, but I have a question regarding the topology aware read with respect to Ratis pipeline.

From my understanding, the intent for topology aware read is for the client to be able to get the block / chunk from the nearest datanode. For RATIS pipeline, it seems we always use `XceiverClientRatis` (in `XceiverClientManager#getClient` we pick the `XceiverClientSpi` implementation based on the pipeline type). However, since we have not supported Linearizable read from follower for Datanodes, won't the block/chunk read using Ratis always go through the pipeline leader? I was expecting the topology-aware read to use `XceiverClientGrpc`, but was not able to find the logic that uses it.

I probably missed something since when the Ratis pipeline is closed, the Ratis group will be removed for the pipeline. This should mean that any Raft client trying to connect to that group will not be able to read the data using Ratis client (will throw `GroupMismatchException`). 

Any clarifications would be appreciated.

**Comment by szetszwo** [comment]
@ivandika3 , for read, it will rebuild a pipeline for closed container; see https://github.com/apache/ozone/blob/60bb0604217fbd44dbc6b115b59fc26a297fcaba/hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java#L275-L279
(the code is changed recently but the logic remains unchanged.)

**Comment by ivandika3** [comment]
@szetszwo Understood, thank you for the info.

**Comment by ivandika3** [comment]
Hi @szetszwo, I have marked this MR as ready. This will finish of the works in https://github.com/apache/ozone/pull/5666 by integrating topology awareness to the Streaming Write Pipeline API. PTAL. Thanks.

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by ivandika3** [comment]
Thank you for the review @szetszwo

**Pull request merged**
