### PR TITLE
HDDS-8040. Increase ratis log segment default size in datanode.

### PR DESCRIPTION
**Pull request by szetszwo**
## What changes were proposed in this pull request?

[HDDS-1719](https://issues.apache.org/jira/browse/HDDS-1719) changed the segment default size from 16KB to 1MB. It is still too small. We should change it to something like 64MB.

## What is the link to the Apache JIRA

HDDS-8040

## How was this patch tested?

By existing tests.

### CODE REVIEW

**Review by adoroszlai — COMMENTED** [review]
Thanks @szetszwo for the patch, LGTM.

**Review by sumitagrawl — COMMENTED** [review]
@szetszwo Thanks for working over this, have few query,
1. What is the impact of increase in segment size and pre-allocated size over memory usages of DN, do memory requirement increases for write chunk or other operation? and if so, by what ratio?
2. If existing pipeline have this new value after restart/upgrade, do this have any impact?

**Comment by adoroszlai** [comment]
Thanks @szetszwo for the patch, @jojochuang for the review.

@szetszwo please answer @sumitagrawl's questions when you have time.

**Comment by szetszwo** [comment]
@sumitagrawl ,

1. The segment size and pre-allocated size changes are for the segment **files** but not the memory.  So, no memory impact unless the files are stored in the memory (ramfs).
2. The files size and the pre-allocated size will be changed after restart.

**Comment by szetszwo** [comment]
@sumitagrawl , @jojochuang , @adoroszlai , thanks a lot for reviewing this!

**Pull request merged**
