### PR TITLE
HDDS-10733. Merge HDDS-7593 (related to hsync and lease recovery) feature branch into master.

### PR DESCRIPTION
**Pull request by ashishkumar50**
## What changes were proposed in this pull request?

Support HSync and lease recovery required for HBASE. This feature is to make HBASE works using Ozone. 
More details about this feature is attached in design doc mentioned in [HDDS-7593](https://issues.apache.org/jira/browse/HDDS-7593).

Below are the conflicts:
```
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMDirectoriesPurgeRequestWithFSO.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
```
Above conflicts are due to HDDS-11194, HDDS-10658, HDDS-11215, HDDS-11259

Vote for merge is OPEN. We will proceed for merge once we get sufficient number of votes.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-10733

## How was this patch tested?

Unit/Integration tests are added for every change.
CI: https://github.com/ashishkumar50/ozone/actions/runs/10141629794/workflow

### CODE REVIEW

**Comment by jojochuang** [comment]
Hi @ashishkumar50 please rebase the merge. We added a few commits in the HDDS-7593 branch. Thanks!

**Comment by smengcl** [comment]
Thanks @ashishkumar50 for the PR.

Also a gentle reminder that one should use `git push` CLI to complete this merge when this is approved.

"Squash and merge" button below must NOT be used.

**Comment by ashishkumar50** [comment]
> Hi @ashishkumar50 please rebase the merge. We added a few commits in the [HDDS-7593](https://issues.apache.org/jira/browse/HDDS-7593) branch. Thanks!

Rebased the latest commits from HDDS-7593 branch. 
One new simple conflict in:
`hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java`

**Review by jojochuang — APPROVED** [review]
+1

**Review by adoroszlai — CHANGES_REQUESTED** [review]
Thanks @ashishkumar50 for working on this.

If I understand correctly, this PR is mixing two kinds of commits:

- Commits of the feature branch (`HDDS-7593`)
- Fixes for any last minute problems since latest merge from `master` into `HDDS-7593`
  * a32b4d0e4d Update enum name to use HBASE_SUPPORT, as this is also used now by finalizeBlock
  * fbe434bf48 Update test case
  * 89a0b5cc92 Fix test case
  * 3257e9cc06 Update test case
  * etc.

I don't think these should be mixed.

- The feature branch must be merged into `master` without squashing commits.
- Commits like those above should be squashed.

These commits are not yet on the feature branch, only on https://github.com/ashishkumar50/ozone/commits/HDDS-10733.

Therefore I think we should:

1. Merge `master` into `HDDS-7593` hopefully last time; no squash.
2. Fix any problems in a PR targeting `HDDS-7593`; squash.
3. Merge `HDDS-7593` into `master` without additional changes; no squash.

No PR needed for (1) and (3).

**Comment by ashishkumar50** [comment]
@adoroszlai, Thanks for the review. This PR has only commits from HDDS-7593 branch. 
The above related to "test case" was just for checking test flakiness. But at the end it is same as HDDS-7593 branch.
And the one related to "HBASE_SUPPORT" commit also it is same as feature branch.

**Comment by adoroszlai** [comment]
> This PR has only commits from [HDDS-7593](https://issues.apache.org/jira/browse/HDDS-7593) branch

@ashishkumar50 Not really:

```
$ git log --oneline origin/HDDS-7593.. | head           
a32b4d0e4d Update enum name to use HBASE_SUPPORT, as this is also used now by finalizeBlock
bb94b50ba9 Rebase latest commits from HDDS-7593 branch
fbe434bf48 Update test case
304c9f836d Merge remote-tracking branch 'upstream/HDDS-7593' into HDDS-10733
89a0b5cc92 Fix test case
3257e9cc06 Update test case
717df1d674 HDDS-10733. Merge HDDS-7593 related to hsync and lease recovery feature branch into master.
...
```

**Comment by ashishkumar50** [comment]
Closing this one, Opened a new [PR](https://github.com/apache/ozone/pull/7033) for review.

**Pull request closed without merging**
