### PR TITLE
HDDS-6434: EC: Overwriting an EC key with a Ratis key fails

### PR DESCRIPTION
**Pull request by umamaheswararao**
## What changes were proposed in this pull request?

Updated the repconfig when key already exist.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-6434

## How was this patch tested?

Added tests.

### CODE REVIEW

**Comment by guihecheng** [comment]
Hi @umamaheswararao , the patch LGTM overall.
 Do we have to test it vice versa that we have a ratis key first, then overwrite  it with an EC key ?

**Comment by umamaheswararao** [comment]
Thanks @guihecheng for the review. It make sense to add a test for verifying other way. I have just added one. Thanks

**Comment by guihecheng** [comment]
@umamaheswararao Thanks for updates, LGTM+1 and verified manually.

**Review by sodonnel — APPROVED** [review]
LGTM

**Pull request merged**
