### PR TITLE
HDDS-7490. fix metaTable error

### PR DESCRIPTION
**Pull request by JacksonYao287**
## What changes were proposed in this pull request?

fix metaTable error

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7490

## How was this patch tested?

no need, this is a trivial bug fix

### CODE REVIEW

**Comment by adoroszlai** [comment]
Thanks @JacksonYao287 for the fix.

> ## How was this patch tested?
> current ut

Since the patch is fixing a bug and tests have been passing without it, I don't think current UT catches the bug, hence it does not validate the fix.

Also, https://github.com/JacksonYao287/ozone/commit/2663f9c31b5578354ccbb25974068e61df24f05c has no CI run, so I don't know which "current UT" was run.

I'm fine committing this without any tests, since it's a trivial fix.  Just please don't say it was tested with existing tests.

**Comment by JacksonYao287** [comment]
> Thanks @JacksonYao287 for the fix.
> 
> > ## How was this patch tested?
> > current ut
> 
> Since the patch is fixing a bug and tests have been passing without it, I don't think current UT catches the bug, hence it does not validate the fix.
> 
> Also, [JacksonYao287@2663f9c](https://github.com/JacksonYao287/ozone/commit/2663f9c31b5578354ccbb25974068e61df24f05c) has no CI run, so I don't know which "current UT" was run.
> 
> I'm fine committing this without any tests, since it's a trivial fix. Just please don't say it was tested with existing tests.

thanks @adoroszlai  for pointing out this , i have changed the description and will be careful later。

**Review by adoroszlai — APPROVED** [review]
Thanks again @JacksonYao287 for the fix.

@errose28 this was introduced in HDDS-6760 as part of SCM HA finalization.  Since it's a new feature in 1.3, I think it should be fixed in 1.3.0 before release.  What's your opinion?

**Review by errose28 — APPROVED** [review]
Thanks for the fix @JacksonYao287. This does looks like something we should cherry pick to 1.3.0. I will bring it up on the vote thread for RC0.

**Comment by JacksonYao287** [comment]
thanks @adoroszlai and @errose28 for the review!

**Pull request merged**
