### PR TITLE
HDDS-8669. Update compose README

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Improve `hadoop-ozone/dist/src/main/compose/README.md` by describing the concepts in a bit more detail.  Include mention of test scripts with custom configs being introduced in #4750.

https://issues.apache.org/jira/browse/HDDS-8669

## How was this patch tested?

:eyes:

### CODE REVIEW

**Comment by adoroszlai** [comment]
@Galsza, @sadanand48, @xBis7, thanks again for reviewing HDDS-8640.  Here is the corresponding doc update.

**Review by xBis7 — APPROVED** [review]
Thanks @adoroszlai for the documentation improvements. Changes LGTM.

**Review by sadanand48 — COMMENTED** [review]
Thanks @adoroszlai for the doc update. LGTM.

**Comment by Galsza** [comment]
Thanks Attila, looking good to me!

**Comment by adoroszlai** [comment]
Thanks @Galsza, @sadanand48, @xBis7 for the review.

**Pull request merged**
