### PR TITLE
HDDS-6873. EC: Add block token support for ECReconstructionCoordinator

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Support secure cluster by using block/container tokens in `ECReconstructionCoordinator`.

https://issues.apache.org/jira/browse/HDDS-6873

## How was this patch tested?

Changed existing integration test to require tokens.

https://github.com/adoroszlai/hadoop-ozone/actions/runs/2544654342

### CODE REVIEW

**Comment by umamaheswararao** [comment]
Changes looks good to me. I just realized, SCMCommand actually defined with token. Do you think we can actually send the container token from SCM itself and use that? 1d is the default expiry time. Just a thought. But current approach also should fine. Even though we are creating containers from DN, ideally they are more responsible by SCM and blocks are responsible for DN. This can be separate JIRA also if that make sense to send the token over wire.

**Comment by adoroszlai** [comment]
> I just realized, SCMCommand actually defined with token. Do you think we can actually send the container token from SCM itself and use that? 1d is the default expiry time. Just a thought. But current approach also should fine. Even though we are creating containers from DN, ideally they are more responsible by SCM and blocks are responsible for DN. This can be separate JIRA also if that make sense to send the token over wire.

Thanks for the idea.  Created HDDS-6939 for this.

**Review by umamaheswararao — APPROVED** [review]
LGTM, thanks for working on this filing separate JIRA. But that can be little low priority though as command already defined with token, we can use later any time. So, I am moving ahead committing this.

**Comment by adoroszlai** [comment]
Thanks @umamaheswararao for reviewing and merging this.

**Comment by umamaheswararao** [comment]
Thanks @adoroszlai for working on this in a short time.
And also thanks for filing the JIRA: https://issues.apache.org/jira/browse/HDDS-6939

**Pull request merged**
