### PR TITLE
HDDS-9100. [HTTPFSGW] Add JvmPauseMonitor for HttpFSServerWebServer

### PR DESCRIPTION
**Pull request by guohao-rosicky**
## What changes were proposed in this pull request?

Add JvmPauseMonitor for HttpFSServerWebServer

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-9100

### CODE REVIEW

**Review by Xushaohong — COMMENTED** [review]
LGTM. Thx @guohao-rosicky for the patch.

**Review by dombizita — COMMENTED** [review]
thanks @guohao-rosicky for the patch, it looks good to me

**Review by fapifta — COMMENTED** [review]
Hi @guohao-rosicky,

first of all thank you for your contribution.
I looked around a bit in the HTTPFS GW code, and I found that there is already an instance where we use a JvmPauseMonitor, within HttpFSServerWebApp. Where we set up the metrics system underneath the HTTPFS GW.

Its metrics are visible on a running HTTPFS GW's jmx output as well.

I am not very familiar with how the bindings happen in the background and what is the lifecycle of these objects, and I can not tell why we do not see the expected pausemonitor info log about starting, but I would look into that before adding a new pause monitor.

Do you have any experience on this and can you try to check?

**Comment by guohao-rosicky** [comment]
@fapifta  thanks for the comment.

Httpfs uses JvmPauseMonitor with the Hadoop metrics. 

I checked this PR(https://github.com/apache/ozone/pull/4814) and there are detailed instructions in it, so I don't think this current PR is needed anymore and I'll close it.

**Pull request closed without merging**
