### PR TITLE
HDDS-11907. OzoneSecretKey does not need to implement Writable

### PR DESCRIPTION
**Pull request by chiacyu**
## What changes were proposed in this pull request?
Since the `OzoneSecretKey` doesn't have to implements `Writable`, we can remove the related unused methods in the class. thanks!

## What is the link to the Apache JIRA

Please take a look at [HDDS-11907](https://issues.apache.org/jira/browse/HDDS-11907) for more details.

## How was this patch tested?

It tested by the CI.

### CODE REVIEW

**Comment by adoroszlai** [comment]
@jojochuang please review

**Review by jojochuang — APPROVED** [review]
The class is private and unstable so we can change at will.

**Comment by jojochuang** [comment]
Apart from OzoneSecretKey.java, SecretKeyProto is defined in both hdds.proto and OmClientProtocol.proto but they are not used in any other places.

Feels like we should remove those two protobuf message definitions too. But I"m not sure if if there's a good process to follow when it comes to removing protobuf messages.

**Comment by adoroszlai** [comment]
Thanks @chiacyu for the patch, @jojochuang for the review.

**Comment by chiacyu** [comment]
Hi, @jojochuang 
sounds good to me, I would create a jira for discussion.

**Pull request merged**
