### PR TITLE
HDDS-7703. Add num of datanodes metrics in ScmBlockDeletingServiceMetrics

### PR DESCRIPTION
**Pull request by symious**
## What changes were proposed in this pull request?

SCM sends delete block commands to different datanodes. 

There is a chance that one datanode has some issue handling the requests, and SCM will be sending all requests to the same datanode. 

This metrics should be helpful to notice this issue.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7703

## How was this patch tested?

unit test.

### CODE REVIEW

**Comment by kerneltime** [comment]
@swamirishi can you please take a look?

**Comment by ChenSammi** [comment]
Hi @symious , this numDatanodesSentCommands will be overwritten every time SCM sends out a new batch of delete blocks.  Could you explain a little further how this transient value will be helpful for issue diagnose?

**Comment by symious** [comment]
Sure. 
Normally the delete requests will be send evenly to all datanodes, but sometimes we met the slow deleting issue caused by some slow datanodes. At this scenario, all the requests will be send only to one or a small amount of datanodes. 
With this metrics, SRE could identify this kind of issue and handle the slow datanode quickly to help improve the deleting speed.

**Comment by DaveTeng0** [comment]
Hey @symious ～ there is some small conflict, otherwise looks good to me！

**Comment by adoroszlai** [comment]
@ChenSammi please take another look

**Review by sumitagrawl — COMMENTED** [review]
@symious Thanks for working over this, IMO, this metric is redundant to BlockDeletionCommandSent, which is incremented every time request is send to DN.

So both metric will give same data only, only difference is, DN count is incremented in single call for all DNs, but BlockDeletionCommandSent is incremented every time request is send.

**Comment by adoroszlai** [comment]
@symious @ChenSammi @sumitagrawl what should we do with this PR?

**Comment by adoroszlai** [comment]
Please feel free to reopen if you would like to continue working on this.

**Pull request closed without merging**
