### PR TITLE
HDDS-11733. Remove okio versioning and unused okhttp dependency

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

- `okio` is transitive-only, versioning is not needed
- `okhttp` 2.7.5 is not required by Ozone or any dependencies, can be removed

https://issues.apache.org/jira/browse/HDDS-11733

## How was this patch tested?

CI:
https://github.com/adoroszlai/ozone/actions/runs/11868908490

### CODE REVIEW

**Comment by ChenSammi** [comment]
The LICENSE.txt under hadoop-ozone/dist/src/main/license/bin mentioned these two package. Shall we manually remove them from the LICENSE.txt?

**Comment by adoroszlai** [comment]
> The LICENSE.txt under hadoop-ozone/dist/src/main/license/bin mentioned these two package.

Thanks @ChenSammi for checking.

```
   com.squareup.okhttp3:okhttp
   com.squareup.okio:okio
```

We still need these entries (note that `okhttp` is the v3 one), since they are part of the binary distribution:

```
share/ozone/lib/okhttp.jar
share/ozone/lib/okio.jar
```

But while verifying, I just noticed that some items introduced by okio upgrade in #5063 are missing from the LICENSE.  Updated now in 4ff2214da279481c6c91864823247188e030f954.

**Review by ChenSammi — APPROVED** [review]
Thanks @adoroszlai .

**Comment by adoroszlai** [comment]
Thanks @ChenSammi for the review.

**Pull request merged**
