### PR TITLE
HDDS-4806. Fix misc acceptance test: List pipelines on unknown host

### PR DESCRIPTION
**Pull request by GlenGeng**
## What changes were proposed in this pull request?

For now, `SCMContainerLocationFailoverProxyProvider` first use `ozone.scm.names` to create rpcProxy, if `ozone.scm.names` is not set, it falls back to use `ozone.scm.client.address`. However, it breaks the master's behavior, which directly use `ozone.scm.client.address` to build the rpcProxy.

In `ozone admin --verbose pipeline list --scm unknown-host`, `unknown-host` will be set to `ozone.scm.client.address`, the created rpcProxy will trigger "java.net.UnknownHostException: Invalid host name: "
 
This Jira https://issues.apache.org/jira/browse/HDDS-4556 and PR https://github.com/apache/ozone/pull/1671  adds a smoketest for `ozonescripts` environment, helps to find this bug.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4806

## How was this patch tested?

CI

### CODE REVIEW

**Comment by GlenGeng** [comment]
After last two merge of master, we have four failures:
The first merge cause the failure unit test (TestContainerEndpoint, TestReconContainerManager) and misc docker test.
The second merge cause the failure of find bugs.

The fix is aims to fix misc acceptance test

@nandakumar131 @bshashikant @amaliujia Please take a look!

**Review by bshashikant — APPROVED** [review]

**Comment by bshashikant** [comment]
The change looks good. I am committing this one as this fixes the acceptance test. Other failures are unrelated.

**Comment by bshashikant** [comment]
Thanks @GlenGeng for the contribution.

**Comment by amaliujia** [comment]
+1 thanks @GlenGeng!

**Pull request merged**
