### PR TITLE
HDDS-9687. Handle key deletion with OM Ratis disabled

### PR DESCRIPTION
**Pull request by z-bb**
## What changes were proposed in this pull request?
Add a handle delete with non-ratis

Currently, deleting directory data will not be deleted in non ratis mode

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-9687

### CODE REVIEW

**Comment by guohao-rosicky** [comment]
Thanks @z-bb working on this, let's waiting ci passed.

**Comment by adoroszlai** [comment]
@aswinshakil can you please review?

**Review by aswinshakil — APPROVED** [review]
Thanks for the patch @z-bb. LGTM+1

**Comment by adoroszlai** [comment]
Thanks @z-bb for the patch, @aswinshakil, @guohao-rosicky for the review.

**Pull request merged**
