### PR TITLE
HDDS-7052. Topology Dynamic List document issue

### PR DESCRIPTION
**Pull request by matthieuschulz**
## What changes were proposed in this pull request?

Minor Doc fixing of the  XML code under the Dynamic List section in hadoop-hdds/docs/content/feature/Topology.md 

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7052

## How was this patch tested?

This patch was tested using a real cluster.

### CODE REVIEW

**Comment by neils-dev** [comment]
Hi @matthieuschulz .  Thanks for this PR!  Please update the Jira linked issue to HDDS-7054.  Please also assign yourself to this jira.

**Review by adoroszlai — CHANGES_REQUESTED** [review]
Thanks @matthieuschulz for the patch, but it changes the wrong example, converting the _static list_ example into a _dynamic_ one.  Please change the code example under _Dynamic list_ instead.

**Comment by matthieuschulz** [comment]
Hi @adoroszlai , I have made the change, thanks for the catch!

**Review by adoroszlai — APPROVED** [review]
Thanks @matthieuschulz for updating the patch.

@xBis7 or @neils-dev can you please also take a look?

**Comment by neils-dev** [comment]
Thanks @matthieuschulz for preparing this PR and its submission!  Thanks @xBis7 for your help.  Thanks @adoroszlai for the review and comments.
Looks great.  LGTM.

**Comment by xBis7** [comment]
LGTM. Thanks @adoroszlai and @neils-dev for the review.

**Comment by adoroszlai** [comment]
Thanks @matthieuschulz for the fix, @neils-dev and @xBis7 for the review.

**Comment by adoroszlai** [comment]
@matthieuschulz please register in Apache Jira and make a comment on the issue or let me know your Jira ID in any other way.

**Comment by neils-dev** [comment]
Thanks @adoroszlai  for looking into the jira id.  cc @swagle

**Comment by xBis7** [comment]
@adoroszlai  Matthieu's Jira ID is `matthieuschulz`. Thanks for looking into this.

**Pull request merged**
