### PR TITLE
HDDS-9660. NPE at OzoneManagerRatisServer.getRaftLeaderId

### PR DESCRIPTION
**Pull request by sumitagrawl**
## What changes were proposed in this pull request?
There is a possibility that first call of method returns non-null value but second time call can return null value, so the way check is done is wrong.
So first get value in local variable and use same for check null and use further.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-9660

## How was this patch tested?

* impact verified with existing cases

### CODE REVIEW

**Review by sadanand48 — APPROVED** [review]
Thanks for the fix @sumitagrawl , LGTM.

**Review by adoroszlai — COMMENTED** [review]
The patch looks good to fix the NPE, but I would like to suggest further enhancement.

```
NullPointerException
  at org.apache.hadoop.ozone.om.ratis.OzoneManagerRatisServer.getRaftLe aderId(OzoneManagerRatisServer.java:838)
  at org.apache.hadoop.ozone.om.OzoneManager.checkLeaderStatus(OzoneManager.java:3983)
  at org.apache.hadoop.ozone.om.ratis.utils.OzoneManagerRatisUtils.checkLeaderStatus(OzoneManagerRatisUtils.java:473)
```

`OzoneManager.checkLeaderStatus` calls both `getRaftLeaderId()` and `getRaftLeaderAddress()`, so leader will still be looked up twice.  Can we change it to `getLeader()` once, and then use both properties of the leader found.

https://github.com/apache/ozone/blob/e14fb8e092cbbcd562877864aff1bc66af9fe59b/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java#L4099-L4100

**Comment by sumitagrawl** [comment]
@adoroszlai updated...

**Review by adoroszlai — COMMENTED** [review]
Thanks @sumitagrawl for updating the patch, LGTM.

**Comment by adoroszlai** [comment]
Thanks @sumitagrawl for the patch, @sadanand48 for the review.

**Pull request merged**
