### PR TITLE
HDDS-10932. Reduce number of watch requests by using CommitInfoProto from NotReplicatedException

### PR DESCRIPTION
**Pull request by ivandika3**
## What changes were proposed in this pull request?

We can use CommitInfoProto in NotReplicatedException introduced in [RATIS-2089](https://issues.apache.org/jira/browse/RATIS-2089) to remove the need for watch MAJORITY_COMMITTED calls if NotReplicatedException is thrown from the DN Ratis leader.

This also requires DN Ratis server watch timeout configuration change hdds.ratis.raft.server.watch.timeout to be lower than the client watch timeout hdds.ratis.raft.client.rpc.watch.request.timeout so that NotReplicatedException will be thrown instead of TimeoutException.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-10932

## How was this patch tested?

Existing tests. Increased the client watch RPC timeout in `TestBlockOutputStream` to be strictly larger than the server watch timeout to reflect the current default configurations.

Clean CI: https://github.com/ivandika3/ozone/actions/runs/9707025051

### CODE REVIEW

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by adoroszlai** [comment]
Thanks @ivandika3 for the patch, @szetszwo for the review.

**Comment by ivandika3** [comment]
Thank you @szetszwo for the review and @adoroszlai for the merge.

**Comment by smengcl** [comment]
Thanks @ivandika3 for the patch!

**Pull request merged**
