### PR TITLE
HDDS-7166. Memory leak in Recon when replacing DB for new checkpoint

### PR DESCRIPTION
**Pull request by duongnguyen0**
## What changes were proposed in this pull request?
Found this when baking RocksDB changes in our internal test cluster.
When updating the database object for a new checkpoint, the existing DB is replaced without closing. 

https://issues.apache.org/jira/browse/HDDS-7166

## How was this patch tested?
Unit test, standard CI.

### CODE REVIEW

**Comment by kerneltime** [comment]
Should the logic to close the DB be moved inside `initializeNewRdbStore`?

**Comment by duongnguyen0** [comment]
> Should the logic to close the DB be moved inside `initializeNewRdbStore`?

Thanks for the review, @kerneltime. I guess the closure of the existing DB should be in `updateOmDB(File newDbLocation)` as it's meant to replace the DB object. But I'm ok either way, think it can be better if `initializeNewRdbStore` only creates and initializes `DBStore` and doesn't attempt to `set`.

**Comment by kerneltime** [comment]
> > Should the logic to close the DB be moved inside `initializeNewRdbStore`?
> 
> Thanks for the review, @kerneltime. I guess the closure of the existing DB should be in `updateOmDB(File newDbLocation)` as it's meant to replace the DB object. But I'm ok either way, think it can be better if `initializeNewRdbStore` only creates and initializes `DBStore` and doesn't attempt to `set`.

I agree. It would be good to place the new DB, initialize it, and then make it available. Looking at the code, I am unsure what the concurrency requirements are here.

**Comment by kerneltime** [comment]
> > > Should the logic to close the DB be moved inside `initializeNewRdbStore`?
> > 
> > 
> > Thanks for the review, @kerneltime. I guess the closure of the existing DB should be in `updateOmDB(File newDbLocation)` as it's meant to replace the DB object. But I'm ok either way, think it can be better if `initializeNewRdbStore` only creates and initializes `DBStore` and doesn't attempt to `set`.
> 
> I agree. It would be good to place the new DB, initialize it, and then make it available. Looking at the code, I am unsure what the concurrency requirements are here.

Looks like It is single-threaded. For now, this is fine, so gave it a ship it.

**Review by kerneltime — APPROVED** [review]

**Comment by adoroszlai** [comment]
Please make sure all tests pass before merging.

**Pull request merged**
