### PR TITLE
[Docs] HDDS-4207. Include version information in docs

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Display version from POM in documentation footer.

If building in a git working copy, also display last commit date and hash, with link to GitHub.

https://issues.apache.org/jira/browse/HDDS-4207

## How was this patch tested?

Built docs locally (`mvn clean package` in `hadoop-hdds/docs`), both in git repo and in `hadoop-ozone-1.0.0-src`.  See text on light gray background at the bottom in these screenshots:

in git repo

in released source tree

### CODE REVIEW

**Review by vivekratnavel — APPROVED** [review]
+1 LGTM.

I tested locally and able to see the "Version: " text with no version displayed. I run "hugo serve" in hadoop-hdds/docs. How do I see the version after "mvn clean package"?

**Comment by adoroszlai** [comment]
Thanks @vivekratnavel for taking a look.

> How do I see the version after "mvn clean package"?

* `open hadoop-hdds/docs/target/classes/docs/index.html` if only built `hadoop-hdds-docs`
* `open hadoop-ozone/dist/target/ozone-1.1.0-SNAPSHOT/docs/index.html` after full build

**Comment by vivekratnavel** [comment]
Thanks @adoroszlai! I also noticed one more thing. The footer does not stick at the bottom of the screen.

For pages with content that do not occupy the full screen, we see the footer with version immediately in the middle of the screen as shown in the screen-shot attached. We should either make this footer stick to the bottom of the screen always or we should this version information in a different space. One alternate space I can think of is the bottom of the left menu bar.

Screen Shot 2020-12-15 at 3 12 30 PM

**Comment by adoroszlai** [comment]
> For pages with content that do not occupy the full screen, we see the footer with version immediately in the middle of the screen as shown in the screen-shot attached.

Thanks @vivekratnavel.  I tried, but don't know enough CSS to achieve this.  Can you give me some pointer or hint?

**Comment by vivekratnavel** [comment]
I referred to this post for sticky footer - https://css-tricks.com/couple-takes-sticky-footer/ and pushed a commit. 

Please check and let me know how it looks.

**Comment by adoroszlai** [comment]
> I referred to this post for sticky footer - https://css-tricks.com/couple-takes-sticky-footer/ and pushed a commit.
> 
> Please check and let me know how it looks.

Thank you very much @vivekratnavel.  It looks great on both long and short pages.

**Comment by adoroszlai** [comment]
Thanks @vivekratnavel for the review and help with the sticky footer.

**Pull request merged**
