### PR TITLE
HDDS-7305. Fix Hadoop imports

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

 * Replace one import from Hadoop's shaded Guava.
 * Add direct dependencies for various Apache Commons libs instead of relying on getting them transitively via Hadoop.

Different Hadoop versions may not depend on all these libraries (or shade different Guava version), so using transitive dependency explicitly (via import) risks breaking with some version of Hadoop.

https://issues.apache.org/jira/browse/HDDS-7305

## How was this patch tested?

Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3228775529

### CODE REVIEW

**Comment by kerneltime** [comment]
How did you identify the pom file changes? I understand the import change, but not sure how the pom file updates were speced out.

**Comment by adoroszlai** [comment]
> How did you identify the pom file changes?

Trial and error.  Added the exclude, then resolved build failures.

**Review by captainzmc — APPROVED** [review]
+1 the change looks good.

**Comment by adoroszlai** [comment]
Thanks @captainzmc for reviewing and merging this.

**Comment by captainzmc** [comment]
Thanks @adoroszlai, I will cherry-pick this to release branch.

**Pull request merged**
