### PR TITLE
HDDS-8269. [Snapshot] Enable CI native building and testing

### PR DESCRIPTION
**Pull request by smengcl**
## What changes were proposed in this pull request?

HDDS-8028 is merged, but the native build (including RocksDB tools) isn't quite triggered and tested on CI.

This aims to enable the native build in CI to facilitate testing in order to prevent regression.

prebuild-1

- [x] Enable native build in PR CI and post-commit CI.
- [ ] Enable selectively in PRs that changed SnapDiff related modules.
- [ ] Separate non-native and native build. Parallelize CI jobs as much as possible to reduce overall CI run time.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8269

## How was this patch tested?

- All existing tests shall pass.

### CODE REVIEW

**Comment by neils-dev** [comment]
The native build within the CI workflow should be run with both java 8 and java 11 compiles.

**Comment by smengcl** [comment]
> The native build within the CI workflow should be run with both java 8 and java 11 compiles.

It already does in `build` phase: https://github.com/apache/ozone/pull/4466/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL68-L96

`compile` phase is current used to build against JDK 11 and 17. But only the `build` phase binary is used to run the consecutive tests IIUC.

**Comment by neils-dev** [comment]
> compile phase is current only used to test compilation against JDK 11 and 17.

Thanks.  Should be great.  It should be able to bring out possible incompatibilities in compile.  As mentioned offline, I noticed a problem with building the native rocks db library with java 11 that did not occur with java 8.  Including compiling with different supported java versions here with the CI should give us a consistent build and root out compatibility issues.

**Comment by prashantpogde** [comment]
I thought we can trigger this only when someone makes changes in the SnapDiff related code paths. In other normal cases we wouldn't have to trigger "-Drocks_tools_native".

**Comment by smengcl** [comment]
> I thought we can trigger this only when someone makes changes in the SnapDiff related code paths. In other normal cases we wouldn't have to trigger "-Drocks_tools_native".

Correct. That is what the second TODO in the list is for:

> Enable **selectively** in PRs that changed SnapDiff related modules.

**Comment by adoroszlai** [comment]
Which tests exercise the native build?  Can we extract them into separate check(s), and avoid the overhead on the critical path (`build -> acceptance`)?

**Comment by smengcl** [comment]
> Which tests exercise the native build? Can we extract them into separate check(s), and avoid the overhead on the critical path (`build -> acceptance`)?

Hi Attila, I plan to upload a compiled JNI jar (with `-snapshot` version) to Apache repo. It would be compiled for Linux 64-bit only for now just to enable CI (plan to cross-compile like rocksdbjni jar later). Take a look at the diagram I just uploaded to the PR description. See if that looks reasonable.

For now we don't have tests specifically for the Rocksdb tools JNI. @swamirishi will add some in the coming weeks. Filed HDDS-8306 for this.

The only tests that would actually be using Rocksdb tools native right now are those SnapDiff tests (e.g. `TestOmSnapshot#testSnapDiff`). Those tests would automatically use the `rocksdb_sst_dump` tool when that is available.

Obviously we would also need to parameterize the SnapDiff tests e.g. to force them to use the sst_dump tool in one set of params, in order to make sure the tool is working as intended. Filed HDDS-8307 for this.

**Comment by swamirishi** [comment]
> makes changes in the SnapDiff related code paths. In other normal cases we wouldn't have to trigger "-Drocks_tools_native".

@prashantpogde you can take a look at #4596 for this & check if it fixes the above issue.

**Comment by swamirishi** [comment]
#4596 triggers selective CI based on the change.

**Comment by smengcl** [comment]
Work is continued by @swamirishi  in #4596 . Closing this PR.

**Pull request closed without merging**
