### PR TITLE
HDDS-11601. Intermittent failure in acceptance balancer test.

### PR DESCRIPTION
**Pull request by Daniilchik**
## What changes were proposed in this pull request?
Fixed LOWER_LIWIT in test-ec.sh of ozone-balancer.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-11601

## How was this patch tested?
Build-branch workflow.

### CODE REVIEW

**Comment by Daniilchik** [comment]
I'm sorry, I missed that. I'll take a look and get back with a fix

**Comment by Daniilchik** [comment]
Seems to be working now, I ran the patch several times on the build-branch workflow, and there were no errors.

**Comment by Daniilchik** [comment]
It failed again with `92291072 > 104857600 * 1.4should be true`. I’ll try changing `-i 1` to `-i 2` in `ozone admin containerbalancer start -t 0.1 -d 100 -i 1`, I think this will solve the problem.

**Comment by adoroszlai** [comment]
Thanks @Daniilchik for updating the patch.  I just launched a [repeated run](https://github.com/adoroszlai/ozone/actions/runs/11512632551) for balancer.  In the meantime, can you please resolve the conflict?

**Comment by adoroszlai** [comment]
2/10 failures:

```
Verify Container Balancer for RATIS/EC containers                     | FAIL |
'97538048 > 104857600 * 1' should be true.
```

```
Verify Container Balancer for RATIS/EC containers                     | FAIL |
'103829504 > 104857600 * 1' should be true.
```

**Comment by Daniilchik** [comment]
I've resolved the conflict and fixed `LOWER_LIMIT` in the test

**Comment by adoroszlai** [comment]
> I've resolved the conflict and fixed `LOWER_LIMIT` in the test

Thanks.

Reducing lower limit arbitrarily does not explain the difference in runs.  Let's keep this as draft until we can find the root cause of the problem.

Please check the difference between runs,

passing:

```
Number of Datanodes involved: 6. Size moved: 170 MB
```

failing:

```
Number of Datanodes involved: 5. Size moved: 96 MB
```

Maybe we need more iterations.  Maybe we need to close EC container after writing each 100MB key, to get more uniform container sizes.

**Comment by adoroszlai** [comment]
Disabled the EC test in `master` temporarily: 72e56d7508faa1248a33dc0c109b0aac10547b84

**Comment by adoroszlai** [comment]
Thanks @Daniilchik for the update.  I guess creating 3 keys instead of 5 is OK.

(FYI, when iterating on the fix and running `repeat-acceptance-test` manually, you can skip regular CI (`build-branch`) by including `[skip ci]` in the commit message.)

**Comment by Daniilchik** [comment]
Fixed the test. [Build-branch](https://github.com/Daniilchik/ozone/actions/runs/11610538633) tests passed, and the [repeat-acceptance-test](https://github.com/Daniilchik/ozone/actions/runs/11610555596) passed as well.

**Review by adoroszlai — APPROVED** [review]

**Pull request merged**
