### PR TITLE
HDDS-11890. Update project description in GitHub

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Update "About" description for Ozone in GitHub.  Copy tagline from new website:

https://github.com/apache/ozone-site/blob/52c086dbc5c3a1960527e3a67ce461c3a2669677/docusaurus.config.js#L32

https://issues.apache.org/jira/browse/HDDS-11890

## How was this patch tested?

n/a

### CODE REVIEW

**Review by nandakumar131 — APPROVED** [review]
LGTM.

**Comment by swamirishi** [comment]
thanks for reviewing the patch @nandakumar131

**Comment by adoroszlai** [comment]
Thanks @nandakumar131 for the review, @swamirishi for merging it.

**Comment by errose28** [comment]
Thanks for updating this Attila

**Pull request merged**
