### PR TITLE
HDDS-5492. Disable failing kubernetes test

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

_kubernetes_ check is failing in CI at `ozone` without any code change.  The same test is passing locally on another Kubernetes distribution.  The failure is probably caused by some environmental change related to persistent volumes.  I propose to disable the failing test temporarily, until it can be fixed.

Last successful run: https://github.com/apache/ozone/runs/3137129344
First failed run: https://github.com/apache/ozone/runs/3140001398

https://issues.apache.org/jira/browse/HDDS-5492

## How was this patch tested?

https://github.com/adoroszlai/hadoop-ozone/runs/3158417215

### CODE REVIEW

**Comment by elek** [comment]
:thinking: 

Let me try to check if it can be fixed easily instead of disabling it

**Review by elek — APPROVED** [review]
I checked and it passes locally. Also found that still we have the other k8s tests which provides basic smoketest coverage.

I am convinced that it's not a regression in the code itself, I am fine to turn it off until it's fixed.

**Comment by adoroszlai** [comment]
Thanks @elek for the review.

**Comment by GeorgeJahad** [comment]
I think the problem is a change in the k3s tool, (which explains why you probably weren't seeing it locally, if you are running an old version.)

I have a fix here:
https://github.com/apache/ozone/pull/2464

**Pull request merged**
