### PR TITLE
HDDS-7375. [Snapshot] Implement `ozone fs` command for creating snapshot

### PR DESCRIPTION
**Pull request by hemantk-12**
## What changes were proposed in this pull request?
This change is to implement create snapshot for ozone file system commands.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-7375

## How was this patch tested?
Using CLI and running following commands:
```
bash-4.2$ ozone fs -createSnapshot /vol1/bucket1 snap
Created snapshot ofs://om/vol1/bucket1/.snapshot/snap
bash-4.2$ ozone fs -createSnapshot /vol1/bucket1 snap
createSnapshot: Snapshot already exists
bash-4.2$ ozone fs -ls /vol1/bucket1/.snapshot/snap
Found 1 items
-rw-rw-rw-   3 hadoop hadoop       3811 2022-11-01 06:09 /vol1/bucket1/.snapshot/snap/key1
```

### CODE REVIEW

**Comment by smengcl** [comment]
Thanks for the patch. Can we add a test for this? Hint: you can check out `TestOzoneShellHA` as a reference.

**Comment by hemantk-12** [comment]
> Thanks for the patch. Can we add a test for this? Hint: you can check out `TestOzoneShellHA` and tests that [use](https://github.com/apache/ozone/blob/de42c614a88c9ca9a082c12625f3dff12508b648/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsHAURLs.java#L224) `FsShell` as a reference.

Thanks for reviewing it. Added integration test as suggested.

**Review by prashantpogde — APPROVED** [review]
LGTM

**Review by smengcl — APPROVED** [review]
lgtm pending CI

**Comment by smengcl** [comment]
Thanks @hemantk-12 for the patch, and @prashantpogde for the review.

**Pull request merged**
