### PR TITLE
HDDS-8315. [Snapshot] Added unit tests for SnapshotDiffManager

### PR DESCRIPTION
**Pull request by hemantk-12**
## What changes were proposed in this pull request?
This change is to add unit tests for `SnapshotDiffManager`.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-8315

## How was this patch tested?
Ran newly added test locally.

### CODE REVIEW

**Review by prashantpogde — APPROVED** [review]
@hemantk-12 Thank you for adding these test cases.

**Comment by smengcl** [comment]
Awaiting #4678 's merge.

**Comment by smengcl** [comment]
Hmm. CI `basic (unit)` is consistently crashing in `TestSnapshotDiffManager`. Looks relevant:

```
[INFO] Running org.apache.hadoop.ozone.om.snapshot.TestSnapshotDiffManager
Error:  Aborted (core dumped)
```

https://github.com/apache/ozone/actions/runs/5281655342/jobs/9566430667
https://github.com/apache/ozone/actions/runs/5281655342/jobs/9565133104
https://github.com/apache/ozone/actions/runs/5281655342/jobs/9563416683
https://github.com/apache/ozone/actions/runs/5281655342/jobs/9561043195

**Comment by hemantk-12** [comment]
> Hmm. CI `basic (unit)` is consistently crashing in `TestSnapshotDiffManager`. Looks relevant:
> 
> ```
> [INFO] Running org.apache.hadoop.ozone.om.snapshot.TestSnapshotDiffManager
> Error:  Aborted (core dumped)
> ```
> 
> https://github.com/apache/ozone/actions/runs/5281655342/jobs/9566430667 https://github.com/apache/ozone/actions/runs/5281655342/jobs/9565133104 https://github.com/apache/ozone/actions/runs/5281655342/jobs/9563416683 https://github.com/apache/ozone/actions/runs/5281655342/jobs/9561043195


Let me take a look.

**Comment by hemantk-12** [comment]
> Hmm. CI `basic (unit)` is consistently crashing in `TestSnapshotDiffManager`. Looks relevant:
> 
> ```
> [INFO] Running org.apache.hadoop.ozone.om.snapshot.TestSnapshotDiffManager
> Error:  Aborted (core dumped)
> ```
> 
> https://github.com/apache/ozone/actions/runs/5281655342/jobs/9566430667 https://github.com/apache/ozone/actions/runs/5281655342/jobs/9565133104 https://github.com/apache/ozone/actions/runs/5281655342/jobs/9563416683 https://github.com/apache/ozone/actions/runs/5281655342/jobs/9561043195

Disabled [the test](https://github.com/apache/ozone/pull/4716/files#diff-11392a9810b911a6b87f9f4440cb5e5342b2a9c112851e7dceafa5103d999e1dR1023) which was causing this failure for now.

Ran it few times and it has passed on my remote repo.
* https://github.com/hemantk-12/ozone/actions/runs/5330463999/jobs/9657161252
* https://github.com/hemantk-12/ozone/actions/runs/5330721864/jobs/9657706212 and https://github.com/hemantk-12/ozone/actions/runs/5330655758/jobs/9657563154
* Ran it 25 times: https://github.com/hemantk-12/ozone/actions/runs/5330731037/jobs/9657730560

**Comment by umamaheswararao** [comment]
@hemantk-12 this needs conflicts resolving. PTAL.

**Review by prashantpogde — APPROVED** [review]
Thank you @hemantk-12 for making these changes.

**Pull request merged**
