### PR TITLE
HDDS-4419. Misleading SCM web UI Safe mode status 

### PR DESCRIPTION
**Pull request by elek**
## What changes were proposed in this pull request?

Improve the usability of SafeMode rule table on the web ui.
See the reports in the JIRA.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4419

## How was this patch tested?

Started and checked the UI

### CODE REVIEW

**Comment by jojochuang** [comment]
Looks good to me, but I was confused initially. This PR was raised for HDDS-4419, isn't it?
Would be nice to take a screenshot, though not required.

**Comment by elek** [comment]
> Looks good to me, but I was confused initially. This PR was raised for HDDS-4419, isn't it?

yes, sorry for the confusion. Fixing.

(Second PR where I made this mistake. For me this double accounting (jira + github) couldn't help.)

**Comment by elek** [comment]
This is the screenshot (of the relevant part):

image

**Review by jojochuang — APPROVED** [review]
LGTM thx.

**Comment by elek** [comment]
Merging it now. Thanks the review @jojochuang

**Pull request merged**
