### PR TITLE
HDDS-7432. Move command summary into Commands object in CommandQueue

### PR DESCRIPTION
**Pull request by sodonnel**
## What changes were proposed in this pull request?

In [HDDS-7402](https://issues.apache.org/jira/browse/HDDS-7402) it was suggested to move the CommandSummary tracking into the Commands inner class. This Jira is to make that small change.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7432

## How was this patch tested?

Existing test added in [HDDS-7402](https://issues.apache.org/jira/browse/HDDS-7402) covers this.

### CODE REVIEW

**Comment by sodonnel** [comment]
Mentioning @swamirishi as it will not let me add you as a reviewer for some reason.

**Review by aswinshakil — COMMENTED** [review]
I took a quick look at the changes. It looks good to me. Let @swamirishi also take a look as he reviewed the previous patch.

**Review by swamirishi — APPROVED** [review]
LGTM

**Review by umamaheswararao — APPROVED** [review]
LGTM

**Pull request merged**
