### PR TITLE
HDDS-4546. Change ozone.datanode.pipeline.limit to 3 by default

### PR DESCRIPTION
**Pull request by sky76093016**
## What changes were proposed in this pull request?

modify "ozone.datanode.pipeline.limit" to 3

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4546

## How was this patch tested?

no test.

### CODE REVIEW

**Comment by adoroszlai** [comment]
@sky76093016 Thanks for working on this.  Test failures seem related to the change in config.

**Comment by sky76093016** [comment]
I tried to make changes but test failures still appear. Do @adoroszlai  have any comments?Thank you.

**Comment by adoroszlai** [comment]
Acceptance test fails because Recon test expects 4 pipelines:

https://github.com/apache/ozone/blob/039d74a69e091b2307c3569b87ea9a3b9e7b4632/hadoop-ozone/dist/src/main/smoketest/recon/recon-api.robot#L63

but now with the increased limit it finds 5:

```
Check if Recon picks up DN heartbeats                                 | FAIL |
'{"pipelines":5,"totalDatanodes":3,"healthyDatanodes":3,"storageReport":{"capacity":267934076928,"used":24576,"remaining":56696799232},"containers":5,"volumes":23,"buckets":87,"keys":171}' does not contain '"pipelines":4'
```

https://github.com/apache/ozone/pull/1657/checks?check_run_id=1555607541#step:7:1684

I think this can be fixed simply by changing the expectation to 5.

Failing integration tests could probably be fixed by manually configuring `....pipeline.limit` to its previous default value of 2.

**Comment by bshashikant** [comment]
This will be addressed with https://github.com/apache/ozone/pull/1717 with some additional changes.

**Comment by sky76093016** [comment]
Thanks to @adoroszlai  for the suggestion, green build has been completed.

**Comment by adoroszlai** [comment]
Thanks @sky76093016 for fixing the tests.

If I understand correctly, @bshashikant's comment says that this change is superseded by #1717 and the PR can be closed without merge.

**Comment by bshashikant** [comment]
Closing this as this has been addressed with https://github.com/apache/ozone/pull/1717.

**Pull request closed without merging**
