### PR TITLE
HDDS-6282. Fix BlockDataStreamOutput#doFlushIfNeeded NPE

### PR DESCRIPTION
**Pull request by guohao-rosicky**
## What changes were proposed in this pull request?

Fix BlockDataStreamOutput#doFlushIfNeeded NPE

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-6282

### CODE REVIEW

**Review by ayushtkn — CHANGES_REQUESTED** [review]
Add a test case

**Comment by guohao-rosicky** [comment]
> Add a test case

This is a fix for a bug that reported errors in JIRA. Use the existing test.

**Comment by captainzmc** [comment]
> Add a test case

Thanks @ayushtkn for the review. this bug was found in our patch that s3gateway support streaming write(HDDS-5869). 
After we enabled s3 streaming, we found that [many CI test cases were reported to NPE](https://github.com/captainzmc/hadoop-ozone/runs/4933136860?check_suite_focus=true#step:4:7959). So, there are enough test cases to support this PR.
After this PR merge, we will continue the development of #2858.

**Comment by captainzmc** [comment]
Hi @guohao-rosicky  HDDS-4454 was synchronous with master branch. Can you rebase this patch？ I think we can merge this bug fix first and continue #2858.

**Review by captainzmc — APPROVED** [review]
+1 The change looks good.

**Comment by captainzmc** [comment]
Failed CI has nothing to do with this PR. Let's merge this patch first and then continue HDDS-5869. Thanks @guohao-rosicky fix this and thanks @ayushtkn for the review.

**Pull request merged**
