### PR TITLE
HDDS-5417. Fix json parse stackoverflow for cmd ozone debug container list.

### PR DESCRIPTION
**Pull request by guihecheng**
## What changes were proposed in this pull request?

Fix json parse stackoverflow for cmd ozone debug container list.
Detailed descriptions in the JIRA.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5417

## How was this patch tested?

manual test.

### CODE REVIEW

**Comment by guihecheng** [comment]
Hi @adoroszlai , could you please help review this, this bug is after this pr: https://github.com/apache/ozone/pull/2158
which add the VolumeSet field into HddsVolume.

**Review by adoroszlai — APPROVED** [review]
Thanks @guihecheng for the fix.  I have verified both the problem and the fix.

(I would prefer adding a test case, but `debug` smoketest is currently not included in any suites.)

**Comment by guihecheng** [comment]
Thanks @adoroszlai , hmmm, it is nice to have a new suite for debug, we could do it later.

**Comment by adoroszlai** [comment]
Thanks @guihecheng for the fix.

**Pull request merged**
