### PR TITLE
HDDS-6602. Incorrect logic in PipelineProvider.pickNodesNotUsed

### PR DESCRIPTION
**Pull request by symious**
## What changes were proposed in this pull request?

In PipelineProvider, pickNodesNotUsed(CONFIG, long, long) filter the results from pickNodesNotUsed(CONFIG) based on metadata/data size.

But in pickNodesNotUsed(CONFIG), the result size is limited by the ReplicationConfig's required node, which means many other usable nodes will not be seen by pickNodesNotUsed(CONFIG, long, long).

This ticket is to solve this issue.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-6602

## How was this patch tested?

unit test.

### CODE REVIEW

**Comment by symious** [comment]
@adoroszlai @errose28 Could you help to review?

**Review by errose28 — COMMENTED** [review]
Good catch @symious. `PipelineProvider` LGTM. Can you clarify how the test changes are related to the bug?

**Comment by symious** [comment]
@errose28 Thanks for the review.

> Can you clarify how the test changes are related to the bug?

Sure. In `TestRatisPipelineProvider.testCreatePipelinesWhenNotEnoughSpace()`, the datanodes' details are created in `init(1, largeContainerConf);`, which can be trace back to `MockNodeManager.populateNodeMetric(...)`, so the datanodes are as follows:
```
      new NodeData(10L * OzoneConsts.TB, OzoneConsts.GB),
      new NodeData(64L * OzoneConsts.TB, 100 * OzoneConsts.GB),
      new NodeData(128L * OzoneConsts.TB, 256 * OzoneConsts.GB),
      new NodeData(40L * OzoneConsts.TB, OzoneConsts.TB),
      new NodeData(256L * OzoneConsts.TB, 200 * OzoneConsts.TB),
      new NodeData(20L * OzoneConsts.TB, 10 * OzoneConsts.GB),
      new NodeData(32L * OzoneConsts.TB, 16 * OzoneConsts.TB),
      new NodeData(OzoneConsts.TB, 900 * OzoneConsts.GB),
      new NodeData(OzoneConsts.TB, 900 * OzoneConsts.GB, NodeData.STALE),
      new NodeData(OzoneConsts.TB, 200L * OzoneConsts.GB, NodeData.STALE),
      new NodeData(OzoneConsts.TB, 200L * OzoneConsts.GB, NodeData.DEAD)
```
In original implementation, the result of `pickNodesNotUsed()` only includes the first datanode, what the remaining capacity is `10TB - 1GB`, which doesn't fulfill the size requirement of `100TB`, so the original implemtation would throw exception.

In new implementation, the result of `pickAllNodesNotUsed()` will include the first 8 datanodes, then `provider` will choose from the all 8 datanodes that fulfills the size requirement of `100TB`, and the result will be the third datanode, so exceptions won't be thrown.

So in order to throw the exception to keep the original assert, we need to change the size to a larger value that all 8 datanodes can't fulfill. And the change will also verify the correctness of the new implementation.

**Comment by ChenSammi** [comment]
The patch LGTM, +1.  

Thanks @symious for fix this, and @errose28 for the code review.

**Comment by ChenSammi** [comment]
> Sure. In `TestRatisPipelineProvider.testCreatePipelinesWhenNotEnoughSpace()`, the datanodes' details are created in `init(1, largeContainerConf);`, which can be trace back to `MockNodeManager.populateNodeMetric(...)`, so the datanodes are as follows:
> 
> ```
>       new NodeData(10L * OzoneConsts.TB, OzoneConsts.GB),
>       new NodeData(64L * OzoneConsts.TB, 100 * OzoneConsts.GB),
>       new NodeData(128L * OzoneConsts.TB, 256 * OzoneConsts.GB),
>       new NodeData(40L * OzoneConsts.TB, OzoneConsts.TB),
>       new NodeData(256L * OzoneConsts.TB, 200 * OzoneConsts.TB),
>       new NodeData(20L * OzoneConsts.TB, 10 * OzoneConsts.GB),
>       new NodeData(32L * OzoneConsts.TB, 16 * OzoneConsts.TB),
>       new NodeData(OzoneConsts.TB, 900 * OzoneConsts.GB),
>       new NodeData(OzoneConsts.TB, 900 * OzoneConsts.GB, NodeData.STALE),
>       new NodeData(OzoneConsts.TB, 200L * OzoneConsts.GB, NodeData.STALE),
>       new NodeData(OzoneConsts.TB, 200L * OzoneConsts.GB, NodeData.DEAD)
> ```
> 
> In original implementation, the result of `pickNodesNotUsed()` only includes the first datanode, what the remaining capacity is `10TB - 1GB`, which doesn't fulfill the size requirement of `100TB`, so the original implemtation would throw exception.
> 
> In new implementation, the result of `pickAllNodesNotUsed()` will include the first 8 datanodes, then `provider` will choose from the all 8 datanodes that fulfills the size requirement of `100TB`, and the result will be the third datanode, so exceptions won't be thrown.
> 
> So in order to throw the exception to keep the original assert, we need to change the size to a larger value that all 8 datanodes can't fulfill. And the change will also verify the correctness of the new implementation.

This explanation is very clear.  However,  I would suggest to add a new straightforward test case in case of this in future. That will help the reviewer understand the code change more easily. Then the code review will be more efficient.

**Comment by symious** [comment]
@ChenSammi @errose28 Thank you for the review.

> However, I would suggest to add a new straightforward test case in case of this in future. That will help the reviewer understand the code change more easily. Then the code review will be more efficient.

Noted with thanks.

**Pull request merged**
