### PR TITLE
HDDS-5782. DatanodeRatisGrpcConfig use wrong type for config keys.

### PR DESCRIPTION
**Pull request by ChenSammi**
https://issues.apache.org/jira/browse/HDDS-5782

### CODE REVIEW

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by ChenSammi** [comment]
Thanks @ayushtkn  for the code review. The failed UT is irrelevant.

**Review by JacksonYao287 — APPROVED** [review]
thanks @ChenSammi for the work! LGTM +1

**Comment by ChenSammi** [comment]
The build is green.  I will merge it.  Thanks all for the code review.

**Pull request merged**
