### PR TITLE
HDDS-11306. OM support system audit log

### PR DESCRIPTION
**Pull request by sumitagrawl**
## What changes were proposed in this pull request?

system audit log framework is added for OM. This is added with having log for startup of OM. This can be used further to added logs for below operation:
- internal request like open file cleanup, purge directory, ...
- other operation critical for debugging

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-11306

## How was this patch tested?

- verified logs over docker and below is the result,
image

### CODE REVIEW

**Review by devmadhuu — APPROVED** [review]
Thanks @sumitagrawl for the patch. LGTM +1

**Comment by errose28** [comment]
Thanks for adding this @sumitagrawl this will be great to have. Are we planning on adding other messages like leader change and open key cleanup in this PR or followup tasks?

**Comment by sumitagrawl** [comment]
> Thanks for adding this @sumitagrawl this will be great to have. Are we planning on adding other messages like leader change and open key cleanup in this PR or followup tasks?

Will be doing in followup PR

**Comment by devmadhuu** [comment]
Thanks @errose28 for review. Thanks @sumitagrawl for the patch.

**Pull request merged**
