### PR TITLE
HDDS-7106. [DiskBalancer] Client-SCM interface (#3663)

### PR DESCRIPTION
**Pull request by ferhui**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## What is the link to the Apache JIRA

(Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HDDS-XXXX. Fix a typo in YYY.)

Please replace this section with the link to the Apache JIRA)

## How was this patch tested?

(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

### CODE REVIEW

**Comment by ferhui** [comment]
@symious It is rebased on master branch, we can push it after CI passes. Please check it again.

**Comment by adoroszlai** [comment]
> It is rebased on master branch, we can push it after CI passes.

Based on @errose28's [comment](https://github.com/apache/ozone/pull/3663#issuecomment-1215771924) from #3663, I think this should wait until release branch for 1.3 is cut.

**Comment by ferhui** [comment]
@adoroszlai Hi, This PR aims to check whether develop branch is good. Because I did a rebase operation to let develop branch catches master. 
Will *not* merge this PR.

**Comment by adoroszlai** [comment]
@ferhui Is the only purpose of this PR to run CI checks?  Those are also run in your fork here: https://github.com/ferhui/ozone/actions/runs/2917658837

**Comment by ferhui** [comment]
> Is the only purpose of this PR to run CI checks? 
Yes.

>Those are also run in your fork here: https://github.com/ferhui/ozone/actions/runs/2917658837
After It passes, will update the develop branch.

**Comment by adoroszlai** [comment]
> > Is the only purpose of this PR to run CI checks?
> 
> Yes.
> 
> > Those are also run in your fork here: https://github.com/ferhui/ozone/actions/runs/2917658837
> 
> After It passes, will update the develop branch.

Fine, but I think it can be updated without PR next time.  All other steps are the same: push to your fork, wait for CI, update feature branch in `apache/ozone`.

**Comment by ferhui** [comment]
@adoroszlai Thanks for your explanation.
May I have a question?
>wait for CI

I am not sure about it, how to wait for CI if no PR?

**Comment by adoroszlai** [comment]
> I am not sure about it, how to wait for CI if no PR?

Checks are run for both PR and commit ("push" event).  To find the CI workflow for the commit in your fork:

1. Open the branch in your fork: https://github.com/ferhui/ozone/tree/HDDS-5713
2. Click on the "4921 commits" text -> leads to https://github.com/ferhui/ozone/commits/HDDS-5713
3. Click on the CI indicator (yellow circle, red x or green checkmark) for the latest commit
4. Click on "Details" for any check in the popup -> leads to https://github.com/ferhui/ozone/runs/7990725854?check_suite_focus=true
5. Click on "Summary" at the top left: https://github.com/ferhui/ozone/actions/runs/2917658837

This workflow run is almost the same as one in the PR, with two differences:
 * It checks your commit, while the PR checks a special "merge your commit into master".  (So if there are any newer commits in master after yours, those are included as well.  If your branch is up-to-date with master, then there is no real difference.)
 * It is always a complete run, while PR may skip some checks depending on the kind of change.

**Comment by adoroszlai** [comment]
@ferhui All checks passed, closing.

**Comment by ferhui** [comment]
@adoroszlai I learnt a lot from you, thanks!

**Pull request closed without merging**
