### PR TITLE
HDDS-7587. Update NOTICE and LICENSE in license/bin/

### PR DESCRIPTION
**Pull request by captainzmc**
## What changes were proposed in this pull request?

We had fix NOTICE and LICENSE in [HDDS-7567](https://issues.apache.org/jira/browse/HDDS-7567) and [HDDS-7568](https://issues.apache.org/jira/browse/HDDS-7568) in src. We should also update the NOTICE and LICENSES in license/bin/.

In this patch, we mainly update the LICENSE and NOTICE that need to be modified, and delete the not needed (Some are no longer used in the project, and some need to change the format from html to txt). 

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7587

## How was this patch tested?

No need.

### CODE REVIEW

**Comment by captainzmc** [comment]
hi, @szetszwo, could you help review this PR? After this is done we will start Ozone RC2.

**Comment by szetszwo** [comment]
@captainzmc , I am traveling so that I may not be able to review this for a few days.

@kaijchen, would you be able to review this?

**Comment by kaijchen** [comment]
There are 267 jars under `ozone-1.3.0/share/ozone/lib`, 250 of them does not contain `ozone` in their name.
If I understand correctly, we should add LICENSE for all those jars included in the binary package.
For jars from the same project, one LICENSE for each project should be enough.

For example, we should add LICENSE for grpc:

```console
$ ls ozone-1.3.0/share/ozone/lib/grpc*
grpc-api-1.48.1.jar
grpc-context-1.48.1.jar
grpc-core-1.48.1.jar
grpc-netty-1.48.1.jar
grpc-protobuf-1.48.1.jar
grpc-protobuf-lite-1.48.1.jar
grpc-stub-1.48.1.jar
```

**Comment by kaijchen** [comment]
The current change looks good. @szetszwo do we need to check licenses for indirect dependencies also?

**Review by kaijchen — APPROVED** [review]

**Comment by szetszwo** [comment]
> Dependencies of dependencies (including so-called "transitive dependencies") are no different from first-order dependencies for the purposes of assembling LICENSE and NOTICE: LICENSE and NOTICE need only be modified to accommodate them only if their bits are bundled.

@kaijchen , the above is quoted from https://infra.apache.org/licensing-howto.html

**Comment by szetszwo** [comment]
@captainzmc , I am checking the license and notice.
- The ratis notice somehow is missing.
- How about updating the ratis and ratis-thirdparty version to 2.4.1 and 1.0.3?

**Review by szetszwo — COMMENTED** [review]
@captainzmc , thanks a lot for working on this!  Tried the following:

1. Generate the release tarball and untar it.
2. Get the jar list: `ls -R share/ozone/lib/`
3. Check the license for each jar.

The jar list has 267 lines.  I checked 144 lines so far.  Got the following changes: https://issues.apache.org/jira/secure/attachment/13053665/4039_review.patch

**Comment by captainzmc** [comment]
Thanks @szetszwo for the patch provided. I will continue to check all jars and update the LICENSE. 
About upgrading ratis to 2.4.1, I recommend not upgrading for in Ozone 1.3.0. Mainly for stability.
We have tested Ozone-1.3.0 use ratis 2.4.0 and found no problem. Upgrade 2.4.1 I'm afraid we don't have time to run the stability test. In addition, I have verified 2.4.1 before, and it seems that [Ozone CI has some OOM problems](https://github.com/captainzmc/hadoop-ozone/actions/runs/3531661540/jobs/5926521476#step:5:3291).

**Comment by szetszwo** [comment]
@captainzmc , sure, we can upgrade Ratis later.

Will continue checking the license tomorrow.

**Comment by szetszwo** [comment]
@captainzmc , just have check all the remaining licenses; see https://issues.apache.org/jira/secure/attachment/13053715/4039_review2.patch

**Comment by captainzmc** [comment]
Thanks @szetszwo! I had updated LICENSE.txt.

**Comment by szetszwo** [comment]
> The ratis notice somehow is missing.

We already have `NOTICE-ratis-thirtparty-misc.txt` so that it is okay.  We should update it as below.  BTW, there is a TYPO in the file name of `NOTICE-ratis-thirtparty-misc.txt` -- "thirtparty" was misspelled.

```diff
diff --git a/hadoop-ozone/dist/src/main/license/bin/licenses/NOTICE-ratis-thirtparty-misc.txt b/hadoop-ozone/dist/src/main/license/bin/licenses/NOTICE-ratis-thirdparty-misc.txt
similarity index 94%
rename from hadoop-ozone/dist/src/main/license/bin/licenses/NOTICE-ratis-thirtparty-misc.txt
rename to hadoop-ozone/dist/src/main/license/bin/licenses/NOTICE-ratis-thirdparty-misc.txt
index a4915c6ae..c47cb75fe 100644
--- a/hadoop-ozone/dist/src/main/license/bin/licenses/NOTICE-ratis-thirtparty-misc.txt
+++ b/hadoop-ozone/dist/src/main/license/bin/licenses/NOTICE-ratis-thirdparty-misc.txt
@@ -1,5 +1,5 @@
 Apache Ratis
-Copyright 2021 The Apache Software Foundation
+Copyright 2017-2022 The Apache Software Foundation
 
 This product includes software developed at
 The Apache Software Foundation (http://www.apache.org/).
@@ -316,25 +316,3 @@ LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 -----------------------------------------------------------------------
-This product uses the dropwizard-hadoop-metrics2.
-
-Copyright 2016 Josh Elser
-
-Licensed under the Apache License v2.0
-
------------------------------------------------------------------------
-This product uses https://github.com/mbocek/docker-ganglia/
-
-Contributed by Michal Bocek
-
-Licensed under the Apache License v2.0
-https://github.com/mbocek/docker-ganglia/blob/master/LICENSE
-
------------------------------------------------------------------------
-This product uses https://github.com/graphite-project/docker-graphite-statsd
-
-Copyright (c) 2013-2016 Nathan Hopkins
-
-Licensed under the MIT License
```

**Comment by captainzmc** [comment]
Thanks @szetszwo for the advice, Just had updated the ratis-thirdparty NOTICE.

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by captainzmc** [comment]
Thanks @szetszwo @kaijchen for the review. Let's merge this. I will start 1.3.0 RC2.

**Comment by kaijchen** [comment]
Thanks @captainzmc and @szetszwo for checking all the dependencies.

**Pull request merged**
