### PR TITLE
HDDS-4785. Document run configuration launch order

### PR DESCRIPTION
**Pull request by vyaslav**
## What changes were proposed in this pull request?

Run configurations startup order

## What is the link to the Apache JIRA

NO

### CODE REVIEW

**Review by adoroszlai — APPROVED** [review]
Thanks @vyaslav for the clarification on how to run Ozone from IDE.  Do you have an Apache Jira user?

**Comment by vyaslav** [comment]
> Thanks @vyaslav for the clarification on how to run Ozone from IDE. Do you have an Apache Jira user?

Thanks for approving @adoroszlai , my Apache Jira Username is `vavramenko`

**Comment by adoroszlai** [comment]
Thanks @vyaslav!

**Comment by amaliujia** [comment]
LGTM thanks @vyaslav for documenting these steps! Now I don't need to watch Ozone videos to find out the steps :)

**Pull request merged**
