### PR TITLE
HDDS-6260. EC: Standalone containers should not move to quasi-closed

### PR DESCRIPTION
**Pull request by sodonnel**
## What changes were proposed in this pull request?

EC Containers use standalone containers when writing. Closing any EC Container results in the container going into a quasi-closed state until the ReplicationManager process checks it and forces it closed.

Quasis-closed is a state only applicable to RATIS containers, as it implies the ratis pipeline has been lost and the container is unable to achieve quorum on closing.

Standalone containers don't have this problem and hence should never go to quasi-closed.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-6260

## How was this patch tested?

Added a new unit test to validate the new logic. Also verified in docker-compose that EC containers no longer goto quasi-close when they are closed like before.

### CODE REVIEW

**Comment by sodonnel** [comment]
Actually, reviewing my testing of the docker compose cluster - this change still doesn't fix it. EC and standalone containers still end up going quasi-closed. I need to rethink it.

**Review by JacksonYao287 — APPROVED** [review]
I also notice this issue too. thanks @sodonnel for the patch. LTGM +1

**Comment by sodonnel** [comment]
I don't think it is possible to tell on the datanode whether a container is RATIS or STAND_ALONE.

The client knows what sort of replication the container should have, and in Ozone, unlike HDFS, the client writes to all 3 DNs in the pipeline. In HDFS DN1 forwards to DN2 etc, so the DNs must know the replication, but in Ozone, this is invisible to the client.

Any Ratis magic is handled by the XceiverServerRatis on the DN, and standalone writes goto XceiverServerGRPC. On the Ozone client, it knows the replication type, and will invoke the correct Xceiver on the server.

When we come to the CloseContainerCommandHandler, it tries to close a container, and it looks for the pipleine associated with it in ozoneContainer.writeChannel:

```
ozoneContainer.getWriteChannel().isExist(closeCommand.getPipelineID()
```

But the write channel is always the XceiverClientRatis, so when we don't find the ratis pipeline for a standalone container (which we never will), the check fails and the container goes quasi-closed.

Aside from some extensive changes on the DN, the only way I can think of to fix this easily, is to add a replicationType field to the closeContainerCommand proto. SCM creates this, and hence must know what sort of container it is - we could easily add replicationType (EC, Standalone, Ratis) to the command and use that in the close handler.

**Comment by sodonnel** [comment]
@nandakumar131 Could you have another look at this please, and let me know if it looks good or needs more changes?

**Review by adoroszlai — APPROVED** [review]
LGTM.

**Review by nandakumar131 — COMMENTED** [review]
+1, LGTM.

**Pull request merged**
