### PR TITLE
HDDS-6954. Migrate simple tests in ozone-recon to JUnit5

### PR DESCRIPTION
**Pull request by kaijchen**
## What changes were proposed in this pull request?

Migrate simple tests in ozone-recon to JUnit5.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-6954

## How was this patch tested?

https://github.com/kaijchen/ozone/actions/runs/2568738472

### CODE REVIEW

**Comment by umamaheswararao** [comment]
@swamirishi please help to review this?

**Review by swamirishi — APPROVED** [review]
LGTM

**Review by adoroszlai — APPROVED** [review]

**Comment by adoroszlai** [comment]
Thanks @kaijchen for the patch, @swamirishi for the review.

**Comment by kaijchen** [comment]
Thanks @swamirishi and @adoroszlai for the review.

**Pull request merged**
