### PR TITLE
HDDS-8482. Let Ozone shell support multiple OM services

### PR DESCRIPTION
**Pull request by whbing**
## What changes were proposed in this pull request?

Ozone cli support multiple ozone.om.service.ids

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8482

## How was this patch tested?

manual tests passed.

without pr:
```bash
$ ozone sh vol ls o3://ozone1
Following ServiceID's [ozone1, ozone2] are defined in the configuration. Use the method getRpcClient which takes serviceID and configuration as param
```

with pr:
```bash
# case1
$ ozone sh vol ls o3://ozone1
[ {
  "metadata" : { }...
]

# case2
$ ozone sh vol ls o3://ozone2
[ {
  "metadata" : { }...
]

# case3
ozone sh vol ls
Service ID or host name must not be omitted when multiple ozone.om.service.ids is defined  
```

### CODE REVIEW

**Review by Xushaohong — APPROVED** [review]
This is exactly the case under the condition **"When host is an HA service ID"** as the code
`if (OmUtils.isOmHAServiceId(conf, ozoneURI.getHost())) `, it is fine to choose the service id through URI host. 
LTGM. Thanks @whbing  for the work.

**Comment by whbing** [comment]
@Xushaohong Thanks for review.  Added test.

**Review by Xushaohong — APPROVED** [review]

**Comment by whbing** [comment]
All tests  passed in https://github.com/whbing/ozone/actions/runs/4794048829
please help trigger this workflows, thanks.

**Comment by adoroszlai** [comment]
Thanks @whbing for the patch, @Xushaohong for the review.

**Pull request merged**
