### PR TITLE
HDDS-11368. Remove dependency on Babel in Vite

### PR DESCRIPTION
**Pull request by devabhishekpal**
## What changes were proposed in this pull request?
Remove dependency on Babel in Vite

Please describe your PR in detail:
* Babel currently uses caniuse-lite as a transitive dependency and it cannot be included in Apache projects
* Recon is already using Vite for builds, but has Babel usage due to the plugin-react, and svgr plugins.
* This PR uses plugin-react-swc to use SWC instead of Babel for transpilation, and removed dependency on SVGR plugin as we are manually exporting SVG icons as React componets.
* There are no Babel plugins currently being used for transpilation, hence the switch from Babel to SWC is also a simple replacement

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-11368

## How was this patch tested?
Patch was tested manually, as well as by running the initial unit tests added to verify no features are broken.

| Screenshot | Description |
|------------|-------------|
|Screenshot 2024-08-26 at 17 44 20|pnpm why output|
|Screenshot 2024-08-26 at 17 45 03 |Overview Page|
|Screenshot 2024-08-26 at 17 45 13|Volumes Page|
|Screenshot 2024-08-26 at 17 45 24 |Volumes Page ACL panel|
|Screenshot 2024-08-26 at 17 45 51|Buckets Page|
| |Datanodes Page|
|Screenshot 2024-08-26 at 17 46 45|Pipelines Page|
| |Containers Page|
|Screenshot 2024-08-26 at 17 47 36| Insights Page File Size Distribution|
|Screenshot 2024-08-26 at 17 47 47|Insights Page Container Size Distribution|
|Screenshot 2024-08-26 at 17 51 43|Overview Page V2|
|Screenshot 2024-08-26 at 17 52 03|Volumes Page V2|
|Screenshot 2024-08-26 at 17 52 11|Volumes Page V2 ACL Panel|

### CODE REVIEW

**Comment by devabhishekpal** [comment]
**For reviewers make sure the following are cross-checked**
- No SVG icons are broken
- Running `pnpm why caniuse-lite` doesn't give any results, meaning caniuse-lite is removed from the project as a dependency

**Comment by devabhishekpal** [comment]
@smitajoshi12 could you help review this PR?

**Comment by smitajoshi12** [comment]
It looks good to me Can you add screenshot of pnpm why caniuse-lite or other transitive dependency license check command.

**Review by ivandika3 — APPROVED** [review]
Thanks @devabhishekpal for the patch, after reading a bit about SWC vs Babel, LGTM +1.

**Comment by ivandika3** [comment]
Thanks @devabhishekpal for tackling the license issue and @devmadhuu for the review.

**Pull request merged**
