### PR TITLE
HDDS-9453. scm-leader-transfer.robot not part of any acceptance test

### PR DESCRIPTION
**Pull request by LZD-PratyushBhatt**
## What changes were proposed in this pull request?

scmha/scm-leader-transfer.robot is not run in any test suite currently.
Aim is to execute this test for atleast one of the suite.

## What is the link to the Apache JIRA
[HDDS-9453](https://issues.apache.org/jira/browse/HDDS-9453)

## How was this patch tested?

CI

### CODE REVIEW

**Comment by kerneltime** [comment]
cc @tanvipenumudy @swamirishi can you please take a look.

**Comment by tanvipenumudy** [comment]
`scm-leader-transfer.robot` was part of `ozonesecure-ha/test.sh` until the change: HDDS-8689, PR https://github.com/apache/ozone/pull/4943 (looks like it has been moved to the `cert-rotation` suite).

**Comment by LZD-PratyushBhatt** [comment]
> `scm-leader-transfer.robot` was part of `ozonesecure-ha/test.sh` until the change: [HDDS-8689](https://issues.apache.org/jira/browse/HDDS-8689), PR #4943 (looks like it has been moved to the `cert-rotation` suite).

Hi @tanvipenumudy , I dont see it being executed as part of https://github.com/apache/ozone/actions/runs/6538885863/job/17774323240?pr=5439 CI, this is for cert-rotation acceptance tests. 
[This](https://github.com/apache/ozone/commit/86607e6349919d97b0af0580a041f02bb274338c) commit disabled the root-ca-rotation tests hence disabling this test too. 
So currently its not being called anywhere.

**Review by adoroszlai — APPROVED** [review]

**Comment by adoroszlai** [comment]
Thanks @LZD-PratyushBhatt for the patch, @tanvipenumudy for the review.

**Pull request merged**
