### PR TITLE
HDDS-6717. Allow running flaky-test-check with specific Ratis commit

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

- Create a callable workflow to build some Ratis commit.
- Let `flaky-test-check` optionally run tests with custom Ratis build it creates by calling the reusable workflow.

This allows testing whether Ratis changes fix or break Ozone tests.

https://issues.apache.org/jira/browse/HDDS-6717

## How was this patch tested?

Run with Ratis build:
https://github.com/adoroszlai/ozone/actions/runs/9062089939

Run without Ratis build:
~https://github.com/adoroszlai/ozone/actions/runs/9066332817~ (skipped Ozone build, too)
https://github.com/adoroszlai/ozone/actions/runs/9068054687 (with Ozone build despite skipped Ratis build)

### CODE REVIEW

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Review by smengcl — APPROVED** [review]
Thanks @adoroszlai for the CI improvement!

**Review by sadanand48 — APPROVED** [review]
Thanks @adoroszlai for the patch, LGTM.

**Comment by adoroszlai** [comment]
Thanks @sadanand48, @smengcl, @szetszwo for the review.

**Pull request merged**
