### PR TITLE
HDDS-5084. Include HISTORY.md/SECURITY.md/CONTRIBUTING.md in the release artifacts.

### PR DESCRIPTION
**Pull request by elek**
JIRA: https://issues.apache.org/jira/browse/HDDS-5084

## What changes were proposed in this pull request?

During the ozone-1.1.0 vote I realized that `HISTORY.md`/`SECURITY.md`/`CONTRIBUTING.md` files are missing from the `bin` and `src` artifacts. I think they include very useful information and would be better to include them in the release artifacts.

## How was this patch tested?

```
mvn clean install -Dmaven.javadoc.skip=true -DskipTests -Psign,dist,src -Dtar -Dgpg.keyname=$CODESIGNINGKEY
  cd hadoop-ozone/dist/target/
tar tzf hadoop-ozone-1.1.0-SNAPSHOT.tar.gz
tar tzf hadoop-ozone-1.1.0-src-SNAPSHOT.tar.gz
```

### CODE REVIEW

**Review by mukul1987 — CHANGES_REQUESTED** [review]
We should update the History.md, it is quite old right now. Including it in the current form in the release doesn't makes sense.

**Comment by adoroszlai** [comment]
> We should update the History.md, it is quite old right now.

@mukul1987 This is a good suggestion, but I disagree with the other statement:

> Including it in the current form in the release doesn't makes sense.

1. It is not going to be part of the 1.1.0 release, so there is plenty of time to update it until the next one.
2. It's not only about HISTORY.md, but other two docs as well.
3. Writing prose for the history doc is quite distinct from updating a script to copy some files.  It may very well be updated by other people, not necessarily @elek.

So I think this change is fine in its scope.

**Comment by mukul1987** [comment]
Fair point @adoroszlai. Can we please create a followup jira and mark it as a blocker for 1.2.0 release? I feel if we will update the history by the next release, then we should be good.

**Comment by elek** [comment]
Thanks the suggestion @mukul1987, very good point.

It seems to be a small update, so I created the patch itself (please see #2149). And agree: as we have PRs for both problems in our radar we can merge the two PRs in any order.

**Comment by mukul1987** [comment]
Thanks Marton. +1 for this patch as well.
I have already added +1 to the other patch.

Thanks for updating the file.

**Review by mukul1987 — APPROVED** [review]
+1,lgrm

**Review by ayushtkn — APPROVED** [review]

**Comment by elek** [comment]
Thanks the review @mukul1987 @ayushtkn and @adoroszlai 

I am merging it after the green build.

**Pull request merged**
