### PR TITLE
HDDS-4649. Upgrade ratis to 1.1.0-35f17fa-SNAPSHOT to address incompatible changes

### PR DESCRIPTION
**Pull request by runzhiwang**
## What changes were proposed in this pull request?

Upgrade ratis to 1.1.0-35f17fa-SNAPSHOT to address incompatible changes

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4649

## How was this patch tested?

no need to add new ut

### CODE REVIEW

**Comment by runzhiwang** [comment]
@elek Could you help review this ? Thanks a lot.

**Comment by amaliujia** [comment]
LGTM

**Comment by lamber-ken** [comment]
hi @runzhiwang, I can't understand why not use `1.1.0-SNAPSHOT` as ratis version? : )

**Comment by elek** [comment]
Thanks the patch @runzhiwang 

I am not sure about the current strategy. We need a Ratis release ASAP to release Ozone 1.1.

On the Ratis mailing list it was suggested to make a backward compatible version from Ratis (1.1) and a 2.0 from the current master.

With this patch it seems that we follow the backward in-compatible changes of Ratis and update to the latest master.

I am fine with that (I think it's less work, seems to be the simplest approach) but it means that we need Ratis 2.0 release for the next Ozone release which may be harder.

@mukul1987 @szetszwo what do you think?

**Comment by runzhiwang** [comment]
@elek Hi, ozone has upgrade ratis version to 1.1.0-c5eafb9-SNAPSHOT in master branch, if we want to use Ratis 1.1, we need to skip some commit in current ozone master.

**Comment by szetszwo** [comment]
> On the Ratis mailing list it was suggested to make a backward compatible version from Ratis (1.1) and a 2.0 from the current master.

I agree with this approach. 

> With this patch it seems that we follow the backward in-compatible changes of Ratis and update to the latest master.

@elek, This pull request is helpful to move the Ozone code forward with the Ratis change.

I guess there may be some confusion.  Let me try to clarify in the next message.

**Comment by szetszwo** [comment]
- ratis-1.0.0 was released on Wed Jul 8 15:09:29 2020: 
- The first incompatible change after ratis-1.0.0 was committed on Wed Sep 16 13:31:28 2020 (07543a4)

For compatibility, create branch-1.1 to include everything up to 07543a4, exclusively.  We can release ratis-1.1.0 from branch-1.1 in the future.  Applications using ratis-1.0.0 can upgrade to ratis-1.1.0 without any compatibility issues.

Then, change the ratis version in master to 2.0.0-SNAPSHOT.  We will release ratis-2.0.0 from the master.  Applications (such as Ozone) like to change their code to address the incompatible changes can move to ratis-2.0.0.

Also, Ozone can keep using the ratis snapshots (i.e. this pull request) from master as before.

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Pull request merged**
