### PR TITLE
HDDS-8996. Remove the redundant getBucketInfo call in OMKeyCreateRequest

### PR DESCRIPTION
**Pull request by guohao-rosicky**
## What changes were proposed in this pull request?

Remove the redundant getBucketInfo call in OMKeyCreateRequest

The getBucketInfo method is called twice in OMKeyCreateRequest, so far it seems like it only needs to be called once, and although getBucketInfo is a relatively lightweight read from FullTableCache, it's still a good idea to remove the redundancy

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8996

### CODE REVIEW

**Comment by kerneltime** [comment]
cc @DaveTeng0 @tanvipenumudy  can you please take a look?

**Review by tanvipenumudy — COMMENTED** [review]
Thank you @guohao-rosicky for the patch. 

+1 LGTM, pending build report.

**Comment by ashishkumar50** [comment]
@guohao-rosicky, Thanks for the patch.
I can see one call which try to read from cache and if cache miss then it reads from db. Other call just reads from the cache. And now you are using call which just reads from the cache. Since bucket table is FULL_CACHE, I think there should not be any problem just reading from the cache here. 
Change LGTM.

**Review by hemantk-12 — COMMENTED** [review]
Thanks for the patch @guohao-rosicky.

Changes look fine but the PR description and jira description are missing the motivation behind this change. It would be great if you could update that.

**Review by Xushaohong — APPROVED** [review]
LTGM

**Comment by guohao-rosicky** [comment]
The getBucketInfo method is called twice in OMKeyCreateRequest, so far it seems like it only needs to be called once, and although getBucketInfo is a relatively lightweight read from FullTableCache, it's still a good idea to remove the redundancy

**Comment by guohao-rosicky** [comment]
> Thanks for the patch @guohao-rosicky.
> 
> Changes look fine but the PR description and jira description are missing the motivation behind this change. It would be great if you could update that.
Thanks for the review @hemantk-12 
Description has been added.

**Review by errose28 — APPROVED** [review]
Thanks @guohao-rosicky for the fix.

**Pull request merged**
