### PR TITLE
HDDS-11759. Remove LegacyReplicationManager

### PR DESCRIPTION
**Pull request by chiacyu**
## What changes were proposed in this pull request?
Due to [HDDS-11516](https://issues.apache.org/jira/browse/HDDS-11516) release note, the `LegacyReplicationManager` would be removed in the  `Ozone 2.0.0`.

## What is the link to the Apache JIRA

Please take a look at [HDDS-11759](https://issues.apache.org/jira/browse/HDDS-11759) for more details.

## How was this patch tested?

It can tested by CI, also pass the tests in local.

### CODE REVIEW

**Comment by adoroszlai** [comment]
Thanks @chiacyu for the patch.  Please enable [workflows](https://github.com/chiacyu/ozone/actions) (at least `build-branch`) in your fork.

**Review by adoroszlai — COMMENTED** [review]
Thanks @chiacyu for the patch.  Largely looks good to me.

There are a couple of leftover text references to `LegacyReplicationManager` and `"hdds.scm.replication.enable.legacy"`, please see details below.

`LegacyRatisContainerReplicaCount` can be completely removed:

```
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyRatisContainerReplicaCount.java
33: * When HDDS-6447 was done to improve the LegacyReplicationManager, work on
35: * the LegacyReplicationManager needed separate handling for healthy and
38: * LegacyReplicationManager to allow {@link RatisContainerReplicaCount} to
40: * and LegacyReplicationManager is removed, this class should be deleted and
68:   * For LegacyReplicationManager, unhealthy replicas are all replicas that
```

Keep only the first sentence of the comment:

```
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisContainerReplicaCount.java
227:   * overridden to ensure LegacyReplicationManager works as intended in
```

Comment can be removed:

```
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerDatanodeNodeLimit.java
531:    // Try the same test with MoveManager instead of LegacyReplicationManager.
```

Comment can be removed:

```
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java
140:    Disable LegacyReplicationManager. This means balancer should select RATIS
```

Comment can be removed:

```
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDatanodeAdminMonitor.java
236:   * Note: This test currently uses the LegacyReplicationManager, as the new
```

Code setting legacy config in the same class can be removed:

```
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDatanodeAdminMonitor.java
244:    conf.setBoolean("hdds.scm.replication.enable.legacy", true);
450:    conf.setBoolean("hdds.scm.replication.enable.legacy", true);
843:    conf.setBoolean("hdds.scm.replication.enable.legacy", false);
```

And code branching based on legacy config:

https://github.com/apache/ozone/blob/3bf2963f9f2eae8b7adfc1de5efeea50ec680965/hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorImpl.java#L444-L457

**Comment by adoroszlai** [comment]
Thanks @chiacyu for updating the patch.  Looks like the checkstyle issue was missed: https://github.com/chiacyu/ozone/actions/runs/12356830790/job/34483652628

**Review by adoroszlai — COMMENTED** [review]
Thanks @chiacyu for the patch, LGTM.

**Review by sodonnel — APPROVED** [review]
Thanks for making this change. I believe it looks good.

**Comment by adoroszlai** [comment]
Thanks @chiacyu for the patch, @sodonnel for the review.

**Pull request merged**
