### PR TITLE
HDDS-7362. Bring back the mechanism to share LRU cache between RocksDB in datanodes

### PR DESCRIPTION
**Pull request by duongkame**
## What changes were proposed in this pull request?
This PR brings back the mechanism to share LRU cache between RocksDB in datanodes

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7362

## How was this patch tested?

Standard CI.

### CODE REVIEW

**Comment by DaveTeng0** [comment]
hmm just for myself learning~ when is the timing a DatanodeDBProfile object being created?

**Comment by duongkame** [comment]
@lokeshj1703 @ChenSammi As mentioned in the [original discussion](https://github.com/apache/ozone/pull/3673#issuecomment-1297455939), please have a look at this PR.

**Comment by captainzmc** [comment]
Hi @ChenSammi, If this PR can reduce the problem of too many LRUCache objects in DN. I think we can cherry-pick it to branch-1.3.  If there is no problem I will turn off revert PR HDDS-7442.

**Comment by duongkame** [comment]
> Thanks @duongkame for the fix. The change make sense. In addition, Did you check the dump of DN? Just make sure if there are still many LRUCache objects.

Yes, I did. Please see below:
```
duong@fubar ~ % jmap -histo:live 81172 | grep Managed
 144:           104           7488  org.apache.hadoop.hdds.utils.db.managed.ManagedColumnFamilyOptions
 388:             4           1056  org.apache.ratis.thirdparty.io.grpc.internal.ManagedChannelImpl
 400:            21           1008  org.apache.hadoop.hdds.utils.db.managed.ManagedDBOptions
 548:             4            544  org.apache.hadoop.hdds.utils.db.managed.ManagedBlockBasedTableConfig
 572:            21            504  org.apache.hadoop.hdds.utils.db.managed.ManagedCheckpoint
 573:            21            504  org.apache.hadoop.hdds.utils.db.managed.ManagedRocksDB
 574:            21            504  org.apache.hadoop.hdds.utils.db.managed.ManagedWriteOptions
1340:             4             96  org.apache.hadoop.hdds.utils.db.managed.ManagedBloomFilter
1341:             4             96  org.apache.hadoop.hdds.utils.db.managed.ManagedLRUCache
1398:             4             96  org.apache.ratis.thirdparty.io.grpc.internal.ManagedChannelImpl$1ChannelCallTracerFactory
```

**Review by captainzmc — APPROVED** [review]

**Comment by ChenSammi** [comment]
LGTM + 1.  Thanks @duongkame .

**Pull request merged**
