### PR TITLE
HDDS-4396. Ozone TLP - update documents

### PR DESCRIPTION
**Pull request by flirmnave**
## What changes were proposed in this pull request?

Update Ozone documents, replaced "Apache Hadoop Ozone" with "Apache Ozone"

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4396

## How was this patch tested?

Local Hugo test.

### CODE REVIEW

**Review by vivekratnavel — APPROVED** [review]
+1 LGTM

**Comment by vivekratnavel** [comment]
@flirmnave Thanks for working on this!

**Review by xiaoyuyao — APPROVED** [review]
LGTM, +1

**Comment by flirmnave** [comment]
Thanks @vivekratnavel @xiaoyuyao for  review and comment.

**Pull request merged**
