### PR TITLE
HDDS-11388. Fix unnecessary call to the DB for ContainerBalancer#getBalancerStatusInfo

### PR DESCRIPTION
**Pull request by ivandika3**
## What changes were proposed in this pull request?

`ContainerBalancer#getBalancerStatusInfo` can get the current running balancer configuration from the in-memory configuration, which is in sync with the backing DB. Also added lock in `getBalancerStatusInfo`.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-11388

## How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by ivandika3** [comment]
Seems container balancer acceptance test failed after this patch. Let me take a look first.

**Comment by siddhantsangwan** [comment]
@ivandika3 let me know when it's ready for review.

**Comment by ivandika3** [comment]
@siddhantsangwan Hi, this patch is ready for review. Thank you.

**Review by siddhantsangwan — COMMENTED** [review]
> This is because shouldRun is not set in the in-memory ContainerBalancerConfigurationProto causing proto exception.

@ivandika3 good find there. This patch looks good. There's a conflict with `testBalancer.robot` that needs to be fixed.

**Review by siddhantsangwan — APPROVED** [review]
LGTM, pending green CI.

**Comment by ivandika3** [comment]
Thank you for the review @siddhantsangwan

**Pull request merged**
