### PR TITLE
HDDS-11271. Add direct dependencies in hadoop-hdds

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Add direct dependency for modules used in `hadoop-hdds`, instead of relying on transitive dependencies for the same.

This should get rid of most items under `Used undeclared dependencies` part of dependency analysis.

Exceptions:

- Test dependencies declared in `hdds-test-utils` and `hdds-hadoop-dependency-test` for convenience.
- Hadoop dependencies declared in `hdds-hadoop-dependency-client` and `hdds-hadoop-dependency-server` for convenience.

https://issues.apache.org/jira/browse/HDDS-11271

## How was this patch tested?

Compared output of `mvn dependency:analyze` before/after the change.

(Some dependencies (e.g. `assertj-core`, `junit-jupiter-params`) appear as new under `Used undeclared`, but it's only due to change in order of dependencies in plugin's output.

```diff
 [INFO] --- maven-dependency-plugin:3.7.1:analyze (default-cli) @ hdds-interface-server ---
-[WARNING] Used undeclared dependencies found:
-[WARNING]    org.apache.ratis:ratis-thirdparty-misc:jar:1.0.6:compile
+[INFO] No dependency problems found
...
 [INFO] --- maven-dependency-plugin:3.7.1:analyze (default-cli) @ hdds-common ---
 [WARNING] Used undeclared dependencies found:
-[WARNING]    org.apache.ratis:ratis-thirdparty-misc:jar:1.0.6:compile
-[WARNING]    org.assertj:assertj-core:jar:3.26.3:test
-[WARNING]    com.fasterxml.jackson.core:jackson-databind:jar:2.16.2:compile
-[WARNING]    org.apache.ratis:ratis-common:jar:3.1.0:compile
-[WARNING]    commons-collections:commons-collections:jar:3.2.2:compile
-[WARNING]    org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
 [WARNING]    org.mockito:mockito-core:jar:4.11.0:test
-[WARNING]    com.fasterxml.jackson.core:jackson-core:jar:2.16.2:compile
-[WARNING]    org.bouncycastle:bcprov-jdk18on:jar:1.78.1:compile
-[WARNING]    jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:provided
-[WARNING]    org.apache.ratis:ratis-client:jar:3.1.0:compile
+[WARNING]    org.assertj:assertj-core:jar:3.26.3:test
 [WARNING]    org.apache.hadoop:hadoop-common:jar:3.3.6:compile
 [WARNING]    org.junit.jupiter:junit-jupiter-api:jar:5.10.3:test
 [WARNING]    org.apache.hadoop:hadoop-hdfs:jar:3.3.6:compile
-[WARNING]    io.jaegertracing:jaeger-core:jar:1.8.1:compile
-[WARNING]    org.apache.ratis:ratis-proto:jar:3.1.0:compile
-[WARNING]    org.bouncycastle:bcutil-jdk18on:jar:1.78.1:compile
-[WARNING]    io.opentracing:opentracing-api:jar:0.33.0:compile
+[WARNING]    org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
 [WARNING]    org.apache.hadoop:hadoop-annotations:jar:3.3.6:compile
-[WARNING]    org.slf4j:slf4j-api:jar:2.0.13:compile
...
 [INFO] --- maven-dependency-plugin:3.7.1:analyze (default-cli) @ hdds-erasurecode ---
 [WARNING] Used undeclared dependencies found:
-[WARNING]    com.google.guava:guava:jar:32.1.3-jre:compile
 [WARNING]    org.assertj:assertj-core:jar:3.26.3:test
 [WARNING]    org.junit.jupiter:junit-jupiter-api:jar:5.10.3:test
 [WARNING]    org.apache.hadoop:hadoop-common:jar:3.3.6:compile
-[WARNING]    org.apache.ozone:hdds-config:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    org.slf4j:slf4j-api:jar:2.0.13:compile
...
 [INFO] --- maven-dependency-plugin:3.7.1:analyze (default-cli) @ hdds-client ---
 [WARNING] Used undeclared dependencies found:
-[WARNING]    org.apache.ratis:ratis-thirdparty-misc:jar:1.0.6:compile
-[WARNING]    org.assertj:assertj-core:jar:3.26.3:test
-[WARNING]    org.apache.ratis:ratis-common:jar:3.1.0:compile
-[WARNING]    org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
-[WARNING]    jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
-[WARNING]    org.apache.ozone:hdds-interface-client:jar:1.5.0-SNAPSHOT:compile
 [WARNING]    org.mockito:mockito-core:jar:4.11.0:test
-[WARNING]    org.apache.commons:commons-lang3:jar:3.14.0:compile
-[WARNING]    com.google.guava:guava:jar:32.1.3-jre:compile
-[WARNING]    io.opentracing:opentracing-util:jar:0.33.0:compile
+[WARNING]    org.assertj:assertj-core:jar:3.26.3:test
 [WARNING]    org.junit.jupiter:junit-jupiter-api:jar:5.10.3:test
 [WARNING]    org.apache.hadoop:hadoop-common:jar:3.3.6:compile
-[WARNING]    org.apache.ratis:ratis-client:jar:3.1.0:compile
-[WARNING]    org.apache.ozone:hdds-config:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    org.apache.ratis:ratis-grpc:jar:3.1.0:compile
-[WARNING]    org.apache.ratis:ratis-proto:jar:3.1.0:compile
-[WARNING]    io.opentracing:opentracing-api:jar:0.33.0:compile
-[WARNING]    org.slf4j:slf4j-api:jar:2.0.13:compile
+[WARNING]    org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
...
 [INFO] --- maven-dependency-plugin:3.7.1:analyze (default-cli) @ hdds-managed-rocksdb ---
 [WARNING] Used undeclared dependencies found:
-[WARNING]    com.google.guava:guava:jar:32.1.3-jre:compile
 [WARNING]    org.apache.hadoop:hadoop-common:jar:3.3.6:compile
-[WARNING]    org.apache.ratis:ratis-common:jar:3.1.0:compile
-[WARNING]    jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
-[WARNING]    org.slf4j:slf4j-api:jar:2.0.13:compile
...
 [INFO] --- maven-dependency-plugin:3.7.1:analyze (default-cli) @ hdds-rocks-native ---
 [WARNING] Used undeclared dependencies found:
 [WARNING]    org.mockito:mockito-core:jar:4.11.0:test
-[WARNING]    org.rocksdb:rocksdbjni:jar:7.7.3:compile
-[WARNING]    org.apache.commons:commons-lang3:jar:3.14.0:compile
-[WARNING]    com.google.guava:guava:jar:32.1.3-jre:compile
 [WARNING]    org.assertj:assertj-core:jar:3.26.3:test
 [WARNING]    org.junit.jupiter:junit-jupiter-api:jar:5.10.3:test
-[WARNING]    org.apache.ozone:hdds-common:jar:1.5.0-SNAPSHOT:compile
 [WARNING]    org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
-[WARNING]    org.slf4j:slf4j-api:jar:2.0.13:compile
...
 [INFO] --- maven-dependency-plugin:3.7.1:analyze (default-cli) @ rocksdb-checkpoint-differ ---
 [WARNING] Used undeclared dependencies found:
-[WARNING]    com.google.protobuf:protobuf-java:jar:2.5.0:compile
-[WARNING]    org.assertj:assertj-core:jar:3.26.3:test
-[WARNING]    commons-collections:commons-collections:jar:3.2.2:compile
-[WARNING]    org.apache.ratis:ratis-common:jar:3.1.0:compile
-[WARNING]    org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
-[WARNING]    org.apache.ozone:hdds-interface-client:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    com.github.vlsi.mxgraph:jgraphx:jar:3.9.8.1:compile
 [WARNING]    org.mockito:mockito-core:jar:4.11.0:test
+[WARNING]    org.assertj:assertj-core:jar:3.26.3:test
 [WARNING]    org.junit.jupiter:junit-jupiter-api:jar:5.10.3:test
 [WARNING]    org.apache.hadoop:hadoop-common:jar:3.3.6:compile
-[WARNING]    org.apache.ozone:hdds-config:jar:1.5.0-SNAPSHOT:compile
 [WARNING]    org.mockito:mockito-junit-jupiter:jar:4.11.0:test
-[WARNING]    org.slf4j:slf4j-api:jar:2.0.13:compile
+[WARNING]    org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
...
 [INFO] --- maven-dependency-plugin:3.7.1:analyze (default-cli) @ hdds-server-framework ---
 [WARNING] Used undeclared dependencies found:
-[WARNING]    org.rocksdb:rocksdbjni:jar:7.7.3:compile
-[WARNING]    com.google.protobuf:protobuf-java:jar:2.5.0:compile
-[WARNING]    io.prometheus:simpleclient:jar:0.16.0:compile
-[WARNING]    org.apache.ratis:ratis-server-api:jar:3.1.0:compile
-[WARNING]    org.apache.ratis:ratis-common:jar:3.1.0:compile
-[WARNING]    commons-validator:commons-validator:jar:1.6:compile
-[WARNING]    com.fasterxml.jackson.core:jackson-databind:jar:2.16.2:compile
-[WARNING]    com.github.jnr:jnr-constants:jar:0.10.4:compile
-[WARNING]    org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
-[WARNING]    jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
 [WARNING]    org.mockito:mockito-core:jar:4.11.0:test
-[WARNING]    com.google.guava:guava:jar:32.1.3-jre:compile
-[WARNING]    org.apache.commons:commons-lang3:jar:3.14.0:compile
-[WARNING]    commons-codec:commons-codec:jar:1.17.0:compile
-[WARNING]    org.apache.hadoop:hadoop-common:test-jar:tests:3.3.6:test
-[WARNING]    jakarta.ws.rs:jakarta.ws.rs-api:jar:2.1.6:compile
-[WARNING]    io.dropwizard.metrics:metrics-core:jar:3.2.6:compile
-[WARNING]    org.glassfish.jersey.core:jersey-server:jar:2.43:compile
-[WARNING]    com.google.code.gson:gson:jar:2.10.1:compile
-[WARNING]    org.apache.ratis:ratis-thirdparty-misc:jar:1.0.6:compile
 [WARNING]    org.assertj:assertj-core:jar:3.26.3:test
-[WARNING]    javax.servlet:javax.servlet-api:jar:3.1.0:compile
-[WARNING]    org.apache.ozone:hdds-interface-client:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    org.eclipse.jetty:jetty-util-ajax:jar:9.4.55.v20240627:compile
-[WARNING]    commons-logging:commons-logging:jar:1.2:compile
-[WARNING]    org.apache.ratis:ratis-metrics-api:jar:3.1.0:compile
-[WARNING]    org.bouncycastle:bcprov-jdk18on:jar:1.78.1:compile
-[WARNING]    org.bouncycastle:bcpkix-jdk18on:jar:1.78.1:compile
-[WARNING]    org.eclipse.jetty:jetty-http:jar:9.4.55.v20240627:compile
+[WARNING]    org.apache.hadoop:hadoop-common:test-jar:tests:3.3.6:test
 [WARNING]    org.apache.hadoop:hadoop-common:jar:3.3.6:compile
 [WARNING]    org.apache.hadoop:hadoop-auth:jar:3.3.6:compile
 [WARNING]    org.junit.jupiter:junit-jupiter-api:jar:5.10.3:test
-[WARNING]    commons-io:commons-io:jar:2.16.1:compile
-[WARNING]    org.apache.ozone:hdds-config:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    io.opentracing:opentracing-api:jar:0.33.0:compile
-[WARNING]    org.slf4j:slf4j-api:jar:2.0.13:compile
-[WARNING]    com.fasterxml.jackson.core:jackson-annotations:jar:2.16.2:compile
+[WARNING]    org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
...
 [INFO] --- maven-dependency-plugin:3.7.1:analyze (default-cli) @ hdds-container-service ---
 [WARNING] Used undeclared dependencies found:
-[WARNING]    org.rocksdb:rocksdbjni:jar:7.7.3:compile
-[WARNING]    info.picocli:picocli:jar:4.7.6:compile
-[WARNING]    org.apache.ratis:ratis-netty:jar:3.1.0:compile
-[WARNING]    com.google.protobuf:protobuf-java:jar:2.5.0:compile
-[WARNING]    org.apache.ozone:hdds-interface-server:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    org.apache.ratis:ratis-server-api:jar:3.1.0:compile
-[WARNING]    org.apache.ratis:ratis-common:jar:3.1.0:compile
-[WARNING]    com.fasterxml.jackson.core:jackson-databind:jar:2.16.2:compile
-[WARNING]    org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
-[WARNING]    jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
 [WARNING]    org.mockito:mockito-core:jar:4.11.0:test
-[WARNING]    io.netty:netty-buffer:jar:4.1.109.Final:compile
-[WARNING]    com.google.guava:guava:jar:32.1.3-jre:compile
-[WARNING]    org.apache.commons:commons-lang3:jar:3.14.0:compile
-[WARNING]    io.opentracing:opentracing-util:jar:0.33.0:compile
-[WARNING]    io.netty:netty-common:jar:4.1.109.Final:compile
-[WARNING]    org.apache.hadoop:hadoop-common:test-jar:tests:3.3.6:test
-[WARNING]    org.apache.ratis:ratis-client:jar:3.1.0:compile
-[WARNING]    org.mockito:mockito-junit-jupiter:jar:4.11.0:test
-[WARNING]    org.apache.ratis:ratis-proto:jar:3.1.0:compile
-[WARNING]    org.apache.ratis:ratis-thirdparty-misc:jar:1.0.6:compile
-[WARNING]    org.apache.logging.log4j:log4j-api:jar:2.23.1:compile
 [WARNING]    ch.qos.reload4j:reload4j:jar:1.2.25:compile
-[WARNING]    org.apache.ozone:hdds-managed-rocksdb:jar:1.5.0-SNAPSHOT:compile
 [WARNING]    org.assertj:assertj-core:jar:3.26.3:test
-[WARNING]    commons-collections:commons-collections:jar:3.2.2:compile
-[WARNING]    org.apache.ozone:hdds-interface-client:jar:1.5.0-SNAPSHOT:compile
+[WARNING]    org.apache.hadoop:hadoop-common:test-jar:tests:3.3.6:test
 [WARNING]    org.apache.hadoop:hadoop-auth:jar:3.3.6:compile
 [WARNING]    org.apache.hadoop:hadoop-common:jar:3.3.6:compile
 [WARNING]    org.apache.hadoop:hadoop-hdfs:jar:3.3.6:compile
 [WARNING]    org.junit.jupiter:junit-jupiter-api:jar:5.10.3:test
-[WARNING]    commons-io:commons-io:jar:2.16.1:compile
-[WARNING]    org.apache.ratis:ratis-grpc:jar:3.1.0:compile
-[WARNING]    org.apache.ratis:ratis-server:jar:3.1.0:compile
-[WARNING]    org.apache.ozone:hdds-config:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    io.opentracing:opentracing-api:jar:0.33.0:compile
-[WARNING]    org.slf4j:slf4j-api:jar:2.0.13:compile
-[WARNING]    com.fasterxml.jackson.core:jackson-annotations:jar:2.16.2:compile
+[WARNING]    org.mockito:mockito-junit-jupiter:jar:4.11.0:test
+[WARNING]    org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
...
 [INFO] --- maven-dependency-plugin:3.7.1:analyze (default-cli) @ hdds-server-scm ---
 [WARNING] Used undeclared dependencies found:
-[WARNING]    org.apache.commons:commons-compress:jar:1.26.2:compile
-[WARNING]    info.picocli:picocli:jar:4.7.6:compile
-[WARNING]    org.apache.ozone:hdds-interface-server:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    org.apache.ratis:ratis-server-api:jar:3.1.0:compile
-[WARNING]    com.fasterxml.jackson.core:jackson-databind:jar:2.16.2:compile
-[WARNING]    org.apache.ratis:ratis-common:jar:3.1.0:compile
-[WARNING]    org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
-[WARNING]    jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
 [WARNING]    org.mockito:mockito-core:jar:4.11.0:test
-[WARNING]    org.apache.commons:commons-lang3:jar:3.14.0:compile
-[WARNING]    com.google.guava:guava:jar:32.1.3-jre:compile
-[WARNING]    org.apache.hadoop:hadoop-common:test-jar:tests:3.3.6:test
-[WARNING]    org.apache.ratis:ratis-client:jar:3.1.0:compile
-[WARNING]    org.mockito:mockito-junit-jupiter:jar:4.11.0:test
-[WARNING]    org.apache.ratis:ratis-proto:jar:3.1.0:compile
-[WARNING]    org.apache.ozone:hdds-interface-admin:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    org.apache.ratis:ratis-thirdparty-misc:jar:1.0.6:compile
-[WARNING]    org.eclipse.jetty:jetty-webapp:jar:9.4.55.v20240627:compile
 [WARNING]    org.apache.hadoop:hadoop-hdfs:test-jar:tests:3.3.6:test
 [WARNING]    org.assertj:assertj-core:jar:3.26.3:test
-[WARNING]    javax.servlet:javax.servlet-api:jar:3.1.0:compile
-[WARNING]    commons-collections:commons-collections:jar:3.2.2:compile
-[WARNING]    org.apache.ozone:hdds-interface-client:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    com.fasterxml.jackson.core:jackson-core:jar:2.16.2:compile
-[WARNING]    org.bouncycastle:bcpkix-jdk18on:jar:1.78.1:compile
+[WARNING]    org.apache.hadoop:hadoop-common:test-jar:tests:3.3.6:test
 [WARNING]    org.apache.hadoop:hadoop-auth:jar:3.3.6:compile
 [WARNING]    org.apache.hadoop:hadoop-common:jar:3.3.6:compile
 [WARNING]    org.junit.jupiter:junit-jupiter-api:jar:5.10.3:test
 [WARNING]    org.apache.hadoop:hadoop-hdfs:jar:3.3.6:compile
-[WARNING]    commons-io:commons-io:jar:2.16.1:compile
-[WARNING]    org.apache.ozone:hdds-config:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    org.apache.ratis:ratis-grpc:jar:3.1.0:compile
-[WARNING]    org.apache.ratis:ratis-server:jar:3.1.0:compile
-[WARNING]    com.fasterxml.jackson.core:jackson-annotations:jar:2.16.2:compile
-[WARNING]    org.slf4j:slf4j-api:jar:2.0.13:compile
+[WARNING]    org.mockito:mockito-junit-jupiter:jar:4.11.0:test
+[WARNING]    org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
...
 [INFO] --- maven-dependency-plugin:3.7.1:analyze (default-cli) @ hdds-tools ---
 [WARNING] Used undeclared dependencies found:
-[WARNING]    info.picocli:picocli:jar:4.7.6:compile
-[WARNING]    org.assertj:assertj-core:jar:3.26.3:test
-[WARNING]    com.fasterxml.jackson.core:jackson-databind:jar:2.16.2:compile
-[WARNING]    org.apache.ratis:ratis-common:jar:3.1.0:compile
-[WARNING]    org.apache.ozone:hdds-interface-client:jar:1.5.0-SNAPSHOT:compile
 [WARNING]    org.mockito:mockito-core:jar:4.11.0:test
-[WARNING]    org.apache.ozone:hdds-container-service:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    com.fasterxml.jackson.core:jackson-core:jar:2.16.2:compile
-[WARNING]    org.apache.commons:commons-lang3:jar:3.14.0:compile
-[WARNING]    com.google.guava:guava:jar:32.1.3-jre:compile
-[WARNING]    commons-codec:commons-codec:jar:1.17.0:compile
+[WARNING]    org.assertj:assertj-core:jar:3.26.3:test
 [WARNING]    org.junit.jupiter:junit-jupiter-api:jar:5.10.3:test
 [WARNING]    org.apache.hadoop:hadoop-common:jar:3.3.6:compile
-[WARNING]    commons-io:commons-io:jar:2.16.1:compile
-[WARNING]    org.apache.ozone:hdds-config:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.16.2:compile
-[WARNING]    org.apache.ozone:hdds-interface-admin:jar:1.5.0-SNAPSHOT:compile
-[WARNING]    com.fasterxml.jackson.core:jackson-annotations:jar:2.16.2:compile
```

### CODE REVIEW

**Review by swamirishi — COMMENTED** [review]
@adoroszlai Just a dumb question here. Are we adding the direct dependencies here for only the classes that are being used by a certain module?

**Comment by adoroszlai** [comment]
> Are we adding the direct dependencies here for only the classes that are being used by a certain module?

Yes.

**Review by swamirishi — APPROVED** [review]
thanks for the patch @adoroszlai changes look good to me

**Comment by adoroszlai** [comment]
Thanks @swamirishi for the review.

**Pull request merged**
