### PR TITLE
HDDS-4181. Add acceptance tests for upgrade, finalization and downgrade.

### PR DESCRIPTION
**Pull request by errose28**
## What changes were proposed in this pull request?

Robot acceptance test and shell scripting framework to automate upgrades and downgrades. Commands can be inserted at any stage in an upgrade/downgrade with callbacks. See README.md for more information.

## What is the link to the Apache JIRA

HDDS-4181

## How was this patch tested?

Added acceptance tests should pass.

## Dependencies

- master merged into upgrade branch.
    - master merged in to the upgrade branch to bring in:
        -  HDDS-4741 (cherry picked here for now), which this PR is based off of.
        -  HDDS-4731, a fix for an incompatible change that fails this test. 
    - The master merge is tracked [here](https://github.com/apache/ozone/pull/1985/). 
    - Master merge is currently blocked by HDDS-4946, which will fix a test failure introduced when bringing master into upgrade branch.

- HDDS-4180 is needed to fix an incompatible change encountered during downgrade.

### CODE REVIEW

**Comment by guihecheng** [comment]
hi @errose28, during my test of this branch, I got an exception thrown from an exited scm docker container:
```
2021-03-10 03:43:45 ERROR StorageContainerManagerStarter:69 - SCM start failed with exception
java.lang.IllegalArgumentException: No enum constant org.apache.hadoop.hdds.protocol.DatanodeDetails.Port.Name.REPLICATION
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at org.apache.hadoop.hdds.protocol.DatanodeDetails$Port$Name.valueOf(DatanodeDetails.java:430)
	at org.apache.hadoop.hdds.protocol.DatanodeDetails.getFromProtoBuf(DatanodeDetails.java:202)
	at org.apache.hadoop.hdds.scm.pipeline.Pipeline.getFromProtobuf(Pipeline.java:307)
	at org.apache.hadoop.hdds.scm.metadata.PipelineCodec.fromPersistedFormat(PipelineCodec.java:44)
	at org.apache.hadoop.hdds.scm.metadata.PipelineCodec.fromPersistedFormat(PipelineCodec.java:33)
	at org.apache.hadoop.hdds.utils.db.CodecRegistry.asObject(CodecRegistry.java:55)
	at org.apache.hadoop.hdds.utils.db.TypedTable$TypedKeyValue.getValue(TypedTable.java:347)
	at org.apache.hadoop.hdds.scm.pipeline.SCMPipelineManager.nextPipelineFromIterator(SCMPipelineManager.java:177)
	at org.apache.hadoop.hdds.scm.pipeline.SCMPipelineManager.initializePipelineState(SCMPipelineManager.java:167)
	at org.apache.hadoop.hdds.scm.pipeline.SCMPipelineManager.<init>(SCMPipelineManager.java:103)
	at org.apache.hadoop.hdds.scm.server.StorageContainerManager.initializeSystemManagers(StorageContainerManager.java:410)
	at org.apache.hadoop.hdds.scm.server.StorageContainerManager.<init>(StorageContainerManager.java:281)
	at org.apache.hadoop.hdds.scm.server.StorageContainerManager.<init>(StorageContainerManager.java:213)
	at org.apache.hadoop.hdds.scm.server.StorageContainerManager.createSCM(StorageContainerManager.java:624)
	at org.apache.hadoop.hdds.scm.server.StorageContainerManagerStarter$SCMStarterHelper.start(StorageContainerManagerStarter.java:144)
	at org.apache.hadoop.hdds.scm.server.StorageContainerManagerStarter.startScm(StorageContainerManagerStarter.java:119)
	at org.apache.hadoop.hdds.scm.server.StorageContainerManagerStarter.call(StorageContainerManagerStarter.java:67)
	at org.apache.hadoop.hdds.scm.server.StorageContainerManagerStarter.call(StorageContainerManagerStarter.java:43)
	at picocli.CommandLine.execute(CommandLine.java:1173)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:1465)
	at org.apache.hadoop.hdds.cli.GenericCli.execute(GenericCli.java:75)
	at org.apache.hadoop.hdds.cli.GenericCli.run(GenericCli.java:66)
	at org.apache.hadoop.hdds.scm.server.StorageContainerManagerStarter.main(StorageContainerManagerStarter.java:56)
No enum constant org.apache.hadoop.hdds.protocol.DatanodeDetails.Port.Name.REPLICATION
2021-03-10 03:43:46 INFO  StorageContainerManagerStarter:124 - SHUTDOWN_MSG:
/************************************************************
SHUTDOWN_MSG: Shutting down StorageContainerManager at c943c7fc2803/10.9.0.14
************************************************************/
```
It seems that the acceptance test for non-rolling upgrade failed, do you have any ideas about this?

**Comment by guihecheng** [comment]
After checking the scm.db for the datanodeDetails things and the issues,
I confirm that it should be fixed by this pr:
https://github.com/apache/ozone/pull/1844
Maybe we could merge the pr into this branch?

**Comment by errose28** [comment]
Thanks for testing this out @guihecheng. Indeed this is a known incompatibility that the test catches, and we need to merge master into the upgrade branch to get the fix. There are a couple fixes we need that are blocking this PR actually. I will update the description to clarify them and should probably convert this back to a draft to avoid confusion.

**Comment by errose28** [comment]
Closing since I need to change the base branch due to merges/fixes from other branches that are now incorporated. Progress will be tracked here: https://github.com/apache/ozone/pull/2056

**Pull request closed without merging**
