### PR TITLE
HDDS-5177. Update link of weekly calls

### PR DESCRIPTION
**Pull request by aeioulisa**
## What changes were proposed in this pull request?
Update link of weekly calls in README

## What is the link to the Apache JIRA
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5177

## How was this patch tested?
no need

### CODE REVIEW

**Review by adoroszlai — APPROVED** [review]
Thanks @aeioulisa for the update.

**Review by cku328 — APPROVED** [review]
Thanks @aeioulisa for fixing it.

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by adoroszlai** [comment]
Merged it despite failed integration check, as it's only a README change.

Thanks @aeioulisa for the fix, @ayushtkn and @cku328 for the review.

**Pull request merged**
