### PR TITLE
HDDS-11561. Refactor Open Key Search Endpoint and Consolidate with OmDBInsightEndpoint Using StartPrefix Parameter.

### PR DESCRIPTION
**Pull request by ArafatKhan2198**
## What changes were proposed in this pull request?
This pull request introduces the following changes:

1. Addition of startPrefix to `/open` endpoint: 
The `startPrefix` parameter has been added to the `/open` endpoint to enable filtering of open keys based on a specific prefix. This change mirrors the behaviour implemented for the /deletePending endpoint and improves search efficiency for open keys.
2. Consolidation of Search Functionality: 
The search functionality for open keys, previously handled in the `OmDBInsightsSearchEndpoint`, has been fully integrated into the `/open` endpoint in `OMDBInsightEndpoint`. The `OmDBInsightsSearchEndpoint` file has been removed as it is no longer needed.
3. Test Class Renaming: 
The test class `TestOmDBSearchEndpoint` has been renamed to `TestOpenKeysSearchEndpoint` to better reflect its purpose, as it now only tests the open keys search functionality.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-11561

## How was this patch tested?

- Unit tests were updated to reflect the changes made to the /open endpoint.
- The renamed TestOpenKeysSearchEndpoint class has been run to verify the correctness of the open key search functionality.
- Manual testing was performed to ensure that both /open and /deletePending endpoints handle startPrefix correctly and return expected results.

### CODE REVIEW

**Comment by ArafatKhan2198** [comment]
@devmadhuu @sumitagrawl please take a look.

**Comment by nandakumar131** [comment]
@ArafatKhan2198, can you please resolve the merge conflict?

**Review by sumitagrawl — APPROVED** [review]
LGTM

**Review by devmadhuu — APPROVED** [review]
Thanks @ArafatKhan2198 . Changes LGTM +1

**Review by devmadhuu — APPROVED** [review]
Thanks @ArafatKhan2198 . Changes LGTM +1 . Let CI pass through.

**Pull request merged**
