### PR TITLE
HDDS-10082. Fix some wrong prompts in StorageContainerManager

### PR DESCRIPTION
**Pull request by jianghuazhu**
## What changes were proposed in this pull request?
There are some error messages in StorageContainerManager, the purpose of this PR is to fix them.
Details: HDDS-10082

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-10082

## How was this patch tested?
It is necessary to ensure that the unit test can pass smoothly.

### CODE REVIEW

**Comment by jianghuazhu** [comment]
ci: https://github.com/jianghuazhu/ozone/actions/runs/7437376105
This is a small fix, can you please review it, @adoroszlai  @hemantk-12 .
Thanks.

**Comment by SaketaChalamchala** [comment]
@errose28 can you please take a look?

**Review by errose28 — APPROVED** [review]
Thanks @jianghuazhu LGTM

**Review by hemantk-12 — APPROVED** [review]
Thanks @jianghuazhu for the patch.

LGTM.

**Comment by jianghuazhu** [comment]
Thanks @errose28  and @hemantk-12 .
CI has a unit test that fails:
https://github.com/apache/ozone/actions/runs/7438076926/job/20277612705?pr=5938

It doesn't seem to have much to do with this PR.
Here are the results of my local test:
image

**Comment by adoroszlai** [comment]
Thanks @jianghuazhu for the fix, @errose28, @hemantk-12 for the review.

**Pull request merged**
