### PR TITLE
HDDS-6666. Make Hugo markdown image syntax add responsive image class

### PR DESCRIPTION
**Pull request by smengcl**
## What changes were proposed in this pull request?

This should solve the image size issue (some are too large, like in PrefixFSO.md) when using the Markdown image syntax (not the shortcode).

Also see comment: https://github.com/apache/ozone/pull/2582/files#r861196807

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-6666

## How was this patch tested?

- Check the generate doc html manually, images should now fit the page text width

```bash
cd hadoop-hdds/docs
hugo serve &
open http://localhost:1313/feature/prefixfso.html
```

### CODE REVIEW

**Review by adoroszlai — APPROVED** [review]
Thanks @smengcl for the fix.

As far as I understand, the problem only happens if the preprocessing logic added in #3122 is skipped (e.g. via `hugo serve`).  Output of static site generation (`dev-support/bin/generate-site.sh`) works fine without this fix, too.

**Comment by adoroszlai** [comment]
@JyotinderSingh can you please take a look, too?

**Comment by JyotinderSingh** [comment]
Hi @smengcl thank you for the patch, just to make sure I understand the functionality correctly - the change you have added automatically substitutes every Markdown img tag with the custom code `{{ .Text }}`? I believe it's called a [render hook](https://gohugo.io/templates/render-hooks/), could you please confirm if I am understanding it properly?

Adding to what @adoroszlai said, currently, the only reason the website does not have the image sizing fix added is that we are skipping the logic added in #3122 in the deployment process because our Jenkins server does not have Maven installed. For the image sizing logic to work correctly, we should use the `mvn clean install` command to generate the website.

Looking at the logic that you have added, I think it completely resolves the issue in my approach (having to generate site using `mvn clean install`) and is a more elegant and understandable solution. I think you should be able to safely remove the the changes linked below in `hadoop-hdds/docs/dev-support/bin/generate-site.sh` I made as a part of #3122.
https://github.com/apache/ozone/pull/3122/files#diff-d9443550225fa81eaea96777ca3c5f615fff136ac1d2fd58dc789e2a458107fcR34-R46

**Comment by smengcl** [comment]
Thanks @JyotinderSingh for the comment. Yes it is a render hook.

I can push a commit to remove the `make_images_responsive.py`.

**Comment by adoroszlai** [comment]
> I can push a commit to remove the `make_images_responsive.py` related changes.

@smengcl Yes, please, let's do that.

**Comment by adoroszlai** [comment]
Thanks @smengcl for the patch, @JyotinderSingh for the review.

**Comment by smengcl** [comment]
Thanks @smengcl @JyotinderSingh for the review!

**Pull request merged**
