### PR TITLE
HDDS-7464. Container Report at SCM is not coming separately for ICR and FCR in prometheus endpoint

### PR DESCRIPTION
**Pull request by sumitagrawl**
## What changes were proposed in this pull request?

Metrics classes seperated for ICR and FCR to report seperately for prometheus

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7464

## How was this patch tested?

1. Unit case to check report normal functionality
2. Over prometheus, its checked for both ICR and FCR reporting

image

image

### CODE REVIEW

**Comment by sumitagrawl** [comment]
@ChenSammi Plz review

**Comment by kerneltime** [comment]
@neils-dev

**Comment by sumitagrawl** [comment]
@neils-dev @kerneltime @ChenSammi Please review

**Comment by neils-dev** [comment]
Thanks @sumitagrawl for filing this jira.  A general comment - on the subject of this jira, _Container Report at SCM is not coming separately for ICR and FCR in prometheus endpoint_ .  Metrics for the full container report, FCR and the incremental container reports, ICR appear to be collected separately with the `SCMContainerManagerMetrics`.  Specifically, the `scm_container_manager_metrics_num_container_reports_processed_successful`, `scm_container_manager_metrics_num_icr_reports_processed_successful`, `scm_container_manager_metrics_num_container_reports_processed_failed`, and
`scm_container_manager_metrics_num_icr_reports_processed_failed` are collected and published to the prom endpoint.

Is this jira for adding additional metrics to be collected and published for FCR and ICR ?

**Comment by sumitagrawl** [comment]
> Thanks @sumitagrawl for filing this jira. A general comment - on the subject of this jira, _Container Report at SCM is not coming separately for ICR and FCR in prometheus endpoint_ . Metrics for the full container report, FCR and the incremental container reports, ICR appear to be collected separately with the `SCMContainerManagerMetrics`. Specifically, the `scm_container_manager_metrics_num_container_reports_processed_successful`, `scm_container_manager_metrics_num_icr_reports_processed_successful`, `scm_container_manager_metrics_num_container_reports_processed_failed`, and `scm_container_manager_metrics_num_icr_reports_processed_failed` are collected and published to the prom endpoint.
> 
> Is this jira for adding additional metrics to be collected and published for FCR and ICR ?

Its not about adding new metrics, Its about issue for reporting to prometheus. By default, prometheus endpoint takes classname as key and report metrics.
For FCR and ICR, classname is same, so causing to take one of metrics report, other is ignored. So as fix, I am separating the class for metrics for FCR & ICR to resolve this.

**Comment by ChenSammi** [comment]
Hi @sumitagrawl , I have gone through the existing code. It looks like both FCR and ICR are reported in prometheus. 
image

image

And both FCR and ICR event queue metrics are exposed through JMX too.  I'm a little confused about this task.

**Comment by sumitagrawl** [comment]
@ChenSammi 
I just check, this existing metrics is ContainerManager metrics for ICR/FCR at SCM

But I have fixed for metrics related to EventQueue for ICR/FCR, this is part of FixedThreadPoolWithAffinityExecutor as earlier reported.

Both are different.

**Comment by sumitagrawl** [comment]
@ChenSammi 
As discussed, its a common problem for FixedThreadPoolWithAffinityExecutor and SingleThreadExecutor

Will create another PR with other implementation for this.

**Pull request closed without merging**
