### PR TITLE
HDDS-4778. Add transactionId into deletingTxIDs when remove it from DB

### PR DESCRIPTION
**Pull request by runzhiwang**
## What changes were proposed in this pull request?

Add transactionId into deletingTxIDs when remove it from DB

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4778

### CODE REVIEW

**Comment by GlenGeng** [comment]
LGTM. Thanks for the fix. Github CI is broken.

CC @bshashikant @amaliujia

**Comment by amaliujia** [comment]
LGTM

**Review by bshashikant — APPROVED** [review]

**Comment by GlenGeng** [comment]
@runzhiwang Please rebase HDDS-2823.

**Comment by runzhiwang** [comment]
@GlenGeng @bshashikant @amaliujia Thanks for review. I have merged it.

**Pull request merged**
