### PR TITLE
HDDS-8385. Ozone can't process snapshot when service UID > 2097151.

### PR DESCRIPTION
**Pull request by GeorgeJahad**
## What changes were proposed in this pull request?

Fix OM HA RatisSnapshot creation to support large group ID's

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8385

## How was this patch tested?

Reproduced the problem by setting the group id of one of the snapshot files like so:

```
chgrp 1301600003 omNode-1/db.snapshots/checkpointState/om.db-c3e20908-b7ea-4650-a538-352c832ceeaa/000051.sst
```

Then confirmed the problem no longer occurs after the fix

### CODE REVIEW

**Review by jojochuang — COMMENTED** [review]
LGTM. I'm wondering if the same issue could occur in other places of the code.
TarArchiveOutputStream is used by SCM checkpoint and datanode container re-replication too.

**Comment by GeorgeJahad** [comment]
@jojochuang  I considered that but because I'm not to familiar with those code paths decided not to.  Do you want me to?

**Comment by jojochuang** [comment]
I think we should. The logic is the same so straightforward. Otherwise It would be really hard for users to troubleshoot a container re-replication failure should it happen.

**Review by kaijchen — COMMENTED** [review]
Thanks @GeorgeJahad for reporting and fixing this issue.

FYI, here's all the usage of `TarArchiveOutputStream` in Ozone:

```console
$ grep -rwl TarArchiveOutputStream . --include '*.java'
./hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
./hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java
./hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/TarContainerPacker.java
./hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestTarContainerPacker.java
./hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java
```

**Review by jojochuang — APPROVED** [review]
+1

**Review by kaijchen — APPROVED** [review]
LGTM

**Pull request merged**
