### PR TITLE
HDDS-11188. Initial setup for new UI layout and enable users to switch to new UI

### PR DESCRIPTION
**Pull request by devabhishekpal**
## What changes were proposed in this pull request?
HDDS-11188. Initial setup for new UI layout and enable users to switch to new UI

Please describe your PR in detail:
- As a part of [HDDS-11153](https://issues.apache.org/jira/browse/HDDS-11153) a new UI is being worked on for Ozone Recon
- However since this will be done is steps we do not want to make changes in the existing stable UI
- Hence we should allow switching of the UI to the users so that they can access the existing UI, while the work for the new UI can be done in the background before migrating.
- This PR provides the changes required to allow users to switch to the new UI and also the initial layout for the pages

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-11188

## How was this patch tested?
Patch was tested manually.

### CODE REVIEW

**Comment by adoroszlai** [comment]
Thanks @devabhishekpal for the patch.  Changed it to draft as there are some build and rat errors.

@ArafatKhan2198 @smitajoshi12 please review

**Comment by devabhishekpal** [comment]
Hi @adoroszlai , thanks for pointing out the build issues.
I have fixed those, removed the files which are currently not required for this PR, and tested out the patch locally.
@smitajoshi12 @ArafatKhan2198 it would be great if you could take a look at this PR.
Thanks

**Review by tanvipenumudy — APPROVED** [review]
Thank you @devabhishekpal for working on the patch, +1.

**Review by ArafatKhan2198 — APPROVED** [review]
Thanks for working on this patch @devabhishekpal LGTM +1

**Comment by tanvipenumudy** [comment]
Thank you @devabhishekpal for the patch, thank you @adoroszlai and @ArafatKhan2198 for the reviews.

**Pull request merged**
