### PR TITLE
HDDS-10139. Support to get hosts from stdin when DN is decommissioning, recommissioning or entering maintenance.

### PR DESCRIPTION
**Pull request by YuanbenWang**
## What changes were proposed in this pull request?

When decommissioning or recommissioning a large number of DNs, current command will be so long because a long list of hosts must be included.
So we should support to get hosts from file when decommissioning or recommissioning DNs.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-10139

## How was this patch tested?

Unit tests.

### CODE REVIEW

**Comment by errose28** [comment]
+1 for stdin instead of a file as a more flexible approach

**Comment by YuanbenWang** [comment]
> If we add this for decommission and recommission, we should also add for the `MaintenanceSubCommand` too.
> 
> I also wonder if passing a filename is the best approach, or would it be better to read from stdin? Eg, in `InfoSubCommand` I recently changed it in #5659 to take a list of containers either on the command line or read from stdin if "-" was passed. It would be good if we had consistency across the commands.

@sodonnel Thank you so much for your constructive feedback on my PR! I will definitely take the suggestions into consideration and use stdin instead of file reading.

**Comment by YuanbenWang** [comment]
@sodonnel I have updated the code according to your suggestions. Could you please help review it? Thanks.

**Review by sodonnel — APPROVED** [review]
LGTM - thanks for implementing the suggestion!

**Comment by YuanbenWang** [comment]
@sodonnel @errose28 Thanks for the code review.

**Pull request merged**
