### PR TITLE
HDDS-11429. Add lifeline to improve heartbeat report

### PR DESCRIPTION
**Pull request by jianghuazhu**
## What changes were proposed in this pull request?
In some cases, Datanode will be blocked from reporting heartbeats to SCM, which is very unfriendly. A lifeline mechanism should be designed here to improve the heartbeat reporting between Datanode and SCM, and Datanode and Recon.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-11429

## How was this patch tested?
We need to ensure that Datanode normally sends lifelines to SCM/Recon.
When the lifeline is turned on, we can see some phenomena.
Datanode log:
```
2024-09-05 23:56:37,458 [Thread-35] DEBUG org.apache.hadoop.ozone.container.common.states.endpoint.LifelineEndpointTask: Sending lifeline message : datanodeDetails {
  uuid: "e86aabe7-ed94-4f6b-adef-7e0e2d646deb"
  ipAddress: "xx.xx.xx.xx"
  hostName: "xxxxxx"
  ports {
    name: "HTTP"
    value: 9882
  }
  ports {
    name: "CLIENT_RPC"
    value: 19864
  }
  ports {
    name: "REPLICATION"
    value: 9886
  }
  ports {
    name: "RATIS"
    value: 9858
  }
  ports {
    name: "RATIS_ADMIN"
    value: 9857
  }
  ports {
    name: "RATIS_SERVER"
    value: 9856
  }
  ports {
    name: "STANDALONE"
    value: 9859
  }
  networkName: "e86aabe7-ed94-4f6b-adef-7e0e2d646deb"
  networkLocation: "/default-rack"
  persistedOpState: IN_SERVICE
  persistedOpStateExpiry: 0
  currentVersion: 2
  uuid128 {
    mostSigBits: -1699356896767226005
    leastSigBits: -5913369186357973525
  }
}
nodeReport {
  storageReport {
    storageUuid: "DS-2c7b04a0-d430-40db-9716-b4b93d00ea62"
    storageLocation: "/opt/software/ozonedata/hddsdata3"
    capacity: 7998352482304
    scmUsed: 35733504
    remaining: 5541872459776
    storageType: DISK
    failed: false
    committed: 0
    freeSpaceToSpare: 5368709120
  }
  storageReport {
    storageUuid: "DS-32faa23d-a524-45b3-a529-28edafc446e5"
    storageLocation: "/opt/software/ozonedata/hddsdata2"
    capacity: 7998352482304
    scmUsed: 193314816
    remaining: 5541872459776
    storageType: DISK
    failed: false
    committed: 5368707979
    freeSpaceToSpare: 5368709120
  }
  storageReport {
    storageUuid: "DS-4093587b-be27-4c26-a5de-9b3a08c1e3c5"
    storageLocation: "/opt/software/ozonedata/hddsdata1"
    capacity: 7998352482304
    scmUsed: 40685568
    remaining: 5541872459776
    storageType: DISK
    failed: false
    committed: 5368705052
    freeSpaceToSpare: 5368709120
  }
  metadataStorageReport {
    storageLocation: "/opt/software/ozonedata/dn/ratis"
    storageType: DISK
    capacity: 7998626281536
    scmUsed: 12652544
    remaining: 5541872459776
    failed: false
  }
}
dataNodeLayoutVersion {
  metadataLayoutVersion: 8
  softwareLayoutVersion: 8
}
```
SCM log:
```
2024-09-06 01:25:07,048 | INFO  | SCMAudit | user=root | ip=xx.xx.xx.xx | op=LIFE_LINE {datanodeUUID=e86aabe7-ed94-4f6b-adef-7e0e2d646deb} | ret=SUCCESS |
```
Recon log:

```
2024-09-07 15:01:29,746 [IPC Server handler 7 on default port 9891] DEBUG org.apache.hadoop.ozone.protocolPB.StorageContainerDatanodeProtocolServerSideTranslatorPB: SCMDatanodeProtocol Lifeline request is received
2024-09-07 15:01:29,746 [IPC Server handler 7 on default port 9891] DEBUG org.apache.hadoop.hdds.scm.server.SCMDatanodeHeartbeatDispatcher: Processing DataNode lifeline. datanodeDetails = e86aabe7-ed94-4f6b-adef-7e0e2d646deb(xxxxxx/xx.xx.xx.xx), layoutVersion = metadataLayoutVersion: 8
softwareLayoutVersion: 8
```
Datanode jmx:
image

SCM jmx:
image

Recon jmx:
image

### CODE REVIEW

**Comment by jianghuazhu** [comment]
ci: https://github.com/jianghuazhu/ozone/actions/runs/10740043260
@szetszwo , can you help review this PR?
Thanks.

**Comment by sodonnel** [comment]
> In some cases, Datanode will be blocked from reporting heartbeats to SCM,

Why is the DN blocked? What is the thread that is supposed to service the heartbeat doing to block it for such a long time?

IMO it would be better to try to fix the issues causing the heartbeat to be blocked, than adding another lifeline protocol which may not be needed.

**Comment by jianghuazhu** [comment]
Thanks to @sodonnel  for the comment.
The Datanode was unable to report heartbeats to the SCM for a long time, which was first documented in HDDS-11331. The inability to report heartbeats to the SCM was due to StateContext#pipelineActions being blocked, which was addressed in HDDS-11331. The addition of the lifeline feature was also mentioned in the comments of HDDS-11331 as an aid to solving this problem.

**Comment by sodonnel** [comment]
Now that [HDDS-11331](https://issues.apache.org/jira/browse/HDDS-11331) is resolved, and the DN command processing should be off the main thread, this sort of problem should not happen.

I think we should avoid complicating things with the lifeline protocol and instead look to address such issues with the DN to keep it responsive.

With the lifeline, it is possible to make a DN appear healthy, but if it cannot heartbeat or process commands, its certainly in a degraded state. The lifeline hides that.

**Comment by jianghuazhu** [comment]
Thanks @sodonnel  for your comments and review.
I understand your suggestion. This PR will be converted to a draft first.

**Comment by kerneltime** [comment]
Side note: When posting logs using a single ` does not format multiline tests. Instead use ``` to format as markdown. Ref: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by jianghuazhu** [comment]
Thanks @kerneltime  for the comment.
I think I learned something new.

**Comment by szetszwo** [comment]
@jianghuazhu , thanks for working this!

The change is quite large.  In such case, we should have a design and more discussion first.

> With the lifeline, it is possible to make a DN appear healthy, but if it cannot heartbeat or process commands, its certainly in a degraded state. The lifeline hides that.

In HDFS, lifelines is to prevent the namenode getting too busy so it won't be able to process datanode heartbeats on time.  In Ozone, if SCM can get too busy, then lifelines become useful.   Lifeline is for SCM but not datanodes. 

However, SCM currently does not have such problem.

**Comment by jianghuazhu** [comment]
Ok, I understand.
Thanks to @szetszwo  for the comment and suggestion.

**Comment by adoroszlai** [comment]
Thanks @jianghuazhu for the patch, @kerneltime, @sodonnel, @szetszwo, @Tejaskriya for the review.  Closed based on discussion.

**Pull request closed without merging**
