### PR TITLE
HDDS-4444. Remove KeyManagerImpl#refreshPipeline because it is the same as refresh().

### PR DESCRIPTION
**Pull request by flirmnave**
## What changes were proposed in this pull request?

Remove KeyManagerImpl#refreshPipeline() and replace with KeyManagerImpl#refresh().

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4444

## How was this patch tested?

Unit test passed.

### CODE REVIEW

**Review by bharatviswa504 — COMMENTED** [review]
Can we remove refresh, and keep refreshPipeline instead, which is clear.

And also right now OmKeyInfo does not have pipelineInfo after HDDS-3658, so it is basically fetchPipeline, I am fine with leaving it as refresh also, just thought of posting here.

**Comment by ChenSammi** [comment]
Hi @flirmnave,  thanks for working on this. 

The key point backed in HDDS-3658 is new API "refresh" is added in the KeyManager interface which is called from other modules.   It's good to remove the duplicate functions and keep the code clean.

**Comment by flirmnave** [comment]
Thanks @bharatviswa504 @ChenSammi for comment and review.

Based on @ChenSammi comment, 
KeyManagerImpl#refresh() is a API which called from other modules,
so I remove KeyManagerImpl#refreshPipeline() and keep KeyManagerImpl#refresh() instead.

**Review by jojochuang — APPROVED** [review]
LGTM
@bharatviswa504  let's get this merged before HDDS-4537 / PR-1660?

**Comment by bharatviswa504** [comment]
@flirmnave Then we can rename in the KeyManager to refreshPipeline, right?

**Review by bharatviswa504 — APPROVED** [review]

**Comment by bharatviswa504** [comment]
> LGTM
> @bharatviswa504 let's get this merged before [HDDS-4537](https://issues.apache.org/jira/browse/HDDS-4537) / PR-1660?

Sure. I am fine with keeping refresh method.

**Comment by flirmnave** [comment]
Thanks @bharatviswa504 @ChenSammi @jojochuang for review and comment.

**Pull request merged**
