### PR TITLE
HDDS-6468. Set correct resource Type for BucketACL and KeyACL

### PR DESCRIPTION
**Pull request by symious**
## What changes were proposed in this pull request?

The resource type checked in BucketACL and KeyACL are now currently VOLUME, need to change to the correct resource type.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-6468

## How was this patch tested?

unit test

### CODE REVIEW

**Review by adoroszlai — COMMENTED** [review]
Thanks @symious for the patch.  The fix itself looks good to me on first glance, but I will have to check more closely.  However, the test case is passing even without the fix, so it doesn't seem to be the right way to validate it.

**Comment by symious** [comment]
@adoroszlai Thanks for the review.

I updated the test case a bit to better validate the changes.

**Review by ferhui — APPROVED** [review]
LGTM

**Review by adoroszlai — APPROVED** [review]

**Comment by adoroszlai** [comment]
Thanks @symious for the fix, @ferhui for the review.

**Comment by symious** [comment]
@adoroszlai @ferhui Thanks for the review and merge.

**Pull request merged**
