### PR TITLE
HDDS-11740. Add debug command to show internal component versions

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Implement debug subcommand to show Ozone internal component versions like:

```
$ ozone debug version
{
  "client" : {
    "name" : "BUCKET_LAYOUT_SUPPORT",
    "protoValue" : 3
  },
  "datanode" : {
    "name" : "COMBINED_PUTBLOCK_WRITECHUNK_RPC",
    "protoValue" : 2
  },
  "om" : {
    "name" : "S3_OBJECT_TAGGING_API",
    "protoValue" : 9
  }
}
```

It can be used in compatibility tests to help validate not only releases, but any specific commit.  (Of course this will require further changes in the tests.)

https://issues.apache.org/jira/browse/HDDS-11740

## How was this patch tested?

Added basic test case to exercise the command in acceptance tests.

CI:
https://github.com/adoroszlai/ozone/actions/runs/11881652506

### CODE REVIEW

**Comment by adoroszlai** [comment]
Tweak for future extensibility: moved component version info into a submap.  Also added Ozone version info.

```json
{
  "components" : {
    "client" : {
      "name" : "BUCKET_LAYOUT_SUPPORT",
      "protoValue" : 3
    },
    "datanode" : {
      "name" : "COMBINED_PUTBLOCK_WRITECHUNK_RPC",
      "protoValue" : 2
    },
    "om" : {
      "name" : "S3_OBJECT_TAGGING_API",
      "protoValue" : 9
    }
  },
  "ozone" : {
    "revision" : "d3cadd856eb2ade5639784c916705de1ae201ed7",
    "url" : "git@github.com:apache/ozone.git",
    "version" : "2.0.0-SNAPSHOT"
  }
}
```

**Comment by errose28** [comment]
Thanks for adding this Attila. +1 for this `ozone debug version` also including the overall ozone version, making it like a lower level extension of `ozone version`.

I like this simple implementation where the command just prints the component version of the current `ozone` executable that is run since it is a `debug` subcommand and those usually run totally local. I think we just need to make the help message a little clearer in explaining this. For example, one might expect one run of `ozone debug version` from the client machine to identify a mixed client/server version scenario, but this is not the case. 

It might be good to add a startup log message for component versions like we have for layout versions, but we can do that in a separate change if we want.

**Comment by adoroszlai** [comment]
Thanks @errose28 for the review.  I'm not sure I can describe it clearly but succintly, here's my attempt at this:

> ```
> description = "Show internal version of Ozone components, as defined in the artifacts where this command is 
>     executed.  It does not communicate with any Ozone services.  Run the same command on different nodes to
>     get a cross-component view of versions.  The goal of this command is to help quickly get a glance of the 
>     latest features supported by Ozone on the current node."
> ```

Let me know if it makes sense or you would like to tweak it.  Once we have the final version, I'll update the PR.

**Comment by errose28** [comment]
Updated description makes sense to me. Should we make the json a little more flexible in case we want to add more info in the future, like software layout version? For example, within each component we could wrap the `name` and `protoValue` fields in a `componentVersion` map so we can add other metadata to each component object later without collisions.

**Review by errose28 — APPROVED** [review]
Thanks for adding this @adoroszlai LGTM

**Comment by adoroszlai** [comment]
Thanks @errose28 for reviewing and merging this.

**Pull request merged**
