### PR TITLE
HDDS-4950. Provide example k8s files to run full HA Ozone

### PR DESCRIPTION
**Pull request by elek**
## What changes were proposed in this pull request?

With the help of @bshashikant I tested how SCM-HA works in K8s environement. It worked well and here I publish the required k8s yaml files for any tests. 

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4950

## How was this patch tested?

The easiest way to test is using [k3s](https://k3s.io/).

As the final definition is optimized for real, multi-node environment with persistence, testing is easier with transforming the files:

```
flekszible generate \
    -t mount:hostPath=/home/elek/projects/ozone/hadoop-ozone/dist/target/ozone-1.1.0-SNAPSHOT,path=/opt/hadoop \
    -t image:image=apache/ozone-runner:20200420-1 \
    -t ozone/onenode
```

Where the first host path is the location of your Ozone build.

### CODE REVIEW

**Comment by bshashikant** [comment]
https://issues.apache.org/jira/browse/HDDS-4957 fixes one of the flaky tests in the branch.

**Comment by bshashikant** [comment]
@elek , can you please rebase against current HDDS-2823 branch as well?

**Comment by GlenGeng** [comment]
Please hold on the merge util we finish merging master back to 2823. Thanks!

**Comment by bshashikant** [comment]
@elek , can you rebase and retrigger the tests now?

**Comment by elek** [comment]
> @elek , can you rebase and retrigger the tests now?

Sure, just rebased the branch and pushed...

**Review by bshashikant — APPROVED** [review]

**Pull request merged**
