### PR TITLE
HDDS-7174. Migrate SCM integration tests to JUnit 5

### PR DESCRIPTION
**Pull request by kaijchen**
## What changes were proposed in this pull request?

Migrate tests under following directories to JUnit 5.

* `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/`
* `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/`

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7174

## How was this patch tested?

https://github.com/kaijchen/ozone/actions/runs/2932207457

### CODE REVIEW

**Comment by kerneltime** [comment]
cc @dombizita

**Comment by kaijchen** [comment]
There might be merge conflicts with HDDS-6975(#3723) in `TestDecommissionAndMaintenance`.
I would suggest merge his first.

**Comment by sodonnel** [comment]
Thanks for mentioning this issue in #3723. Hopefully I can get it merged today or tomorrow. I would appreciate if if you can hold on this one until then.

**Review by adoroszlai — APPROVED** [review]
Thanks @kaijchen for the patch.

**Pull request merged**
