### PR TITLE
HDDS-8251. RocksIterator is not closed properly in snapshot

### PR DESCRIPTION
**Pull request by duongkame**
## What changes were proposed in this pull request?

RocksObject leaks in snapshot.
```
2023-03-23 09:44:20,288 [Finalizer] WARN  managed.ManagedRocksObjectUtils (ManagedRocksObjectUtils.java:assertClosed(54)) - RocksIterator is not closed properly
 StackTrace for unclosed instance: org.apache.hadoop.hdds.utils.db.managed.ManagedObject.<init>(ManagedObject.java:35)
org.apache.hadoop.hdds.utils.db.managed.ManagedRocksIterator.<init>(ManagedRocksIterator.java:28)
org.apache.hadoop.hdds.utils.db.managed.ManagedRocksIterator.managed(ManagedRocksIterator.java:32)
org.apache.hadoop.hdds.utils.db.RocksDatabase.newIterator(RocksDatabase.java:757)
org.apache.hadoop.hdds.utils.db.RDBTable.iterator(RDBTable.java:167)
org.apache.hadoop.hdds.utils.db.TypedTable.iterator(TypedTable.java:286)
org.apache.hadoop.ozone.om.SnapshotChainManager.loadFromSnapshotInfoTable(SnapshotChainManager.java:266)
org.apache.hadoop.ozone.om.SnapshotChainManager.<init>(SnapshotChainManager.java:63)
org.apache.hadoop.ozone.om.OmMetadataManagerImpl.start(OmMetadataManagerImpl.java:480)
org.apache.hadoop.ozone.om.OmMetadataManagerImpl.<init>(OmMetadataManagerImpl.java:319)
org.apache.hadoop.ozone.om.OzoneManager.instantiateServices(OzoneManager.java:747)
org.apache.hadoop.ozone.om.OzoneManager.<init>(OzoneManager.java:628)
org.apache.hadoop.ozone.om.OzoneManager.createOm(OzoneManager.java:713)
org.apache.hadoop.ozone.MiniOzoneHAClusterImpl$Builder.createOMService(MiniOzoneHAClusterImpl.java:518)
org.apache.hadoop.ozone.MiniOzoneHAClusterImpl$Builder.build(MiniOzoneHAClusterImpl.java:426)
org.apache.hadoop.ozone.om.TestOmSnapshot.init(TestOmSnapshot.java:175)
org.apache.hadoop.ozone.om.TestOmSnapshot.<init>(TestOmSnapshot.java:144) 
```

```
2023-03-23 10:10:20,868 [Finalizer] WARN  managed.ManagedRocksObjectUtils (ManagedRocksObjectUtils.java:assertClosed(54)) - RocksIterator is not closed properly
 StackTrace for unclosed instance: org.apache.hadoop.hdds.utils.db.managed.ManagedObject.<init>(ManagedObject.java:35)
org.apache.hadoop.hdds.utils.db.managed.ManagedRocksIterator.<init>(ManagedRocksIterator.java:28)
org.apache.hadoop.ozone.om.snapshot.RocksDbPersistentList.iterator(RocksDbPersistentList.java:85)
org.apache.hadoop.ozone.om.snapshot.SnapshotDiffManager.addToReport(SnapshotDiffManager.java:658)
org.apache.hadoop.ozone.om.snapshot.SnapshotDiffManager.generateDiffReport(SnapshotDiffManager.java:612)
org.apache.hadoop.ozone.om.snapshot.SnapshotDiffManager.generateSnapshotDiffReport(SnapshotDiffManager.java:343)
org.apache.hadoop.ozone.om.snapshot.SnapshotDiffManager.getSnapshotDiffReport(SnapshotDiffManager.java:196)
org.apache.hadoop.ozone.om.OmSnapshotManager.getSnapshotDiffReport(OmSnapshotManager.java:455)
org.apache.hadoop.ozone.om.OzoneManager.snapshotDiff(OzoneManager.java:4493)
org.apache.hadoop.ozone.protocolPB.OzoneManagerRequestHandler.snapshotDiff(OzoneManagerRequestHandler.java:1223)
org.apache.hadoop.ozone.protocolPB.OzoneManagerRequestHandler.handleReadRequest(OzoneManagerRequestHandler.java:300)
org.apache.hadoop.ozone.protocolPB.OzoneManagerProtocolServerSideTranslatorPB.submitReadRequestToOM(OzoneManagerProtocolServerSideTranslatorPB.java:223)
org.apache.hadoop.ozone.protocolPB.OzoneManagerProtocolServerSideTranslatorPB.processRequest(OzoneManagerProtocolServerSideTranslatorPB.java:177)
org.apache.hadoop.hdds.server.OzoneProtocolMessageDispatcher.processRequest(OzoneProtocolMessageDispatcher.java:87) 
```

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8251

## How was this patch tested?

No more leak warnings when running `TestOmSnapshot` integration test.

### CODE REVIEW

**Comment by duongkame** [comment]
@hemantk-12 Can you please review this?

**Review by hemantk-12 — APPROVED** [review]
LGTM,.

Thanks for the quick fix @duongkame.

Sorry for all these memory leak. I tired to fix this in #4438

**Review by adoroszlai — APPROVED** [review]
Thanks @duongkame for the fix.

**Comment by smengcl** [comment]
Thanks @duongkame for the quick fix!

**Comment by smengcl** [comment]
I was wondering if there is a findbugs warning for leaking resources so we can hopefully avoid this before a commit is merged. Then I realized [spotbugs](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#obl-method-may-fail-to-clean-up-stream-or-resource-on-checked-exception-obl-unsatisfied-obligation-exception-edge) might be the one. Filed HDDS-8268

**Pull request merged**
