### PR TITLE
HDDS-4791. StateContext.getReports may return list with size larger t…

### PR DESCRIPTION
**Pull request by symious**
…he maxLimit

## What changes were proposed in this pull request?

- Fix the logic to return the correct size of the result list.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4791

## How was this patch tested?

Unit Test.

### CODE REVIEW

**Comment by symious** [comment]
@elek @adoroszlai Could you help to review this PR? Thanks in advance.

**Review by dineshchitlangia — APPROVED** [review]
+1 @symious  thanks for the improvement

**Review by adoroszlai — COMMENTED** [review]
Thanks @symious for finding this discrepancy introduced in HDDS-4404.

The proposed solution has a problem (`IndexOutOfBoundsException`) in edge case: if `maxLimit` is smaller than the number of available misc. reports.  And if they are equal, `getIncrementalReports` is called unnecessarily as it will be limited to 0 items.

Also, I'm not sure behavior for `maxLimit < 3` can be well defined other than throwing some exception.

Since `getReports` is called from only one place, with unlimited list size:

https://github.com/apache/ozone/blob/df38294e34544d073fe2e3c85f329d53f88e70c3/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java#L302

I think it would be better to just remove `maxLimit` parameter.

**Comment by smengcl** [comment]
Thanks @symious for the patch. Yes this was an oversight.

I have the same concern as @adoroszlai mentioned. `maxLimit - nonIncrementalReports.size() < 0` can be a problem.

I agree that we should just remove the `maxLimit` param from `getReports()`:

https://github.com/apache/ozone/blob/6b67ae0c40110af195b897fb70a87dc6e82d467e/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java#L327-L330

and put `getIncrementalReports(endpoint, Integer.MAX_VALUE - 3)` inside, maybe.

**Comment by symious** [comment]
@adoroszlai @smengcl Thanks for the review, added a commit to handle the edge case.

**Review by smengcl — APPROVED** [review]
+1 on the latest change.

A caveat is if maxLimit <= 3, the getReports may always return the same set of reports because once containerReports/nodeReport/pipelineReports are set, they are only updated but not removed. It makes most sense if the caller of getReports specifies maxLimit > 4.

**Comment by symious** [comment]
@smengcl @adoroszlai Thanks for the review.

**Pull request merged**
