### PR TITLE
HDDS-8006. [snapshot] Add unit test cases for snapshot delete

### PR DESCRIPTION
**Pull request by jyotirmoy-gh**
## What changes were proposed in this pull request?

Add unit-testcases for snapshot delete - `TestOmSnapshot`

- testCreateSnapshotMissingMandatoryParams
- testDeleteSnapshotTwice
- testDeleteSnapshotFailure
- testDeleteSnapshotMissingMandatoryParams

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8006

## How was this patch tested?

Testcase files - `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java`

### CODE REVIEW

**Comment by jyotirmoy-gh** [comment]
@smengcl @sadanand48 @nilotpalnandi - Please review

**Review by smengcl — APPROVED** [review]
Thanks @jyotirmoy-gh for the test additions!

**Review by prashantpogde — APPROVED** [review]
Thank you @jyotirmoy-gh. The test cases look good to me.

**Comment by adoroszlai** [comment]
`TestOmSnapshot` (the class being changed) has failed:

* in @jyotirmoy-gh's fork for all 3 commits
  * https://github.com/jyotirmoy-gh/ozone/actions/runs/4242114172/jobs/7373203285#step:5:7810
  * https://github.com/jyotirmoy-gh/ozone/actions/runs/4242173232/jobs/7373337122#step:5:3336
  * https://github.com/jyotirmoy-gh/ozone/actions/runs/4242211689/jobs/7373428163#step:5:3336
* in the PR for both runs of the last commit (was cancelled in previous runs)
  * https://github.com/apache/ozone/actions/runs/4242212133/jobs/7373435640#step:5:3336
  * https://github.com/apache/ozone/actions/runs/4242212133/jobs/7474740898#step:5:3336
* and now on `master`:
  * https://github.com/apache/ozone/actions/runs/4296771836/jobs/7488905670#step:5:3383

Please do not merge with failing tests.

**Comment by adoroszlai** [comment]
@smengcl thanks for submitting revert PR, but I don't think it is necessary.  Only `testSnapDiffWithMultipleSSTs` is failing, which has been flaky even before this PR (HDDS-8005), only now it fails consistently.  I propose to disable `testSnapDiffWithMultipleSSTs` (via `@Ignore`) and fix it in HDDS-8005, instead of reverting this PR.  The new test cases are probably good in themselves.

**Comment by smengcl** [comment]
> `TestOmSnapshot` (the class being changed) has failed:
> 
> * in @jyotirmoy-gh's fork for all 3 commits
>   
>   * https://github.com/jyotirmoy-gh/ozone/actions/runs/4242114172/jobs/7373203285#step:5:7810
>   * https://github.com/jyotirmoy-gh/ozone/actions/runs/4242173232/jobs/7373337122#step:5:3336
>   * https://github.com/jyotirmoy-gh/ozone/actions/runs/4242211689/jobs/7373428163#step:5:3336
> * in the PR for both runs of the last commit (was cancelled in previous runs)
>   
>   * https://github.com/apache/ozone/actions/runs/4242212133/jobs/7373435640#step:5:3336
>   * https://github.com/apache/ozone/actions/runs/4242212133/jobs/7474740898#step:5:3336
> * and now on `master`:
>   
>   * https://github.com/apache/ozone/actions/runs/4296771836/jobs/7488905670#step:5:3383
> 
> Please do not merge with failing tests.

Thanks @adoroszlai for pointing that out. Sorry about the trouble. Not sure how I could have missed that in the first place. (Subconsciously I thought the other +1 implied a green CI.) Will double check from now on.

**Comment by smengcl** [comment]
> The new test cases are probably good in themselves.

I see. Now that it is reverted we can fix it in a new PR, together with the reverted changes. Would you file a new PR for this @jyotirmoy-gh ?

**Comment by jyotirmoy-gh** [comment]
@smengcl , I will create a new PR for this.

**Comment by jyotirmoy-gh** [comment]
PR for new changes - https://github.com/apache/ozone/pull/4331

**Pull request merged**
