### PR TITLE
HDDS-8941. Intermittent timeout in TestContainerBalancerTask

### PR DESCRIPTION
**Pull request by ArafatKhan2198**
## What changes were proposed in this pull request?
- Enabled the test method `TestContainerBalancerTask` with a fix.
- The small change fixes the testDelayedStart of TestContainerBalancerTask method timing out, the reason why its timing out is because of the fact that sometimes it takes more than 20millisecond to go into waiting state.
So by increasing the waiting time to 40 seconds, I was able to run the test successfully 600 times.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-8941

## How was this patch tested?

I was able to run the test successfully 600 times.
https://github.com/ArafatKhan2198/ozone/actions/runs/7617671268
https://github.com/ArafatKhan2198/ozone/actions/runs/7617674689
https://github.com/ArafatKhan2198/ozone/actions/runs/7617675944

### CODE REVIEW

**Comment by ArafatKhan2198** [comment]
@siddhantsangwan could you take a look.

**Comment by adoroszlai** [comment]
Thanks @ArafatKhan2198 for the patch.  There is an unused import:

https://github.com/ArafatKhan2198/ozone/actions/runs/7637376931/job/20806129469

**Comment by ArafatKhan2198** [comment]
Done @adoroszlai

**Review by siddhantsangwan — COMMENTED** [review]
LGTM. Running CI.

**Review by adoroszlai — APPROVED** [review]

**Comment by adoroszlai** [comment]
Thanks @ArafatKhan2198 for the patch.

**Pull request merged**
