### PR TITLE
HDDS-4219. Revisit 'static' nature of OM Layout Version Manager.

### PR DESCRIPTION
**Pull request by avijayanhwx**
## What changes were proposed in this pull request?

- Cleanup of OM and HDDS layout version manager classes. 
- Moved away from static initialization for ease of unit testing. 
- Renamed SCM and Datanode finalization action for first upgrade version.
- Removed higher level HDDS Layout feature and action catalog classes.
- Combine SCM and Datanode LayoutVersionManager since they are essentially the same.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-4219

## How was this patch tested?
Unit testing.

### CODE REVIEW

**Comment by fapifta** [comment]
Hi @avijayanhwx thank you for working on this one, the changes look good to me.

One thing I would note is the missing newline at the end of the HDDSLayoutFeature class, other than that it looks good to me.
+1 otherwise.

**Comment by avijayanhwx** [comment]
> Hi @avijayanhwx thank you for working on this one, the changes look good to me.
> 
> One thing I would note is the missing newline at the end of the HDDSLayoutFeature class, other than that it looks good to me.
> +1 otherwise.

Thanks for the review @fapifta. Based on offline review, I have further simplified the HDDS actions. PTAL

**Review by fapifta — APPROVED** [review]
+1

**Comment by avijayanhwx** [comment]
Failed test in CI (TestSCMRestart) was fixed in HDDS-4679.

**Review by swagle — APPROVED** [review]
+1 LGTM, super like the fact that we have moved away from static initializers avoiding need for test instrumentation, we should document best practices for Ozone based on such refactors.

**Comment by avijayanhwx** [comment]
Thanks for the review @fapifta  & @swagle!

**Pull request merged**
