### PR TITLE
HDDS-5175. ozone fs trash service does not handle bucket -rm -R

### PR DESCRIPTION
**Pull request by neils-dev**
…rive delete of bucket invoked with Trash enabled.

## What changes were proposed in this pull request?

When the trash service is enabled and a _bucket_ recursive delete, `rm -r`, ozone fs command is invoked a fatal error occurs ( _**Fatal internal error**_ for _ofs_ and _**Null Pointer Exception**_ for _o3fs_). 

This patch fixes the fatal error condition for handling the ozone fs shell `rm -r` command for buckets through the ozone trash policy specific _moveToTrash_ method.  When the recursive rm is invoked with trash enabled, the trash policy _moveToTrash_ method is called to provide placing the item (through rename) to the bucket specific trash.  Because the the bucket is recursively deleted along with all keys in this case, the Trash directory (found under the bucket) is also affected causing the fatal error.  This patch detects the error condition and handles the condition by throwing an informative error and directs the user to apply _**-skipTrash**_ option to override and perform the delete.
## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5175

## How was this patch tested?
Patch was tested invoking ozone fs shell commands with trash service enabled on the docker ozonesecure cluster.

```
$ cd hadoop-ozone/dist/target/ozone-1.2.0-SNAPSHOT/compose/ozonesecure
$ docker-compose up -d --scale datanode=3
$ docker-compose exec scm bash
```

```
bash-4.2$ kinit -kt /etc/security/keytabs/testuser.keytab testuser/scm@EXAMPLE.COM
bash-4.2$ ozone sh volume create vol1
bash-4.2$  ozone fs -mkdir -p /vol1/bucket1
bash-4.2$ ozone fs -touch /vol1/bucket1/key1

```
To create error:
ofs:
`bash-4.2$ ozone fs -rm -R /vol1/bucket1`
o3fs:
`ozone fs -rm -R o3fs://bucket1.vol1`

**_Apply patch through core-site configuration: using ozone specific trash policy:_**

set **`_<property> <name>fs.trash.classname</name><value>org.apache.hadoop.ozone.om.TrashPolicyOzone</value> </property>`_**

set `fs.trash.classname=org.apache.hadoop.ozone.om.TrashPolicyOzone
`
`bash-4.2$ vi /etc/hadoop/core-site.xml`
insert `<property> <name>fs.trash.classname</name><value>org.apache.hadoop.ozone.om.TrashPolicyOzone</value> </property>`

_ofs fix:_
recursive_rm_bucket_ofs

_o3fs fix:_
recursive_rm_bucket_o3fs

override and delete with `-skipTrash` option:
recursive_rm_bucket_skiptrash_ofs

### CODE REVIEW

**Review by sadanand48 — COMMENTED** [review]
Thanks @neils-dev for finding this. The patch looks good to me . +1.

**Review by avijayanhwx — APPROVED** [review]
Thanks for working on this @neils-dev. LGTM. Is there a doc item for Ozone trash or Bucket delete where we can add a statement that bucket delete is not allowed without skipTrash?

**Comment by neils-dev** [comment]
> Thanks for working on this @neils-dev. LGTM. Is there a doc item for Ozone trash or Bucket delete where we can add a statement that bucket delete is not allowed without skipTrash?

Thanks for your review and comments @avijayanhwx.  There indeed is a doc and associated jira for the Ozone trash feature, I believe it is HDDS-3367.  I'd be happy to add a statement to the jira.  Also, @sadanand48 any thoughts on this?

**Comment by sadanand48** [comment]
Thanks @avijayanhwx for the suggestion . We can  maybe mention this in the ofs/o3fs docs (https://github.com/apache/ozone/blame/master/hadoop-hdds/docs/content/interface/Ofs.md#L199)

**Comment by sadanand48** [comment]
Created PR https://github.com/apache/ozone/pull/2505 for the documentation part.

**Comment by adoroszlai** [comment]
Thanks @neils-dev for the patch, @avijayanhwx and @sadanand48 for the review.

@sadanand48 FYI, the same problem affects Ozone with `TrashPolicyDefault` (if `fs.trash.classname` is not set).  Is this a valid use case?  Can we do something to avoid using this trash policy, e.g. update Ozone's default setting to the custom implementation?

**Pull request merged**
