### PR TITLE
HDDS-7338. Reduced number of OzoneVolume constructors

### PR DESCRIPTION
**Pull request by myskov**
## What changes were proposed in this pull request?

I reduced number of constructors in org.apache.hadoop.ozone.client.OzoneVolume to 1 (from 7) and refactored javadoc comments.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7338

## How was this patch tested?

unit tests

### CODE REVIEW

**Review by smengcl — APPROVED** [review]
Thanks @myskov for cleaning this up.

**Review by adoroszlai — COMMENTED** [review]
Do we need to worry about backward compatibility here?

**Comment by myskov** [comment]
@adoroszlai I don't think so. 
Let's imagine a case that a Hadoop user uses an old client (without these changes) to access data on a newer (with these changes) remote Ozone cluster. As these changes consist only of internal ozone client changes, there should not be any issues with backward compatibility.

**Comment by neils-dev** [comment]
On backwards compatibility, need to ensure that changes to `OzoneVolume` constructors work with older versions of the om DB for the `OmVolumeArgs` that are returned by the `metadatamanager` and used in the patch to create the `OzoneVolumes` in the `RpcClient`.  
For example the `RpcClient` `bulidOzoneVolume` issues an RPC request to the ozone manager to return the `volumeinfo` that is retrieved from the `metadatamanager` as a `OmVolumeArgs` from different versions .

**Comment by DaveTeng0** [comment]
hey @myskov ~ there is one latest comment from @neils-dev . Please help take a look when you have time, thanks!

**Comment by adoroszlai** [comment]
Thanks again @myskov for the patch.  It turns out an improvement ticket had long been open for these constructors, finally implemented in #4262.

**Pull request closed without merging**
