### PR TITLE
HDDS-5987. [Ozone-Streaming] Add XceiverClientRatis stream config

### PR DESCRIPTION
**Pull request by guohao-rosicky**
Add XceiverClientRatis stream config
jira: https://issues.apache.org/jira/browse/HDDS-5987

### CODE REVIEW

**Comment by guohao-rosicky** [comment]
hi @captainzmc , can you help review this patch?

**Comment by captainzmc** [comment]
This is ozone's patch used fix RATIS-1424?

**Comment by guohao-rosicky** [comment]
@captainzmc , 

> 这是用于修复 RATIS-1424 的臭氧补丁吗？

yes,  
the configuration in ratis needs to be applied in ozone.

**Review by captainzmc — APPROVED** [review]
+1 Thanks @guohao-rosicky,  the change looks good. Let's merge this and continue the stability test.

**Pull request merged**
