### PR TITLE
HDDS-3911. Compile error in acceptance test on HDDS-2823

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Fix compile error in `acceptance` check on `HDDS-2823` branch.  The error is caused by the following:

1. HDDS-3597 eliminated the need for installing Protobuf, now we use `protobuf-maven-plugin` to compile `.proto` files.
2. HDDS-3757 changed `acceptance` check to build directly on GitHub's runner.  Previously it was built inside a docker container which [comes with Protobuf pre-installed](https://github.com/apache/hadoop-docker-ozone/blob/87d5222ad232191759aca649e84c836b588eb8b3/Dockerfile#L26-L36).
3. HDDS-3621 moved proto files to separate subprojects.
4. HDDS-3186 introduced `SCMRatisProtocol.proto` on the `HDDS-2823` branch, in the old location and using `hadoop-maven-plugins:protoc` to compile it.  (It was the correct location and plugin at that time.)
5. 82c30a4d2 merged the above 1-3 changes from `master` to `HDDS-2823`, so now `protoc` is no longer available when building Ozone for `acceptance`.  Other checks are still run in the docker container, so they are not affected.

The fix is to move new `SCMRatisProtocol.proto` to `hadoop-hdds/interface-server` project, and let it be compiled by `protobuf-maven-plugin`.

https://issues.apache.org/jira/browse/HDDS-3911

## How was this patch tested?

Compiled locally after uninstalling Protobuf:

```
$ which protoc
protoc not found

$ mvn -DskipTests clean package
...
[INFO] BUILD SUCCESS
```

Acceptance test compiles fine:
https://github.com/adoroszlai/hadoop-ozone/runs/826834813#step:5:8603

### CODE REVIEW

**Comment by timmylicheng** [comment]
Is this happening for master as well?

**Comment by adoroszlai** [comment]
> Is this happening for master as well?

No, it's specific to the `HDDS-2823` branch.  I've updated the PR description with an explanation.

**Review by nandakumar131 — APPROVED** [review]

**Comment by nandakumar131** [comment]
The test failure doesn't seem to be related. Thanks @adoroszlai for the quick fix.

**Comment by nandakumar131** [comment]
I have retriggered the prechecks.

**Review by xiaoyuyao — APPROVED** [review]
Change LGTM, +1 pending CI.

**Comment by timmylicheng** [comment]
I will merge this. Thanks @adoroszlai for the contribution.

**Pull request merged**
