### PR TITLE
HDDS-7525. Migrate key digest from MD5 to SHA256 in Ozone shell

### PR DESCRIPTION
**Pull request by GAOJHIHCYUAN**
## What changes were proposed in this pull request?

Modifing using strong hashing algorithms for security-sensitive

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7525

## How was this patch tested?

image

### CODE REVIEW

**Comment by kerneltime** [comment]
cc @xBis7 @swamirishi can you please take a look.

**Review by xBis7 — COMMENTED** [review]
@GAOJHIHCYUAN Thanks for the patch. Is there a particular reason for proposing this change other than improving security?

BTW, I tested it with freon while checking the metrics and there is no noticeable difference in performance. I don't think there will be any issues with merging this change.

**Review by kerneltime — APPROVED** [review]

**Comment by GAOJHIHCYUAN** [comment]
> @GAOJHIHCYUAN Thanks for the patch. Is there a particular reason for proposing this change other than improving security?
> 
> BTW, I tested it with freon while checking the metrics and there is no noticeable difference in performance. I don't think there will be any issues with merging this change.

**Comment by GAOJHIHCYUAN** [comment]
> @GAOJHIHCYUAN Thanks for the patch. Is there a particular reason for proposing this change other than improving security?

No,there is not a particular reason, just improving security.

> BTW, I tested it with freon while checking the metrics and there is no noticeable difference in performance. I don't think there will be any issues with merging this change.

**Review by kaijchen — APPROVED** [review]

**Comment by kaijchen** [comment]
Thanks @GAOJHIHCYUAN for the work, thanks @kerneltime for the review.

**Pull request merged**
