### PR TITLE
HDDS-10268. [hsync] Add OpenTracing traces to client side read path

### PR DESCRIPTION
**Pull request by jojochuang**
## What changes were proposed in this pull request?
Add client side trace spans to ofs file system APIs and input/output stream APIs.

Select screenshots:

input stream read()
Screenshot 2024-02-23 at 10 31 43 AM

outputstream hsyc
Screenshot 2024-02-23 at 5 03 42 PM

file system contentSummary API
Screenshot 2024-02-23 at 10 43 46 AM

file system create file API
Screenshot 2024-02-23 at 5 06 45 PM

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-10268

## How was this patch tested?

Tested in a dev cluster.

### CODE REVIEW

**Comment by kerneltime** [comment]
cc @tanvipenumudy

**Review by smengcl — APPROVED** [review]
Thanks @jojochuang for adding the new spans and tags. lgtm

**Comment by smengcl** [comment]
Retriggered CI

**Comment by adoroszlai** [comment]
@duongkame @kerneltime @tanvipenumudy please review

**Comment by smengcl** [comment]
Thanks @jojochuang for the patch.

**Pull request merged**
