### PR TITLE
HDDS-10180. Update proto.lock from Ozone 1.4.0

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Continue #6044 with additional changes from #6074.

https://issues.apache.org/jira/browse/HDDS-10180

## How was this patch tested?

`mvn -DskipTests clean verify`

CI build:
https://github.com/adoroszlai/ozone/actions/runs/7636117693/job/20802633998

### CODE REVIEW

**Comment by symious** [comment]
@adoroszlai Thank you for the fix.

I was wondering if we must use protolock@0.16.0 for the lock generation in the future?

**Comment by adoroszlai** [comment]
> I was wondering if we must use protolock@0.16.0 for the lock generation in the future?

No, the new version will be fine.

**Comment by symious** [comment]
> No, the new version will be fine.

Confirmed no more error or warnings. LGTM.

**Comment by adoroszlai** [comment]
@errose28 would you like to take a look?

**Review by errose28 — APPROVED** [review]
Thanks for taking care of the proto updates @adoroszlai

**Comment by adoroszlai** [comment]
Thanks @symious for the initial patch and review, @errose28 for reviewing and merging this (and preserving co-author info).

**Pull request merged**
