### PR TITLE
HDDS-9365. [hsync] DataNode to deserialize Ratis transaction only once.

### PR DESCRIPTION
**Pull request by szetszwo**
## What changes were proposed in this pull request?

Today DataNode deserializes request proto at every callback method: applyTransaction, applyTransaction, writeTransaction, readTransaction.
 
For a transaction, the deserialzation happens more than 5 times (readTransaction happens twice for leader)
 
It's super expensive. We should deserialize only once during preAppendTransaction() which takes place in parallel.
 
## What is the link to the Apache JIRA

HDDS-9365

## How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Review by jojochuang — APPROVED** [review]
LGTM

**Comment by jojochuang** [comment]
Looks like the PR fails the acceptance tests consecutively. @szetszwo can you check again?

**Comment by szetszwo** [comment]
The test failures were due to the context is not created in follower.  Just have updated the code to see if it can pass the tests.

**Comment by szetszwo** [comment]
@jojochuang , it can pass the tests now.  Please take a look again.  Thanks.

**Review by jojochuang — APPROVED** [review]
Looks great!

**Pull request merged**
