### PR TITLE
HDDS-6296. Update Netty to the latest 4.1.74.Final.

### PR DESCRIPTION
**Pull request by jojochuang**
Change-Id: I88692a6327d7aa734f8e380e622a34be4d0edf75

## What changes were proposed in this pull request?
Update our Netty dependency to the latest version.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-6296

## How was this patch tested?
Existing unit tests/acceptance tests.

### CODE REVIEW

**Review by adoroszlai — COMMENTED** [review]
Thanks @jojochuang for the patch.

Dependency check fails because the new Netty version introduces two new jars (Java classes were split from native jars into separate ones).

https://github.com/apache/ozone/runs/5137806010?check_suite_focus=true#step:5:11

**Review by adoroszlai — COMMENTED** [review]
I think two more changes are needed for `ozone-csi` to pass, both because current Ratis 2.2.0 does not shade all Netty native libs (RATIS-1443).

1. Need to specify `classifier` in `hadoop-ozone/csi/pom.xml` for the native libs.  Currently these are found as a side effect of the incomplete shading.
```diff
diff --git hadoop-ozone/csi/pom.xml hadoop-ozone/csi/pom.xml
index 45645fb65..f64a40e5f 100644
--- hadoop-ozone/csi/pom.xml
+++ hadoop-ozone/csi/pom.xml
@@ -72,10 +72,12 @@ http://maven.apache.org/xsd/maven-4.0.0.xsd">
     <dependency>
       <groupId>io.netty</groupId>
       <artifactId>netty-transport-native-epoll</artifactId>
+      <classifier>linux-x86_64</classifier>
     </dependency>
     <dependency>
       <groupId>io.netty</groupId>
       <artifactId>netty-transport-native-unix-common</artifactId>
+      <classifier>linux-x86_64</classifier>
     </dependency>
     <dependency>
       <groupId>log4j</groupId>
```
2. We also need to upgrade Ratis (and before that Ratis needs to update its Thirdparty dependency).  Without upgrading (and with the `classifier` change from item 1) we get:
`IllegalStateException: Multiple resources found for 'META-INF/native/libnetty_transport_native_epoll_x86_64.so' with different content: [jar:file:/opt/hadoop/share/ozone/lib/ratis-thirdparty-misc-0.7.0.jar!/META-INF/native/libnetty_transport_native_epoll_x86_64.so, jar:file:/opt/hadoop/share/ozone/lib/netty-transport-native-epoll-4.1.74.Final-linux-x86_64.jar!/META-INF/native/libnetty_transport_native_epoll_x86_64.so]`

**Comment by jojochuang** [comment]
Alright, sounds like we should table it for now, working on the Ratis side before coming back to this.

**Comment by adoroszlai** [comment]
> Alright, sounds like we should table it for now, working on the Ratis side before coming back to this.

I've already started:
https://issues.apache.org/jira/browse/RATIS-1515

but encountered some compatibility issues (will try to post some details).

**Comment by adoroszlai** [comment]
Closing for now.

**Pull request closed without merging**
