### PR TITLE
HDDS-5667. documentation page layout

### PR DESCRIPTION
**Pull request by sky76093016**
## What changes were proposed in this pull request?

The layout of the overview interface is different from other interfaces (the content part on the right). 

The purpose of this issue is to maintain a consistent layout.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5667

## How was this patch tested?

Hugo serve pass.

image

### CODE REVIEW

**Comment by sky76093016** [comment]
cc @cku328

**Comment by iamabug** [comment]
LGTM +1.

**Review by iamabug — APPROVED** [review]

**Review by cku328 — APPROVED** [review]
Whether the page layout should be set with right border padding or not, I think it can be discussed further, but at the moment most of them are.

I +1 for this patch because it has a consistent layout. Thanks @sky76093016.

**Comment by iamabug** [comment]
Thanks for the patch @sky76093016 and the review @cku328 , I am merging this.

**Pull request merged**
