### PR TITLE
HDDS-2346. Replication manager config has wrong description

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Copy the correct description from [old `ozone-default.xml`](https://github.com/apache/hadoop/pull/773/files#diff-1e26884a3be02959ddb7c4c65591f630).  Reformatted to make checkstyle happy.

https://issues.apache.org/jira/browse/HDDS-2346

## How was this patch tested?

Verified the generated config property in `hadoop-hdds/server-scm/target/classes/ozone-default-generated.xml`.

### CODE REVIEW

**Review by bharatviswa504 — APPROVED** [review]
+1 LGTM.

**Comment by bharatviswa504** [comment]
Thank You @adoroszlai for the contribution.

**Comment by adoroszlai** [comment]
Thanks @bharatviswa504 for reviewing and merging this.

**Comment by Ko-dany** [comment]
## Jira Tickets Updated (100 total)

### ✅ Fixed in PR (24 tickets) - Status: In Progress
**Netty 4.1.136 → 4.1.137**
OSV-42714, OSV-42713, OSV-42712, OSV-42711, OSV-42710, OSV-42709, OSV-42708, OSV-42707, OSV-42706, OSV-42705, OSV-42704, OSV-42703, OSV-42694, OSV-42688, OSV-42687, OSV-42633, OSV-42623, OSV-42622, OSV-42620, OSV-42619, OSV-42618, OSV-42617, OSV-42616, OSV-42615

### ✅ Already Fixed (7 tickets) - Status: In Progress
- **OpenTelemetry** (1): OSV-42684 - Already at 1.62.0
- **Commons Configuration** (2): OSV-42624, OSV-42621 - Already at 2.15.0
- **Log4j** (4): OSV-42692, OSV-42691, OSV-42690, OSV-42632 - Already at 2.26.0

### ⚠️ Exception Request - Deferred (58 tickets)

**Spring Framework (50)** - Status: Exception Request (Deferred)
OSV-42683 through OSV-42634
Reason: Spring 6.2.20 not published (6.2.19 is latest); Spring 5→6 breaking upgrade; no upstream support

**Jetty (8)** - Status: Exception Request (Deferred)  
OSV-42697, OSV-42696, OSV-42695, OSV-42689, OSV-42686, OSV-42627, OSV-42626, OSV-42625
Reason: Jetty 9→12 breaking upgrade; no upstream support

### 🔗 Transitive Dependencies (11 tickets)
**Jackson (11)** - Assigned, commented as transitive
OSV-42702, OSV-42701, OSV-42700, OSV-42699, OSV-42698, OSV-42693, OSV-42685, OSV-42631, OSV-42630, OSV-42629, OSV-42628
Note: From Hadoop (ODP-pinned); no Hadoop tickets exist yet

**Pull request merged**
