### PR TITLE
HDDS-6284. Add BlockDeletingService worker size config

### PR DESCRIPTION
**Pull request by guohao-rosicky**
## What changes were proposed in this pull request?

Add BlockDeletingService worker size config

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-6284

### CODE REVIEW

**Review by mukul1987 — APPROVED** [review]

**Review by adoroszlai — COMMENTED** [review]
`BlockDeletingServiceTestImpl` also needs to pass the new parameter in:

https://github.com/apache/ozone/blob/5c3aa0185bfc43edc046274f39e32267dd6fad27/hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/testutils/BlockDeletingServiceTestImpl.java#L47-L48

**Review by adoroszlai — APPROVED** [review]
Thanks @guohao-rosicky for updating the patch.

**Comment by guohao-rosicky** [comment]
@adoroszlai 
Can this PR be merged？

**Comment by adoroszlai** [comment]
@mukul1987 would you like to take another look or can we merge it?

**Comment by mukul1987** [comment]
Looks good to me. Merging this.

**Pull request merged**
