### PR TITLE
HDDS-5282. Relocate classes copied from Hadoop

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Ozone has some test classes partially copied from Hadoop, located in the original packages.  Relocate these to avoid [classpath conflict](https://mail-archives.apache.org/mod_mbox/hadoop-common-dev/202105.mbox/%3CCADiq6%3Dyxoa47hR%3DYi8Aw6uWoJwqusOnvOvbu%2B0H7zvj0ktQBdQ%40mail.gmail.com%3E).

https://issues.apache.org/jira/browse/HDDS-5282

## How was this patch tested?

https://github.com/adoroszlai/hadoop-ozone/actions/runs/892794650

### CODE REVIEW

**Review by ayushtkn — COMMENTED** [review]
Thanx @adoroszlai for the fix.
Do you plan to add some enforcement rules in pom.xml to restrict such imports as well? So that other folks don't land up using the utils from Hadoop jars, or that won't be required?

**Review by jojochuang — COMMENTED** [review]
Thanks for working on this. This is required to support Hadoop 3.3.

**Comment by adoroszlai** [comment]
> Do you plan to add some enforcement rules in pom.xml to restrict such imports as well?

Thanks @ayushtkn for the suggestion.  Updated checkstyle rules with this.

**Review by elek — APPROVED** [review]
+1, LGTM (after a green build)

**Review by ayushtkn — APPROVED** [review]
Thanx for the fix.
Changes LGTM. Guess you need to resolve the conflicts...

**Comment by adoroszlai** [comment]
Thanks @ayushtkn, @elek and @jojochuang for the review.

**Pull request merged**
