### PR TITLE
HDDS-5451. Incorrect PENDINGDELETEBLOCKCOUNT caused by resent command.

### PR DESCRIPTION
**Pull request by ChenSammi**
https://issues.apache.org/jira/browse/HDDS-5451

### CODE REVIEW

**Comment by ChenSammi** [comment]
Hi @lokeshj1703 , would you help to review the patch?

**Review by lokeshj1703 — APPROVED** [review]
@ChenSammi Thanks for working on this PR! The changes look good to me. +1.

**Comment by lokeshj1703** [comment]
@ChenSammi Thanks for the contribution! I have committed the PR to master branch.

**Comment by ChenSammi** [comment]
Thanks @lokeshj1703  for the code review.

**Pull request merged**
