### PR TITLE
HDDS-6930. SCM,OM,RECON should not print ERROR and exit with code 1 on successful shutdown

### PR DESCRIPTION
**Pull request by navinko**
## What changes were proposed in this pull request?
Updated exit status to zero for normal shutdown.
## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-6930

Please replace this section with the link to the Apache JIRA)

## How was this patch tested?
I did local testing and verified the logs for SCM shutdown.
Screenshot 2022-10-17 at 8 26 11 PM

### CODE REVIEW

**Comment by kerneltime** [comment]
cc @devmadhuu

**Review by aswinshakil — COMMENTED** [review]
Thanks for working on this. Can we change the scope of this to include [OM](https://github.com/apache/ozone/blob/e7f4c05d0967932d5bde49c51501ba83e6af532a/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java#L2092) and [Recon](https://github.com/apache/ozone/blob/5ba6728f7c2535d4ada5a78a99504424e3d7bd4a/hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java#L355) as well? As I have seen same shutdown error message there as well.

**Comment by navinko** [comment]
Thanks @kerneltime @aswinshakil for reviewing this . I have updated the Jira scope and code changes .

**Comment by aswinshakil** [comment]
Thanks for the patch @navinko. Approved it. Looks like the CI is not triggered here, but looking at [this](https://github.com/navinko/ozone/actions/runs/3272158978) CI passed.

**Review by aswinshakil — APPROVED** [review]

**Review by smengcl — APPROVED** [review]

**Comment by navinko** [comment]
Thanks @aswinshakil @ChenSammi  @kerneltime @smengcl for reviewing and merging this PR

**Pull request merged**
