### PR TITLE
HDDS-4338. Fix the issue that SCM web UI banner shows "HDFS SCM".

### PR DESCRIPTION
**Pull request by yuyang733**
## What changes were proposed in this pull request?

Fix the issue that the SCM web UI banner shows "HDFS SCM". Change the "HDFS SCM" to the "Ozone SCM".

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4338

## How was this patch tested?

Passed all default unit tests and checked it after the actual startup.

### CODE REVIEW

**Review by xiaoyuyao — COMMENTED** [review]
Thanks @yuyang733 for the patch. It LGTM. A few other places that should be fixed. 

hddsDatanode/index.html 
Line25: HDFS=>HDDS

scm/index.html, in addition to the fix included in the patch at line 49, two other places need to be fixed.
Line 25/27 HDFS->HDDS

**Comment by yuyang733** [comment]
> Thanks @yuyang733 for the patch. It LGTM. A few other places that should be fixed.
> 
> hddsDatanode/index.html
> Line25: HDFS=>HDDS
> 
> scm/index.html, in addition to the fix included in the patch at line 49, two other places need to be fixed.
> Line 25/27 HDFS->HDDS

Thanks for your comments. I have fixed it.

**Review by xiaoyuyao — APPROVED** [review]
LGTM, +1

**Comment by xiaoyuyao** [comment]
Thanks @yuyang733  for the contribution. PR has been merged.

**Pull request merged**
