### PR TITLE
HDDS-3415. Enable TestContainerPlacement#testContainerPlacementCapacity

### PR DESCRIPTION
**Pull request by devmadhuu**
## What changes were proposed in this pull request?
This PR fixes an Unhealthy test `TestContainerPlacement#testContainerPlacementCapacity`. This test was failing because storage reports were not set for datanodes to assert capacity, used and remaining bytes of datanodes due to which asserts were failing. And this test case was also not setting the `NetworkTopology` for SCM Node Manager.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-3415

## How was this patch tested?

This patch is tested using existing Junit test run and make sure that it runs fine and healthy.

### CODE REVIEW

**Comment by devmadhuu** [comment]
@adoroszlai  pls review.

**Comment by devmadhuu** [comment]
@adoroszlai  can you pls review ?

**Review by swamirishi — APPROVED** [review]
Thank you for the patch @devmadhuu, changes look good to me

**Comment by adoroszlai** [comment]
Thanks @devmadhuu for the patch, @swamirishi for the review.

**Pull request merged**
