### PR TITLE
HDDS-9816. Addendum: fix compile error due to conflict with HDDS-9303

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Fix compile error caused by HDDS-9816 and HDDS-9303.

https://issues.apache.org/jira/browse/HDDS-9816

## How was this patch tested?

Compiled locally.

### CODE REVIEW

**Review by sodonnel — APPROVED** [review]

**Review by hemantk-12 — APPROVED** [review]
Thanks for the quick fix @adoroszlai

**Review by sadanand48 — APPROVED** [review]
Thanks for reporting & fixing it, @adoroszlai , @sodonnel .

**Comment by adoroszlai** [comment]
Thanks @hemantk-12, @sadanand48, @sodonnel for the review.

**Comment by ChenSammi** [comment]
@adoroszlai , this change caused compile failure,

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project ozone-manager: Compilation failure
Error:  /home/runner/work/ozone/ozone/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java:[3038,16] incompatible types: java.lang.String cannot be converted to java.util.List<java.util.List<java.lang.String>>
Error:  -> [Help 1]
```

https://github.com/apache/ozone/actions/runs/7168115694/job/19515934863?pr=5749

**Comment by adoroszlai** [comment]
> this change caused compile failure

@ChenSammi it fixed the compile error that was caused by the change mentioned in PR description.

Your PR is still built against the previous commit:

> HEAD is now at ecb77b7 Merge 32e628eef008413395c3d30daa77671e0b801668 into fd9bb1e2a41230721261619490b93cd07c752bb0

https://github.com/apache/ozone/actions/runs/7168115694/job/19515934863?pr=5749#step:2:491

To fix it, please merge current `master` into your branch.

**Comment by ChenSammi** [comment]
> > this change caused compile failure
> 
> @ChenSammi it fixed the compile error that was caused by the change mentioned in PR description.
> 
> Your PR is still built against the previous commit:
> 
> > HEAD is now at [ecb77b7](https://github.com/apache/ozone/commit/ecb77b7d7809f62d47125550759e627eca2357d7) Merge [32e628e](https://github.com/apache/ozone/commit/32e628eef008413395c3d30daa77671e0b801668) into [fd9bb1e](https://github.com/apache/ozone/commit/fd9bb1e2a41230721261619490b93cd07c752bb0)
> 
> https://github.com/apache/ozone/actions/runs/7168115694/job/19515934863?pr=5749#step:2:491
> 
> To fix it, please merge current `master` into your branch.

Right, @adoroszlai , this patch fixes the compile issue. Just curious, the JIRAs caused compile failure are all recent merged. How does their CI build no find the compile failure?

**Comment by hemantk-12** [comment]
> > > this change caused compile failure
> > 
> > 
> > @ChenSammi it fixed the compile error that was caused by the change mentioned in PR description.
> > Your PR is still built against the previous commit:
> > > HEAD is now at [ecb77b7](https://github.com/apache/ozone/commit/ecb77b7d7809f62d47125550759e627eca2357d7) Merge [32e628e](https://github.com/apache/ozone/commit/32e628eef008413395c3d30daa77671e0b801668) into [fd9bb1e](https://github.com/apache/ozone/commit/fd9bb1e2a41230721261619490b93cd07c752bb0)
> > 
> > 
> > https://github.com/apache/ozone/actions/runs/7168115694/job/19515934863?pr=5749#step:2:491
> > To fix it, please merge current `master` into your branch.
> 
> Right, @adoroszlai , this patch fixes the compile issue. Just curious, the JIRAs caused compile failure are all recent merged. How does their CI build not find the compile failure?

I think both commits were fine independently and CI passed on both of them. Compilation failed when both were merged into master branch.

**Comment by adoroszlai** [comment]
> How does their CI build not find the compile failure?

Events:

 * last PR build for HDDS-9303: HEAD is now at 8eb8805 Merge 89b1c07f306d9d4ede735ef7f2b9f9e5cc5754ce into eb7e8d009e701d1dc7a792deca1b5d6893d051c0
 * ... (many commits on `master`)
 * last PR build for HDDS-9816: HEAD is now at a1eec72 Merge 61e2881f2ecec5bce314a08e48e0507dbcc1213a into 3c9df5cf3292b2feb0ffa1aa9c254b1c51c8cb9a
 * ... (few commits on `master`)
 * HDDS-9303 is merged as dd431cde68
 * ... (many commits on `master`)
 * HDDS-9816 is merged as 94f539d700

Git reports conflict for the second PR if commits on `master` edit the same lines, but it doesn't know about code syntax/semantics.

If I remember correctly there is an option in Github to only allow PR merge if its branch is up-to-date with the base branch.  But that requires more work for both developers and CI.

The current behavior is similar to optimistic locking in DBs.  I think it's fine in most cases.

**Pull request merged**
