### PR TITLE
HDDS-10565. Merge master `97038ef` to feature branch HDDS-7593

### PR DESCRIPTION
**Pull request by smengcl**
DO NOT merge this directly from GitHub, which will result in an undesired squash commit. Pushing this branch from local will automatically mark this PR as merged.

## What changes were proposed in this pull request?

Resolve conflicts brought by new commits on master branch. Especially:

- HDDS-5865 (https://github.com/apache/ozone/pull/6408)

```
Merge remote-tracking branch 'asf/master' into HDDS-7593

Conflicts:
hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockInputStreamFactoryImpl.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/DummyBlockInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockInputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyInputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestChunkStreams.java
```

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-10565

## How was this patch tested?

- All existing tests should pass.

### CODE REVIEW

**Review by jojochuang — APPROVED** [review]
+1

**Comment by smengcl** [comment]
FYI I just merged new commit HDDS-10442 from latest HDDS-7593 branch to this one.

It won't show up in this PR diff because it cancels out but it is in the branch now:

https://github.com/smengcl/hadoop-ozone/commits/HDDS-7593-master-merge-97038ef/

**Comment by smengcl** [comment]
CI passed: https://github.com/apache/ozone/actions/runs/8457412905/job/23169313675?pr=6419

Pushed with `--force-with-lease` to ASF repo from local.

**Comment by smengcl** [comment]
Thanks @jojochuang for the review.

**Pull request merged**
