### PR TITLE
HDDS-8551. Fix the generic type of CodecRegistry.getCodec

### PR DESCRIPTION
**Pull request by szetszwo**
## What changes were proposed in this pull request?

Do not get codec from super classes and interfaces.

## What is the link to the Apache JIRA

HDDS-8551

## How was this patch tested?

By existing tests.

### CODE REVIEW

**Review by adoroszlai — COMMENTED** [review]
Thanks @szetszwo for the patch.  Can you please add a unit test?

**Comment by szetszwo** [comment]
@adoroszlai , thanks a lot for reviewing this.  Just have added a test and done some refactoring.

**Review by adoroszlai — APPROVED** [review]
Thanks @szetszwo for updating the patch.  It seems changes in `ByteStringCodec` belong to HDDS-8559 and HDDS-8542, but they are fine.

**Comment by szetszwo** [comment]
@adoroszlai , thanks a lot for reviewing this!

> It seems changes in `ByteStringCode` belong to ...

The change is for the test.  Since `ByteString` is `abstract`, its instances are subclass objects.

**Pull request merged**
