### PR TITLE
[DO NOT MERGE] Backport some fixes and compatibility commits from master to ozone-1.4

### PR DESCRIPTION
**Pull request by xichen01**
## What changes were proposed in this pull request?
Backport the following commit from master to ozone-1.4 for 1.4.1. Including some bug fixes and necessary dependencies.

HDDS-8900. Mark TestSecretKeysApi#testSecretKeyApiSuccess as flaky
HDDS-10985. EC Reconstruction failed because the size of currentChunks was not equal to checksumBlockDataChunks. (#7009)
HDDS-11375. DN startup fails due to illegal configuration of raft.grpc.message.size.max (#7128)
~~HDDS-11350. NullPointerException thrown on checking container balancer status (#7134)~~
~~HDDS-11120. Rich rebalancing status info (#6911)~~
HDDS-9889. Refactor tests related to dynamical adaptation for datanode limits in ContainerBalancer (#5758)
HDDS-10612. Add Robot test to verify Container Balancer for RATIS containers (#6457)
HDDS-11331. Fix Datanode unable to report for a long time (#7090)
HDDS-11320. Update OM, SCM, Datanode conf for RATIS-2135. (#7080)
HDDS-10773. Simplify OM RaftProperties formatting (#6605)
HDDS-10761. Add raft close threshold config to OM RaftProperties (#6594)
HDDS-11309. Increase CONTAINER_STATE Column Length in UNHEALTHY_CONTAINERS to Avoid Truncation (#7071)
HDDS-10293. IllegalArgumentException: containerSize Negative (#6178)
HDDS-9819. Recon - Potential memory overflow in Container Health Task. (#5841)
HDDS-11209. Avoid insufficient EC pipelines in the container pipeline cache (#6974)
HDDS-11152. OMDoubleBuffer error when handling snapshot's background operations (#7112)
HDDS-9198. Maintain local cache in OMSnapshotPurgeRequest to get updated snapshotInfo and pass the same to OMSnapshotPurgeResponse (#7045)
HDDS-11137. Removed locks from SnapshotPurge and SnapshotSetProperty APIs. (#7018)

## How was this patch tested?

https://github.com/xichen01/ozone/actions/runs/10927685549

### CODE REVIEW

**Comment by xichen01** [comment]
@adoroszlai @hemantk-12 @whbing @devmadhuu @ArafatKhan2198 @szetszwo @jianghuazhu @afilpp @Montura @juncevich @siddhantsangwan @jojochuang @slfan1989 please check that your commits are correctly cherry-picked.

**Comment by devmadhuu** [comment]
@xichen01 LGTM.

**Comment by slfan1989** [comment]
@xichen01 LGTM.

**Comment by jianghuazhu** [comment]
@xichen01 LGTM.

**Comment by jojochuang** [comment]
HDDS-11375 LGTM

**Review by siddhantsangwan — COMMENTED** [review]
My commits look OK. Thanks @xichen01.

**Comment by whbing** [comment]
@xichen01  LGTM for my commits

**Comment by adoroszlai** [comment]
> [HDDS-11120](https://issues.apache.org/jira/browse/HDDS-11120). Rich rebalancing status info (#6911)

I'm not sure this is appropriate for a patch release.

**Comment by ArafatKhan2198** [comment]
@xichen01 LGTM!

**Comment by hemantk-12** [comment]
Thanks, @xichen01 for backporting these changes. Snapshot changes look good to me +1.

**Comment by xichen01** [comment]
> > [HDDS-11120](https://issues.apache.org/jira/browse/HDDS-11120). Rich rebalancing status info (#6911)
> 
> I'm not sure this is appropriate for a patch release.

@adoroszlai 
[HDDS-11120](https://issues.apache.org/jira/browse/HDDS-11120) makes "cherry-pick"  [HDDS-11350](https://issues.apache.org/jira/browse/HDDS-11350)  less conflicting, and it's also a useful ticket, so it's backported too.

**Comment by adoroszlai** [comment]
> > > [HDDS-11120](https://issues.apache.org/jira/browse/HDDS-11120). Rich rebalancing status info (#6911)
> > 
> > I'm not sure this is appropriate for a patch release.
> 
> [HDDS-11120](https://issues.apache.org/jira/browse/HDDS-11120) makes "cherry-pick" [HDDS-11350](https://issues.apache.org/jira/browse/HDDS-11350) less conflicting, and it's also a useful ticket, so it's backported too.

Patch releases are not for "useful" tickets (improvements), rather for bugfixes and security issues.  Does HDDS-11350 affect 1.4.0 anyway?

Please also see HDDS-11385, which is a follow-up to HDDS-11120.

**Comment by xichen01** [comment]
[HDDS-11350](https://issues.apache.org/jira/browse/HDDS-11350) is caused by  [HDDS-11120](https://issues.apache.org/jira/browse/HDDS-11120), not a fix for the previous bug. So if we don't cherry-pick HDDS-11120, the HDDS-11350 doesn't need to be backported.
So remove the patches HDDS-11350 and HDDS-11120 in the release.
cc: @adoroszlai

**Comment by xichen01** [comment]
Merged using:
```bash
git checkout ozone-1.4
git pull
git merge --ff-only ozone-1.4-backport
git push
```

**Pull request merged**
