### PR TITLE
HDDS-9919. Update version to 1.5.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by symious**
## What changes were proposed in this pull request?

This ticket is to update Ozone version from "1.4.0-SNAPSHOT" to "1.5.0-SNAPSHOT".

The release of 1.4.0-SNAPSHOT will be based on the last commit from this one.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-9919

### CODE REVIEW

**Comment by ChenSammi** [comment]
There are two dependency-reduced-pom.xml files, which is still using 1.4.0-SNAPSHOT.

**Comment by adoroszlai** [comment]
@ChenSammi `dependency-reduced-pom.xml` is a build artifact.  If new version is built locally with `-DskipShade`, `ozonefs-shaded` and `ozonefs-filesystem-hadoop*` modules are skipped, output from earlier build can be left over.

**Comment by symious** [comment]
@ChenSammi Yes, as @adoroszlai mentioned, these two files are generated locally, they are not in the code base.

**Comment by ChenSammi** [comment]
Okay.  The rest looks good to me. Thanks @symious .

**Comment by symious** [comment]
@ChenSammi @adoroszlai Thank you for the review.

One thing I'm not sure is https://github.com/apache/ozone/blob/82d27595958f70a7468a38899bf48b2208bebe64/pom.xml#L71, should we change to another name?

**Comment by adoroszlai** [comment]
Yes, I guess we can choose the [national park](https://en.wikipedia.org/wiki/List_of_national_parks_of_the_United_States) starting with the next letter of the alphabet from:

* [Indiana Dunes](https://en.wikipedia.org/wiki/Indiana_Dunes_National_Park)
* [Isle Royale](https://en.wikipedia.org/wiki/Isle_Royale_National_Park)

Both sound great to me. :)

**Comment by ChenSammi** [comment]
Oh, didn't notice such a "ozone.release" property was added to carry the release name. Is it mentioned in that ozone release guide? @symious , if not, we can add one step/notice for this.

**Comment by symious** [comment]
@ChenSammi Found that it's a National park name, updated to a new one, PTAL.

**Comment by ChenSammi** [comment]
@symious , can we use national part name, close to prior "Hot Spring", leave enough name candidates for later releases? The name is picked in order to avoid conflict with each other.

**Comment by symious** [comment]
@ChenSammi Sure.
@adoroszlai Didn't notice last comment. I'll change to "[Indiana Dunes](https://en.wikipedia.org/wiki/Indiana_Dunes_National_Park)".

**Comment by ChenSammi** [comment]
@adoroszlai , could you like to take another look?

**Review by adoroszlai — APPROVED** [review]

**Pull request merged**
