### PR TITLE
HDDS-10006. Pass TransactionInfo in OzoneManagerRequestHandler.handleWriteRequest.

### PR DESCRIPTION
**Pull request by szetszwo**
## What changes were proposed in this pull request?

```java
//OzoneManagerRequestHandler
  public OMClientResponse handleWriteRequest(OMRequest omRequest,
      long transactionLogIndex) throws IOException {
```
In OzoneManagerRequestHandler.handleWriteRequest, only transactionLogIndex is passed without the term. However, it uses a Map/Function to get the term later on. We should pass TransactionInfo, which includes both term and index.

```java
//OzoneManagerDoubleBuffer
Function<Long, Long> indexToTerm 
```
## What is the link to the Apache JIRA

HDDS-10006

## How was this patch tested?

Updating existing tests.

### CODE REVIEW

**Comment by ChenSammi** [comment]
@szetszwo , thanks working on this,  the idea is very straight forward.  But from performance and GC point of view, the TransactionInfo.value() construction in applyTransaction is expensive compared with current solution.  In TransactionInfo.value(),  it will construct a transactionInfoString every time which is not needed in applyTransaction case. 

Instead of pass in TransactionInfo, pass TermIndex is enough and not that expensive than TransactionInfo.  Or keeping the current solution is also an option to me.

**Comment by szetszwo** [comment]
> ... which is not needed in applyTransaction case.

@ChenSammi , thanks for reviewing this!  `TransactionInfo` is needed for [omMetadataManager.getTransactionInfoTable().putWithBatch(..)](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java#L374-L375).

**Comment by szetszwo** [comment]
> Instead of pass in TransactionInfo, we can pass TermIndex which is enough and not that expensive than TransactionInfo.

@ChenSammi , Tried to use TermIndex instead of TransactionInfo (https://github.com/apache/ozone/pull/5860/commits/4bfd86b1a0bcaaf47e62b45645761d99380a68db).  It is good idea.  Please take a look.

**Review by ChenSammi — APPROVED** [review]
Thanks @szetszwo for this work.

**Comment by szetszwo** [comment]
@ChenSammi , thanks a lots for reviewing and merging this!

**Pull request merged**
