### PR TITLE
HDDS-4434.Fix typo in Admin.md

### PR DESCRIPTION
**Pull request by sky76093016**
## What changes were proposed in this pull request?

I corrected the spelling of the word.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4434

## How was this patch tested?
No need.

### CODE REVIEW

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by ayushtkn** [comment]
Can you assign the jira to your name, or can you help me with your jira id, If you aren't able to do so. Would be great if you can put up a comment in the jira itself, I will pick the id from there

**Comment by sky76093016** [comment]
@ayushtkn I have already replied in JIRA, thank you.

**Review by cku328 — APPROVED** [review]
LGTM+1. Thanks @sky76093016  for working on this.
Let's wait for full green build.

**Comment by ayushtkn** [comment]
Merged PR, Thanx @sky76093016  for the contribution and @cku328 for the review!!!

**Comment by cku328** [comment]
Thanks @ayushtkn for merging it.

Should we modify Git commit message to make it look the same as the others?
image
A blank character is missing...

**Comment by ayushtkn** [comment]
That is ok. You can't change the commit message without reverting. And this commit will still stay.
Until the jira id is correct, things would be good

**Pull request merged**
