### PR TITLE
HDDS-6537. Deprecate the renameKeys API

### PR DESCRIPTION
**Pull request by captainzmc**
## What changes were proposed in this pull request?

In [HDDS-3904](https://issues.apache.org/jira/browse/HDDS-3904) I add renameKeys to make BasicOzoneFileSystem get better performance. Because FSO([HDDS-2939](https://issues.apache.org/jira/browse/HDDS-2939)) development takes a long time, so we adopted this solution. Now FSO has been completed, and renameKeys has been replaced by FSO in FileSystem and is not used anywhere. So let's delete it to make our code cleaner.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-6537

## How was this patch tested?
Removing this should not affect other UT

### CODE REVIEW

**Comment by adoroszlai** [comment]
@captainzmc I don't think we should be removing public API without deprecating it first.

**Comment by captainzmc** [comment]
> @captainzmc I don't think we should be removing public API without deprecating it first.

Thanks @adoroszlai  for the advice.  Agree. I will set the method to Deprecated first. Let's keep them for the next release.

**Review by adoroszlai — APPROVED** [review]
Thanks @captainzmc for updating the patch, LGTM.

**Comment by captainzmc** [comment]
Thanks @adoroszlai

**Pull request merged**
