### PR TITLE
HDDS-4800. Fix TestContainerEndpoint after merging master to HDDS-2823.

### PR DESCRIPTION
**Pull request by GlenGeng**
## What changes were proposed in this pull request?

TestContainerEndpoint is broken after merging master to HDDS-2823 at Feb.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4800
## How was this patch tested?

CI

### CODE REVIEW

**Comment by GlenGeng** [comment]
After last two merge of master, we have four failures, one is findBugs, due to the second merge, 
The first merge cause the failure unit test(TestContainerEndpoint, TestReconContainerManager) and misc docker.
The second merge cause the failure of find bugs.

The fix is aims to the TestContainerEndpoint.

**Comment by bshashikant** [comment]
@GlenGeng , can you please add some detail about what was causing the test failure?

**Comment by GlenGeng** [comment]
After diff `hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java` between HDDS-2823 and master, the reason for failure is:

```
  void putContainerInfos(int num) throws IOException {
    for (int i = 1; i <= num; i++) {
      final ContainerInfo info = newContainerInfo(i);
      reconContainerManager.getContainerStore().put(new ContainerID(i), info);
      reconContainerManager.getContainerStateManager().addContainerInfo(
          i, info, null, null);
    }
  }
```
is replaced by 
```
for (int i = 1; i <= num; i++) {
  final ContainerInfo info = newContainerInfo(i);
  reconContainerManager.addNewContainer(I,
      new ContainerWithPipeline(info, pipeline));
}
```

It requires `pipeline` to exist in `ReconPipelineManager`, otherwise `addNewContainer` will fail, due to pipeline not found exception. The  thus the solution is quite straight forward, add the random generated pipeline into `ReconPipelineManager`.

BTW
```
// Mock ReconStorageContainerManagerFacade and other SCM related methods
```
it is already removed from master, and during the merge, we just remove it too.

The fix of `TestReconContainerManager` is due to the same reason.

**Review by bshashikant — APPROVED** [review]

**Comment by bshashikant** [comment]
The unit test failures is due to TestReconContainerManager. I am committing this one to unblock other PRs as the failures reported with this are unrelated to the PR.

**Comment by bshashikant** [comment]
Thanks @GlenGeng for the contribution.

**Pull request merged**
