### PR TITLE
HDDS-6510. Incremental Checkpointing Support

### PR DESCRIPTION
**Pull request by Xushaohong**
## What changes were proposed in this pull request?
**1. Unify the RDB snapshot provider for both OM and SCM**
**2. Support the incremental snapshot/checkpoint**  
(could support Recon in the future, since Recon delta download which gets updates from WAL is also not stable)

The design doc:
https://docs.google.com/document/d/1tcZA4p8u0I52IpN80XIlABZrSmn9dRiGw4fpEBhi2pg/edit#heading=h.lwha5swobgc3

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-6510

## How was this patch tested?
UT and Integration Test now.

### CODE REVIEW

**Comment by Xushaohong** [comment]
@hanishakoneru @nandakumar131 @errose28 @JacksonYao287  PTAL

**Comment by errose28** [comment]
Hi @Xushaohong I just did a high level read-through of the proposal.
> Recon delta download which gets updates from WAL is also not stable
- Can you site specific examples where it does not work in its current state, and why we cannot use a similar mechanism for OM incremental snapshot.

- It seems there may be some duplication between the snapshot diff feature being implemented on the snapshot branch and this feature, due to the sst file comparisons between checkpoints. I've only looked at each at a high level so someone like @smengcl could weigh in more on this if we decide to go this route.

**Comment by Xushaohong** [comment]
Hi @errose28 
 
> * Can you site specific examples where it does not work in its current state, and why we cannot use a similar mechanism for OM incremental snapshot.

GetUpdatesSince is mainly for streaming updates, and is limited by the WAL ttl, https://github.com/facebook/rocksdb/blob/5f52dbc5054ab0524563580fd064aa87f611afdc/java/src/main/java/org/rocksdb/RocksDB.java#L3947-L3963. 

Recon currently tries getting the delta updates, if that fails then will ask for the full snapshot. The WAL at leader starting from the snapshot index might already got purged since the snapshot would be big enough in the future.The incremental snapshot could be effective since it is a common solution for the RDB checkpoint mechianism. Recon can just download the incremental part of snapshot/checkpoint instead of asking the full snapshot every time until it can use delta updates.

> * It seems there may be some duplication between the snapshot diff feature being implemented on the snapshot branch and this feature, due to the sst file comparisons between checkpoints. I've only looked at each at a high level so someone like @smengcl could weigh in more on this if we decide to go this route.

This should be fine, the IC logic is not changing the original snapshot logic, which should be compatible.

**Comment by kerneltime** [comment]
@GeorgeJahad please take a look at this.

**Comment by errose28** [comment]
Thanks for the info @Xushaohong, your explanation makes sense. The Ratis log would probably be longer than the RocksDB WAL, so we can assume if we need a snapshot because there are no Ratis logs, those entries would have been flushed from the RocksDB WAL as well. Hence Recon's mechanism for incremental updates is not useful in this case.

**Comment by Xushaohong** [comment]
> Thanks for the info @Xushaohong, your explanation makes sense. The Ratis log would probably be longer than the RocksDB WAL, so we can assume if we need a snapshot because there are no Ratis logs, those entries would have been flushed from the RocksDB WAL as well. Hence Recon's mechanism for incremental updates is not useful in this case.

Yes, exactly!

**Comment by prashantpogde** [comment]
@Xushaohong How does this work in presence of HA failovers and OM leader changing? Two different OM nodes need not have the same notion of transaction index at which the checkpoint was taken.  There is also the issue of RocksDB compaction that can throw off SST file comparison.
We have a Snapshot feature that can help with something like this. It does take care of OM HA as well as rocksDB compaction. This can all be simplified if you can leverage the Snapshot feature. We can also do a zoom call during common time window to go over details.

**Comment by Xushaohong** [comment]
> How does this work in presence of HA failovers and OM leader changing? 

The whole install of snapshot may take a few times, which involves one full snaphsnapshot and the other incremental snapshots.
In my design, the follower only installs the Incremental snapshot from the same leader. This is protected by an AtomicReference lastLeader and the function RDBSnapshotProvider#checkLeaderConsistent, which will check the previous leader if is the same one and also check the candidate DB dir(which stores the snapshot downloaded at the follower side).

> For the issue of RocksDB compaction that can throw off SST file comparison.

Here my SST file comparison is a static comparison which is just a file name comparision. Since the RDB checkpoint from the same DB ensures each SST file with the same name is totally same. This might be a little tricky, and I have the UT for this.

> We have a Snapshot feature that can help with something like this. It does take care of OM HA as well as rocksDB compaction. This can all be simplified if you can leverage the Snapshot feature. We can also do a zoom call during common time window to go over details.

Last week, I have quickly scanned the Snapshot Feature branch, and some contents could be unified with mine. I agree with doing a Zoom call, how about you scheduling a time (GMT+8), and let's have a sync up? @prashantpogde

**Comment by GeorgeJahad** [comment]
please include me in the meeting @prashantpogde

**Comment by GeorgeJahad** [comment]
To facilitate the discussion, @prashantpogde asked me to write up a document:  https://docs.google.com/document/d/18roFnTzm8HkT3O3GkbSEBViSnAv0iqAzAca7OYwflMs

The first half of the doc explains how this PR works.  The second half covers my thoughts on how it might be integrated with OmSnapshotting.

**Comment by DaveTeng0** [comment]
Hey @Xushaohong ! Just a heads-up that there is some conflict with the master branch~

**Comment by Xushaohong** [comment]
> Hey @Xushaohong ! Just a heads-up that there is some conflict with the master branch~

Hi @DaveTeng0, I am wondering if someone could help review this PR.  Would you like to take over after my future update?

**Comment by adoroszlai** [comment]
@errose28 @GeorgeJahad please review

**Comment by errose28** [comment]
Last I heard this was being discussed with the snapshot team and @prashantpogde was taking over reviewing this feature. I'm not sure what the current status is from the snapshot point of view.

**Comment by DaveTeng0** [comment]
> 

@Xushaohong! I'll do my best to find what help I could provide for this PR! lol (since I'm kindf newbie into this feature~)

**Comment by Xushaohong** [comment]
Hi @errose28, we had a sync-up meeting together with @prashantpogde and @GeorgeJahad and the conclusion is leaving this Incremental checkpointing independent now, which does not affect the SNAPSHOT feature. So this PR needs to be reviewed.

**Comment by Xushaohong** [comment]
> > 
> 
> @Xushaohong! I'll do my best to find what help I could provide for this PR! lol (since I'm kindf newbie into this feature~)

Thx @DaveTeng0, please feel free to comment and ask.

**Comment by errose28** [comment]
Thanks for the update @Xushaohong. I won't have bandwidth any time soon to review this change unfortunately but we can try to find another reviewer.

**Comment by Xushaohong** [comment]
Please look at https://github.com/apache/ozone/pull/3980.

**Pull request closed without merging**
