### PR TITLE
HDDS-5713. Rebase of Disk balancer branch - do not merge.

### PR DESCRIPTION
**Pull request by sodonnel**
## What changes were proposed in this pull request?

Testing a rebase of the disk balancer branch (HDDS-5713) against master.

### CODE REVIEW

**Comment by adoroszlai** [comment]
Thanks @sodonnel for working on this.  Is the goal only to run a full CI workflow before updating the feature branch?

**Comment by sodonnel** [comment]
@adoroszlai Yes, I wanted to ensure the CI was clean after rebasing the branch, as there have been a lot of changes on tests, junit4 removed etc, and this branch was forked a long time ago. I probably could have ran this in my fork, but also though it was a good idea to leave being this closed PR as evidence we tested the rebase.

**Comment by adoroszlai** [comment]
> this closed PR as evidence we tested the rebase

Good point.

**Pull request closed without merging**
