### PR TITLE
HDDS-4605. Enable Multi Raft by default in Ozone.

### PR DESCRIPTION
**Pull request by bshashikant**
## What changes were proposed in this pull request?

1) Ensure single node ratis pipeline is not accounted for determining the pipeline limit

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4605

## How was this patch tested?

Modified UT

### CODE REVIEW

**Review by lokeshj1703 — COMMENTED** [review]
@bshashikant Thanks for working on the PR! The changes look good to me. Do we need to set the config `ScmConfigKeys.OZONE_DATANODE_PIPELINE_LIMIT` in tests? It should work by default? I have other minor comments inline.

**Comment by bshashikant** [comment]
> @bshashikant Thanks for working on the PR! The changes look good to me. Do we need to set the config `ScmConfigKeys.OZONE_DATANODE_PIPELINE_LIMIT` in tests? It should work by default? I have other minor comments inline.

@lokeshj1703 , thanks for looking into this. I have added the limit on some specific tests and these tests need only one pipeline to function properly. Enabling multiRaft by default for these break the assumptions made in the tests,

**Review by nandakumar131 — COMMENTED** [review]
+1, LGTM.

**Comment by bshashikant** [comment]
The test failures seem to be resulting out of space issue in test environement.
`StorageContainerException Occurred.
org.apache.hadoop.hdds.scm.container.common.helpers.StorageContainerException: java.io.IOException: No space left on device
	at org.apache.hadoop.ozone.container.keyvalue.helpers.ChunkUtils.wrapInStorageContainerException(ChunkUtils.java:331)
	at org.apache.hadoop.ozone.container.keyvalue.helpers.ChunkUtils.writeData(ChunkUtils.java:125)
	at org.apache.hadoop.ozone.container.keyvalue.helpers.ChunkUtils.writeData(ChunkUtils.java:110)
	at org.apache.hadoop.ozone.container.keyvalue.impl.FilePerBlockStrategy.writeChunk(FilePerBlockStrategy.java:120)
	at org.apache.hadoop.ozone.container.keyvalue.impl.ChunkManagerDispatcher.writeChunk(ChunkManagerDispatcher.java:70)
	at org.apache.hadoop.ozone.container.keyvalue.KeyValueHandler.handleWriteChunk(KeyValueHandler.java:722)
	at org.apache.hadoop.ozone.container.keyvalue.KeyValueHandler.dispatchRequest(KeyValueHandler.java:199)
	at org.apache.hadoop.ozone.container.keyvalue.KeyValueHandler.handle(KeyValueHandler.java:163)
	at org.apache.hadoop.ozone.container.common.impl.HddsDispatcher.dispatchRequest(HddsDispatcher.java:309)
	at org.apache.hadoop.ozone.container.common.impl.HddsDispatcher.lambda$dispatch$0(HddsDispatcher.java:171)
	at org.apache.hadoop.hdds.server.OzoneProtocolMessageDispatcher.processRequest(OzoneProtocolMessageDispatcher.java:87)
	at org.apache.hadoop.ozone.container.common.impl.HddsDispatcher.dispatch(HddsDispatcher.java:170)
	at org.apache.hadoop.ozone.container.common.transport.server.ratis.ContainerStateMachine.dispatchCommand(ContainerStateMachine.java:398)
	at org.apache.hadoop.ozone.container.common.transport.server.ratis.ContainerStateMachine.runCommand(ContainerStateMachine.java:408)
	at org.apache.hadoop.ozone.container.common.transport.server.ratis.ContainerStateMachine.lambda$handleWriteChunk$2(ContainerStateMachine.java:445)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.writev(FileDispatcherImpl.java:72)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:239)
	at java.nio.channels.FileChannel.write(FileChannel.java:414)
	at org.apache.hadoop.ozone.common.ChunkBufferImplWithByteBufferList.writeTo(ChunkBufferImplWithByteBufferList.java:186)
	at org.apache.hadoop.ozone.container.keyvalue.helpers.ChunkUtils.writeDataToChannel(ChunkUtils.java:163)
	at org.apache.hadoop.ozone.container.keyvalue.helpers.ChunkUtils.lambda$writeData$1(ChunkUtils.java:111)
	at org.apache.hadoop.ozone.container.keyvalue.helpers.ChunkUtils.writeData(ChunkUtils.java:123)`

**Pull request merged**
