### PR TITLE
HDDS-3689. Add various profiles to MiniOzoneChaosCluster to run different modes.

### PR DESCRIPTION
**Pull request by mukul1987**
## What changes were proposed in this pull request?

This change add datanode, OM and a mix of both as a chaos mode. The chaos tests have helped in finding multiple issues in Ozone.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3689

## How was this patch tested?
Ran MiniOzoneChaosCluster.

### CODE REVIEW

**Review by elek — CHANGES_REQUESTED** [review]
+1, LGTM thanks the patch @mukul1987 

One (very) minor NIT: the description of the subcommands are not updated:

```
Commands:
  all           run chaos cluster across all daemons
  datanode      run chaos cluster across all daemons
  ozonemanager  run chaos cluster across all daemons
```

And we need a green build.

**Comment by elek** [comment]
/pending on green build + small description fix

**Comment by mukul1987** [comment]
@elek I have addressed the comment in the lastest patch, please have a look.

**Review by elek — APPROVED** [review]

**Comment by elek** [comment]
Merged, thanks the patch @mukul1987

**Pull request merged**
