### PR TITLE
HDDS-8837. [Recon] Heatmap UI improvements

### PR DESCRIPTION
**Pull request by devabhishekpal**
## What changes were proposed in this pull request?

Ozone Recon has a Heatmap component which displays the heatmap of the access of the various buckets/volumes/keys.
This PR makes the following changes:

- Change heatmap colour scheme to a more neutral and Ozone compliant theme
- Fonts are changed to Roboto
- Spacing and component layout is changed to better utilize the available space

## What is the link to the Apache JIRA

[HDDS-8837](https://issues.apache.org/jira/browse/HDDS-8837): [Recon] Heatmap UI improvements

## How was this patch tested?

This patch was tested manually.
| Screenshots | Description |
|--------------|------------|
|ReconHeatmap-typeBucketcustomTimeFilter| Heatmap with custom select last 90 days time and Bucket type filter|
|ReconHeatmap-typeKeyFilter| Heatmap with Key type filter|
|ReconHeatmap-typeVolumeCustomTimeFilter| Heatmap with custom select last 90 days time and Volume type filter|
|ReconHeatmapDatePicker| Heatmap Custom Select 90 days date picker|

### CODE REVIEW

**Comment by devabhishekpal** [comment]
Hello, could someone please review this PR? @smengcl @dombizita @smitajoshi12 @ivandika3

**Comment by errose28** [comment]
cc @devmadhuu who has worked with Recon heatmap

**Comment by devmadhuu** [comment]
@devabhishekpal  thanks for working on this patch. Can you explain what those different color shades represent ? IMO heatmap is only to keep single color with variying shades, We have 3 categories currently to show keys/buckets falling under:

1. Less Accessed
2. Moderate Accessed
3. Most Accessed

So less accessed ones should be lighter yellow or amber, Moderate accessed should be orange shade and Most  Accessed should be towards darker side may be Red... This color scheme makes more sense for heatmap feature.

Ok with changing fonts to. match Ozone standard.

**Comment by devabhishekpal** [comment]
So the reason to divide the heatmap into shades of green and red was because within the shades of same colour it is harder to read quickly and interpret the data.

By separating the colour to red and green we can bring attention quickly to areas where most access happens, which otherwise we would have taken some time to view and interpret

**Comment by devabhishekpal** [comment]
Updated the colour scheme as recommended. Would appreciate feedback, or changes.
New colour scheme:
Screenshot 2023-06-15 at 9 34 01 PM

**Comment by krishnaasawa1** [comment]
@smitajoshi12 please check

**Comment by devabhishekpal** [comment]
Hello, I am closing this PR since there is plan for new improvements which are different from what was done in this PR.

**Pull request closed without merging**
