### PR TITLE
HDDS-7497. Fix mkdir does not update bucket's usedNamespace

### PR DESCRIPTION
**Pull request by xichen01**
## What changes were proposed in this pull request?
Fix `Ozone` fs `mkdir` does not update bucket's `usedNamespace`

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-7497

## How was this patch tested?
Before this PR: 
Bucket property `usedNamespace` will become negative after delete a directory, because the `mkdir` will not increase the `usedNamespace` of bucket but `rmdir` will decrease `usedNamespace`.
```java
"usedNamespace" can be updated when `mkdir`

[root@Linux /root/ozone]% ozone sh bucket create s3v/bucket1
[root@Linux /root/ozone]% ozone fs -mkdir ofs://localhost/s3v/bucket1/dir1
[root@Linux /root/ozone]% ozone sh bucket info s3v/bucket1
{
  "metadata" : { },
  "volumeName" : "s3v",
  "name" : "bucket1",
  "storageType" : "DISK",
  "versioning" : false,
  "usedBytes" : 0,
  "usedNamespace" : 0,
  "creationTime" : "2022-11-16T11:17:26.512Z",
  "modificationTime" : "2022-11-16T11:17:26.512Z",
  "quotaInBytes" : -1,
  "quotaInNamespace" : -1,
  "bucketLayout" : "OBJECT_STORE",
  "owner" : "root"
}

[root@Linux /root/ozone]% ozone fs -rmdir ofs://localhost/s3v/bucket1/dir1
[root@Linux /root/ozone]% ozone sh bucket info s3v/bucket1
{
  "metadata" : { },
  "volumeName" : "s3v",
  "name" : "bucket1",
  "storageType" : "DISK",
  "versioning" : false,
  "usedBytes" : 0,
  "usedNamespace" : -1,
  "creationTime" : "2022-11-16T11:17:26.512Z",
  "modificationTime" : "2022-11-16T11:17:26.512Z",
  "quotaInBytes" : -1,
  "quotaInNamespace" : -1,
  "bucketLayout" : "OBJECT_STORE",
  "owner" : "root"
}
[root@Linux /root/ozone]%
```
---

After this PR:
Bucket property `usedNamespace` will not be negative
```java
[root@Linux /root/ozone]% ozone sh bucket create s3v/bucket1
[root@Linux /root/ozone]% ozone fs -mkdir ofs://localhost/s3v/bucket1/dir1
[root@Linux /root/ozone]% ozone sh bucket info s3v/bucket1
{
  "metadata" : { },
  "volumeName" : "s3v",
  "name" : "bucket1",
  "storageType" : "DISK",
  "versioning" : false,
  "usedBytes" : 0,
  "usedNamespace" : 1,
  "creationTime" : "2022-11-16T11:17:26.512Z",
  "modificationTime" : "2022-11-16T11:17:26.512Z",
  "quotaInBytes" : -1,
  "quotaInNamespace" : -1,
  "bucketLayout" : "OBJECT_STORE",
  "owner" : "root"
}

[root@Linux /root/ozone]% ozone fs -rmdir ofs://localhost/s3v/bucket1/dir1
[root@Linux /root/ozone]% ozone sh bucket info s3v/bucket1
{
  "metadata" : { },
  "volumeName" : "s3v",
  "name" : "bucket1",
  "storageType" : "DISK",
  "versioning" : false,
  "usedBytes" : 0,
  "usedNamespace" : 0,
  "creationTime" : "2022-11-16T11:17:26.512Z",
  "modificationTime" : "2022-11-16T11:17:26.512Z",
  "quotaInBytes" : -1,
  "quotaInNamespace" : -1,
  "bucketLayout" : "OBJECT_STORE",
  "owner" : "root"
}
[root@Linux /root/ozone]%

`FSO` bucket will have the same result as above
```

### CODE REVIEW

**Review by sadanand48 — CHANGES_REQUESTED** [review]
Thanks @xichen01 for working on this, left a few comments inline , please take a look

**Comment by kerneltime** [comment]
This is a user facing change, it would be good to describe the desired behavior for FSO, OBS and Legacy.
cc @xBis7

**Comment by sadanand48** [comment]
Thanks @xBis7  for your comments. 

> If we were to accept this change then we would have to modify the whole system.



Currently Ozone directory create doesn’t account to an increment in the `usedNamespace` field of a bucket although delete directory decrements , the `usedNamespace`. I had also filed this [issue](https://issues.apache.org/jira/browse/HDDS-4854) once.
Although when I checked the definition of namespace online in hadoop context I got

> In Hadoop we refer to a Namespace as a file or directory which is handled by the Name Node

I agree directories are zero sized keys and so they don't account for `usedBytes` calculation, but I'm not very sure about the namespace. If we don't consider it, we shouldn't decrement it as part of delete.

cc @ChenSammi @sumitagrawl any thoughts?

**Comment by xichen01** [comment]
The initial issue I encountered was finding that the `usedNamespace` of our bucket was a negative value, and then locating that it was cause by that `mkdir` was not increasing `usedNamespace` but `rmdir` will `decreasing`
Maybe I should add this part of the description.

**Review by xBis7 — COMMENTED** [review]
@xichen01 I've left some comments inline. I confirmed in docker that it works with `ozone fs` commands such as `mkdir` and `touch` but `usedNamespace` should also be counting directories created with the `ozone sh` commands. It counts a key if it is created with `ozone sh key put` but if the keyname contains a directory that doesn't exist but is to be created then this directory won't be counted.

We might be able to fix this without having a different implementation for each bucket layout, by counting the levels of the keyName before incrementing `usedNamespace`. For this to work we should check if the directory already exists or needs to be created.

**Comment by xichen01** [comment]
@xBis7 
If execute `ozone sh key put ${keyname}`  but if the `${keyname}` contains a directory that doesn't exist. 
For FSO bucket, these "missing paths will be created automatically, I think these automatically created directories should increase `Usednamespace`.

```shell
[root@linux ~/root/ozone]$ ozone sh bucket create s3v/bucket4 -l FILE_SYSTEM_OPTIMIZED
[root@linux ~/root/ozone]$ ozone sh key put /s3v/bucket4/dir1/dir2/dir3/dir4/file119 ~/1M.img
[root@linux ~/root/ozone]$ ozone sh key ls s3v/bucket4 | grep name
  "name" : "dir1/",
  "name" : "dir1/dir2/",
  "name" : "dir1/dir2/dir3/",
  "name" : "dir1/dir2/dir3/dir4/",
  "name" : "dir1/dir2/dir3/dir4/file119",
```

 But for the Object bucket, these "missing paths" will not be created, they are not real, and should not increase `Usednamespace`

Do you have any suggestions?

**Comment by xBis7** [comment]
> For FSO bucket, these "missing paths will be created automatically, I think these automatically created directories should increase Usednamespace.

@xichen01 From what I saw, `usedNamespace` value doesn't increment in this case.

> But for the Object bucket, these "missing paths" will not be created, they are not real, and should not increase Usednamespace

I agree. 

> Do you have any suggestions?

You could get the `BucketInfo` and from that, check the `BucketLayout`. A LEGACY bucket with `ozone.om.enable.filesystem.paths` set to false, acts exactly like an OBS bucket, so in addition to the layout you should also check configs.

We should count directories only for FSO buckets and LEGACY buckets with `ozone.om.enable.filesystem.paths` set to true. @sadanand48 any thoughts on this?

**Comment by sadanand48** [comment]
> We should count directories only for FSO buckets and LEGACY buckets with ozone.om.enable.filesystem.paths set to true.

Yes agree @xBis7  , we should increment only if missing directories are created as part of key creates which is not the case for OBS.
@xichen01 I think you can look into [OMDirectoryCreateRequest#getAllParentInfo](https://github.com/apache/ozone/blob/6abee8a48cdbb9b79c9347638a33cb6d91602df6/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequest.java#L260)  and I guess the namespace increment should be done here as this is the place when the missing dirs get created.

**Review by sadanand48 — COMMENTED** [review]
Thanks @xichen01 for updating the PR, the changes look good to me.

**Comment by xBis7** [comment]
Thanks @xichen01 for the changes and @sadanand48 for the review. LGTM! I tested it locally and everything works as expected.

**Review by sadanand48 — APPROVED** [review]

**Pull request merged**
