### PR TITLE
HDDS-8717. Optimize checkACLsWithFSO to reduce redundant checks

### PR DESCRIPTION
**Pull request by whbing**
## What changes were proposed in this pull request?

Remove redundant checks in OMClientRequest#checkACLsWithFSO

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8717

Please replace this section with the link to the Apache JIRA)

## How was this patch tested?

ci：
https://github.com/whbing/ozone/actions/runs/5122110056

### CODE REVIEW

**Comment by whbing** [comment]
Parent ACL checking logic redefined in [HDDS-8717](https://github.com/apache/ozone/pull/4439/files#diff-c41e5b8d16771255aaf9b64fa5565417426d1bff8875cb45d1965334adad8806). Most cases just need READ permission for volume, see code:
```java
    // OzoneAclUtils#getParentNativeAcl
    // for bucket, except CREATE, all cases need READ for volume
    if (resType == BUCKET) {
      if (aclRight == IAccessAuthorizer.ACLType.CREATE) {
        return IAccessAuthorizer.ACLType.WRITE;
      }
      return IAccessAuthorizer.ACLType.READ;
    }
```
No need to check WRITE permission for volume when delete/rename key.

**Review by sadanand48 — COMMENTED** [review]
> Parent ACL checking logic redefined in [HDDS-8717](https://github.com/apache/ozone/pull/4439/files#diff-c41e5b8d16771255aaf9b64fa5565417426d1bff8875cb45d1965334adad8806). Most cases just need READ permission for volume

Thanks @whbing for the change, looks good to me according to the statement above that now key writes don't check volume acls and it is always set to Read to be at par with Ranger.

However in the native acl types I see  NONE as a type which means no permission for user, 
`enum ACLType {
    READ,
    WRITE,
    CREATE,
    LIST,
    DELETE,
    READ_ACL,
    WRITE_ACL,
    ALL,
    NONE;`
If I set  acl this at volume, this would be ignored as for any key write it doesn't check volume acl which makes setting NONE useless. Not sure what could be long term solution here but we might need to re-evaluate & document native authorizer behaviour and whats expected.

**Comment by whbing** [comment]
> > Parent ACL checking logic redefined in [HDDS-8717](https://github.com/apache/ozone/pull/4439/files#diff-c41e5b8d16771255aaf9b64fa5565417426d1bff8875cb45d1965334adad8806). Most cases just need READ permission for volume
> 
> Thanks @whbing for the change, looks good to me according to the statement above that now key writes don't check volume acls and it is always set to Read to be at par with Ranger.
> 
> However in the native acl types I see NONE as a type which means no permission for user, `enum ACLType { READ, WRITE, CREATE, LIST, DELETE, READ_ACL, WRITE_ACL, ALL, NONE;` If I set acl this at volume, this would be ignored as for any key write it doesn't check volume acl which makes setting NONE useless. Not sure what could be long term solution here but we might need to re-evaluate & document native authorizer behaviour and whats expected.

In fact, the volume's `READ` acl is checked for most operations for `bucket` or `key` operation. (Just `CREATE` bucket need volume's `WRITE` acl). 
Acls for volume will always be checked  in `OzoneNativeAuthorizer#checkAccess` as follow:

```bash
// OzoneNativeAuthorizer#checkAccess
switch (objInfo.getResourceType()) {
    case VOLUME:
      ...
      boolean volumeAccess =  isOwner ||
          volumeManager.checkAccess(objInfo, context);
      return volumeAccess;
    case BUCKET:
      ...
      return (bucketAccess
          && volumeManager.checkAccess(objInfo, parentContext));
    case KEY:
      ...
      return (keyAccess
          && prefixManager.checkAccess(objInfo, parentContext)
          && bucketManager.checkAccess(objInfo, parentContext)
          && volumeManager.checkAccess(objInfo, parentVolContext));
    case PREFIX:
      return (prefixAccess
          && bucketManager.checkAccess(objInfo, parentContext)
          && volumeManager.checkAccess(objInfo, parentVolContext));
    default:
      throw new OMException("Unexpected object type:" +
          objInfo.getResourceType(), INVALID_REQUEST);
```
`volumeManager.checkAccess(objInfo, parentVolContext))` will check volume's acl even if `objInfo.getResourceType()` is KEY. If NONE acl in a volume (or a bucket, a key), will permission denied.

**Comment by sadanand48** [comment]
> volumeManager.checkAccess(objInfo, parentVolContext)) will check volume's acl even if objInfo.getResourceType() is KEY. If NONE acl in a volume (or a bucket, a key), will permission denied.

Got it. Thanks @whbing for clarifying.

**Review by sumitagrawl — APPROVED** [review]
@whbing Thanks for working over this, LGTM +1

The changes in ACL for Native, and comparision is done as part of HDDS-7697, ref doc, https://issues.apache.org/jira/secure/attachment/13055895/ACL%20comparision%20for%20Ranger%20and%20Native%20ACL.docx

While validating permission, all parent context is getting validated by respective checkAcls() inside, re-validation of volume specific is redundant here.

**Comment by adoroszlai** [comment]
@aswinshakil @smengcl would you like to take a look?

**Comment by adoroszlai** [comment]
Thanks @whbing for the patch, @sadanand48, @sumitagrawl for the review.

**Comment by smengcl** [comment]
Thanks @whbing for the optimization.

**Pull request merged**
