### PR TITLE
HDDS-10081. Copy and migrate Hadoop base test classes to JUnit5

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Ozone relies on base test classes from Hadoop for:

 * `TestOzoneConfigurationFields`
 * filesystem contract tests

Currently those base classes are implemented using JUnit4 (migration is in progress in Hadoop repo).

This PR:

 * copies the base classes from Hadoop 3.3.6
 * migrates them to JUnit5 as much as possible (incorporating in-progress changes from Hadoop) without touching the concrete implementation subclasses in Ozone

`TestConfigurationFieldsBase` is completely migrated.

Abstract contract tests:

 * assertions migrated to AssertJ (HADOOP-19025)
 * `extends Assert` removed from `AbstractFSContractTestBase` and `ContractTestUtils`
 * JUnit5 lifecycle annotations added (but JUnit4-ones also kept)
 * `@Test` annotations left unchanged (still using JUnit4)
 * slightly tweaked for checkstyle/findbugs (but still need some suppression), since rules in Hadoop seem more lenient

Most Ozone contract tests use `Parameterized` runner, which requires quite some refactoring for migrating to JUnit5.  HDDS-10074 will finish that by refactoring Ozone's contract tests to JUnit5, and simply replacing `@Test` annotations in the abstract contract test base classes.

https://issues.apache.org/jira/browse/HDDS-10081

## How was this patch tested?

Existing _integration (contract)_ check in [CI](https://github.com/adoroszlai/ozone/actions/runs/7439172167/job/20238914151#step:6:142):

```
Tests run: 357, Failures: 0, Errors: 0, Skipped: 6
```

### CODE REVIEW

**Comment by SaketaChalamchala** [comment]
@hemantk-12 can you please take a look?

**Comment by SaketaChalamchala** [comment]
@swamirishi could you please take a look as well?

**Comment by adoroszlai** [comment]
This might seem to be a large change, but most of the code is copied from Hadoop.  Since this code is intended to be temporary in Ozone, I don't think we need to inspect it in detail, or adapt to Ozone coding conventions (beyond what checkstyle/findbugs complains about).

Having the same number of tests before/after the change, and with all tests passing, I think it should be fine.

If it helps during review, the follow-up change (conversion of Ozone contract tests to JUnit5) can be peeked at: https://github.com/adoroszlai/ozone/commit/708f49bdb8fb52c770e581bb9d74c9fb28a1f38c.

**Review by hemantk-12 — APPROVED** [review]
Thanks @adoroszlai for the patch.

Approving it without paying much attention to details as it is copied.

**Comment by adoroszlai** [comment]
Thanks @hemantk-12 for the review.  I pushed a new commit that replaces an import, because it is no longer accepted in Ozone after HDDS-10099:

```diff
-import org.apache.hadoop.thirdparty.com.google.common.base.Charsets;
+import com.google.common.base.Charsets;
```

**Review by hemantk-12 — APPROVED** [review]

**Review by smengcl — APPROVED** [review]
lgtm at a glance. Thanks @adoroszlai

**Pull request merged**
