### PR TITLE
HDDS-9582. OM transport factory configuration mismatch

### PR DESCRIPTION
**Pull request by duongkame**
## What changes were proposed in this pull request?
Fix OM transport factory configuration mismatch.
See [HDDS-9582](https://issues.apache.org/jira/browse/HDDS-9582)

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-9582

## How was this patch tested?

CI, plus local run to verify that S3 still works normally.

### CODE REVIEW

**Review by adoroszlai — COMMENTED** [review]
Thanks @duongkame for the patch, LGTM.

Tested as:

```
$ docker-compose exec -T s3g ozone freon -Dozone.om.transport.class=org.apache.hadoop.ozone.om.protocolPB.GrpcOmTransportFactory ockg -n1 -t1
...
2023-12-20 14:29:40,880 [main] INFO protocolPB.OmTransportFactory: Loading OM transport implementation org.apache.hadoop.ozone.om.protocolPB.GrpcOmTransportFactory as specified by configuration.
2023-12-20 14:29:41,213 [main] INFO protocolPB.GrpcOmTransport: GrpcOmTransport: started
...
2023-12-20 14:29:42,844 [shutdown-hook-0] INFO freon.BaseFreonGenerator: Successful executions: 1
```

Also checked acceptance test logs to verify that it uses `Hadoop3OmTransportFactory` by default, and uses `Hadoop27OmTransportFactory` for Hadoop 2.

We may want to change the two new log messages to `debug` to avoid polluting the output by default.

**Comment by xBis7** [comment]
@duongkame Thanks for the changes, it LGTM! Can you update your branch to the latest master? Changes are on top of a commit from last month. Although there are no conflicts with master, there could be a change that along with this patch, breaks the tests.

> We may want to change the two new log messages to debug to avoid polluting the output by default.

@adoroszlai I tested it locally, these logs will appear only once at the creation of a new `RpcClient`. I don't see them in OM logs.

**Comment by adoroszlai** [comment]
> these logs will appear only once at the creation of a new `RpcClient`. I don't see them in OM logs.

Yes, they appear only once.  But I'm not sure users running `hdfs dfs -put` and other operations are interested in this detail.  (The fact that Hadoop metrics system logs at info level is also a pain...)

```
$ hdfs dfs -put /opt/hadoop/NOTICE.txt ofs://omservice/volume1/bucket1/ozone-72528
2023-12-20 00:38:45 INFO  OmTransportFactory:62 - Loading OM transport implementation org.apache.hadoop.ozone.om.protocolPB.Hadoop3OmTransportFactory as specified by configuration.
2023-12-20 00:38:46 INFO  MetricsConfig:120 - Loaded properties from hadoop-metrics2.properties
2023-12-20 00:38:46 INFO  MetricsSystemImpl:378 - Scheduled Metric snapshot period at 10 second(s).
2023-12-20 00:38:46 INFO  MetricsSystemImpl:191 - XceiverClientMetrics metrics system started
2023-12-20 00:38:46 INFO  MetricRegistries:64 - Loaded MetricRegistries class org.apache.ratis.metrics.dropwizard3.Dm3MetricRegistriesImpl
```

**Comment by xBis7** [comment]
> I don't think it's necessary. CI run for PR builds/tests merge into current master:
> 
> > HEAD is now at https://github.com/apache/ozone/commit/be72540658e3e98aa9687afa146844279f43cf41 Merge https://github.com/apache/ozone/commit/f04f4afca262908c551ec7c8c8010681012a4893 into https://github.com/apache/ozone/commit/b55437f06b4ad524ebf4af42b31a92541160bede
> 
> https://github.com/apache/ozone/actions/runs/7269033371/job/19806008549#step:2:494

@adoroszlai Thanks for the clarification.

> But I'm not sure users running `hdfs dfs -put` and other operations are interested in this detail.

Yes, you are right, switching the log level to debug would be best.

**Comment by duongkame** [comment]
> > these logs will appear only once at the creation of a new `RpcClient`. I don't see them in OM logs.
> 
> Yes, they appear only once. But I'm not sure users running `hdfs dfs -put` and other operations are interested in this detail. (The fact that Hadoop metrics system logs at info level is also a pain...)
> 
> ```
> $ hdfs dfs -put /opt/hadoop/NOTICE.txt ofs://omservice/volume1/bucket1/ozone-72528
> 2023-12-20 00:38:45 INFO  OmTransportFactory:62 - Loading OM transport implementation org.apache.hadoop.ozone.om.protocolPB.Hadoop3OmTransportFactory as specified by configuration.
> 2023-12-20 00:38:46 INFO  MetricsConfig:120 - Loaded properties from hadoop-metrics2.properties
> 2023-12-20 00:38:46 INFO  MetricsSystemImpl:378 - Scheduled Metric snapshot period at 10 second(s).
> 2023-12-20 00:38:46 INFO  MetricsSystemImpl:191 - XceiverClientMetrics metrics system started
> 2023-12-20 00:38:46 INFO  MetricRegistries:64 - Loaded MetricRegistries class org.apache.ratis.metrics.dropwizard3.Dm3MetricRegistriesImpl
> ```

Got your point. I just think in production these logs can be informatic on the server-side. In a happy time, no one cares. But in case of any problem, it's a good assertion, even for a command client as the example above. Transport protocol is an important piece of information when clients talk to OM.

**Comment by adoroszlai** [comment]
> Transport protocol is an important piece of information when clients talk to OM.

OK, log level can be changed in config if needed.

Thanks @duongkame for the patch, @xBis7 for the review.

**Pull request merged**
