### PR TITLE
HDDS-9140. [Recon] Upgrade node, pnpm and package versions to the latest compatible version.

### PR DESCRIPTION
**Pull request by devabhishekpal**
## What changes were proposed in this pull request?

This PR updates the pnpm packages to the latest, compatible version.
It will upgrade the minor versions only, and update the packages so that no base code changes are required.

## What is the link to the Apache JIRA

[HDDS-9140](https://issues.apache.org/jira/browse/HDDS-9140)

## How was this patch tested?

The patch was tested manually.

https://github.com/apache/ozone/assets/43001336/ebb8f47e-1b6d-4498-80b9-7f08fc8744f4

https://github.com/apache/ozone/assets/43001336/5e96f48f-6bd4-4169-9650-b2ea4fdb3ba0

This PR will update the following:
| Package Name | Previous Version | Upgraded To |
|--------------|------------------|-------------|
| @ant-design/icons | ^5.1.4 | ^5.2.5 |
| @babel/core | ^7.0.0 | ^7.22.10 |
| @fontsource/roboto | ^4.5.8 | - |
| @types/classnames | ^2.2.10 | ^2.3.1 |
| @types/jest | 24.0.12 | - |
| @types/node | 11.13.9 | - |
| @types/react | 16.8.15 | - |
| @types/react-dom | 16.8.4 | - |
| @types/react-router-dom | ^4.3.3 | ^4.3.5 |
| ag-charts-community | ^7.3.0 | - |
| ag-charts-react" | ^7.3.0 | - |
| antd | ^3.26.9 | ^3.26.20 |
| axios | ^0.21.4 | ^0.27.2 |
| babel-jest | ^24.9.0 | - |
| babel-plugin-import | ^1.11.0 | ^1.13.8 |
| classnames | ^2.2.6 | ^2.3.2 |
| customize-cra | ^0.2.12 | ^0.2.14 |
| filesize | ^6.1.0 | ^6.4.0 |
| less | ^3.9.0 | ^3.13.1 |
| less-loader | ^5.0.0 | - |
| moment | ^2.24.0 | ^2.29.4 |
| plotly.js | ^1.54.1 | ^1.58.5 |
| pretty-ms | ^5.1.0 | - |
| react | ^16.8.6 | - |
| react-app-rewired | ^2.1.3 | ^2.2.1 |
| react-dom | ^16.8.6 | ^16.14.0 |
| react-plotly.js | ^2.4.0 | ^2.6.0 |
| react-router | ^5.1.2 | ^5.3.4 |
| react-router-dom | ^5.0.0 | 5.3.4 |
| react-scripts | ^3.1.2 | - |
| react-select | ^3.0.3 | ^3.2.0 |
| typescript | 3.4.5 | 3.5.3 |

### CODE REVIEW

**Comment by smitajoshi12** [comment]
@devabhishekpal 

Abishek  Please check UI functionality on different browser as we are upgrading libraries and with cluster data.

**Comment by devabhishekpal** [comment]
Thanks for the suggestion @smitajoshi12 .
Here are the screen captures for the UI with cluster data on Safari and Firefox as well.
Safari:

https://github.com/apache/ozone/assets/43001336/222d6aea-16ee-4b10-9553-36a3a1597bf8

Firefox:

https://github.com/apache/ozone/assets/43001336/5508e19f-6e4a-4bc8-9610-6c8543f4d255

**Review by errose28 — APPROVED** [review]
Thanks for the updates and multi-browser tests @devabhishekpal. LGTM. @smitajoshi12 if this looks good to you as well then we can merge.

**Comment by smitajoshi12** [comment]
It Looks good to me.

**Comment by smengcl** [comment]
Thanks @devabhishekpal for the patch.

@devabhishekpal Pls try to use the PR title as your first commit message next time.

@errose28 Pls watch out for the merged commit message next time.

**Pull request merged**
