### PR TITLE
HDDS-7619. Update SCM term in datanode when command is received

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Update datanode's record of "SCM leader term" as soon as command is added to the queue to help drop obsolete commands sooner.

https://issues.apache.org/jira/browse/HDDS-7619

## How was this patch tested?

Added unit test.

https://github.com/adoroszlai/hadoop-ozone/actions/runs/3677335765

### CODE REVIEW

**Review by siddhantsangwan — APPROVED** [review]
@adoroszlai The changes look good to me!

**Comment by siddhantsangwan** [comment]
Do we have multiple threads adding and getting commands from the command queue? 
Checking the usages of `getNextCommand()`, it seems we only have a single thread getting commands right now:
```
    /**
     * Task that periodically checks if we have any outstanding commands.
     * It is assumed that commands can be processed slowly and in order.
     * This assumption might change in future. Right now due to this assumption
     * we have single command  queue process thread.
     */

```

Even if we have multiple threads, I don't think there are any potential problems related to multithreaded inconsistency in the new code. I'm asking for better understanding.

**Review by sodonnel — APPROVED** [review]
LGTM

**Comment by adoroszlai** [comment]
Thanks @siddhantsangwan, @sodonnel for the review.

**Pull request merged**
