### PR TITLE
HDDS-11472. Avoid recreating external access authorizer on OM state reload

### PR DESCRIPTION
**Pull request by spacemonkd**
## What changes were proposed in this pull request?

HDDS 11472. Return single instance of Access Authorizer for OM

Please describe your PR in detail:
* Currently when we instantiate OM we request an instance of AccessAuthorizer from OzoneAuthorizerFactory
* This may cause previous instances of AccessAuthorizer to not be cleared on subsequent calls.
* As a part of this PR we are checking if an instance of AccessAuthorizer is already present in the Factory and returning that, else we initialize with new value
* This will ensure we do not un-necessarily create new authorizer objects.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-11472

## How was this patch tested?
Patch was tested via Unit tests

### CODE REVIEW

**Review by adoroszlai — CHANGES_REQUESTED** [review]
Thanks @devabhishekpal for working on this.

The proposed solution doesn't seem right:

- OM cannot keep using the old native authorizer as is, because `KeyManager` and `PrefixManager` are re-created.  Using the old instances will lead to cryptic bugs.
- We only need to avoid re-creating non-native authorizer (e.g. Ranger-based one).  I think that's fine because only native authorizer has direct access to OM's internal state.

I think we need to change `OzoneAuthorizerFactory#create` to look up authorizer in a cache here:

https://github.com/apache/ozone/blob/acf3fdc7c2c14a418bd680fd69228ccee91d85cd/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneAuthorizerFactory.java#L83

and only call `newInstance` if no instance is found in the cache.  In that case the instance also needs to be stored in the cache.

**Comment by adoroszlai** [comment]
On second thought, it may be better to handle this in `OzoneManager#instantiateServices` like this:

```java
if (accessAuthorizer == null || accessAuthorizer.isNative()) {
  accessAuthorizer = OzoneAuthorizerFactory.forOM(this);
}
```

**Review by adoroszlai — APPROVED** [review]

**Review by fapifta — CHANGES_REQUESTED** [review]
Hi @devabhishekpal thank you for taking this one on, also thank you @adoroszlai for the initial review.

It seems that the test failures are relevant, as the tests are calling the restart() method of Ozone Manager, while they are changing the configuration related to how the authorizer instances are being created.

The failing test's init starts om with acls disabled, and that leads to create an OzoneAccessAuthorizer instance as the accessAuthorizer during OM start, for this state, the restart does not re-create the accessAuthorizer if acls are enabled in the meantime, so all operations remain allowed.

As from the history I do not see why the restart method was implemented initially, and I am not sure if we need it, so we have a few options:
- revisit the restart method and HDDS-964 which added it, so we will know if we really need it in those tests this way, or we can remove it.
- change OzoneAccessAuthorizer to be a native authorizer, this may have some interesting consequences that I do not see, but in general it seems to be ok
- move the logic back to the factory and correct it based on what we learned from the test runs and discussions.


On a side note, the PR description may also need some review and changes based on the final solution.

**Comment by adoroszlai** [comment]
Thanks @fapifta for catching this.

> * change OzoneAccessAuthorizer to be a native authorizer, this may have some interesting consequences that I do not see, but in general it seems to be ok

I vote for this option.  `OzoneAccessAuthorizer` is just a no-op (allows everything) and is native to Ozone (vs. being external).

> * revisit the restart method

We should do this in a follow-up.  `restart` is only used in tests.  I think such custom logic in tests reduces their ability to catch real bugs, and introduces test-only problems like this.

**Comment by adoroszlai** [comment]
@fapifta can you please take another look?

**Review by fapifta — APPROVED** [review]
+1, thank you for the changes!

**Comment by adoroszlai** [comment]
Thanks @devabhishekpal for the patch, @fapifta for the review.

**Comment by devabhishekpal** [comment]
Thanks @adoroszlai for helping with the changes as well

**Pull request merged**
