### PR TITLE
HDDS-9415. ozone-debug-lease-recovery.robot not part of acceptance tests

### PR DESCRIPTION
**Pull request by LZD-PratyushBhatt**
## What changes were proposed in this pull request?

[HDDS-9255](https://issues.apache.org/jira/browse/HDDS-9255) introduced robot tests for lease Recovery, but the tests were never executed.
Aim is to add these tests in atleast one test suite.

## What is the link to the Apache JIRA
[HDDS-9415](https://issues.apache.org/jira/browse/HDDS-9415)

## How was this patch tested?
CI: 
Working in fork CI : https://github.com/LZD-PratyushBhatt/ozone/actions/runs/6452398832/job/17514936342?pr=7

### CODE REVIEW

**Comment by LZD-PratyushBhatt** [comment]
CI passed. @adoroszlai can you please review this? 
Thanks!

**Review by adoroszlai — COMMENTED** [review]
Thanks @LZD-PratyushBhatt for working on this.

The name `execute_debug_tests` is a bit misleading.  It's a complex test for `ozone debug read-replicas`.  I think the lease recovery test would be more appropriate here:

https://github.com/apache/ozone/blob/00081b04c993850f86d09868673be6f875d48591/hadoop-ozone/dist/src/main/compose/ozone/test.sh#L48-L49

**Review by adoroszlai — APPROVED** [review]
Thanks @LZD-PratyushBhatt for updating the patch.

```
Ozone-Debug-Lease-Recovery :: Test lease recovery of ozone filesystem         
==============================================================================
Test ozone debug recover for o3fs                                     | PASS |
------------------------------------------------------------------------------
Test ozone debug recover for ofs                                      | PASS |
------------------------------------------------------------------------------
Ozone-Debug-Lease-Recovery :: Test lease recovery of ozone filesystem | PASS |
2 tests, 2 passed, 0 failed
```

https://github.com/LZD-PratyushBhatt/ozone/actions/runs/6471625833/job/17571593897#step:5:822

**Comment by LZD-PratyushBhatt** [comment]
Thanks @adoroszlai for the review!

**Pull request merged**
