### PR TITLE
HDDS-9968. Avoid using Files.createTempDirectory in AbstractReconSqlDBTest

### PR DESCRIPTION
**Pull request by devmadhuu**
## What changes were proposed in this pull request?
This PR is raised to incorporate below tasks:

`AbstractReconSqlDBTest uses Files.createTempDirectory. We should replace it with @TempDir. The problem is that AbstractReconSqlDBTest is used in two different ways:`

```
Several tests extend AbstractReconSqlDBTest. JUnit lifecycle method is executed, @TempDir can be used.
ReconTestInjector and TestReconWithDifferentSqlDBs create instance of AbstractReconSqlDBTest explicitly. These should provide temp directory via parameter.
```

## What is the link to the Apache JIRA

Please create an issue in ASF JIRA before opening a pull request, and you need to set the title of the pull
request which starts with the corresponding JIRA issue number. (e.g. HDDS-XXXX. Fix a typo in YYY.)

(Please replace this section with the link to the Apache JIRA)
https://issues.apache.org/jira/browse/HDDS-9968

## How was this patch tested?
This patch is being tested by executing all existing test cases which are extending and using `AbstractReconSqlDBTest` and  ReconTestInjector classes.

### CODE REVIEW

**Comment by devmadhuu** [comment]
@adoroszlai  pls review. Workflow run has passed in CI: https://github.com/devmadhuu/ozone/actions/runs/7583425300

**Comment by adoroszlai** [comment]
@ivandika3 would you like to review?

**Comment by ivandika3** [comment]
Thanks @devmadhuu for the patch. The changes make sense. LGTM +1.

Learnt that if a test is constructing the AbstractReconSqlDBTest directly, the test is responsible to create the schema since it will not trigger BeforeEach create schema hook.

**Review by adoroszlai — APPROVED** [review]

**Comment by adoroszlai** [comment]
Thanks @devmadhuu for the patch, @ivandika3 for the review.

**Pull request merged**
