### PR TITLE
HDDS-9436. Intermittent failure in TestOzoneSnapshotRestore#testUnorderedDeletion

### PR DESCRIPTION
**Pull request by jyotirmoy-gh**
## What changes were proposed in this pull request?

Fix intermittent failure in the test by waiting so that create/delete operations are finished properly before key count is done

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-9436

## How was this patch tested?

Ran test multiple times
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.ozone.om.snapshot.TestOzoneSnapshotRestore
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 62.567 s - in org.apache.hadoop.ozone.om.snapshot.TestOzoneSnapshotRestore
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0
```

### CODE REVIEW

**Comment by jyotirmoy-gh** [comment]
@adoroszlai - Please review

**Comment by adoroszlai** [comment]
Thanks @jyotirmoy-gh for the patch.  Please use [this workflow](https://github.com/jyotirmoy-gh/ozone/actions/workflows/intermittent-test-check.yml) to trigger repeated runs (e.g. 10 splits x 10 iterations).

**Comment by adoroszlai** [comment]
`master` had 8 failures in 300 runs (2.66%): https://github.com/jyotirmoy-gh/ozone/actions/runs/6643542770/job/18052565542#step:3:19

**Comment by jyotirmoy-gh** [comment]
Workflow runs with the code fix - https://github.com/jyotirmoy-gh/ozone/actions/runs/6644693622/job/18056008629

**Review by hemantk-12 — APPROVED** [review]
Thanks for the patch.

Looks good to me.

**Pull request merged**
