### PR TITLE
HDDS-7211. remove dead code from org.apache.hadoop.ozone.omKeyManagerImpl

### PR DESCRIPTION
**Pull request by myskov**
## What changes were proposed in this pull request?

This PR removes dead code from omKeyManagerImpl class. The most significant part of the removed code is helper methods of listStatusFSO(), which is unreachable and has been removed.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7211

## How was this patch tested?

Existing unit and integration tests

### CODE REVIEW

**Review by kerneltime — APPROVED** [review]

**Comment by kerneltime** [comment]
I think there needs to be a couple of more reviewers to approve this PR, there is a lot of code that is being deleted (which is good) but we need to be sure that it won't be missed.

**Comment by aswinshakil** [comment]
Thank you for working on this @myskov. I remember there was a plan to do a [cleanup](https://github.com/apache/ozone/pull/3444#discussion_r881710613) patch of `listStatusFSO()` after this [patch](https://github.com/apache/ozone/pull/3444) but wasn't done. I can approve it once the merge conflicts are resolved.

**Review by aswinshakil — COMMENTED** [review]
Thank you for working on this @myskov. I remember there was a plan to do a [cleanup](https://github.com/apache/ozone/pull/3444#discussion_r881710613) patch of `listStatusFSO()` after this [patch](https://github.com/apache/ozone/pull/3444) but wasn't done. I can approve it once the merge conflicts are resolved.

**Comment by myskov** [comment]
@aswinshakil I resolved all conflicts.

**Review by adoroszlai — APPROVED** [review]
Thanks @myskov for the cleanup, LGTM.  We can wait for @aswinshakil to take another look before merging this.

**Comment by adoroszlai** [comment]
Thanks @myskov for the patch, @aswinshakil, @kerneltime for the review.

**Pull request merged**
