### PR TITLE
HDDS-4912. Support inline upgrade from containerId, delTxnId, localId to SequenceIdGenerator.

### PR DESCRIPTION
**Pull request by GlenGeng**
## What changes were proposed in this pull request?

Support inline upgrade from containerId, delTxnId, localId to SequenceIdGenerator.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4912

## How was this patch tested?

CI

### CODE REVIEW

**Comment by GlenGeng** [comment]
@bshashikant @mukul1987 The upgrade PR for sequenceIdGen

**Review by bshashikant — COMMENTED** [review]
@GlenGeng , the change looks good. However, it would make sense to write a upgrade test(acceptance test) and have some verification. What do you think?

**Comment by bshashikant** [comment]
@GlenGeng , can u rename /Users/sbanerjee/github/hadoop-ozone/hadoop-ozone/dist/src/main/compose/upgrade/todo-test.sh to test.sh and see after enabling the upgrade tests, if all work fine.

cc @mukul1987 .

**Comment by GlenGeng** [comment]
@bshashikant @mukul1987 I've manually do a upgrade test from latest master to last commit of this PR, the upgrade logic for delTrxId, containerId and localId works as expected.

**Comment by bshashikant** [comment]
Thanks @GlenGeng for the contribution.

**Pull request merged**
