### PR TITLE
HDDS-9937. Move add response in doubleBuffer from validateAndUpdateCache to handleWriteRequest

### PR DESCRIPTION
**Pull request by ChenSammi**
## What changes were proposed in this pull request?
Move add response in doubleBuffer from validateAndUpdateCache to handleWriteRequest,
to make sure every response returned from validateAndUpdateCache is added to doubleBuffer.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-9937

## How was this patch tested?
covered by existing test cases

### CODE REVIEW

**Comment by whbing** [comment]
Looks good to me ! +1

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by szetszwo** [comment]
@whbing , thanks for the idea given in https://github.com/apache/ozone/pull/5749#issuecomment-1857438554 and reviewing this!

**Comment by ChenSammi** [comment]
@whbing @szetszwo,  thanks for the review.

**Pull request merged**
