### PR TITLE
HDDS-8393. [Recon] Include Roboto font using fontsource instead

### PR DESCRIPTION
**Pull request by ivanzlenko**
## What changes were proposed in this pull request?

The direct link for the Google Roboto font has been replaced with the use of the Fontsource module. 

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8393

Please replace this section with the link to the Apache JIRA)

## How was this patch tested?

Manual testing

### CODE REVIEW

**Comment by kerneltime** [comment]
cc @devmadhuu can you please review as well?

**Review by dombizita — CHANGES_REQUESTED** [review]
hi @ivanzlenko, thanks for taking this up. I checked out your PR and created a docker cluster locally and the Recon UI changed for me, I'm not sure what caused it. could you look into it? do you experience the same? I attach screenshots from the overview and the pipelines page, before and after your patch.


old-overview
old-pipelines
new-overview
new-pipelines

cc @smitajoshi12, maybe you can help with this

**Comment by ivanzlenko** [comment]
Hi @dombizita, yeah, I can reproduce it using docker container. Not faced ths earlier because I've tested it using pnpm dev server.

**Comment by ivanzlenko** [comment]
@dombizita I've fixed this issue.

**Comment by smitajoshi12** [comment]
I will check with docker and pnpm dev server.

**Comment by smitajoshi12** [comment]
Checked font of Recon UI looks good.

image

**Comment by ivanzlenko** [comment]
@dombizita @smengcl can you check this review please?

**Review by smengcl — APPROVED** [review]
Thanks @ivanzlenko for the patch.

One question for @adoroszlai , now that we bundle Roboto font when building Ozone, do we need to add a LICENSE notice somewhere for it? Not sure if this applies to non-jar / non-binary .

fyi the font is also licensed under Apache 2.0: https://fonts.google.com/specimen/Roboto/about

**Comment by ivanzlenko** [comment]
@adoroszlai @smengcl I've added License file

**Review by dombizita — APPROVED** [review]
thanks for working on this @ivanzlenko, it looks good to me!

**Comment by dombizita** [comment]
thanks @ivanzlenko for the patch! thanks @devmadhuu, @smitajoshi12, @adoroszlai and @smengcl for reviewing it!

**Comment by ivanzlenko** [comment]
Thanks for review!

**Pull request merged**
