### PR TITLE
HDDS-10924. TestSCMHAManagerImpl#testAddSCM fails on ratis master

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Tweak `TestSCMHAManagerImpl` to let it pass with Ratis 3.1.0.

https://issues.apache.org/jira/browse/HDDS-10924

## How was this patch tested?

Ozone CI with Ratis 3.1.0 RC0:
https://github.com/adoroszlai/ozone/actions/runs/9306740993

Regular CI:
https://github.com/adoroszlai/ozone/actions/runs/9306735813

### CODE REVIEW

**Comment by duongkame** [comment]
Should we just mock to provide a null checkpoint, like [this](https://github.com/duongkame/ozone/commit/fabe6bdd37c29c103ff342ed2d3f3bc8af9cada4)

**Comment by adoroszlai** [comment]
> Should we just mock to provide a null checkpoint, like [this](https://github.com/duongkame/ozone/commit/fabe6bdd37c29c103ff342ed2d3f3bc8af9cada4)

Since this is a unit test for `SCMHAManagerImpl`, I don't think we should mock/override its methods, rather some of its collaborators.

**Review by nandakumar131 — APPROVED** [review]

**Comment by nandakumar131** [comment]
Thanks @adoroszlai for the quick fix and thanks @duongkame for taking a look at the fix.

**Comment by adoroszlai** [comment]
Thanks @nandakumar131 for the review.

**Pull request merged**
