### PR TITLE
HDDS-4936. Change ozone groupId from org.apache.hadoop to org.apache.ozone

### PR DESCRIPTION
**Pull request by ChenSammi**
https://issues.apache.org/jira/browse/HDDS-4936

(this pr continues the work / discussion started in #2018)

### CODE REVIEW

**Comment by ChenSammi** [comment]
@adoroszlai , Could you check if your patches are all included in this new MR

**Review by elek — APPROVED** [review]
+1, thanks the update @ChenSammi 

I tried to merge the same master to the last commit from #2018 (which includes the commits from @adoroszlai) and the difference were very small:

```
diff --git hadoop-hdds/common/pom.xml hadoop-hdds/common/pom.xml
index 6da1ff570..bc6dde7ca 100644
--- hadoop-hdds/common/pom.xml
+++ hadoop-hdds/common/pom.xml
@@ -193,8 +193,8 @@ https://maven.apache.org/xsd/maven-4.0.0.xsd">
       <artifactId>hdds-interface-client</artifactId>
     </dependency>
     <dependency>
-      <groupId>org.apache.hadoop</groupId>
-      <artifactId>hadoop-hdds-interface-admin</artifactId>
+      <groupId>org.apache.ozone</groupId>
+      <artifactId>hdds-interface-admin</artifactId>
     </dependency>
     <dependency>
       <groupId>org.hamcrest</groupId>
diff --git pom.xml pom.xml
index 40bdaaf82..664172922 100644
--- pom.xml
+++ pom.xml
@@ -2002,7 +2002,7 @@ xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xs
           </dependencies>
           <configuration>
             <configLocation>hadoop-hdds/dev-support/checkstyle/checkstyle.xml</configLocation>
-            <suppressionsLocation>hdds/dev-support/checkstyle/suppressions.xml</suppressionsLocation>
+            <suppressionsLocation>hadoop-hdds/dev-support/checkstyle/suppressions.xml</suppressionsLocation>
             <includeTestSourceDirectory>true</includeTestSourceDirectory>
             <failOnViolation>false</failOnViolation>
             <format>xml</format>
```

In Both cases this PR is the good one.

It also confirms that all the commits from @adoroszlai  are included here.

**Comment by ChenSammi** [comment]
Thanks @elek . I will hold on the commit until Mukul finishes Cloudera internal release.

**Comment by adoroszlai** [comment]
@ChenSammi Since now we have conflicts on both PRs, I have merged `master` into your original branch and resolved conflicts.  Closing this duplicate in favor of the original PR.

**Pull request closed without merging**
