### PR TITLE
HDDS-8766. Use empty BufferPool for EC reconstruction

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Avoid unnecessary `BufferPool` creation for EC reconstruction flow:

```
// TODO: Let's avoid unnecessary bufferPool creation. This pool actually
//  not used in EC flows, but there are some dependencies on buffer pool.
```

Use an empty singleton `BufferPool` for that.

Also, convert some validation checks to real preconditions in `BufferPool` (i.e. perform the check before changing state, not afterwards).

https://issues.apache.org/jira/browse/HDDS-8766

## How was this patch tested?

Existing tests:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5186666728

### CODE REVIEW

**Review by sodonnel — APPROVED** [review]
LGTM

**Comment by adoroszlai** [comment]
@sodonnel thanks for the review.  I've expanded the unit test and made some small tweaks in `BufferPool` and `ChunkBufferImplWithByteBuffer`: be702db38cbc99f1e6f7139b57132aa14ccfc007  Would you like to take another look?

**Comment by sodonnel** [comment]
Checked the latest commit - LGTM.

**Comment by adoroszlai** [comment]
Thanks @sodonnel for taking another look.

**Pull request merged**
