### PR TITLE
HDDS-11578. Rename snapshot dir constant in OzoneConsts

### PR DESCRIPTION
**Pull request by weimingdiit**
## What changes were proposed in this pull request?
Rename snapshot dir constant in OzoneConsts

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-11578

## How was this patch tested?
 unit tests

### CODE REVIEW

**Review by sarvekshayr — APPROVED** [review]
Thank you @weimingdiit for the patch. The changes look good to me.

**Review by Tejaskriya — APPROVED** [review]
LGTM

**Comment by weimingdiit** [comment]
@sarvekshayr @Tejaskriya  Thanks for your review !

**Review by adoroszlai — APPROVED** [review]

**Comment by slfan1989** [comment]
+1.

**Review by slfan1989 — APPROVED** [review]

**Comment by adoroszlai** [comment]
Thanks @weimingdiit for the patch, @sarvekshayr, @slfan1989, @Tejaskriya for the review.

**Pull request merged**
