### PR TITLE
[HDDS-5452] Add link method to ContainerStateMachine for Ratis streaming

### PR DESCRIPTION
**Pull request by ckj996**
## What changes were proposed in this pull request?

Add link method to ContainerStateMachine for Ratis streaming.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5452

## How was this patch tested?

CI test will be added after the client is ready.

### CODE REVIEW

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

Ozone datanode may store the log index somewhere using the link(..) method.  This can be done later if there is a need.

**Comment by szetszwo** [comment]
@ckj996 , there is a windbags warning.  Please take a look.  Thanks.

**Comment by ckj996** [comment]
@szetszwo Hi, I have fixed it. Can you please approve the workflow? Thanks.

**Comment by szetszwo** [comment]
Re-commit this for fixing the commit message format.
```
commit 97cb05c2eafc4a33001e739737a2064dd623f6a9 (HEAD -> HDDS-4454, origin/HDDS-4454)
Author: Kaijie Chen <chen@kaijie.org>
Date:   Sun Jul 18 12:18:10 2021 +0800

    HDDS-5452. Add link method to ContainerStateMachine for Ratis streaming (#2422)
```
@ckj996 , please use the standard commit message next time.  Thanks.

**Comment by ckj996** [comment]
> @ckj996 , please use the standard commit message next time. Thanks.

Sure.

Btw, I forgot to add the `@Override` annotation, shall we fix that?

**Comment by szetszwo** [comment]
> Btw, I forgot to add the `@Override` annotation, shall we fix that?

Sure, let's add the @Override annotation when we change the file next time.

**Comment by ckj996** [comment]
> > Btw, I forgot to add the `@Override` annotation, shall we fix that?
> 
> Sure, let's add the @Override annotation when we change the file next time.
> 

I've fixed it in HDDS-5481(#2451).

**Pull request merged**
