### PR TITLE
HDDS-7086. DataNode UI to show failed volumes too

### PR DESCRIPTION
**Pull request by dombizita**
## What changes were proposed in this pull request?

In this change I added the volume state to the VolumeInfoMetrics so it will be exposed to the JMX of the datanodes and added a volume state column to the Volume Information's table on the Datanode WebUI. I modified that if a volume fail it will still have a VolumeInfoMetrics with the information added that it is failed.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7086

## How was this patch tested?

Tested locally on a cluster that the volume state have been exposed to the datanode's JMX (`jmx?qry=Hadoop:service=HddsDatanode,name=VolumeInfoMetrics*`) and I can also see it on the WebUI.
```
{
  "beans" : [ {
    "name" : "Hadoop:service=HddsDatanode,name=VolumeInfoMetrics-/data/hdds",
    "modelerType" : "VolumeInfoMetrics-/data/hdds",
    "tag.Context" : "ozone",
    "tag.VolumeState" : "NORMAL",
    "tag.VolumeType" : "DATA_VOLUME",
    "tag.StorageDirectory" : "/data/hdds/hdds",
    "tag.StorageType" : "DISK",
    "tag.DatanodeUuid" : "70b1bce3-779b-4733-bf2d-fc27cafcb3f1",
    "tag.Hostname" : "6971e80c0c05",
    "TotalCapacity" : 47549485056,
    "Capacity" : 47549485056,
    "Available" : 47549263872,
    "LayoutVersion" : 1,
    "Reserved" : 0,
    "Used" : 221184
  }, {
    "name" : "Hadoop:service=HddsDatanode,name=VolumeInfoMetrics-/data/secondary_volume",
    "modelerType" : "VolumeInfoMetrics-/data/secondary_volume",
    "tag.Context" : "ozone",
    "tag.VolumeState" : "FAILED",
    "tag.VolumeType" : "DATA_VOLUME",
    "tag.StorageDirectory" : "/data/secondary_volume/hdds",
    "tag.StorageType" : "DISK",
    "tag.DatanodeUuid" : "70b1bce3-779b-4733-bf2d-fc27cafcb3f1",
    "tag.Hostname" : "6971e80c0c05",
    "TotalCapacity" : 47549272064,
    "Capacity" : 47549272064,
    "Available" : 47549263872,
    "LayoutVersion" : 1,
    "Reserved" : 0,
    "Used" : 8192
  } ]
}
```
Screenshot 2022-09-07 at 15 26 30

### CODE REVIEW

**Comment by dombizita** [comment]
@ArafatKhan2198 could you please take a look at my patch?

**Review by jojochuang — APPROVED** [review]
Looks great. Thanks!

**Comment by ArafatKhan2198** [comment]
+1 LGTM

**Comment by jojochuang** [comment]
Merged. Thanks @dombizita for the PR and @ArafatKhan2198 for the review!

**Pull request merged**
