### PR TITLE
HDDS-9831. Fix NPE and remove unnecessary logic in HddsConfServlet

### PR DESCRIPTION
**Pull request by wzhallright**
## What changes were proposed in this pull request?
Remove unnecessary logic in HddsConfServlet.java.   
`response.setContentType()` already defined in doGet()

Please describe your PR in detail:

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-9831

### CODE REVIEW

**Comment by adoroszlai** [comment]
Thanks @wzhallright for the patch.  Have you had a chance to test it, too?

**Comment by wzhallright** [comment]
Thanks for review! @adoroszlai . Unit tests have been added, please take a look if you have time.   
And fixed another hidden bug, if cmd is `getPropertyByTag` but not tags parameter in request, then throw NPE.

**Review by adoroszlai — COMMENTED** [review]
Thank you very much @wzhallright for adding the unit test.

We're in the process of moving to JUnit5 (HDDS-6729).  Since it is a big project, affecting hundreds of test classes, we're making it gradually.  Thus, we cannot remove dependency on JUnit4 yet.  However, `hadoop-hdds/framework` is already migrated.  For such modules usage of JUnit4 is prevented by using `maven-enforcer-plugin`, that's why the [build is failing](https://github.com/wzhallright/ozone/actions/runs/7111160391/job/19358772657#step:6:1434) with the new patch.

Can you please change the new test to use JUnit5?

https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4

**Comment by wzhallright** [comment]
@adoroszlai Oh, that's a great project. change junit to junit5. Thanks for review.

**Comment by adoroszlai** [comment]
Thanks @wzhallright for updating the patch.  Please take a look at checkstyle and findbugs failures:

https://github.com/wzhallright/ozone/actions/runs/7112684316/job/19363113952#step:7:11

https://github.com/wzhallright/ozone/actions/runs/7112684316/job/19363114525#step:7:11

**Comment by wzhallright** [comment]
Usually I use Google Checkstyle to format the code locally, which leads to format confusion between different projects. I fixed checkstyle&findbugs. Please take a look again. Thanks! @adoroszlai

**Review by adoroszlai — APPROVED** [review]

**Comment by adoroszlai** [comment]
Thanks @wzhallright for the fix and adding test coverage for this class.

**Pull request merged**
