### PR TITLE
HDDS-7976. FsShell creates unrelated trace spans

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Currently `OzoneFsShell` creates unrelated spans, e.g. `ozone fs -mkdir ofs://om/vol1` results in 3 separate spans:

before

This PR adds a main span in `OzoneFsShell` to encompass spans created by inner method calls, similar to how `OzoneShell`, `OzoneAdmin` etc. do it.

https://issues.apache.org/jira/browse/HDDS-7976

## How was this patch tested?

```
cd hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/ozone
export COMPOSE_FILE=docker-compose.yaml:monitoring.yaml
./run.sh -d
sleep 60
docker-compose exec scm ozone fs -mkdir ofs://om/vol1
open http://localhost:16686
```

after

Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4186458710

### CODE REVIEW

**Review by jojochuang — COMMENTED** [review]
Looks good. Is it possible to log arguments (argv) of the shell in the span?

**Comment by adoroszlai** [comment]
> Is it possible to log arguments (argv) of the shell in the span?

I hope so.  I have filed a follow-up task for that (HDDS-7978) because it affects other CLI commands, not only `ozone fs`.

**Review by jojochuang — APPROVED** [review]
Ah. Ok. Glad it's being taken care of. Thanks for the PR @adoroszlai

**Comment by adoroszlai** [comment]
Thanks @jojochuang for the review.

**Pull request merged**
