### PR TITLE
HDDS-5696. Close grpcReplicationClient on exception.

### PR DESCRIPTION
**Pull request by ChenSammi**
https://issues.apache.org/jira/browse/HDDS-5696

### CODE REVIEW

**Comment by ChenSammi** [comment]
thenApply will not be executed if the grpcReplicationClient.download throws exception.

**Comment by ChenSammi** [comment]
Hey @sodonnel, would you help me to review this patch?

**Review by bshashikant — APPROVED** [review]

**Comment by bshashikant** [comment]
Thanks @ChenSammi for the contribution.

**Comment by ChenSammi** [comment]
Thank @bshashikant for the code review.

**Pull request merged**
