### PR TITLE
HDDS-9443. Skip unhealthy tests in repeated runs workflow

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

The new `flaky-test-check` workflow should skip `@Unhealthy` tests (these were `@Ignore` or `@Disabled` previously).

Also, convert a few leftover `@Disabled` instances to `@Unhealthy`.

https://issues.apache.org/jira/browse/HDDS-9443

## How was this patch tested?

Triggered run for `TestSecureOzoneCluster`, confirmed 2 unhealthy tests (of 16 total) were [excluded](https://github.com/adoroszlai/hadoop-ozone/actions/runs/6498802347):

```
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 139.993 s - in org.apache.hadoop.ozone.TestSecureOzoneCluster
```

Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6498802347

### CODE REVIEW

**Comment by adoroszlai** [comment]
@ArafatKhan2198 @devmadhuu please review

**Review by devmadhuu — COMMENTED** [review]
@adoroszlai  thanks for taking care this. LGTM +1. However is it possible to fail checkstyle if someone adds a "@disabled" annotation in any new test case and enforce "@unhealthy".

**Comment by adoroszlai** [comment]
Thanks @devmadhuu for the review.

> However is it possible to fail checkstyle if someone adds a `@Disabled` annotation

Good point, added enforcer rule to fail the build in that case.

(Please use `` to quote annotations to avoid mentioning innocent Github users.)

**Comment by ArafatKhan2198** [comment]
Hi @adoroszlai  thanks for working on this!
I executed the TestSecureOzoneCluster on my local fork's CI 100 times, specifically for the changes in this PR.

Although the `testCertificateRotationUnRecoverableFailure` is marked with **`@Unhealthy`**, the test still runs and fails. You can see the failure here: [link](https://github.com/ArafatKhan2198/ozone/actions/runs/6528972365/job/17725951880#step:5:3814).

Have I overlooked something?

**Comment by adoroszlai** [comment]
> Have I overlooked something?

This PR is changing the `flaky-test-check` workflow.  You ran your test by editing the regular CI workflow, which is not affected by this change.  You need to add `-DexcludedGroups="unhealthy,org.apache.ozone.test.UnhealthyTest"` to skip unhealthy tests here:

https://github.com/ArafatKhan2198/ozone/blob/38ed1f6a0f4b11cfd67f5dad48be8e8e5921d772/.github/workflows/ci.yml#L347

**Comment by adoroszlai** [comment]
@sadanand48 please review

**Review by sadanand48 — APPROVED** [review]
Thanks @adoroszlai , LGTM.

**Review by ArafatKhan2198 — APPROVED** [review]
Thanks @adoroszlai LGTM

**Comment by adoroszlai** [comment]
Thanks @ArafatKhan2198, @devmadhuu, @sadanand48 for the review.

**Pull request merged**
