### PR TITLE
HDDS-10241. Improve the response for the Deleted Directories Insight Endpoint.

### PR DESCRIPTION
**Pull request by ArafatKhan2198**
## What changes were proposed in this pull request?
The current response of Deleted-Directories Insights has the following parameters :- 

```
"key":"/-9223372036854775552/-9223372036854775040/-9223372036854775040/dir1/-9223372036854774527",
"path": "dir1",
```
As we can see its confusing and not very intuitive for the user. 

We want the final response parameters to be like this :- 
```
"key": "dir1", 
"path": "volume/bucket1/dir1/dir2/dir3",
```
Here we will have to construct the path of the directory with their actual names rather than printing out the object ID's.
And we will also have to make a few changes to the frontend to accommodate this new info accordingly.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-10241

## How was this patch tested?

Manual Testing & Unit Testing

### CODE REVIEW

**Review by dombizita — CHANGES_REQUESTED** [review]
Thanks for this change @ArafatKhan2198, it's much more intuitive this way. I think we will need to adjust these tests (where we are asserting the key names) to your changes: https://github.com/apache/ozone/blob/95d9222fcb0f8895e4c8d2f97bcba6586cb99ef0/hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOmDBInsightEndPoint.java#L640-L736

**Comment by dombizita** [comment]
@ArafatKhan2198 please check the failures [here](https://github.com/ArafatKhan2198/ozone/actions/runs/7708494045/job/21008038727) and adjust the tests, thanks! 
```
Error:  Failures: 
Error:    TestOmDBInsightEndPoint.testGetDeletedDirInfo:732 expected: </sampleVol/bucketOne/dir_one> but was: <dir_one>
Error:    TestOmDBInsightEndPoint.testGetDeletedDirInfoLimitParam:667 expected: </sampleVol/bucketOne/dir_one> but was: <dir_one>
Error:    TestOmDBInsightEndPoint.testGetDeletedDirInfoPrevKeyParam:699 expected: </sampleVol/bucketOne/dir_three> but was: <dir_three>
```

**Comment by ArafatKhan2198** [comment]
Thanks for the find @dombizita please check now.

**Review by dombizita — APPROVED** [review]
Thanks for working on this @ArafatKhan2198, looks good to me!

**Comment by dombizita** [comment]
Can you take a look at this @devmadhuu?

**Review by devmadhuu — APPROVED** [review]
Thanks @ArafatKhan2198 for working on this patch. LGTM +1

**Comment by dombizita** [comment]
Thanks for the patch @ArafatKhan2198! Thanks for the review @devmadhuu!

**Pull request merged**
