### PR TITLE
HDDS-10330. Rename additional Ozone/HDDS config keys prefixed with 'dfs'

### PR DESCRIPTION
**Pull request by sarvekshayr**
## What changes were proposed in this pull request?
Renaming additional config keys prefixed with 'dfs' to 'ozone'.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-10330

## How was this patch tested?
Successfully passed all the CI jobs

### CODE REVIEW

**Comment by sarvekshayr** [comment]
> Although overall the change is good, we should think about backward compatibility. This will affect existing installations (after upgrade). We should track such changes to include in release notes.

Yes, I'm aware about backward compatibility. It will be addressed in the following patch https://issues.apache.org/jira/browse/HDDS-10331 where Java constants will be renamed and the deprecating keys will be added in the OzoneConfiguration.java .

**Review by adoroszlai — CHANGES_REQUESTED** [review]
> Yes, I'm aware about backward compatibility. It will be addressed in the following patch https://issues.apache.org/jira/browse/HDDS-10331 where Java constants will be renamed and the deprecating keys will be added in the OzoneConfiguration.java .

Deprecation should be included in the PR changing the config keys, not the one changing constant names.

These patches should not be split based on two sets of config keys.

Please make these additional config key changes and deprecation in #6187.  Move out renaming of constants from that PR.

**Comment by sarvekshayr** [comment]
Okay, I'll make the changes as indicated.

**Comment by adoroszlai** [comment]
Thanks a lot @sarvekshayr for your understanding.  I have updated the set of tasks to reflect this separation.

Issues outstanding for a long time tend to get outdated.  When working on such old issues, I suggest:
- checking if the problem / task is still applicable, or was resolved by another change since then
- ensuring it's up-to-date and complete

Please feel free to ask for clarification or updates before starting.  We tend to file issues and then forget to update them, sorry about that.

**Comment by adoroszlai** [comment]
Thanks @sarvekshayr for the patch, @myskov for the review.

Closing this one.  Let's continue in HDDS-815 and HDDS-10331.

**Pull request closed without merging**
