### PR TITLE
HDDS-5382. Increase default container report interval to 60 mins

### PR DESCRIPTION
**Pull request by sadanand48**
## What changes were proposed in this pull request?
During scale testing of ozone with 350k+ containers and nearly 1 million replica reports it was observed that, there is a sudden burst in SCM heap usage . In HDFS, the full block report interval is 6 hours by default and in between, there are incremental block reports. Similarly, there are incremental reports in SCM . Setting the full container report interval to 1 hour make things quite stable as determined from tests and 60s for full report seems very aggressive.

Increase default container report interval to 60 mins .

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-5382

## How was this patch tested?
only a config change

### CODE REVIEW

**Comment by guihecheng** [comment]
Hi @sadanand48 , sorry to disturb, but I happen to see this and can't help wonder why the default report intervals are changed? I can't find any descriptions in the related jira either, could you please explain a bit? thanks~

**Comment by bshashikant** [comment]
@guihecheng , during scale testing if ozone with 350k+ containers and nearly 1 million replica reports it was observed that, there is a sudden burst in scm heap usage . In hdfs, the fill block report interval is 6 hours by default and in between, there are incremental bock reports. Similarly, there are incremental reports in SCM . Setting the full container report interval to 1 hour make things quite stable as determined from tests and 60s for full report seems very aggressive.

**Comment by bshashikant** [comment]
@sadanand48 , please change the default container and pipeline report interval to 60s in acceotance tests and in MiniOzoneCluster so that there are no random/intermittent failures bcoz of this.

**Comment by guihecheng** [comment]
Thanks @bshashikant for the explanation, this is very useful pr for a production deployment.

**Comment by ChenSammi** [comment]
@sadanand48 ,  can you elaborate a bit why pipeline report interval is changed to 60m?  If I remember correctly, today, Pipeline Manager will use this pipeline report interval as the timeout to wait for a pipeline be ready for serve wright.

**Comment by JacksonYao287** [comment]
maybe for now , we could just only change container full report interval , which is a heavy burden of scm.

**Comment by bshashikant** [comment]
> @sadanand48 , can you elaborate a bit why pipeline report interval is changed to 60m? If I remember correctly, today, Pipeline Manager will use this pipeline report interval as the timeout to wait for a pipeline be ready for serve wright.

I think, the pipeline report is sent on heartbeat as soon as a pipeline is created or pipeline is closed and destroyed. There is no  dependency on the pipeline report interval as such for opening up the pipeline for write. Full report intervals can be sent a higher interval.
 cc ~ @nandakumar131

**Comment by bshashikant** [comment]
@nandakumar131 , can you also have a look?

**Review by bshashikant — APPROVED** [review]

**Comment by jojochuang** [comment]
I support increasing the default interval. @ChenSammi feel free to let us know if something is still holding back.

**Review by mukul1987 — APPROVED** [review]
+1, LGTM

**Review by mukul1987 — APPROVED** [review]
Thanks for changing this to only the container report interval.

**Comment by ChenSammi** [comment]
The last patch LGTM, +1.

**Pull request merged**
