### PR TITLE
HDDS-9249. Intermittent failure in TestRootCARotationManager#testProcessingCheck

### PR DESCRIPTION
**Pull request by ChenSammi**
https://issues.apache.org/jira/browse/HDDS-9249

Test the TestRootCARotationManager in personal repo with 10 * 10 iteration. 

https://github.com/ChenSammi/ozone/actions/runs/6147386344/job/16678776945

### CODE REVIEW

**Comment by ChenSammi** [comment]
@adoroszlai , could you help to review this patch? I run it locally, the total execution of testProcessingCheck remains all most the same.

**Comment by adoroszlai** [comment]
Thanks @ChenSammi for working on this.

> Test the TestRootCARotationManager in personal repo with 10 * 10 iteration.
> 
> https://github.com/ChenSammi/ozone/actions/runs/6147386344/job/16678776945

`TestRootCARotationManager` is a unit test, `integration.sh` does not run it.  Thus 10x10 iterations executed 0 tests in this case.

Try replacing it with `unit.sh` (also need to replace job name `integration` with `unit`).

**Comment by ChenSammi** [comment]
image

Tested it locally. 

@adoroszlai , could you help take another look?

**Review by adoroszlai — APPROVED** [review]
Thanks @ChenSammi for the fix.  Passed in 1000/1000 [runs](https://github.com/adoroszlai/hadoop-ozone/actions/runs/6233237084) in CI.

**Comment by ChenSammi** [comment]
@adoroszlai , thanks.

**Pull request merged**
