### PR TITLE
HDDS-7875. Intermittent failure in TestBlockOutputStream(FlushDelay).

### PR DESCRIPTION
**Pull request by devmadhuu**
## What changes were proposed in this pull request?

This PR fixes the inconsistent and unstable assertion being done which is related to count of pending container operation count metrics for `WriteChunk` and `PutBlock` operations. Pending container operation count metrics for each operation is stored in `pendingOpsArray` array and metric count of each operation gets incremented and decremented  based on operation start and completion and since the operation is Async operation , this metric can be very inconsistent to be predicted correctly and assert in test, so we should assert total operation count metric which this PR is taking care in all related test cases.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7875

## How was this patch tested?

This patch is tested with multiple iterations of running each test case and removed flaky annotation. Here is the [green CI link](https://github.com/devmadhuu/ozone/actions/runs/6433750887) over forked branch with 2 attempts of same multiple iterations.

### CODE REVIEW

**Review by adoroszlai — COMMENTED** [review]
Thanks @devmadhuu for the patch, LGTM.

**Comment by adoroszlai** [comment]
@devmadhuu `TestOMRatisSnapshots` fork timeout is fixed since then, please merge `master` into your branch to get a new CI run

**Review by kerneltime — APPROVED** [review]

**Comment by adoroszlai** [comment]
On second look: the issue also covers `TestBlockOutputStream`, can you please also test that one?

**Comment by devmadhuu** [comment]
> On second look: the issue also covers `TestBlockOutputStream`, can you please also test that one?

Thanks @adoroszlai for pointing out, I fixed the timeout issue in TestBlockOutputStream. Here is [green CI link](https://github.com/devmadhuu/ozone/actions/runs/6569895068) after the fix.

**Comment by adoroszlai** [comment]
Thanks @devmadhuu for the patch, @kerneltime for the review.

**Pull request merged**
