### PR TITLE
HDDS-7600. [Snapshot] Mark all new proto message fields as optional

### PR DESCRIPTION
**Pull request by smengcl**
## What changes were proposed in this pull request?

Mark all new proto message fields as optional before snapshot feature branch is merged to master branch.

Context: https://github.com/apache/ozone/pull/3985/files#r1041505724

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7600

## How was this patch tested?

- Existing tests should pass.

### CODE REVIEW

**Comment by nandakumar131** [comment]
@smengcl, why do we need to mark the field as optional? If the message itself is optional, then the fields are never used.
If someone wants to use that message, we should have the mandatory fields as required.

**Comment by smengcl** [comment]
> @smengcl, why do we need to mark the field as optional? If the message itself is optional, then the fields are never used. If someone wants to use that message, we should have the mandatory fields as required.

Hi Nanda, as I mentioned previously in this PR comment:

https://github.com/apache/ozone/pull/3824#discussion_r1011376445

`required` field is an outdated concept in proto2, where protobuf 3 has completely ditched this concept, so every single field in proto3 is implicitly `optional`, reason being that user can always check the whether the field is set with `hasABCField()`.

A significant drawback of `required` is that it makes it significantly harder to deprecate and remove a field in the future, which IIRC was also blocking Hadoop from moving to pure proto3. Although we are still using proto2 syntax, I would suggest strongly moving away from `required` and embrace `optional`.

**Review by prashantpogde — APPROVED** [review]
LGTM

**Comment by smengcl** [comment]
Thanks @nandakumar131 and @prashantpogde for the reviews.

**Pull request merged**
