### PR TITLE
HDDS-5947. Remove unused mina-core and sshd-core dependencies

### PR DESCRIPTION
**Pull request by elek**
JIRA: https://issues.apache.org/jira/browse/HDDS-5947

## What changes were proposed in this pull request?

Bump the version of Mina dependency to avoid https://github.com/advisories/GHSA-6mcm-j9cj-3vc3

## How was this patch tested?

Full CI

### CODE REVIEW

**Review by adoroszlai — COMMENTED** [review]
Thanks @elek for the patch.  Maybe I'm missing something, but I haven't found `mina-core` being used by any Ozone modules.  It only appears in the `dependencyManagement`, but in actual dependencies.

**Review by ayushtkn — APPROVED** [review]
Makes sense to remove, 
PR title would need to be changed before committing.

**Review by adoroszlai — APPROVED** [review]
Thanks @elek for updating the patch.

**Comment by adoroszlai** [comment]
Thanks @elek for the patch, @ayushtkn for the review.

**Pull request merged**
