### PR TITLE
HDDS-7426. (superseded)

### PR DESCRIPTION
**Pull request by szetszwo**
## What changes were proposed in this pull request?

Add a new acceptance test for Streaming Pipeline.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7426

## How was this patch tested?

NA

### CODE REVIEW

**Comment by kerneltime** [comment]
@duongkame

**Comment by kerneltime** [comment]
cc @swamirishi

**Comment by szetszwo** [comment]
The test for secure ozone clusters currently is failing.  It needs https://github.com/apache/ratis/pull/791 .

**Review by duongkame — APPROVED** [review]
+1, LGTM.

**Comment by szetszwo** [comment]
Sorry that I have accidentally used apache/ozone git repo instead of my fork.  Submitted #4019 to supersedes this.

**Comment by szetszwo** [comment]
> The test looks good, yet, it's failing `Test timeout 5 minutes exceeded.`. Can you look into it?

@duongkame , thank for reviewing this.  The secure fs test needs https://github.com/apache/ratis/pull/791 .

**Pull request closed without merging**
