### PR TITLE
HDDS-6805. Add acceptance tests for bucket layout post finalization behaviour validation.

### PR DESCRIPTION
**Pull request by JyotinderSingh**
## What changes were proposed in this pull request?

Add acceptance tests to validate the behavior of bucket layout feature post-upgrade-finalization.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-6805

## How was this patch tested?

Added robot tests.

### CODE REVIEW

**Comment by errose28** [comment]
Hi @JyotinderSingh, can you merge master back in to this PR to pick up #3487 and check the compat acceptance test failure?

**Comment by swamirishi** [comment]
@JyotinderSingh this PR needs to be rebased with master. Are you still working on this?

**Comment by JyotinderSingh** [comment]
Hi @swamirishi, I'm afraid I no longer have bandwidth to work on this PR.

**Comment by kerneltime** [comment]
@errose28 I am closing this jira for now until we can find a volunteer to work on this. I am marking the Jira as a newbie jira for some one new to take a look at the missing tests.

**Pull request closed without merging**
