### PR TITLE
Revert "HDDS-9426. Calculate Exclusive size for deep cleaned snapshot's deleted directories. (#5579)"

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Revert HDDS-9426 (#5579 and addendum), because it introduced incompatible proto changes (https://github.com/apache/ozone/pull/6044#issuecomment-1903577742).  These were not caught because backwards compatibility check was still comparing to Ozone 1.3.0's proto definition.  But HDDS-9426 is not present in 1.4.0, it was implemented during the release process.  So we need it to be compatible with 1.4.0 proto definitions.

https://issues.apache.org/jira/browse/HDDS-9426

## How was this patch tested?

Verified backwards compatibility check does not report any errors with `proto.lock` changes from #6044 after this revert.

```
$ mvn -DskipTests clean verify
...
[INFO] --- proto-backwards-compatibility:1.0.7:backwards-compatibility-check (default) @ ozone-interface-client ---
[INFO] protolock cmd line: hadoop-ozone/interface-client/target/protolock-bin/protolock status --lockdir=hadoop-ozone/interface-client/target/classes --protoroot=hadoop-ozone/interface-client/target/classes
[INFO] protolock cmd line: hadoop-ozone/interface-client/target/protolock-bin/protolock commit --lockdir=hadoop-ozone/interface-client/target/classes --protoroot=hadoop-ozone/interface-client/target/classes
[INFO] Backwards compatibility check passed.
```

### CODE REVIEW

**Comment by adoroszlai** [comment]
@swamirishi CI cannot verify compatibility until `proto.lock` changes for 1.4.0 are in.  But it cannot be committed until this incompatible change is there.  So the simplest way is:

1. revert
2. commit `proto.lock`
3. re-create PR for this change

**Comment by swamirishi** [comment]
> @swamirishi CI cannot verify compatibility until `proto.lock` changes for 1.4.0 are in. But it cannot be committed until this incompatible change is there. So the simplest way is:
> 
> 1. revert
> 2. commit `proto.lock`
> 3. re-create PR for this change

Makes sense

**Comment by adoroszlai** [comment]
Thanks @swamirishi, I'll wait a bit for others to check.

If anyone wants to merge this, please add the following in the "extended description":

```
Reason for revert: incompatible proto changes

This reverts commit 05284942fa5ec8026de0618f61af9b7cd758a90b.
This reverts commit d969689e83241e2d5bec2c878324ee1ce84c0fe4.
```

**Review by aswinshakil — APPROVED** [review]
Thanks for finding this and reverting @adoroszlai. I was not aware of this incompatibility.  

As suggested, we can revert #5579 and merge #6044. I'll raise a PR for this change once both are merged.

**Comment by adoroszlai** [comment]
Thanks @aswinshakil, @swamirishi for the review.

> I was not aware of this incompatibility.

No problem, that's why the check exists.  For future releases we should update `proto.lock` sooner, maybe right after cutting the release branch.

**Pull request merged**
