### PR TITLE
HDDS-11312. [hsync] Added upgrade tests

### PR DESCRIPTION
**Pull request by hemantk-12**
## What changes were proposed in this pull request?
This change is to add upgrade tests and set the basic framework to add more tests for hsync. 
1. The upgrade tests added are currently using lease recovery API only. We can add other APIs `listOpenFiles`. (I tried to add listOpenFiles API as well but was facing issues when running in a non-HA environment. Will work on that as an improvement.)
2. Added HSync and HFlush tests via freon.

## What is the link to the Apache JIRA
HDDS-11312

## How was this patch tested?
Green CI for acceptance tests in my forked branch: https://github.com/hemantk-12/ozone/actions/runs/10512044391

### CODE REVIEW

**Review by jojochuang — COMMENTED** [review]
The test log I saw https://github.com/apache/ozone/actions/runs/10513900938/job/29131287213?pr=7110


> chown: changing ownership of '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.5.0-SNAPSHOT/compose/upgrade/upgrades/non-rolling-upgrade/execution/1.4.0-1.5.0/data/om3': Operation not permitted
> chown: changing ownership of '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.5.0-SNAPSHOT/compose/upgrade/upgrades/non-rolling-upgrade/execution/1.4.0-1.5.0/data/recon': Operation not permitted
> chown: changing ownership of '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.5.0-SNAPSHOT/compose/upgrade/upgrades/non-rolling-upgrade/execution/1.4.0-1.5.0/data/scm2': Operation not permitted

Probably okay. I don't see it fails afterwards.

The test "Test HSync Prior To Finalization" got executed and passed. But does it do "Generate key by HSYNC"? I see it just execute 'ozone debug recover'

**Comment by hemantk-12** [comment]
> The test "Test HSync Prior To Finalization" got executed and passed. But does it do "Generate key by HSYNC"?

I tried adding `Generate key by HSYNC` in upgrade tests but [this condition](https://github.com/apache/ozone/blob/7da2a57e1cb9d7393e4d686446d986289b12c757/hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ContentGenerator.java#L112-L114) is always bypassing the hsync/flush.

**Comment by jojochuang** [comment]
Is this one blocked by PR #7153 and #7152?

**Comment by jojochuang** [comment]
Looks good. Let's open it up for review once #7152 and #7153 are merged?

**Review by jojochuang — APPROVED** [review]
LGTM

**Pull request merged**
