### PR TITLE
HDDS-4602. Ozone shell failed with Kerberos enabled

### PR DESCRIPTION
**Pull request by Xinshiyou**
## What changes were proposed in this pull request?
add UserGroupInformation.setConf in top class :  GenericCli.java

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-4602

## How was this patch tested?

Compile and run in local environment, that's OK.

### CODE REVIEW

**Comment by xiaoyuyao** [comment]
Thanks @Xinshiyou reporting this. I remember we have acceptance test that covers this. 
How do you repro it? Have you "kinit" before running the CLI with security enabled?

**Comment by Xinshiyou** [comment]
> Thanks @Xinshiyou reporting this. I remember we have acceptance test that covers this.
> How do you repro it? Have you "kinit" before running the CLI with security enabled?

Thanks for your attention. Yes, I run "kinit" as root for hdfs/`host`@myrealm，then run ozone shell. 

I will try again to confirm this problem.

**Comment by Xinshiyou** [comment]
Hi @xiaoyuyao ,
I try again with the following command, and got the following error:
`
-> klist
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: hdfs@myrealm

Valid starting       Expires              Service principal
12/21/2020 10:35:32  12/22/2020 10:35:32  krbtgt/myrealm@myrealm
	renew until 12/28/2020 10:35:32

-> whoami
root

-> bin/ozone sh  volume list
Couldn't create RpcClient protocol

-> date
Mon Dec 21 11:30:55 CST 2020
`

And security configure in ozone-site.xml：
` 
 <property>
        <name>ozone.security.enabled</name>
        <value>true</value>
        <tag>SECURITY</tag>
  </property>
  <property>
        <name>hadoop.security.authentication</name>
        <value>kerberos</value>
        <tag>SECURITY</tag>
  </property>
`

**Comment by Xinshiyou** [comment]
Finally, I figure out：this because UGI read configure from core-site.xml\hdfs-site.xml, rather from ozone-site.xml.

Maybe, we can explain it in detail in the document.

**Pull request closed without merging**
