### PR TITLE
HDDS-9523. Ozone manager doesn't honor property 'hadoop.security.token.service.use_ip'

### PR DESCRIPTION
**Pull request by ChenSammi**
Hadoop use property "hadoop.security.token.service.use_ip" to control when the IP or the host name will be used as  service name in delegation token. 

If hadoop.security.token.service.use_ip is true(default).  then IP address will be used to construct the Token service field, otherwise, then use host name. 

Currently in Ozone, service name in delegation token always use host name.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-9523

## How was this patch tested?

Tested by the enhanced existing unit test.

### CODE REVIEW

**Comment by ChenSammi** [comment]
> Could you please document that Ozone uses this Hadoop property? It would be very helpful in standalone Ozone installations.

Currently none of delegation used properties are documented. I created a track JIRA https://issues.apache.org/jira/browse/HDDS-9586 for this.

**Comment by ChenSammi** [comment]
@jojochuang , could you help to take another look?

**Review by adoroszlai — APPROVED** [review]

**Comment by adoroszlai** [comment]
Thanks @ChenSammi for the patch, @jojochuang, @myskov for the review.

**Comment by ChenSammi** [comment]
@adoroszlai ,thank you for review and merge the patch.

**Pull request merged**
