### PR TITLE
HDDS-6418. Datanode usage info uses wrong version number

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

`DatanodeUsageInfo` passes _datanode_ version (`datanodeDetails.getCurrentVersion()`) to the `toProto` method instead of _client_ version.  Datanode builds the response based on that version number.  If client is at version 0 and datanode at version 1, client cannot handle unknown ports. But here datanode will include replication port in DN details proto, based on its own version=1.  I think that specific situation is not possible, because usageinfo command did not exist at client version=0. But the same could happen if we introduced a new pair of client and datanode versions.

This PR changes to use client version, which is sent in `ScmContainerLocationRequest#version`:

https://github.com/apache/ozone/blob/bf38696d061be8e54968b595bc22bc4744bb9251/hadoop-hdds/interface-admin/src/main/proto/ScmAdminProtocol.proto#L43

https://issues.apache.org/jira/browse/HDDS-6418

## How was this patch tested?

Added integration test case, which verifies that the response is built based on client's version.  (It tests with datanode version = 0 and client version = 1, which is a bit different situation, but it's eaiser to tweak datanode version for the test).

https://github.com/adoroszlai/hadoop-ozone/actions/runs/1945512550

### CODE REVIEW

**Review by fapifta — APPROVED** [review]
Hi @adoroszlai,

the patch looks good to me, I think we can commit it, so that later on in #3155 we can take this as well, and see where we end up with passing the versions between different parts of the code.

**Comment by adoroszlai** [comment]
> Can we put this on hold if the scope is really this large?

I'd rather keep this patch limited in its scope.  I'll check other use cases separately.

**Comment by adoroszlai** [comment]
> In DatanodeDetails, we have. a method called getProtobufMessage, which uses the same toProto(int) call with the ClientVersion.CURRENT_VERSION value (so with the by the datanode known highest client version, instead of the actual client version). This getProtobufMessage method is used in the getExtendedProtobufMessage() method, in heartbeat (which is not a problem atm as we do not have rolling upgrade), CreatePipelineCommand, ReplicateContainerCommand, and in the getContainerReplicas call in the SCMClientProtocolServer. We need to validate if these are also called from the client side, and if so, then we need to change the behavior for those as well.

Filed HDDS-6429 for `getContainerReplicas`.  I haven't found any other place where incoming client version is ignored.  Heartbeat and `*Command` for for SCM-datanode communication.

**Review by fapifta — APPROVED** [review]
Thank you @adoroszlai for working on this, I think this patch solves the particular problem, and I don't have objections to commit it, but on the long run, I think we still will need to touch this code again, as we proceed with the compatibility questions.

**Comment by adoroszlai** [comment]
Thanks @fapifta for the review.

**Pull request merged**
