### PR TITLE
HDDS-8113. Remove Hadoop 2.7 compatibility hack

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

HDDS-8095 copied the `StreamCapabilities` interface from Hadoop, added by HDFS-11644 in 2.9.  Since we have upgraded to Hadoop 2.10, it is no longer needed.

https://issues.apache.org/jira/browse/HDDS-8113

## How was this patch tested?

CI:
https://github.com/adoroszlai/ozone/actions/runs/7172435971

### CODE REVIEW

**Comment by adoroszlai** [comment]
/pending let's wait with this until branch cut, so that 1.4.0 can still support Hadoop 2.7

**Comment by jojochuang** [comment]
What about CapableOzoneFSInputStream and CapableOzoneFSInputStream? IIRC they were also added to workaround the lack of StreamCapabilities in Hadoop 2.

**Comment by adoroszlai** [comment]
> What about CapableOzoneFSInputStream and CapableOzoneFSInputStream? IIRC they were also added to workaround the lack of StreamCapabilities in Hadoop 2.

Yes, they implement `StreamCapabilities` as subclasses, separate from the base `OzoneFS*Stream` classes due to compatibility.  But their code is not copied from Hadoop, so we need to put it somewhere.  I don't see much benefit in merging them into their base classes.

**Review by jojochuang — APPROVED** [review]
Removing CapableOzoneFSInputStream CapableOzoneFSOutputStream
 would simplify the code a bit. We now have many layers of output stream and input stream and hard to reason about.
I'm okay if we do not plan to do that now.

**Comment by adoroszlai** [comment]
Thanks @jojochuang for the review.

**Pull request merged**
