### PR TITLE
HDDS-8355. Intermittent failure in TestOMRatisSnapshots#testInstallSnapshot

### PR DESCRIPTION
**Pull request by GeorgeJahad**
## What changes were proposed in this pull request?

This test was flaky because one thread trys to read the log output from another thread before the log has been generated.

I confirmed this by hitting a breakpoint on the assertion failure, then looking at the log and seeing that it had subsequently been updated by another thread.

The fix is to poll the log for a few seconds until it is updated to the expected contents.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8355

## How was this patch tested?

Without the fix, I was able to reproduce the problem by running the test class 5 times repeatedly in intellij.

With the fix, I was unable to reproduce the problem after running it in intellij 50 times.

I also ran the CI 25 times without this failing.

### CODE REVIEW

**Comment by adoroszlai** [comment]
Thanks @GeorgeJahad for the patch.  Checkstyle reports some indentation problem:

```
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java
 679: 'method def' child has incorrect indentation level 6, expected level should be 4.
 680: 'block' child has incorrect indentation level 10, expected level should be 8.
```

`@Flaky` can be removed completely.

Other than that it looks good so far.

**Comment by adoroszlai** [comment]
@GeorgeJahad can you please share the link to repeated CI runs?

**Comment by GeorgeJahad** [comment]
@adoroszlai Why do you ask? Are you seeing a problem somewhere?

The links are here, https://github.com/GeorgeJahad/ozone/actions/workflows/post-commit.yml  , labeled "trigger new CI check 1-26"

Some failed for other reasons and some I canceled some once the om tests passed, but in all of them the om integration tests passed.

**Comment by GeorgeJahad** [comment]
In this one: "trigger new CI check 26" https://github.com/GeorgeJahad/ozone/actions/runs/4740249336 the om integration test failed for a different reason; the testOmRatisSnapshot test did pass.

**Review by adoroszlai — APPROVED** [review]
> Why do you ask? Are you seeing a problem somewhere?

No, but I think it's useful to document it.

Anyway, I triggered a [repeated run](https://github.com/adoroszlai/hadoop-ozone/actions/runs/4747294939) with the patch, and it passed in all runs (except one split was cancelled at the very start).

(BTW, when running repeated tests in CI, disabling unnecessary checks helps save time, [example](https://github.com/adoroszlai/hadoop-ozone/commit/b4d551696b11f00e2c4256e64a0b3fbe87820da6).)

**Comment by GeorgeJahad** [comment]
Thanks @adoroszlai 
For the record these were my runs.  (The om integration tests including the TestOmRatisSnapshot class, passed on each.):

```
https://github.com/GeorgeJahad/ozone/actions/runs/4740037723
https://github.com/GeorgeJahad/ozone/actions/runs/4739882033
https://github.com/GeorgeJahad/ozone/actions/runs/4739688108
https://github.com/GeorgeJahad/ozone/actions/runs/4739541532
https://github.com/GeorgeJahad/ozone/actions/runs/4739375783
https://github.com/GeorgeJahad/ozone/actions/runs/4739240425
https://github.com/GeorgeJahad/ozone/actions/runs/4739066965
https://github.com/GeorgeJahad/ozone/actions/runs/4738911442
https://github.com/GeorgeJahad/ozone/actions/runs/4738729784
https://github.com/GeorgeJahad/ozone/actions/runs/4738570900
https://github.com/GeorgeJahad/ozone/actions/runs/4738393612
https://github.com/GeorgeJahad/ozone/actions/runs/4738223920
https://github.com/GeorgeJahad/ozone/actions/runs/4738034314
https://github.com/GeorgeJahad/ozone/actions/runs/4737887420
https://github.com/GeorgeJahad/ozone/actions/runs/4737696448
https://github.com/GeorgeJahad/ozone/actions/runs/4737534048
https://github.com/GeorgeJahad/ozone/actions/runs/4737320242
https://github.com/GeorgeJahad/ozone/actions/runs/4737131814
https://github.com/GeorgeJahad/ozone/actions/runs/4736904674
https://github.com/GeorgeJahad/ozone/actions/runs/4736904216
https://github.com/GeorgeJahad/ozone/actions/runs/4736378602
https://github.com/GeorgeJahad/ozone/actions/runs/4736064711
https://github.com/GeorgeJahad/ozone/actions/runs/4735675034
https://github.com/GeorgeJahad/ozone/actions/runs/4735250360
https://github.com/GeorgeJahad/ozone/actions/runs/4734973217
```

**Pull request merged**
