### PR TITLE
HDDS-5880 Remove SPNEGO principal for S3 Gateway

### PR DESCRIPTION
**Pull request by Taybou**
## What changes were proposed in this pull request?

Remove SPNEGO principal for S3 Gateway

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5880

## How was this patch tested?

No functionality changes. Existing tests cover this.

### CODE REVIEW

**Review by adoroszlai — CHANGES_REQUESTED** [review]
Thanks @Taybou for the patch.

Removing the Kerberos principal does not work, S3 Gateway HTTP server start fails with: `Problem starting http server`.

@avijayanhwx Aren't there parts of the S3G HTTP endpoint that should keep using SPNEGO (JMX and other Ozone-specific stuff)?  Is that possible on the same port, or should we start separate HTTP servers?

**Comment by avijayanhwx** [comment]
> Thanks @Taybou for the patch.
> 
> Removing the Kerberos principal does not work, S3 Gateway HTTP server start fails with: `Problem starting http server`.
> 
> @avijayanhwx Aren't there parts of the S3G HTTP endpoint that should keep using SPNEGO (JMX and other Ozone-specific stuff)? Is that possible on the same port, or should we start separate HTTP servers?

Good point @adoroszlai. The diagnostic servlets need not be behind SPNEGO walls. That said, it is possible to add SPNEGO only for specific servlets by overriding some BaseHTTPServer logic in the S3G HTTP server class. What are the other servlet endpoints in s3g? Does it have a /conf endpoint?

**Comment by adoroszlai** [comment]
> What are the other servlet endpoints in s3g? Does it have a /conf endpoint?

We have some common endpoints (`/conf`, `/jmx`, `/logLevel`, `/logs`, `/prom`, `/stacks`, `/static`).

**Comment by avijayanhwx** [comment]
Currently in other Ozone components, only /prom endpoint is not being a SPNEGO filter. If we want to keep that for s3g, we need a way to secure all endpoints except thee /prom and s3 compatible endpoints to be SPNEGO disabled, but others keep the filter enabled. That may be difficult to do on a single HTTP server since the s3 endpoints are dynamic (/{bucket-name}).

**Comment by adoroszlai** [comment]
/pending Thanks again @Taybou for the patch.  Based on the discussion about Recon endpoints, this needs much more effort.  Please feel free to reach out if you need help on that.  It is also OK if you would like to pass on this task.

**Pull request closed without merging**
