### PR TITLE
HDDS-8163. Use try-with-resources to ensure close rockdb connection in SstFilteringService

### PR DESCRIPTION
**Pull request by DaveTeng0**
## What changes were proposed in this pull request?
Use try-with-resources to ensure close rockdb connection in SstFilteringService

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-8163

## How was this patch tested?
current CI unit tests

### CODE REVIEW

**Review by hemantk-12 — APPROVED** [review]
LGTM.

**Review by sadanand48 — APPROVED** [review]

**Comment by sadanand48** [comment]
Thanks @DaveTeng0 for the quick fix and @hemantk-12 for the review.

**Comment by adoroszlai** [comment]
Please pay attention when merging PRs. If it has a single commit, GitHub uses the commit's message by default, not the PR title.

**Comment by sadanand48** [comment]
Thanks @adoroszlai , the dot got missed , will take care of it in future.

**Pull request merged**
