### PR TITLE
HDDS-10869. SCMNodeManager#getUsageInfo memory occupancy optimization

### PR DESCRIPTION
**Pull request by guohao-rosicky**
## What changes were proposed in this pull request?

SCMNodeManager#getUsageInfo this method will obtain the number of containers for the node, create a container ID set, calculate the size of this set, and create a large temporary object.

When there are too many containers in a node, this is a very time-consuming operation.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-10869

### CODE REVIEW

**Review by adoroszlai — COMMENTED** [review]
Thanks @guohao-rosicky for the patch, LGTM.

The new method can be used in Recon, too:

https://github.com/apache/ozone/blob/611066af95f5fb239769219051c2ef4882d2a931/hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NodeEndpoint.java#L155-L157

**Comment by ChenSammi** [comment]
LGTM.  It's better to improve the operation in Recon code too, as @adoroszlai suggested.

**Review by siddhantsangwan — APPROVED** [review]
Good catch @guohao-rosicky. Approving this, but it'll be good if we can incorporate the suggestion made by @adoroszlai.

**Review by ChenSammi — APPROVED** [review]
Thanks @guohao-rosicky for the update. The last patch LGTM. Thanks @adoroszlai and @siddhantsangwan for the review.

**Pull request merged**
