### PR TITLE
HDDS-7240. List all volume operation should go through ACL check as well in order to trigger audit logging

### PR DESCRIPTION
**Pull request by dombizita**
## What changes were proposed in this pull request?

Previously the list all volume operation only went through the ACL check if the list all volume was disabled. Because of this the audit logging wasn't triggered. I removed the if condition checking the `ozone.om.volume.listall.allowed`'s value, so the ACL check gets triggered in every case (if the ACL is enabled). I also updated the `ozone.om.volume.listall.allowed`'s description in `ozone-default.xml`.

OzoneNativeAuthorizer wouldn't be affected by this change, because of [this](https://github.com/apache/ozone/pull/1395) change, the allowListAllVolumes is set [here](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java#L762) on the authorizer side.  

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7240

## How was this patch tested?

Run related tests.

### CODE REVIEW

**Review by smengcl — APPROVED** [review]
+1 pending CI. Thanks @dombizita

**Comment by kerneltime** [comment]
cc @duongkame

**Review by duongkame — APPROVED** [review]
+1, thanks @dombizita for the patch.

**Comment by smengcl** [comment]
Thanks @dombizita for the patch. Thanks @duongkame for the review.

**Pull request merged**
