### PR TITLE
HDDS-10087. Clean up code in NodeDecommissionManager

### PR DESCRIPTION
**Pull request by jianghuazhu**
## What changes were proposed in this pull request?
There are some obsolete codes in NodeDecommissionManager, and the purpose of this PR is to clean them up.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-10087

## How was this patch tested?
Need to ensure that unit tests pass.

### CODE REVIEW

**Comment by jianghuazhu** [comment]
ci: https://github.com/jianghuazhu/ozone/actions/runs/7450232295
Can you help me take a look at this PR, @adoroszlai .
Thanks.

**Review by adoroszlai — COMMENTED** [review]
Thanks @jianghuazhu for the patch, LGTM.

While reviewing I noticed that some of the member variables can even be removed:

```
  private final EventPublisher eventQueue;
  private final ReplicationManager replicationManager;
  private final OzoneConfiguration conf;
```

can be used directly from constructor param, and:

```
  private long monitorInterval;
```

can be converted to local variable in constructor.

Sorry for missing this in the Jira issue.  May I ask you to make this change?

**Comment by jianghuazhu** [comment]
OK, I will update later.

**Comment by jianghuazhu** [comment]
I've updated it, @adoroszlai .

**Review by adoroszlai — COMMENTED** [review]
Thanks @jianghuazhu for updating the patch, LGTM.

**Review by sodonnel — APPROVED** [review]
LGTM - thanks for the cleanup. I've a feeling this class got modified recently which may have caused some of these problems, but I am not sure.

**Comment by adoroszlai** [comment]
Thanks @jianghuazhu for the patch, @sodonnel for the review.

> I've a feeling this class got modified recently which may have caused some of these problems

Right.

> * remove useless `this.metrics = null` assignment

This one was added in HDDS-2642.

> * merge identical `catch` blocks in `mapHostnamesToDatanodes`
> * remove `throws InvalidHostStringException` from `recommissionNodes` and `startMaintenanceNodes`, as it is never thrown by these methods

These were introduced in HDDS-9511.

**Pull request merged**
