### PR TITLE
HDDS-6173. Merge master branch including s3g persistent connection changes into feature branch

### PR DESCRIPTION
**Pull request by neils-dev**
## What changes were proposed in this pull request?

Merge requested in PR #2945 to merge Apache Ozone master branch with HDDS-5881 changes INTO HDDS-4400-s3-performance feature branch.  Merge allows s3 gateway gRPC to work with s3 gateway persistent connection changes made in HDDS-5881 found in master branch.

see major code files affected in attachment.
[merge_conflicts.txt](https://github.com/apache/ozone/files/7843517/merge_conflicts.txt)

Also,this list of diffs should cover the necessary changes made to the grpc code to integrate with the Master merge. 
[merge_integration_diffs.txt](https://github.com/apache/ozone/files/7865664/merge_integration_diffs.txt)

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-6173

## How was this patch tested?

Unit tests for s3 gateway and acceptance tests for s3 gateway.
Passes both s3 gateway specific unit tests and acceptance tests with the ozonesecure cluster.

### CODE REVIEW

**Comment by GeorgeJahad** [comment]
Hey Neil, 800 files seems like a lot of files to review.  I wonder if we could make it easier.

If I'm understanding things correctly, there are really just 15 files that really need to be reviewed.  Here are those diffs:

https://github.com/GeorgeJahad/ozone/compare/HDDS-4440-updated-feature-branch..neils-dev:5881_merge

Note that diff is between a branch I created from the old feature branch, and your 5881_merge branch.

To understand the diff better let me describe how the two branches were created.

To create your 5881_merge branch, you:
* started from the feature branch, 
* merged in the latest master, 30cb5e7644fc3fcb524ba9ede9059a118b03f2fd, 
* resolved the merge conflicts, and 
* integrated the s3 grpc changes with the hadoop rpc changes.


To create my branch, I:
* got the s3grpc diffs from the old feature branch and 
* patched 30cb5e7644fc3fcb524ba9ede9059a118b03f2fd with it. 
 
I let the merge conflicts be rejected, and didn't try to integrate the hrpc changes.

Here is the code:

```
# tag the last master merged into the feature branch
git tag oldGrpcMaster db574d1cfffc8c0a57bef4dcdec008bb6c6c3fba

# get the s3grpc changes in the old feature branch
git diff oldGrpcMaster  HDDS-4440-s3-performance > /tmp/s3grpc.diff

# tag the master that will be the basis of the new feature branch
git tag newGrpcMaster 30cb5e7644fc3fcb524ba9ede9059a118b03f2fd

#create updated feature branch
git checkout newGrpcMaster
git checkout -b HDDS-4440-updated-feature-branch

# Now patch the new feature branch with the s3grpc changes
# note that the changes that don't merge cleanly will be rejected
# and will be resolved by hand in the next commit
patch -p1 -f < /tmp/s3grpc.diff
git add .
git commit -m "added s3grpc changes not including merge conflicts"
```


Now that branch has all the s3grpc changes commited up to now, without resolving any merge conflicts, or integrating the grpc changes with hadoop rpc.

Those are things you added, and I think are the main things the reviewers want to see.

They get those diffs by comparing my branch with yours.  

What do you think?

**Comment by neils-dev** [comment]
Thanks @GeorgeJahad, I like the idea, however there are things shown in the diffs generated that are incorrect, also missing changes ie. OzoneClientProto.  It does give a good reference to some of the changes.  This is linked to PR #2945. and was asked for there, so a better idea of the changes are seen in that PR (excluding the TLS).  In that PR the hrpc changes (HDDS-5581) are 'patched' into the 4440-feature-branch and clearer to see the integration between the feature branch and the 5581.  Basically, this PR is a merge from the master into the feature branch.  As a result some changes were necessary to the already reviewed s3gateway gRPC code  in the feature branch.  No additional code was added as the TLS code (2945) will be added to this merge.

**Comment by neils-dev** [comment]
Added a file to the pull-request description: `merge_integration_diffs.txt ` based on followup discussions with @GeorgeJahad to highlight the changes made to the s3g feature branch to integrate with the merge of Master to HDDS-4440-s3-performance.

**Comment by kerneltime** [comment]
Taking a look @neils-dev

**Comment by kerneltime** [comment]
I went over the commits that might be in conflict and looks good. 
LGTM
cc @adoroszlai can you please merge this PR.

**Pull request merged**
