### PR TITLE
HDDS-5035. Use default config values to solve generated config file conflict

### PR DESCRIPTION
**Pull request by symious**
## What changes were proposed in this pull request?

- Use default config values to initialize configurations

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5035

## How was this patch tested?

The user's assembled fat jar works fines now.

### CODE REVIEW

**Comment by symious** [comment]
@elek @adoroszlai Could you help to review this PR?

**Review by elek — COMMENTED** [review]
Thanks the patch @symious 

It looks good to me. I took me some time to test it, I think a simple unit test would help a lot to demonstrate the fix

Is there any chance to add a simple unit test (at least for a few types)?

As far as I see `TestConfigurationReflectionUtil` is parametrized (which makes it hard to add anything) but worst case we can add a new test class.

**Comment by symious** [comment]
@elek Thanks for the review, have added a unit test to simulate this case. Please have a check.

**Comment by symious** [comment]
@elek Thanks for the review. 
Sorry for not adding the unit test in the first place, it took some time to find a way to simulate the scenario for the unit test.

**Comment by elek** [comment]
>  Sorry for not adding the unit test in the first place, it took some time to find a way to simulate the scenario for the unit test.

Sure, no problem. **Now** I understand that it was a tricky request, but earlier I thought it's a simpler problem ;-)

**Pull request merged**
