### PR TITLE
HDDS-3684. Add tests for replication annotation

### PR DESCRIPTION
**Pull request by amaliujia**
## What changes were proposed in this pull request?

Add tests for replication annotation

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3684

## How was this patch tested?

Unit Test

### CODE REVIEW

**Comment by amaliujia** [comment]
R: @timmylicheng

**Comment by amaliujia** [comment]
Also R: @nandakumar131

**Comment by nandakumar131** [comment]
@amaliujia FYI: We already have a `MockRatisServer` which is inside `MockSCMHAManager.java`, please extract it out if required and reuse the same.

**Comment by amaliujia** [comment]
@nandakumar131 

thanks! I moved the existing MockRatisServer out and re-use that one.

**Comment by amaliujia** [comment]
@timmylicheng  

conflicts resolved.

**Comment by timmylicheng** [comment]
@amaliujia Looks like we have new conflicts. Could you please take another look?

**Comment by amaliujia** [comment]
@timmylicheng I found this PR has lagged too much so just created a new PR which is based on the most recent HDDS-2823: https://github.com/apache/ozone/pull/1650

**Pull request closed without merging**
