### PR TITLE
HDDS-9147. Replaced GenericTestUtils#wait with Awaitility#await in hadoop-ozone packages

### PR DESCRIPTION
**Pull request by hemantk-12**
## What changes were proposed in this pull request?
This change is to replace [GenericTestUtils#wait](https://github.com/apache/ozone/blob/387c53781aae03f944906a0add58f51250d36687/hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/GenericTestUtils.java#L214) with [Awaitility#await](https://github.com/awaitility/awaitility) hadoop-ozone packages. Awaitility provides the same functionality as **GenericTestUtils** with more granular configuration.

This is part 3 of [HDDS-9147](https://issues.apache.org/jira/browse/HDDS-9147).

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-9147

## How was this patch tested?
No functional or logical change so just run the CI/CD on fork couple of time.
* https://github.com/hemantk-12/ozone/actions/runs/5843839777
* https://github.com/hemantk-12/ozone/actions/runs/5844969161

### CODE REVIEW

**Comment by sodonnel** [comment]
Looking at Awaitility (for the first time), it hasn't had a release in nearly 18 months, and shows little recent activity.

People on the project are also already familiar with GenericTestUtils, as it is widely used in Hadoop. I'm not sure doing a like for like swap like this, in favor of a fairly stale looking project is a good idea or worth the review effort.

**Comment by hemantk-12** [comment]
Please a look of this as well @errose28 @kerneltime

**Comment by kerneltime** [comment]
@hemantk-12 I am all for refactoring and removing code in favor of newer projects, but I wonder if this project is still alive. After the community sync I took a look; this project has had no activity for issues or PRs for some time now, including updating dependencies (which for test code is not as severe). https://github.com/awaitility/awaitility/issues
The last commit is a commit around adding support for showing funding sources. https://github.com/awaitility/awaitility/commit/a56dce91b2abff03beb4773180ec6e5edb0117d7

**Comment by hemantk-12** [comment]
@kerneltime and @sodonnel, I see your point of "no activity for issues or PRs ". I know it is not a fair argument but we have other dependencies like [Hamcrest](https://github.com/hamcrest/JavaHamcrest) which have no activity for a year or more similar to  `Awaitility` but is still in Ozone and is used in tests.

I believe `Awaitility` improves the readability and provides more granularity over GenericTestUtils/LambdaTestUtils. If we are not aligned and skeptical about its usage, I'm OK keep using GenericTestUtils/LambdaTestUtils. Also if we go with not using Awaitility, then we should remove the exiting usage of it.

**Comment by sodonnel** [comment]
It was mentioned on the community sync yesterday that Awaitility was needed for Snaphots, so I had a look around and found only two instances of it used in test code, in `ManagedRocksObjectUtils.waitForFileDelete()` and `RDBCheckpointUtils.waitForCheckpointDirectoryExist()`.

In both cases the code looks largely like this:

```
  public static boolean waitForCheckpointDirectoryExist(File file,
      Duration maxWaitTimeout) {
    Instant start = Instant.now();
    try {
      with().atMost(maxWaitTimeout)
          .pollDelay(POLL_DELAY_DURATION)
          .pollInterval(POLL_INTERVAL_DURATION)
          .await()
          .until(file::exists);
      LOG.info("Waited for {} milliseconds for checkpoint directory {}" +
              " availability.",
          Duration.between(start, Instant.now()).toMillis(),
          file.getAbsoluteFile());
      return true;
    } catch (ConditionTimeoutException exception) {
      LOG.info("Checkpoint directory: {} didn't get created in {} secs.",
          maxWaitTimeout.getSeconds(), file.getAbsolutePath());
      return false;
    }
  }
```

This could easily have been written like:

```
  public static boolean waitForCheckpointDirectoryExist2(File file,
      Duration maxWaitTimeout) {
    Instant start = Instant.now();
    while(true) {
      Duration duration = Duration.between(start, Instant.now());
      if (file.exists()) {
        LOG.info("Waited for {} milliseconds for checkpoint directory {}" +
                " availability.", duration.toMillis(), file.getAbsoluteFile());
        return true;
      }
      if (duration.toMillis() > maxWaitTimeout.toMillis()) {
        LOG.info("Checkpoint directory: {} didn't get created in {} secs.",
            maxWaitTimeout.getSeconds(), file.getAbsolutePath());
        return false;
      }
      try {
        Thread.sleep(100);
      } catch (InterruptedException e) {
        e.printStackTrace();
        // break out etc
      }
    }
  }
```

Which isn't any more complex, avoids bring in another dependency, and avoids someone needing to go look at the Java docs to understand what all the magic methods on the library do.

While it is good to reuse libraries, every one we add, adds a barrier to understanding the code, by needing to read about the library, which could be simple java code in this case.

In my opinion, it would be easier to remove the usage of Awaitility in these two non-test code instances, and then keep with what we already have in lambda utils. People already know it, it avoids these rather large patches which could cause cherry-pick conflicts and make backports harder, etc.

**Comment by hemantk-12** [comment]
@sodonnel I agree that `Awaitility` might not be a good choice in the above case and can be (should be) changed as you suggested. But when it comes to tests, `Awaitility` provides much more flexibility compare to `GenericTestUtils` or `LambdaTestUtils` e.g. exception handling, assertion in lambda, deadlock detection, providing time in Duration (which is much more readable than converting milliseconds).
Regarding "People already know it, keep it as it is.", I do not agree with it. It gives the impression that we refrain from trying out new things. Also the reason for this large patch was to not accumulate more tech-debt otherwise we would be in the situation that we have `GenericTestUtils`, `LambdaTestUtils`, `Awaitility` ... etc at the same time and different people use different way to test the code.

Having said that, I will discard all three PRs and create a jira to remove `Awaitility` from existing code.

**Comment by hemantk-12** [comment]
Discarding the changes for now based on above discussion.

**Comment by adoroszlai** [comment]
See also #5923.

**Pull request closed without merging**
