### PR TITLE
HDDS-4936. Change ozone groupId from org.apache.hadoop to org.apache.ozone

### PR DESCRIPTION
**Pull request by ChenSammi**
https://issues.apache.org/jira/browse/HDDS-4936

### CODE REVIEW

**Comment by amaliujia** [comment]
I left a question in the JIRA for more context.

**Comment by ayushtkn** [comment]
@ChenSammi is this change going to break any older application codes which have any of the ozone modules as dependency due to this?

**Comment by amaliujia** [comment]
LGTM

@ayushtkn I am thinking this change will only impact future releases. When users bump up versions, maybe change the group is ok?

**Comment by ChenSammi** [comment]
Current applications which depend on ozone modules,  if they don't upgrade ozone module version,  they need to do nothing.  
If they want to upgrade ozone module version, say from 1.0.0 to 1.1.0,  they have to change ozone module groupId from "org.apache.org" to "org.apache.ozone" at the same time,  otherwise there will be maven module not found error.  

@ayushtkn  do you think it's a big problem for current user?

**Comment by ayushtkn** [comment]
Not sure, shouldn’t be a big problem, may be during release an explicit mention of this would be good or somewhere in the Release notes.
If you folks are convinced,Nothing blocking from my side.

**Review by elek — COMMENTED** [review]
Thanks the patch @ChenSammi, it looks good to me.

Do we plan to remove tha `hadoop-` prefixes from the `artifactId`s, too? Or in a separated patch?

**Comment by arp7** [comment]
Hi @ChenSammi, can you please keep this PR open for a few days so more people can take a look and call out any potential incompatibilities?

**Comment by ChenSammi** [comment]
> Thanks the patch @ChenSammi, it looks good to me.
> 
> Do we plan to remove tha `hadoop-` prefixes from the `artifactId`s, too? Or in a separated patch?

@elek , do you mean change "hadoop-main-ozone" to "ozone",  change "hadoop-hdds" to "ozone-hdds", something like these? 
I guess it requires changing the source code directory name as long as the artifactId, which will have obvious impact on current developers.  Ideally, we should replace existing "hadoop" keywords as many as possible. But I 'm not sure how big the impact is by change the artifactId and directory name.  Maybe I can send out an email to the dev list to collect more feedback 

as @amaliujia  has suggested.

**Comment by ChenSammi** [comment]
> Hi @ChenSammi, can you please keep this PR open for a few days so more people can take a look and call out any potential incompatibilities?

Sure.

**Comment by elek** [comment]
> do you mean change "hadoop-main-ozone" to "ozone", change "hadoop-hdds" to "ozone-hdds", something like these?

Yes, exactly. 

Directory names and artifact names are different. Directory names are referenced only in the `<modules>` section of the parent pom files. ArtifactIds are used in other places together with `groupId`. `artifactId` can be changed without modifying the directory structure (but some direct reference to the final `hadoop-ozone-filesystem-hadoop2-1.1.0-SNAPSHOT.jar` may require update) 

While directory rename affects only the developers (therefore I am fine with delay it) the artifactId should be changed in downstream projects. As we cause some minor inconveniences with the `groupId` change I would prefer to change both at the same time to cause inconvenience only once. (Can be done either in this patch or in another patch which follows this closely.)

**Comment by adoroszlai** [comment]
> As we cause some minor inconveniences with the `groupId` change I would prefer to change both at the same time to cause inconvenience only once.

Totally agree.

**Comment by ChenSammi** [comment]
Uploaded a new commit to remove Keyword “Hadoop” from the artificatID.

**Comment by adoroszlai** [comment]
@ChenSammi I had fixed several remaining issues in your branch:

* 98b6a07c2 Fix IDEA run configs
* 57157df34 Fix ozone-manager artifact name
* 2a2416126 Fix module names
* 715a95664 Fix GH workflow
* 0f7bf9f72 Update module names in coverage.sh
* 81334ed91 Fix checkstyle

Why did you overwrite those?

**Comment by ChenSammi** [comment]
> @ChenSammi I had fixed several remaining issues in your branch:
> 
>     * [98b6a07](https://github.com/apache/ozone/commit/98b6a07c2b5f4af2b003f68f2b4e5d2f6a27d37c) Fix IDEA run configs
> 
>     * [57157df](https://github.com/apache/ozone/commit/57157df34a0cd02bf14d5f66ecc8638b8902ad29) Fix ozone-manager artifact name
> 
>     * [2a24161](https://github.com/apache/ozone/commit/2a24161262cc12a4712225bb5bb03e4848aa3a38) Fix module names
> 
>     * [715a956](https://github.com/apache/ozone/commit/715a95664e9f9efd510a1545d724915abc6cc1fb) Fix GH workflow
> 
>     * [0f7bf9f](https://github.com/apache/ozone/commit/0f7bf9f721ce14416245153ebb23b055c773073f) Update module names in coverage.sh
> 
>     * [81334ed](https://github.com/apache/ozone/commit/81334ed914d7facc6b21c4cceaff597b86228f2b) Fix checkstyle
> 
> 
> Why did you overwrite those?

@adoroszlai ,  sorry,  I didn't notice it's your fixes.  I just thought it's part of the impact of previous master branch force push.

Would you please resubmit your comments again?

**Comment by elek** [comment]
I fetched the original commits from @adoroszlai  (`git fetch origin 98b6a07c2b5f4af2b003f68f2b4e5d2f6a27d37c`) and merged it back to the latest branch from @ChenSammi and finally pushed it (`git push git@github.com:ChenSammi/ozone.git HEAD:HDDS-4936`)

Now it should contain all the fixes.

**Comment by ChenSammi** [comment]
> I fetched the original commits from @adoroszlai (`git fetch origin 98b6a07c2b5f4af2b003f68f2b4e5d2f6a27d37c`) and merged it back to the latest branch from @ChenSammi and finally pushed it (`git push git@github.com:ChenSammi/ozone.git HEAD:HDDS-4936`)
> 
> Now it should contain all the fixes.

Thanks @elek  for the help.    I tried to rebase this branch with master to resolve the conflicting files, but met a lot of unexpected conflicts. So I manually applied @adoroszlai 's patche one by one.  Here is the new MR https://github.com/apache/ozone/pull/2104.

**Comment by ChenSammi** [comment]
@mukul1987 ， can we merge this PR now？

**Comment by mukul1987** [comment]
@ChenSammi , lets merge the change then.

**Comment by ChenSammi** [comment]
> 
> 
> @ChenSammi , lets merge the change then.

Thanks @mukul1987 , would you help to approve the merge?

**Review by mukul1987 — APPROVED** [review]
LGTM

**Comment by ChenSammi** [comment]
Thanks @adoroszlai @elek @mukul1987 for the help.

**Pull request merged**
