### PR TITLE
HDDS-5298. Use netty-bom to ensure consistent Netty version

### PR DESCRIPTION
**Pull request by risdenk**
## What changes were proposed in this pull request?

Replaces uses of `netty.version` and uses `netty-bom` in top level pom `dependencyManagement` section to ensure consistent Netty version.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5298

## How was this patch tested?

`mvn clean verify`

### CODE REVIEW

**Comment by risdenk** [comment]
FWIW locally I keep getting this error when using `mvn clean verify`. I haven't dug into it and not sure if its related to this change or not:

```
...
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   TestHddsVolumeChecker.testCheckAllVolumes[6] » OutOfMemory unable to create ne...
[ERROR]   TestHddsVolumeChecker.testCheckAllVolumes[7] » OutOfMemory unable to create ne...
[ERROR]   TestHddsVolumeChecker.testCheckOneVolume:158 » OutOfMemory unable to create ne...
[ERROR]   TestHddsVolumeChecker.testCheckOneVolume:158 » OutOfMemory unable to create ne...
[ERROR]   TestHddsVolumeChecker.testVolumeDeletion:257 » OutOfMemory unable to create ne...
[ERROR]   TestHddsVolumeChecker.testVolumeDeletion[6] » OutOfMemory unable to create new...
[ERROR]   TestHddsVolumeChecker.testVolumeDeletion[7] » OutOfMemory unable to create new...
[INFO]
[ERROR] Tests run: 366, Failures: 0, Errors: 7, Skipped: 4
...
```

**Comment by risdenk** [comment]
I checked master and see the same test failures locally for me so doesn't look related to this change. Also looks like the CI checks passed. Thanks @adoroszlai  for kicking those off again.

**Review by adoroszlai — APPROVED** [review]
Thanks @risdenk for this fix.  Netty artifact versions are now consistent in `share/ozone/lib`:

```
netty-buffer-4.1.63.Final.jar
netty-codec-4.1.63.Final.jar
netty-codec-http-4.1.63.Final.jar
netty-codec-http2-4.1.63.Final.jar
netty-codec-socks-4.1.63.Final.jar
netty-common-4.1.63.Final.jar
netty-handler-4.1.63.Final.jar
netty-handler-proxy-4.1.63.Final.jar
netty-resolver-4.1.63.Final.jar
netty-transport-4.1.63.Final.jar
netty-transport-native-epoll-4.1.63.Final.jar
netty-transport-native-unix-common-4.1.63.Final.jar
```

instead of the mix we had previously:

```
netty-buffer-4.1.63.Final.jar
netty-codec-4.1.63.Final.jar
netty-codec-http-4.1.51.Final.jar
netty-codec-http2-4.1.51.Final.jar
netty-codec-socks-4.1.51.Final.jar
netty-common-4.1.63.Final.jar
netty-handler-4.1.63.Final.jar
netty-handler-proxy-4.1.51.Final.jar
netty-resolver-4.1.63.Final.jar
netty-transport-4.1.63.Final.jar
netty-transport-native-epoll-4.1.63.Final.jar
netty-transport-native-unix-common-4.1.63.Final.jar
```

**Review by bharatviswa504 — APPROVED** [review]
+1 LGTM. (With this I got to learn about maven BOM also)

**Comment by bharatviswa504** [comment]
Thank You @risdenk for the contribution and @adoroszlai for the review.

**Pull request merged**
