### PR TITLE
HDDS-7704. [snapshot] Add unit-testcases for snapshot restore

### PR DESCRIPTION
**Pull request by jyotirmoy-gh**
## What changes were proposed in this pull request?

Add UTs for Snapshot Restore - `TestOzoneSnapshotRestore`

```
- testRestoreSnapshot
- testRestoreSnapshotDifferentBucket
- testRestoreSnapshotDifferentBucketLayout
```

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7704

## How was this patch tested?

Testcase file - `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneSnapshotRestore.java`
```
mvn -Dtest=TestOzoneSnapshotRestore test
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.ozone.om.snapshot.TestOzoneSnapshotRestore
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 265.872 s - in org.apache.hadoop.ozone.om.snapshot.TestOzoneSnapshotRestore
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
```

### CODE REVIEW

**Comment by jyotirmoy-gh** [comment]
@smengcl @sadanand48 @nilotpalnandi - Please review

**Review by sadanand48 — COMMENTED** [review]
Thanks @jyotirmoy-gh for the patch, looks good overall. Although I'm not sure if we should call it 'restore' as here  we are copying from snapshot to active DB and new blocks for the new keys  would be written again  whereas during actual restore only metadata must be added back to the Active rocksdb, but I guess  we  would need to change this file  when actual snapshot restore is implemented. @smengcl any thoughts?

**Comment by smengcl** [comment]
> Thanks @jyotirmoy-gh for the patch, looks good overall. Although I'm not sure if we should call it 'restore' as here we are copying from snapshot to active DB and new blocks for the new keys would be written again whereas during actual restore only metadata must be added back to the Active rocksdb, but I guess we would need to change this file when actual snapshot restore is implemented. @smengcl any thoughts?

Thanks @sadanand48 for the comment. I'm actually fine with the "restore" name. `TestOzoneSnapshotRead` might be more accurate, but too vague by itself.

**Review by smengcl — APPROVED** [review]

**Comment by smengcl** [comment]
Thanks @jyotirmoy-gh for the test addition. Thanks @sadanand48 for the review.

**Comment by adoroszlai** [comment]
@jyotirmoy-gh @sadanand48 @smengcl 

This new test is failing on the feature branch.  Since it has passed in the PR, I assume it is due to some other change between the PR's CI run and the time the PR was actually merged.

https://github.com/apache/ozone/actions/runs/4010177337/jobs/6886380732#step:5:3205
https://github.com/apache/ozone/actions/runs/4012530839/jobs/6891046898#step:5:3209
https://github.com/apache/ozone/actions/runs/4012534734/jobs/6906204716#step:5:3209

**Pull request merged**
