### PR TITLE
HDDS-7421. Respect OZONE_LOGLEVEL and OZONE_ROOT_LOGGER for CLI commands

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

(Some) Ozone CLI commands log to `ozone-shell.log` instead of the console.  The goal was to reduce output clutter, but it causes problems due to file ownership.

Other Ozone commands use a log config inherited from Hadoop, which allows customising root logger and default log level via environment variables OZONE_ROOT_LOGGER and OZONE_LOGLEVEL.

The goal of this task is to get rid of the custom config for CLI, scrap `ozone-shell.log`, and respect these environment variables.  CLI commands should disable logging by default.

https://issues.apache.org/jira/browse/HDDS-7421

## How was this patch tested?

Tested a few commands to verify they do not show log by default (but show regular output, see second command):

```
$ ozone sh volume create /vol2

$ ozone fs -mkdir ofs://om/vol/buck/dir/subdir
mkdir: `ofs://om/vol/buck/dir': No such file or directory

$ ozone fs -mkdir -p ofs://om/vol/buck/dir/subdir
```

But log can be enabled by either `OZONE_LOGLEVEL`:

```
$ OZONE_LOGLEVEL=info ozone sh volume create /vol1
2022-10-26 18:57:49,237 [main] INFO rpc.RpcClient: Creating Volume: vol1, with hadoop as owner and space quota set to -1 bytes, counts quota set to -1

$ OZONE_LOGLEVEL=DEBUG ozone fs -mkdir -p ofs://om/vol/buck/dir/subdir/other
...
2022-10-26 19:15:59,808 [main] DEBUG ipc.ProtobufRpcEngine: Call: submitRequest took 8ms
2022-10-26 19:15:59,814 [main] DEBUG fs.Globber: glob ofs://om/vol/buck/dir/subdir/other: duration 0:00.037s
...
```

or by `OZONE_ROOT_LOGGER`:

```
$ OZONE_ROOT_LOGGER=DEBUG,console ozone sh bucket create /s3v/buck
2022-10-26 18:59:25,399 [main] DEBUG lib.MutableMetricsFactory: field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.getGroups with annotation @org.apache.hadoop.metrics2.annotation.Metric(sampleName="Ops", always=false, valueName="Time", about="", interval=10, type=DEFAULT, value={"GetGroups"})
2022-10-26 18:59:25,404 [main] DEBUG lib.MutableMetricsFactory: field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.loginFailure with annotation @org.apache.hadoop.metrics2.annotation.Metric(sampleName="Ops", always=false, valueName="Time", about="", interval=10, type=DEFAULT, value={"Rate of failed kerberos logins and latency (milliseconds)"})
...
2022-10-26 18:59:25,815 [IPC Client (939475028) connection to om/172.25.0.8:9862 from hadoop] DEBUG ipc.Client: IPC Client (939475028) connection to om/172.25.0.8:9862 from hadoop: closed
2022-10-26 18:59:25,815 [IPC Client (939475028) connection to om/172.25.0.8:9862 from hadoop] DEBUG ipc.Client: IPC Client (939475028) connection to om/172.25.0.8:9862 from hadoop: stopped, remaining connections 0
```

Daemon logs are not changed:

```
$ docker-compose logs scm | head
Attaching to ozone_scm_1
scm_1       | No '-XX:...' jvm parameters are set. Adding safer GC settings '-XX:ParallelGCThreads=8 -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled' to the OZONE_OPTS
scm_1       | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
scm_1       | 2022-10-26 18:56:18,317 [main] INFO server.StorageContainerManagerStarter: STARTUP_MSG: 
scm_1       | /************************************************************
scm_1       | STARTUP_MSG: Starting StorageContainerManager
scm_1       | STARTUP_MSG:   host = 2ab1fd025ab6/172.25.0.2
scm_1       | STARTUP_MSG:   args = [--init]
scm_1       | STARTUP_MSG:   version = 1.3.0-SNAPSHOT
```

Added a couple of assertions in acceptance tests to verify output is empty for happy path CLI executions.

Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3318850256

### CODE REVIEW

**Comment by adoroszlai** [comment]
@ArafatKhan2198

**Comment by sodonnel** [comment]
Just had a quick look at this so far. Does this then remove the log file that the shell log output has traditionally gone into? After this change, log messages are suppressed unless we set the env variable `OZONE_ROOT_LOGGER=INFO,console`?

**Comment by adoroszlai** [comment]
> Does this then remove the log file that the shell log output has traditionally gone into? After this change, log messages are suppressed unless we set the env variable `OZONE_ROOT_LOGGER=INFO,console`?

Yes.

**Comment by sodonnel** [comment]
I tried this out with the OZONE_ROOT_LOGGER setting at various levels and it looks good:

```
bash-4.2$ OZONE_ROOT_LOGGER=DEBUG,console ozone sh volume create /vol1
2022-10-27 11:27:35,434 [main] DEBUG lib.MutableMetricsFactory: field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.getGroups with annotation @org.apache.hadoop.metrics2.annotation.Metric(always=false, sampleName="Ops", valueName="Time", about="", interval=10, type=DEFAULT, value={"GetGroups"})
2022-10-27 11:27:35,437 [main] DEBUG lib.MutableMetricsFactory: field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.loginFailure with annotation @org.apache.hadoop.metrics2.annotation.Metric(always=false, sampleName="Ops", valueName="Time", about="", interval=10, type=DEFAULT, value={"Rate of failed kerberos logins and latency (milliseconds)"})
2022-10-27 11:27:35,437 [main] DEBUG lib.MutableMetricsFactory: field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.loginSuccess with annotation @org.apache.hadoop.metrics2.annotation.Metric(always=false, sampleName="Ops", valueName="Time", about="", interval=10, type=DEFAULT, value={"Rate of successful kerberos logins and latency (milliseconds)"})
2022-10-27 11:27:35,437 [main] DEBUG lib.MutableMetricsFactory: field private org.apache.hadoop.metrics2.lib.MutableGaugeInt org.apache.hadoop.security.UserGroupInformation$UgiMetrics.renewalFailures with annotation @org.apache.hadoop.metrics2.annotation.Metric(always=false, sampleName="Ops", valueName="Time", about="", interval=10, type=DEFAULT, value={"Renewal failures since last successful login"})
2022-10-27 11:27:35,438 [main] DEBUG lib.MutableMetricsFactory: field private org.apache.hadoop.metrics2.lib.MutableGaugeLong org.apache.hadoop.security.UserGroupInformation$UgiMetrics.renewalFailuresTotal with annotation @org.apache.hadoop.metrics2.annotation.Metric(always=false, sampleName="Ops", valueName="Time", about="", interval=10, type=DEFAULT, value={"Renewal failures since startup"})
2022-10-27 11:27:35,438 [main] DEBUG impl.MetricsSystemImpl: UgiMetrics, User and group related metrics
2022-10-27 11:27:35,516 [main] DEBUG util.Shell: setsid exited with exit code 0
...
2022-10-27 11:27:35,901 [main] DEBUG ipc.Client: removing client from cache: Client-cc25afd97c55431b91894353158cbb5e
2022-10-27 11:27:35,901 [main] DEBUG ipc.Client: stopping actual client because no more references remain: Client-cc25afd97c55431b91894353158cbb5e
2022-10-27 11:27:35,901 [main] DEBUG ipc.Client: Stopping client
2022-10-27 11:27:35,902 [IPC Client (1937693946) connection to om/172.30.0.6:9862 from hadoop] DEBUG ipc.Client: IPC Client (1937693946) connection to om/172.30.0.6:9862 from hadoop: closed
2022-10-27 11:27:35,902 [IPC Client (1937693946) connection to om/172.30.0.6:9862 from hadoop] DEBUG ipc.Client: IPC Client (1937693946) connection to om/172.30.0.6:9862 from hadoop: stopped, remaining connections 0
bash-4.2$ OZONE_ROOT_LOGGER=INFO,console ozone sh volume create /vol2 
2022-10-27 11:27:49,551 [main] INFO rpc.RpcClient: Creating Volume: vol2, with hadoop as owner and space quota set to -1 bytes, counts quota set to -1
bash-4.2$ OZONE_ROOT_LOGGER=OFF,console ozone sh volume create /vol2
VOLUME_ALREADY_EXISTS Volume already exists
bash-4.2$ OZONE_ROOT_LOGGER=OFF,console ozone sh volume create /vol3
bash-4.2$
```

**Review by sodonnel — APPROVED** [review]

**Comment by neils-dev** [comment]
Thanks @adoroszlai for this patch for logging in the ozone shell.  I see that we will no longer be logging to ozone-shell.log, resolving potential file permission issues.  With this change logs are suppressed until the user specifies the logging through environment variables.  Is there documentation for the user to know which environment variables to set to enable logging (`OZONE_LOGLEVEL`, `OZONE_ROOT_LOGGER`)?

**Comment by adoroszlai** [comment]
> With this change logs are suppressed until the user specifies the logging through environment variables. Is there documentation for the user to know which environment variables to set to enable logging (`OZONE_LOGLEVEL`, `OZONE_ROOT_LOGGER`)?

Good point @neils-dev, we'll need to add such doc.  But neither was `ozone-shell.log` documented, so the same log that is now suppressed was also not visible to users before. :)

**Comment by neils-dev** [comment]
+1 for patch.

**Comment by neils-dev** [comment]
Thanks @adoroszlai for patch for the improvement.  Thanks @sodonnel for reviewing.

**Comment by adoroszlai** [comment]
Thanks @neils-dev, @sodonnel for the review.

**Pull request merged**
