### PR TITLE
HDDS-5316. Fix datanode reserved space calculation.

### PR DESCRIPTION
**Pull request by guihecheng**
## What changes were proposed in this pull request?

This tries to fix the datanode reserved space calculation, details in the issue description and code comments.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5316

## How was this patch tested?

new UTs.

### CODE REVIEW

**Comment by guihecheng** [comment]
@ChenSammi @bshashikant please help review this, thanks~

**Comment by ChenSammi** [comment]
Thanks @guihecheng for working on this.  The patch LGTM.  Can you please add a unit test for the space calculation?

**Comment by guihecheng** [comment]
@ChenSammi sure, will add more tests, thanks~

**Comment by guihecheng** [comment]
@ChenSammi updated with more tests, thanks~

**Comment by ChenSammi** [comment]
+1.

**Pull request merged**
