### PR TITLE
HDDS-6685. Follower OM crashed when validating S3 auth info.

### PR DESCRIPTION
**Pull request by ChenSammi**
https://issues.apache.org/jira/browse/HDDS-6685

### CODE REVIEW

**Review by nandakumar131 — COMMENTED** [review]
+1, the changes look good.

**Comment by adoroszlai** [comment]
Thanks @ChenSammi for working on this.

Can you please check `TestOzoneManagerPrepare`?  Seems to be failing consistently (also locally).

**Comment by ChenSammi** [comment]
> Thanks @ChenSammi for working on this.
> 
> Can you please check `TestOzoneManagerPrepare`? Seems to be failing consistently (also locally).

TestOzoneManagerPrepare is passed locally on my laptop. I just pushed a new patch. Let's see if   TestOzoneManagerPrepare still fails in CI.

**Comment by ChenSammi** [comment]
Thanks @nandakumar131 and @adoroszlai for the code review.

**Comment by kaijchen** [comment]
Hi @ChenSammi, seems this PR breaks `TestOzoneManagerPrepare#testPrepareDownedOM`, could you please take a look?

* With this change: https://github.com/kaijchen/ozone/actions/runs/2273676445
* Without this change: https://github.com/kaijchen/ozone/actions/runs/2273677044

**Comment by adoroszlai** [comment]
@ChenSammi `TestOzoneManagerPrepare` was flaky before (HDDS-5990), but it is definitely much worse now than previously.

Seems like stop/start logic is not entirely fail-safe, or test needs additional/adjusted `waitFor` checks?

```
2022-05-05 01:41:52,188 [pool-2338-thread-1] ERROR om.OzoneManager (ExitUtils.java:terminate(133)) - Terminating with exit status 1: Failed to start RPC Server.
java.net.BindException: Problem binding to [localhost:41487] java.net.BindException: Address already in use
  ...
  at org.apache.hadoop.ozone.om.OzoneManager.startRpcServer(OzoneManager.java:1084)
  at org.apache.hadoop.ozone.om.OzoneManager.getRpcServer(OzoneManager.java:1054)
  at org.apache.hadoop.ozone.om.OzoneManager.installCheckpoint(OzoneManager.java:3366)
  at org.apache.hadoop.ozone.om.OzoneManager.installCheckpoint(OzoneManager.java:3254)
  at org.apache.hadoop.ozone.om.OzoneManager.installSnapshotFromLeader(OzoneManager.java:3231)
```

https://github.com/adoroszlai/ozone-build-results/tree/master/2022/05/05/14826/it-flaky/hadoop-ozone/integration-test

**Comment by adoroszlai** [comment]
Idea for fixing the bind exception: https://github.com/adoroszlai/hadoop-ozone/commit/65e11fa696640ba683c3e5a2c961355fe2d0870b

Running 10 iterations:
https://github.com/adoroszlai/hadoop-ozone/runs/6302199651

Let's see if it's enough.

**Comment by adoroszlai** [comment]
Yes, it seems bind exception is fixed.  But `testPrepareDownedOM` still times out at `assertClusterNotPrepared`, because the restarted OM does not get the cancel prepare request.  It is stuck installing snapshot.

**Comment by adoroszlai** [comment]
Upgrade to current Ratis 2.3.0-SNAPSHOT (current `master`) with Ratis Thirdparty 1.0.0 (pending release) seems to resolve the problem.

**Comment by adoroszlai** [comment]
HDDS-10177 seems to be caused by this change.

**Pull request merged**
