### PR TITLE
HDDS-7583. Support efficient Snapdiff only until configured Snapshot History

### PR DESCRIPTION
**Pull request by swamirishi**
## What changes were proposed in this pull request?

Adding config to only support Snapshot based on the max number of Snapshot history count

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-7583
## How was this patch tested?
Only Config changes. No unit test cases required

### CODE REVIEW

**Review by prashantpogde — APPROVED** [review]

**Comment by smengcl** [comment]
UT failure is related:

```
Error:  Failures: 
Error:    TestOzoneConfigurationFields>TestConfigurationFieldsBase.testCompareConfigurationClassAgainstXml:493 class org.apache.hadoop.ozone.OzoneConfigKeys class org.apache.hadoop.hdds.scm.ScmConfigKeys class org.apache.hadoop.ozone.om.OMConfigKeys class org.apache.hadoop.hdds.HddsConfigKeys class org.apache.hadoop.hdds.recon.ReconConfigKeys class org.apache.hadoop.ozone.recon.ReconServerConfigKeys class org.apache.hadoop.ozone.s3.S3GatewayConfigKeys class org.apache.hadoop.hdds.scm.server.SCMHTTPServerConfig class org.apache.hadoop.hdds.scm.server.SCMHTTPServerConfig$ConfigStrings class org.apache.hadoop.hdds.scm.ScmConfig$ConfigStrings has 1 variables missing in ozone-default.xml Entries:   ozone.om.snapshot.history.max.count expected:<0> but was:<1>
[INFO] 
Error:  Tests run: 140, Failures: 1, Errors: 0, Skipped: 2
```

https://github.com/apache/ozone/actions/runs/3604533693/jobs/6073987647

Is this new config actually being used anywhere yet?

**Comment by swamirishi** [comment]
> UT failure is related:
> 
> ```
> Error:  Failures: 
> Error:    TestOzoneConfigurationFields>TestConfigurationFieldsBase.testCompareConfigurationClassAgainstXml:493 class org.apache.hadoop.ozone.OzoneConfigKeys class org.apache.hadoop.hdds.scm.ScmConfigKeys class org.apache.hadoop.ozone.om.OMConfigKeys class org.apache.hadoop.hdds.HddsConfigKeys class org.apache.hadoop.hdds.recon.ReconConfigKeys class org.apache.hadoop.ozone.recon.ReconServerConfigKeys class org.apache.hadoop.ozone.s3.S3GatewayConfigKeys class org.apache.hadoop.hdds.scm.server.SCMHTTPServerConfig class org.apache.hadoop.hdds.scm.server.SCMHTTPServerConfig$ConfigStrings class org.apache.hadoop.hdds.scm.ScmConfig$ConfigStrings has 1 variables missing in ozone-default.xml Entries:   ozone.om.snapshot.history.max.count expected:<0> but was:<1>
> [INFO] 
> Error:  Tests run: 140, Failures: 1, Errors: 0, Skipped: 2
> ```
> 
> https://github.com/apache/ozone/actions/runs/3604533693/jobs/6073987647
> 
> Is this new config actually being used anywhere yet?

No

**Comment by smengcl** [comment]
> > UT failure is related:
> > ```
> > Error:  Failures: 
> > Error:    TestOzoneConfigurationFields>TestConfigurationFieldsBase.testCompareConfigurationClassAgainstXml:493 class org.apache.hadoop.ozone.OzoneConfigKeys class org.apache.hadoop.hdds.scm.ScmConfigKeys class org.apache.hadoop.ozone.om.OMConfigKeys class org.apache.hadoop.hdds.HddsConfigKeys class org.apache.hadoop.hdds.recon.ReconConfigKeys class org.apache.hadoop.ozone.recon.ReconServerConfigKeys class org.apache.hadoop.ozone.s3.S3GatewayConfigKeys class org.apache.hadoop.hdds.scm.server.SCMHTTPServerConfig class org.apache.hadoop.hdds.scm.server.SCMHTTPServerConfig$ConfigStrings class org.apache.hadoop.hdds.scm.ScmConfig$ConfigStrings has 1 variables missing in ozone-default.xml Entries:   ozone.om.snapshot.history.max.count expected:<0> but was:<1>
> > [INFO] 
> > Error:  Tests run: 140, Failures: 1, Errors: 0, Skipped: 2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/apache/ozone/actions/runs/3604533693/jobs/6073987647
> > Is this new config actually being used anywhere yet?
> 
> No

Okay. Could you fix the test breakage with an addendum? It is failing on the snapshot feature branch now: https://github.com/apache/ozone/actions/runs/3689651078/jobs/6245836865

**Comment by smengcl** [comment]
I am reverting this commit now that it is failing other patch post-commit CI on the snapshot feature branch:
https://github.com/apache/ozone/actions/runs/3716634979/jobs/6303182818

**Pull request merged**
