### PR TITLE
HDDS-7838. gRPC channel created block input/output stream not shutdown properly

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Fix `Block(Input/Output)Stream` to release the gRPC client on `close` and `unbuffer` to avoid:

```
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=1786, target=127.0.0.1:39499} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at org.apache.ratis.thirdparty.io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	...
	at org.apache.ratis.thirdparty.io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
	at org.apache.hadoop.hdds.scm.XceiverClientGrpc.connectToDatanode(XceiverClientGrpc.java:188)
	at org.apache.hadoop.hdds.scm.XceiverClientGrpc.connect(XceiverClientGrpc.java:158)
	at org.apache.hadoop.hdds.scm.XceiverClientManager$2.call(XceiverClientManager.java:243)
	at org.apache.hadoop.hdds.scm.XceiverClientManager$2.call(XceiverClientManager.java:224)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
  ...
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
	at org.apache.hadoop.hdds.scm.XceiverClientManager.getClient(XceiverClientManager.java:224)
	at org.apache.hadoop.hdds.scm.XceiverClientManager.acquireClient(XceiverClientManager.java:168)
	at org.apache.hadoop.hdds.scm.XceiverClientManager.acquireClientForReadData(XceiverClientManager.java:157)
	at org.apache.hadoop.hdds.scm.storage.BlockInputStream.acquireClient(BlockInputStream.java:261)
	...
	at org.apache.hadoop.ozone.client.io.OzoneInputStream.read(OzoneInputStream.java:56)
```

and similar reports.

`TestOzoneRpcClientWithRatis` also had unclosed streams in the test itself, fixed those, too.

https://issues.apache.org/jira/browse/HDDS-7838

## How was this patch tested?

Ran `TestStorageContainerManagerHA`, `TestFailureHandlingByClient` which tend to have such errors in their output (even if the tests are passing).  Verified no `ManagedChannel` problem reported related to `BlockInputStream`/`BlockOutputStream`.

Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4018918379
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4019832659

### CODE REVIEW

**Comment by jojochuang** [comment]
Nice fix. I've seen this error on some of the nodes in our clusters.

**Review by jojochuang — APPROVED** [review]
Looks correct to me.

**Comment by neils-dev** [comment]
I see some branch conflicts here now.  May be due to the recent feature branch merge.

**Comment by adoroszlai** [comment]
> I see some branch conflicts here now. May be due to the recent feature branch merge.

Thanks @neils-dev for the notification, I have resolved the conflict.  `BlockOutputStream` was recently changed for HSync support.  @jojochuang might also want to take another look at that class.

**Review by jojochuang — APPROVED** [review]
Merging it

**Comment by adoroszlai** [comment]
Thanks @jojochuang for reviewing and committing it.

**Pull request merged**
