### PR TITLE
HDDS-9335. OMKeyDeleteRequest using the wrong bucket layout

### PR DESCRIPTION
**Pull request by guohao-rosicky**
## What changes were proposed in this pull request?

OMKeyDeleteRequest using the wrong bucket layout

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-9335

## How was this patch tested?

existing UT

### CODE REVIEW

**Comment by sodonnel** [comment]
Looks correct to me, but I'll also let someone who knows more about OM comment.

**Review by hemantk-12 — COMMENTED** [review]
Change looks good to me.

In testing, you said existing unit tests. I'm curios how it was not captured by existing unit/integration tests. Are we missing tests for it? If yes, please add the relevant tests.

**Review by sumitagrawl — APPROVED** [review]
@guohao-rosicky Thanks for working over this,
bucketLayout used here is only to get respective Table: fileTable or keyTable (based on bucket type), so using DEFAULT or OBS (as provided in constructor) does not have any impact to functionality.

To avoid confusion from code perspective, this changes seems good.

Additionally, IMO, we can remove method with passing bucketLayout and merge both, as below is used only in UT cases and getBucketLayout() itself can be used with no impact.

**Comment by guohao-rosicky** [comment]
> we can remove method with passing bucketLayout and merge both
 
Thanks  @sodonnel @ivandika3 @hemantk-12 @sumitagrawl  for the review, I think it's a good idea. I'll modify it.

**Comment by sumitagrawl** [comment]
@guohao-rosicky Plz fix UT cases as impact of changes

**Comment by guohao-rosicky** [comment]
> @guohao-rosicky Plz fix UT cases as impact of changes

Thanks for the revew @sumitagrawl, PTAL.
All ci passed, see: https://github.com/guohao-rosicky/ozone/actions/runs/6438542195

**Review by sumitagrawl — APPROVED** [review]
@guohao-rosicky LGTM +1

**Pull request merged**
