### PR TITLE
HDDS-11030. Do not throw OperatorCreationException from CertificateApprover#sign

### PR DESCRIPTION
**Pull request by fapifta**
## What changes were proposed in this pull request?
The CertificateApprover interface is using OperatorCreationException from BouncyCastle as a signed exception thrown from DefaultApprover#sign method. In order to clean this BouncyCastle class from the generic interface, I removed it from the checked exceptions on the interface, and wrapped it into a generic CertificateException at DefaultApprover.

This is part of the effort to shrink down direct BouncyCastle dependencies to the minimum before moving things to the crypto modules.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-11030

## How was this patch tested?
This is a fairly simple change, we do not have tests testing for this particular exception to be thrown though. I am reluctant to create one as of now, as this code has to be moved around, and we are planning to review the tests when the actual move is done.

### CODE REVIEW

**Review by Galsza — APPROVED** [review]
@fapifta thank you for this change, looking good to me

**Review by dombizita — APPROVED** [review]
Thanks for the patch @fapifta, looks good to me! Please resolve merge conflicts!

**Comment by fapifta** [comment]
Thank you for the review @dombizita pending CI on conflict resolution.

**Comment by dombizita** [comment]
Thanks for working on this @fapifta! Thanks for the review @Galsza!

**Comment by fapifta** [comment]
Thank you for the reviews and merging!

**Pull request merged**
