### PR TITLE
HDDS-5302. CleanUp V1 Code of DeletedBlockLogImpl

### PR DESCRIPTION
**Pull request by Xushaohong**
## What changes were proposed in this pull request?

The original V1 code has been replaced by the V2 code for a long while.
To better understand the code and less misleading information, the code of the raw version should be cleaned up.

I've spent some time checking all the implemented methods in the V1 code and comparing them to the V2 one by one. Luckily the code quality of V2 is good enough that it has covered all places where the V1 code used to work.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5302

## How was this patch tested?
CI

### CODE REVIEW

**Review by smengcl — APPROVED** [review]
lgtm

**Review by JacksonYao287 — APPROVED** [review]
thanks @Xushaohong for this work, the changes looks good to me. since we have removed ` DeletedBlockLogImpl` now, maybe we can rename `DeletedBlockLogImplV2` to `DeletedBlockLogImpl`.

**Comment by Xushaohong** [comment]
> thanks @Xushaohong for this work, the changes looks good to me. since we have removed ` DeletedBlockLogImpl` now, maybe we can rename `DeletedBlockLogImplV2` to `DeletedBlockLogImpl`.

yep, I think the renaming of `DeletedBlockLogImplV2` needs more vote

**Comment by bshashikant** [comment]
> > thanks @Xushaohong for this work, the changes looks good to me. since we have removed ` DeletedBlockLogImpl` now, maybe we can rename `DeletedBlockLogImplV2` to `DeletedBlockLogImpl`.
> 
> yep, I think the renaming of `DeletedBlockLogImplV2` needs more vote

Let's go ahead with Rename.

**Comment by Xushaohong** [comment]
> > > thanks @Xushaohong for this work, the changes looks good to me. since we have removed ` DeletedBlockLogImpl` now, maybe we can rename `DeletedBlockLogImplV2` to `DeletedBlockLogImpl`.
> > 
> > 
> > yep, I think the renaming of `DeletedBlockLogImplV2` needs more vote
> 
> Let's go ahead with Rename.

@bshashikant Done with renaming . Pls, take a look.

**Review by bshashikant — APPROVED** [review]

**Pull request merged**
