### PR TITLE
HDDS-10934. Refactor TestOzoneRpcClient hierarchy

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Refactor `TestOzoneRpcClientAbstract` and its subclasses:

1. `TestOzoneRpcClient` and `TestOzoneRpcClientWithRatis` are subclasses of `TestOzoneRpcClientAbstract.`  They used to execute the same test cases with OM Ratis disabled (relying on default setting) and enabled (explicitly), respectively.  HDDS-4498 enabled OM Ratis by default, so now both classes test with OM Ratis enabled.  This change disables OM Ratis for `TestOzoneRpcClient`, and fixes one test case that was failing with NPE in this setup.
2. `TestSecureOzoneRpcClient` should directly extend `TestOzoneRpcClientAbstract` to avoid confusion caused by shadowed lifecycle methods.
3. Allow passing `MiniOzoneCluster.Builder` to `startCluster` to avoid code duplication in `TestSecureOzoneRpcClient`.
4. Rename `TestOzoneRpcClientAbstract` to `OzoneRpcClientTests` to follow naming conventions.
5. Move test cases from `TestOzoneRpcClientWithRatis` to the base class to extend coverage for other configs.

(Items 2-5 were added after initial round of review.)

https://issues.apache.org/jira/browse/HDDS-10934

## How was this patch tested?

CI:
https://github.com/adoroszlai/ozone/actions/runs/9282222672/job/25540423674#step:5:2276

### CODE REVIEW

**Review by errose28 — COMMENTED** [review]
Overall fix makes sense. There's some other weird stuff in this area, not sure if we want to handle it in this PR or a follow up:
- The tests run for both ratis and non-ratis cases (in `TestOzoneRpcClientAbstract`) and those run only for Ratis cases (in `TestOzoneRpcClientWithRatis`) seem kind of arbitrary.
  - Maybe we can either unify them so all tests run in both setups, or only a minimal amount of validation is done in the non-ratis setup.
- `TestSecureOzoneRpcClient` extends `TestOzoneRpcClient`, so now the secure tests are only running in a non-ratis OM setup.
  - Also tests that are unique to `TestOzoneRpcClientWithRatis` are not run in a secure setup.

**Comment by adoroszlai** [comment]
Thanks @errose28 for the review.

> * The tests run for both ratis and non-ratis cases (in `TestOzoneRpcClientAbstract`) and those run only for Ratis cases (in `TestOzoneRpcClientWithRatis`) seem kind of arbitrary.
>   
>   * Maybe we can either unify them so all tests run in both setups, or only a minimal amount of validation is done in the non-ratis setup.
>   * Also tests that are unique to `TestOzoneRpcClientWithRatis` are not run in a secure setup.

Agree, we should move them to the parent class.

> * `TestSecureOzoneRpcClient` extends `TestOzoneRpcClient`, so now the secure tests are only running in a non-ratis OM setup.

This is not the case, since `TestSecureOzoneRpcClient` creates its own cluster, `TestOzoneRpcClient#init` is not invoked due to "shadowing" (which is a bit obscure).  Otherwise it would be testing an unsecure setup or starting two clusters.  This should be improved, too.

Will push a few more commits.

**Comment by adoroszlai** [comment]
@errose28 patch is updated, please take another look

**Review by errose28 — APPROVED** [review]
Thanks for doing the refactoring @adoroszlai. LGTM

**Comment by adoroszlai** [comment]
Thanks @errose28 for the review.

**Pull request merged**
