### PR TITLE
HDDS-10574. Improve TestObjectPut

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Improve `TestObjectPut`:

* reduce code duplication
* avoid unnecessary mocking

This is in preparation for HDDS-10570.

https://issues.apache.org/jira/browse/HDDS-10574

## How was this patch tested?

CI:
https://github.com/adoroszlai/ozone/actions/runs/8401371232

### CODE REVIEW

**Comment by adoroszlai** [comment]
Can someone please review?  The goal of this change is to prepare this unit test for an upcoming bugfix (reducing change in the patch for the real fix).

**Comment by adoroszlai** [comment]
@ivandika3 please take a look

**Comment by adoroszlai** [comment]
Thanks @ivandika3 for the review, your PR is merged and this one is updated.

@duongkame can you please also review?

**Review by hemantk-12 — APPROVED** [review]
Thanks, @adoroszlai  for the cleanup.

Overall change looks good to me.

**Comment by adoroszlai** [comment]
Thanks @hemantk-12, @ivandika3 for the review.

**Pull request merged**
