### PR TITLE
HDDS-6817. Bump rocksdbjni to 7.2.2

### PR DESCRIPTION
**Pull request by smengcl**
## What changes were proposed in this pull request?

There are a bunch of bug fixes since 7.0.4, see https://github.com/facebook/rocksdb/releases

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-6817

## How was this patch tested?

- Existing tests should pass.

### CODE REVIEW

**Comment by kerneltime** [comment]
LGTM if tests pass. We don't have any other gate keeping for now.

**Review by ayushtkn — APPROVED** [review]
LGTM

**Review by JacksonYao287 — APPROVED** [review]
LGTM +1!

**Comment by JacksonYao287** [comment]
thanks @smengcl for the patch and @kerneltime @ayushtkn for the review , i have committed this patch to master branch

**Comment by smengcl** [comment]
Thanks @kerneltime @ayushtkn @JacksonYao287 for reviewing this.

**Pull request merged**
