### PR TITLE
HDDS-10122. GSON requires tweaks for Java 17.

### PR DESCRIPTION
**Pull request by ArafatKhan2198**
## What changes were proposed in this pull request?
This issue is related to the use of GSON in the codebase and its compatibility with Java 17. The proposed solution is to replace GSON with Jackson to reduce dependencies.

### Affected Modules:
The replacement of GSON with Jackson is considered for several modules in the project, including:

- `KeyValueContainerMetadataInspector` and `TestKeyValueContainerMetadataInspector` in the `hadoop-hdds/container-service` module.
- `HddsConfServlet` and `EventQueue` in the `hadoop-hdds/framework` module, along with its corresponding tests.
- Several classes in `hadoop-ozone/common`, especially related to multitenancy and access policies `AccessPolicy` 
 & `RangerAccessPolicy`.
- Multiple integration tests and tools within the `hadoop-ozone` module, such as `TestReconWithOzoneManager`, `TestOzoneShellHA`, and various classes in the tools sub-module related to Ozone Shell, tenant management, and debug tools.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-10122?filter=-1

## How was this patch tested?

Currently Draft State will be adding more classes into it.

### CODE REVIEW

**Comment by adoroszlai** [comment]
@ArafatKhan2198 please check test failures

**Comment by adoroszlai** [comment]
Thanks @ArafatKhan2198 for continuing work on this.  There are still some test failures.

**Comment by ArafatKhan2198** [comment]
The forked CI passed successfully :- https://github.com/ArafatKhan2198/ozone/actions/runs/8308711361

**Comment by ArafatKhan2198** [comment]
@adoroszlai Could you please take a look

**Review by adoroszlai — COMMENTED** [review]
Thanks @ArafatKhan2198 for the patch.

To make the change more manageable, I suggest splitting it to separate patches:

1. `ozone tenant`
2. `ozone admin namespace`
3. `ozone debug`
4. rest of the change, including `EventQueue` (still has GSON), and removal of `gson` as a dependency

Created HDDS-10538 with sub-tasks for this purpose.

(Please see few inline comments, too.)

**Pull request closed without merging**
