### PR TITLE
HDDS-5702. SCM remote benchmark tool.

### PR DESCRIPTION
**Pull request by guihecheng**
## What changes were proposed in this pull request?

SCM remote benchmark tool for throughput
3 kinds of test for now:
- allocate block
- allocate container
- process reports

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5702

## How was this patch tested?

manual test.

### CODE REVIEW

**Comment by guihecheng** [comment]
@ChenSammi @bshashikant please help review this thanks~

**Comment by bshashikant** [comment]
@guihecheng , can you look at the test failures? I will be reviewing this in the meanwhile.
Thanks.

**Comment by guihecheng** [comment]
@bshashikant thanks, this test is just a sub command to freon and do not touch the integration test, the test failure looks related to scm-ha and should be unrelated.

**Comment by bshashikant** [comment]
@nandakumar131 , can you help reviewing this?

**Comment by bshashikant** [comment]
@guihecheng , can you retrigger the CI?

**Comment by guihecheng** [comment]
@bshashikant sure, ci retriggered, let's see the results.
This commit simply adds a benchmark class, so if the CI fails again, maybe I should do a merge master to fix it.

**Comment by bshashikant** [comment]
Thanks @guihecheng for the work.

**Pull request merged**
