### PR TITLE
HDDS-8353. Intermittent failure in TestBlockDeletion#testContainerStatisticsAfterDelete

### PR DESCRIPTION
**Pull request by devmadhuu**
## What changes were proposed in this pull request?

This PR fixes the timeout issues in `TestBlockDeletion#testContainerStatisticsAfterDelete` test case. This was intermittently timed out due to explicit CLOSE of containers in one of the DNs in cluster in test case code. If DN turns out to be LEADER, then ratis submission of request for CLOSE of containers in followers will never through and other 2 DNs will have containers always be in OPEN state, due to which block deletion were never triggered for other 2 DNs and were executed only on LEADER DN, so the reason after a period of time, test was getting timed out.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8353

## How was this patch tested?

This patch was tested using multiple CI runs of test case including all test of whole `TestBlockDeletion` test class. Here is the green [CI link](https://github.com/devmadhuu/ozone/actions/runs/6393240738) in forked branch.

### CODE REVIEW

**Comment by devmadhuu** [comment]
@adoroszlai @ArafatKhan2198 pls review.

**Review by ayushtkn — COMMENTED** [review]
> If DN turns out to be LEADER, then ratis submission of request for CLOSE of containers in followers will never through and other 2 DNs will have containers always be in OPEN state, due to which block deletion were never triggered for other 2 DNs and were executed only on LEADER DN, so the reason after a period of time, test was getting timed out.

2 Questions:

- Why don't we check for the leader, if it is the leader node, stop another node? maybe something like in ``TestContainerStateMachineFailureOnRead#testReadStateMachineFailureClosesPipeline`` or if there is any other way to figure that out
- If that was the only reason, why we need to increase the timeout now from 5k to 20k?

**Comment by devmadhuu** [comment]
> * testReadStateMachineFailureClosesPipeline

@ayushtkn Thanks for the review. Sorry I didn't get your point why we would like Follower to shutdown. Its a 3 DN cluster and we want to test if blocks are getting deleted and space is getting reclaimed after blocks getting deleted on all 3 DNs. So test is fine, but explicit closing of container on one DN without knowing whether its leader or follower doesn't make sense, so I removed it because we shouldn't change the state machine explicitly from test just to make it work and this was creating problem.

And we have increased time out because if you see , it takes slightly more time to reclaim the space due to various time related configs of various other background services in cluster. I also observed that other tests in the same test class are using 30 secs of wait.
Kindly let me know your thoughts.

**Review by sumitagrawl — APPROVED** [review]
@devmadhuu Thanks for working over this, LGTM
Due to explicit setting of container state close, this is impacting closing of container on followers and further impact delete of blocks in all DNs.

**Comment by sumitagrawl** [comment]
> > If DN turns out to be LEADER, then ratis submission of request for CLOSE of containers in followers will never through and other 2 DNs will have containers always be in OPEN state, due to which block deletion were never triggered for other 2 DNs and were executed only on LEADER DN, so the reason after a period of time, test was getting timed out.
> 
> 2 Questions:
> 
> * Why don't we check for the leader, if it is the leader node, stop another node? maybe something like in `TestContainerStateMachineFailureOnRead#testReadStateMachineFailureClosesPipeline` or if there is any other way to figure that out
> * If that was the only reason, why we need to increase the timeout now from 5k to 20k?

@ayushtkn Problem here is, there is explicit setting of memory container state in DN to close. So other follower state remains open. So if leader already having closed state, it will not close container on other followers.
This further impact avoiding the delete blocks. So Explicit set of memory state must be avoided in HA in one of node.

Related in increase in time, its just to give extra time for sync as there is possibility of delay in sync, but check frequency is 500 milli sec. (In test case, HB time is 200 milli sec which can add overload to DN).

**Comment by ayushtkn** [comment]
Makes sense. I am not sure why the test was previously doing that.

> one DN without knowing whether its leader or follower doesn't make sense

So, I thought ``cluster.getHddsDatanodes().get(0)`` this explicit ``get(0)`` was creating a problem, that we chose without knowiing whether it is a leader or a follower, so thought rather than ``get(0)``, we should check if isLeader(dn0) : choose dn1 instead else dn0. 

Anyway thanks for the clarifications, can proceed with the commit, no objections from my side

**Review by ArafatKhan2198 — APPROVED** [review]
Thanks for the find @devmadhuu 
LGTM +1

**Comment by adoroszlai** [comment]
Thanks @devmadhuu for the fix, @ArafatKhan2198, @ayushtkn, @sumitagrawl for the review.

**Pull request merged**
