### PR TITLE
HDDS-11794. Display HostName in OM / SCM Overview.

### PR DESCRIPTION
**Pull request by slfan1989**
## What changes were proposed in this pull request?

We implemented the display of the DN HostName information on the DN page in [HDDS-11462](https://issues.apache.org/jira/browse/HDDS-11462) #7206 . I think we should display similar information in OM and SCM as well. This is a small change.

## What is the link to the Apache JIRA

HDDS-11794. Display HostName in OM / SCM Overview. 

> OM

image

> SCM 

image

## How was this patch tested?

Manual test.

### CODE REVIEW

**Comment by slfan1989** [comment]
@ivandika3 Could you help review this PR? Thank you very much!

**Review by ivandika3 — APPROVED** [review]
@slfan1989 Thanks for the patch. LGTM +1.

One question, since [HDDS-11462](https://issues.apache.org/jira/browse/HDDS-11462) https://github.com/apache/ozone/pull/7206) updated the `overview.html` template to get the host name, before this patch, the OM and SCM overview html only have empty hostname?

**Comment by slfan1989** [comment]
> @slfan1989 Thanks for the patch. LGTM +1.
> 
> One question, since [HDDS-11462](https://issues.apache.org/jira/browse/HDDS-11462) #7206) updated the `overview.html` template to get the host name, before this patch, the OM and SCM overview html only have empty hostname?

@ivandika3  Thank you very much for reviewing this PR! Before this PR, OM and SCM did not display the hostname information, which was consistent with the previous behavior. We have added a check to ensure that the related information is only displayed if the `hostName` exists.

https://github.com/apache/ozone/blob/69538b0b85f495f0a51c120b379f052a3c838e14/hadoop-hdds/framework/src/main/resources/webapps/static/templates/overview.html#L17

**Comment by ivandika3** [comment]
@slfan1989 Ok thanks for the info.

**Comment by ivandika3** [comment]
@slfan1989 Thanks for the patch.

**Comment by slfan1989** [comment]
> @slfan1989 Thanks for the patch.

@ivandika3 Thank you very much for reviewing the code!

**Pull request merged**
