### PR TITLE
[DO NOT MERGE] Backport some fixes, performance optimizations from master to ozone-1.4 #6929

### PR DESCRIPTION
**Pull request by xichen01**
## What changes were proposed in this pull request?
Backport the following fixes from master to ozone-1.4 for 1.4.1. Includes Ratis upgrade, some bug fixes, as well as performance optimizations, and necessary dependencies.

HDDS-11186. First container log missing from bundle (#6952)
HDDS-11172. Bump vite to 4.5.3 (#6918)
HDDS-11104. Bump maven-dependency-plugin to 3.7.1 (#6903)
HDDS-10910. Bump Ratis to 3.1.0 (#6872)
HDDS-10983. EC Key read corruption when the replica index of container in DN mismatches (#6779)
HDDS-11013. Ensure version is always set in ContainerCommandRequestProto (#6812)
HDDS-10999. Remove dependency on ratis-server from Ozone Client (#6800)
HDDS-10924. TestSCMHAManagerImpl#testAddSCM fails on ratis master (#6753)
HDDS-10832. Client should switch to streaming based on OpenKeySession replication (#6683)
HDDS-10875. XceiverRatisServer#getRaftPeersInPipeline should be called before XceiverRatisServer#removeGroup (#6696)
HDDS-10371. NPE in OzoneAclUtils.isOwner (#6676)
HDDS-10781. Do not use OFSPath in O3FS BasicOzoneClientAdapterImpl (#6614)
HDDS-10696. Fix test failure caused by empty snapshot installation (#6659)
HDDS-10608. Recon can't get full key when using Recon API. (#6492)
HDDS-10834. Revert snapshot diff output change added in HDDS-9360 (#6660)
HDDS-10815. Bump Spring Framework to 5.3.34 (#6643)
HDDS-10803. HttpServer fails to start with wildcard principal (#6631)
HDDS-10806. Bump Bouncy Castle to 1.78.1 (#6632)
HDDS-10787. Updated rocksdb-checkpoint-differ to use managed RocksDB objects (#6625)
HDDS-10720. Datanode volume DU reserved percent should have a non-zero default value. (#6561)
HDDS-10792. Bump Netty to 4.1.109.Final (#6622)
HDDS-10784. Multipart upload to encrypted bucket fails with ClassCastException (#6618)
HDDS-10783. Close SstFileReaderIterator in RocksDBCheckpointDiffer (#6616)
HDDS-10614. Avoid decreasing cached space usage below zero (#6508)
HDDS-10652. EC Reconstruction fails with "IOException: None of the block data have checksum" after upgrade (#6520)
HDDS-10156. Optimize Snapshot Cache get and eviction (#6024)
HDDS-10452. Improve Recon Disk Usage to fetch and display Top N records based on size. (#6318)
HDDS-10206. Expose jmx metrics for snapshot cache size on the ozone manager. (#6138)
HDDS-9534. Support namespace summaries (du, dist & counts) for LEGACY buckets with file system disabled (#5517)
HDDS-5865. Make read retry interval and attempts in BlockInputStream configurable (#6408)
HDDS-10505. Move space reservation logic to VolumeUsage (#6370)
HDDS-10504. Remove unused VolumeInfo#configuredCapacity (#6363)
HDDS-7810. Support namespace summaries (du, dist & counts) for OBJECT_STORE buckets. (#4245)
HDDS-10250. Use SnapshotId as key in SnapshotCache (#6139)
HDDS-10262. Encapsulate SnapshotCache inside OmSnapshotManager (#6135)
HDDS-10246. Remove KeyValueHandler.checkContainerIsHealthy to improve read performance (#6127)
HDDS-10029. Improved logs for SCMDeletedBlockTransactionStatusManager (#5888)
HDDS-10225. Speed up TestSCMHAManagerImpl. (#6109)
HDDS-10219. Bump frontend-maven-plugin to 1.15.0 (#6104)
HDDS-10178. Shaded Jar build failure in case-insensitive filesystem (#6045)
HDDS-8888. Consider Datanode queue capacity when sending DeleteBlocks command (#4939)
HDDS-10070. Intermittent failure in TestWritableRatisContainerProvider (#5930)
HDDS-8982. Log flooded by WritableRatisContainerProvider if pipeline's nodes are not found (#5911)
HDDS-10046. Replace PrecomputedVolumeSpace with SpaceUsageSource.Fixed (#5904)
HDDS-9883. Recon - Improve the performance of processing IncrementalContainerReport from DN (#5793)
HDDS-9959. Propagate group remove to other datanodes during pipeline close (#5827)
HDDS-10007. Rename ManagedSstFileReader in rocksdb-checkpoint-differ (#5859)
HDDS-10027. NPE in VolumeInfoMetrics.getCommitted() (#5885)
HDDS-9922. Migrate TestOzoneFileInterfaces to JUnit5 (#5838)
HDDS-9807. Consider volume committed space when checking if datanode can host new container (#5721)
HDDS-9966. Bump maven-shade-plugin to 3.5.1 (#5823)
HDDS-6152. Migrate TestOzoneFileSystem to JUnit5 (#5795)
HDDS-8882. Manage status of DeleteBlocksCommand in SCM to avoid sending duplicates to Datanode (#4988)

## How was this patch tested?

https://github.com/xichen01/ozone/actions/runs/9990984927

### CODE REVIEW

**Comment by xichen01** [comment]
@adoroszlai @vtutrinov @ivandika3 @devmadhuu @whbing @Cyrill @hemantk-12 @ArafatKhan2198 @SaketaChalamchala @ceekay47 @swamirishi @siddhantsangwan @rohit-kb @errose28 @chungen0126 please check that your commits are correctly cherry-picked

**Review by adoroszlai — APPROVED** [review]
Thanks @xichen01 for working on this.  Backport of my commits look OK.

**Review by ivandika3 — APPROVED** [review]
@xichen01 Thanks for the backports. LGTM for my patches.

**Comment by devmadhuu** [comment]
Thanks @xichen01 for working on this. Backport of my commits look OK.

**Review by ArafatKhan2198 — APPROVED** [review]
Thanks @xichen01 for working on this. BackPort of my commits look good.

**Comment by hemantk-12** [comment]
Thanks @xichen01 for the patch. Backport of my changes look good.

**Comment by rohit-kb** [comment]
Thanks for the backport. Mine are good too

**Comment by xichen01** [comment]
Thank you for the reviews @adoroszlai and @ivandika3 @devmadhuu @ArafatKhan2198 @hemantk-12 @rohit-kb

Merged using:
```bash
git checkout ozone-1.4
git pull
git merge --ff-only ozone-1.4-backport
git push
```

**Pull request merged**
