### PR TITLE
HDDS-7194. EC: Enable balancer for EC containers.

### PR DESCRIPTION
**Pull request by hemantk-12**
## What changes were proposed in this pull request?

Currently balancer is disabled for EC containers. This change is to enable the balancer for EC containers by removing the excluding EC container check in `ContainerBalancerSelectionCriteria`.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-7194

## How was this patch tested?
Existing unit tests.

### CODE REVIEW

**Review by DaveTeng0 — COMMENTED** [review]
looks good~

**Review by JacksonYao287 — COMMENTED** [review]
we do not support balancing EC container for now. all the balance related logic at scm side is in legacyReplicationManager, but all the EC container will be handled by ReplicatonManager , not legacyReplicationManager. so it will take no effect for EC container , please see the code here

https://github.com/apache/ozone/blob/30d1a4e359de6cf5d1393a2a922a1a04f5ff6a52/hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java#L316

we can do this after we refactor `move` related code in LegacyRM, this is one task of refactoring the whole replcationManager , and will be done soon later!

**Review by siddhantsangwan — COMMENTED** [review]
I agree with @JacksonYao287. We are excluding EC containers in balancer until there's support for move in RM.

**Comment by umamaheswararao** [comment]
Thanks @JacksonYao287 and @siddhantsangwan for the review! I have not followed the balancer code much, is the balancer code clean to move to new RM? Then let's repurpose this JIRA. As per request, this has been assigned as newbie JIRA to @hemantk-12 . If of you would like to take up the refactoring, please feel free to take up. Thanks

**Comment by siddhantsangwan** [comment]
@JacksonYao287 has taken up the refactoring task - https://issues.apache.org/jira/browse/HDDS-6572

**Comment by sodonnel** [comment]
Closing this, as there is a wider design effort required to enable the balancer for EC.

**Pull request closed without merging**
