### PR TITLE
HDDS-8470. Intermittent failure in TestStorageContainerManager#testContainerReportQueueTakingMoreTime.

### PR DESCRIPTION
**Pull request by devmadhuu**
This PR fixes the Intermittent failure in TestStorageContainerManager#testContainerReportQueueTakingMoreTime. Intermittent failure was detected in below assertion:
Assert.assertTrue(containerReportExecutors.longWaitInQueueEvents() >= 1);

This assertion statement asserts that number of container reports, waiting in event queue more than queueWaitThreshold is greater than 1. This metric of longWaitInQueue is incremented if report is waiting in event queue longer than wait threshold value of 1s set by test case. Due to timing issue, assertion use to fail intermittently and this PR fixes that with usage of semaphore. This PR also improves the test case by reducing the time needed to finish the test case.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-8470

## How was this patch tested?
This patch is tested by running all test cases of TestStorageContainerManager in repeated CI flakytest workflow by running 500 iterations. Here is the green CI [link](https://github.com/devmadhuu/ozone/actions/runs/7244420268/job/19775989967) for the same. Flaky Workflow CI run passes for TestStorageContainerManager#testContainerReportQueueTakingMoreTime, failures are related to timeout for TestStorageContainerManager#testBlockDeletionTransactions for which we already have [HDDS-8492](https://issues.apache.org/jira/browse/HDDS-8492)

### CODE REVIEW

**Comment by devmadhuu** [comment]
@adoroszlai @sumitagrawl Pls review.

**Comment by adoroszlai** [comment]
Thanks @devmadhuu for working on this.  Repeated run has some failures of `testContainerReportQueueTakingMoreTime`:

https://github.com/devmadhuu/ozone/actions/runs/7244420268/job/19771465893#step:5:8526
https://github.com/devmadhuu/ozone/actions/runs/7244420268/job/19771465993#step:5:6078
https://github.com/devmadhuu/ozone/actions/runs/7244420268/job/19771465993#step:5:6742
https://github.com/devmadhuu/ozone/actions/runs/7244420268/job/19771466100#step:5:4446

**Comment by devmadhuu** [comment]
> Thanks @devmadhuu for working on this. Repeated run has some failures of `testContainerReportQueueTakingMoreTime`:
> 
> https://github.com/devmadhuu/ozone/actions/runs/7244420268/job/19771465893#step:5:8526 https://github.com/devmadhuu/ozone/actions/runs/7244420268/job/19771465993#step:5:6078 https://github.com/devmadhuu/ozone/actions/runs/7244420268/job/19771465993#step:5:6742 https://github.com/devmadhuu/ozone/actions/runs/7244420268/job/19771466100#step:5:4446

Ok Attila, ideally should not have happened, Have re-run after reducing threshold.

**Comment by devmadhuu** [comment]
> > Thanks @devmadhuu for working on this. Repeated run has some failures of `testContainerReportQueueTakingMoreTime`:
> > https://github.com/devmadhuu/ozone/actions/runs/7244420268/job/19771465893#step:5:8526 https://github.com/devmadhuu/ozone/actions/runs/7244420268/job/19771465993#step:5:6078 https://github.com/devmadhuu/ozone/actions/runs/7244420268/job/19771465993#step:5:6742 https://github.com/devmadhuu/ozone/actions/runs/7244420268/job/19771466100#step:5:4446
> 
> Ok Attila, ideally should not have happened, Have re-run after reducing threshold.

After reducing threshold, I don't see failures related to `testContainerReportQueueTakingMoreTime` test case here 
https://github.com/devmadhuu/ozone/actions/runs/7284095962

**Review by adoroszlai — APPROVED** [review]

**Comment by adoroszlai** [comment]
Thanks @devmadhuu for the patch.

**Pull request merged**
