### PR TITLE
HDDS-4560: Add ReadWriteLock into PipelineStateManagerV2Impl to protect contentions between RaftServer and PipelineManager

### PR DESCRIPTION
**Pull request by GlenGeng**
## What changes were proposed in this pull request?

Add ReadWriteLock into PipelineStateManagerV2Impl to protect contentions between RaftServer and PipelineManager.

If current leader SCM (as leader of term N) steps down while there are on-going transactions, there might be read/write contentions that new leader SCM (as leader of term N+1) has replicated some raft log entries encapsulating method addPipeline()/removePipeline()/updatePipelineState() to the underlying RaftServer that are being applied by StateMachineUpdater, and at the same time PipelineManager is calling getPipelines().

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4560

## How was this patch tested?

CI

### CODE REVIEW

**Comment by GlenGeng** [comment]
@ChenSammi @nandakumar131 @runzhiwang  Please take a look! Thanks.

**Comment by runzhiwang** [comment]
without this patch, what will happen ? exception threw ?

**Comment by GlenGeng** [comment]
Yes, since there is no concurrency control.

**Comment by runzhiwang** [comment]
@GlenGeng  Is it possible to make all the data structure thread safe ?

**Comment by GlenGeng** [comment]
> s it possible to make all the data structure thread safe ?

The key point here is synchronize the access to underlying container/pipeline state to ensure the causality, which will be broken by the thread safe data structure..

**Review by nandakumar131 — APPROVED** [review]

**Pull request merged**
