### PR TITLE
HDDS-4748. sonarqube issue fix - "static" members should be accessed statically

### PR DESCRIPTION
**Pull request by mookkiah**
JIRA: https://issues.apache.org/jira/browse/HDDS-4748

Signed-off-by: Mahendran Mookkiah <mahendran.mookkiah@gmail.com>

## What changes were proposed in this pull request?

SonarQube issue -  https://sonarcloud.io/project/issues?id=hadoop-ozone&issues=AW5md-cWKcVY8lQ4Zr22&open=AW5md-cWKcVY8lQ4Zr22

## What is the link to the Apache JIRA

No JIRA ticket - code improvement contribution

Please replace this section with the link to the Apache JIRA)

## How was this patch tested?

Ran the below command which resulted into success
`mvn -T4 clean install`

### CODE REVIEW

**Comment by mookkiah** [comment]
Build failed because of timeout which is nothing to do with this PR

Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test (default-test) on project hadoop-ozone-integration-test: There was a timeout or other error in the fork -> [Help 1]

**Review by ayushtkn — APPROVED** [review]
LGTM

**Review by xiaoyuyao — APPROVED** [review]
LGTM, +1.

**Comment by ayushtkn** [comment]
Are we checking in without jira id as well? Well creating a jira wouldn't hurt though...

**Comment by elek** [comment]
> Are we checking in without jira id as well? Well creating a jira wouldn't hurt though...

I am fine with merge trivial patches with patches, seems to be an unnecessary overhead for me for small contributions.

But to remain on the safe side I created one Jira (in my Ozone development CLI tool I have a subcommand to create issues for PRS: https://github.com/elek/ogh `ogh jira open 1748`. Not perfect (yet), but I am planning to improve...)

**Comment by elek** [comment]
Merging it. Thanks the patch @mookkiah and the review @xiaoyuyao @ayushtkn

**Pull request merged**
