### PR TITLE
HDDS-4130:  remove the left part of the 1st edition of RatisServer of…

### PR DESCRIPTION
**Pull request by GlenGeng**
… SCM HA which is copied from OM HA

## What changes were proposed in this pull request?

The 1st edition of RatisServer of SCM HA is copied from OM HA.
This version is abandoned, since we finally choose the RatisServer that is implemented by InvocationHandler.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4130

## How was this patch tested?

CI

### CODE REVIEW

**Comment by GlenGeng** [comment]
cc @runzhiwang @timmylicheng @amaliujia

**Comment by GlenGeng** [comment]
TestDecommissionAndMaintenance is a known flaky case on master branch.

**Comment by runzhiwang** [comment]
@GlenGeng Thanks the patch. I have merged it

**Comment by amaliujia** [comment]
+1

**Pull request merged**
