### PR TITLE
HDDS-5091. Add project separation and first stable release to the HISTORY.md

### PR DESCRIPTION
**Pull request by elek**
JIRA: https://issues.apache.org/jira/browse/HDDS-5091

## What changes were proposed in this pull request?

As @mukul1987 notified us in #2140 the `HISTORY.md` is not updated recently. I think the two main events since the last update are the first stable release and the project separation to TLP.

I added a paragraph about these events. 

## How was this patch tested?

This is a readme change. No test is required just :eye:

### CODE REVIEW

**Review by mukul1987 — APPROVED** [review]
+1, LGTM

**Comment by mukul1987** [comment]
Thanks for updating the history Marton. I agree that we should try to keep updating it on every release. But thanks anyways for this update. I really appreciate this.

**Comment by elek** [comment]
> I agree that we should try to keep updating it on every release. 

Thanks for reporting the problem. Yes, we can update it with every release, but at least at the end of the year with can add a quick overview. We may not need to mention all the features, but the big improvements (like SCM-HA) should definitely be added...

Will try to keep in my mind and not forget it...

**Comment by bharatviswa504** [comment]
@elek 
Do we want to mention about 1.0 release which we declare production-ready/GA and removed beta and also about the OM HA feature released as part of 1.0.0?

**Comment by elek** [comment]
>  Do we want to mention about 1.0 release which we declare production-ready/GA and removed beta and also about the OM HA feature released as part of 1.0.0?

Thanks for the idea @bharatviswa504, the first stable release was mentioned:

> In September/October 2020 -- just after the first stable release...

I just added the `1.0.0` version number to here.

Personally I don't feel that we need to add all the release and all the features to here, for me, this HISTORY is more about the huge milestones. 1.0.0 is definitely a very large milestone, but I would mention HA when we achieve full HA (both OM and SCM HA are released).

But I can be easily convinced, this is just my opinion. I am fine even if somebody would like to include [the official roadmap](https://cwiki.apache.org/confluence/display/OZONE/Ozone+Roadmap) at the end of this doc.

If you have any suggested sentence, let me know, and I will include it.

**Comment by bharatviswa504** [comment]
>>but I would mention HA when we achieve full HA (both OM and SCM HA are released).
I am fine with it if we want to mention once we have complete HA.

My thought process here is as part of the 1.0.0 stable release OM HA is completed and which is a big feature. But it also makes sense to mention once we have complete HA(both OM and SCM). I also don't have strong opinion here.

**Review by bharatviswa504 — APPROVED** [review]

**Comment by elek** [comment]
Thanks for the answer @bharatviswa504. I am merging it now, and we can improve it later.

I would say something like this at the end of the year:

```
During 2021 Ozone had 2 (3?) main releases with significant new features and many small bug and security fixes. Full HA setup become available with supporting HA for the two metadata server compnent (Ozone Manager HA from 1.0.0 and Storage Container Manger HA from 1.2.0). 
```

**Pull request merged**
