### PR TITLE
HDDS-10906. [hsync] 6th merge from master

### PR DESCRIPTION
**Pull request by jojochuang**
## What changes were proposed in this pull request?
HDDS-10906. [hsync] 6th merge from master

Please describe your PR in detail:
Only two trivial conflicts due to 
(1) TestBlockOutputStream.java: HDDS-10557
(2) BasicOzoneClientAdapterImpl.java: HDDS-10781

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-10906

## How was this patch tested?

Unit tests

### CODE REVIEW

**Comment by jojochuang** [comment]
cc @chungen0126 because both conflicts are associated with your PRs.

**Comment by jojochuang** [comment]
wrong base

**Comment by chungen0126** [comment]
Here are the details of the PRs:
[HDDS-10557](https://issues.apache.org/jira/browse/HDDS-10557)
This PR fix the assertions in `testWriteExactlyFlushSize ` and `testWriteExactlyFlushSize` that `writeChunk` and `putBlock` requests can complete soon after write. 
Things that change:

- pendingContainerOpCountMetrics: The value is equal or less than the `BlockOutputStream` send, and is equal to the start when  it flush.
- commitIndexMap: The size of `commitIndexMap` is zero if the `putBlock` completed.

[HDDS-10781](https://issues.apache.org/jira/browse/HDDS-10781)
This PR remove the use of `OFSPath` in BasicOzoneClientAdapterImpl because it is an Utility class for OFS not O3FS.

**Review by ashishkumar50 — APPROVED** [review]
Thanks @jojochuang, LGTM

**Pull request merged**
