### PR TITLE
HDDS-8636. Containers in schema V1 fail for replication after the 1.3.0 upgrade

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

> @k5342 found a `NullPointerException` while replicating V1 containers in Ozone 1.3.0.  V1 containers do not have the `schemaVersion` field in the `.container` file

The NPE is fixed by adding and using a comparison function that considers `null` and `V1` to be equal.

https://issues.apache.org/jira/browse/HDDS-8636

## How was this patch tested?

Tested in real cluster:
https://github.com/apache/ozone/pull/4723#issuecomment-1554645068

Updated parameterized unit tests that exercise different schema versions to also test `null` value.

https://github.com/adoroszlai/hadoop-ozone/actions/runs/5032201568

### CODE REVIEW

**Review by errose28 — COMMENTED** [review]
LGTM. @adoroszlai would you like to add more tests or do you think it is sufficient? I am fine either way.

**Comment by adoroszlai** [comment]
Thanks @errose28 for the review.

> would you like to add more tests or do you think it is sufficient?

It turns out that there are some parameterized unit tests that are run for each schema version.  Amended the list of versions with `null`, I think that should be fine for test coverage.

**Review by errose28 — APPROVED** [review]
LGTM with the test update

**Comment by adoroszlai** [comment]
Thanks @errose28 for reviewing and merging this.

**Pull request merged**
