### PR TITLE
HDDS-5336. Fix datanode capacity related race condition.

### PR DESCRIPTION
**Pull request by errose28**
## What changes were proposed in this pull request?

After merging master into the upgrade branch in HDDS-5321, an intermittent failure was noticed in TestSCMNodeManager#testLayoutOnHeartbeat.

The issue occurs in SCMNodeManager#register, where the node is added to the nodeStateManager firing the NEW_NODE event, before the node report containing storage information for the new node is processed. The event triggers a one shot run on the background pipeline creator which will read the node's storage information to determine if it can hold a pipeline. If the storage report has not yet been processed when this happens, no pipeline will be created to use the new node when it is registered, because the node still appears to have no free space.

In this fix, the NEW_NODE event is moved to not fire until all reports given to SCMNodeManager#register have been processed. The output of the existing test has also been modified for clearer output if a similar event occurs in the future.

Although the bug is present on master as well, the fix was done on the upgrade branch because:
1. That is where the test to reproduce the issue resides.
2. The fix works better with SCMNodeManager modifications already done for upgrades.
3. Upgrade branch is expected to be merged into master soon.

## What is the link to the Apache JIRA

HDDS-5336

## How was this patch tested?

Original failed multiple times on CI:
- https://github.com/apache/ozone/runs/2787582345
- https://github.com/errose28/hadoop-ozone/runs/2748815362

Fix was tested with 100 runs on CI:
- https://github.com/errose28/hadoop-ozone/runs/2797649712

I was unable to reproduce the original failure with 400 runs locally, so CI was used for testing.

### CODE REVIEW

**Comment by errose28** [comment]
Unit test failure for `TestSCMNodeManager#testScmLayoutOnRegister` came in with the merge from master. It is different than this PR which uses `TestSCMNodeManager#testLayoutOnHeartbeat`. Currently investigating...

**Review by avijayanhwx — APPROVED** [review]
LGTM +1

**Comment by errose28** [comment]
Thanks for the review and fixes @avijayanhwx. The fixes for unit tests applied on top of the original change LGTM.

**Comment by avijayanhwx** [comment]
Thank you @errose28, merging this.

**Pull request merged**
