### PR TITLE
HDDS-9031. Upgrade acceptance tests to Docker Compose v2

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Change acceptance tests to use Docker Compose v2, if available.

~`ozonescripts` environment has some non-test scripts (`start.sh`, etc.), these require Docker Compose v2 after the change.~

`env-compose.robot` is unused, can be removed.

https://issues.apache.org/jira/browse/HDDS-9031

## How was this patch tested?

Acceptance tests with Docker Compose v1 uninstalled:
https://github.com/adoroszlai/ozone/actions/runs/9041151300

Regular CI:
https://github.com/adoroszlai/ozone/actions/runs/9041151733

### CODE REVIEW

**Comment by kerneltime** [comment]
> ozonescripts environment has some non-test scripts (start.sh, etc.), these require Docker Compose v2 after the change.
Can you elaborate on why they require docker compose v2 vs an optional use like the `hadoop-ozone/dist/src/main/compose/testlib.sh` script?

**Comment by smengcl** [comment]
> > ozonescripts environment has some non-test scripts (start.sh, etc.), these require Docker Compose v2 after the change.
> 
> Can you elaborate on why they require docker compose v2 vs an optional use like the `hadoop-ozone/dist/src/main/compose/testlib.sh` script?

Actually `testlib.sh` is already using v2 if it is available. It is a clever trick to override `docker-compose` to use v2 if that is available:

https://github.com/apache/ozone/pull/6667/files#diff-f26853740acf7f82a794bddb61e32ae145d12fdb0e08cd4a4c18a991e93742d0R34-R36

**Review by smengcl — APPROVED** [review]
Thanks @adoroszlai !

**Comment by adoroszlai** [comment]
> Can you elaborate on why they require docker compose v2

For these scripts I wanted to avoid using `testlib.sh` or duplicate the code.

> I think it is possible to use the same trick as well.

Done by extracting the `docker-compose` function definition to its own script.  Updated `ozonescripts` to use it.  Also in `ozone/run.sh`, which I completely missed earlier.

**Pull request merged**
