### PR TITLE
HDDS-8414. Recon: Heatmap Absolute Path in Response at end node level on HyperLink End Point Response.

### PR DESCRIPTION
**Pull request by devmadhuu**
## What changes were proposed in this pull request?

This PR is to add "path" attribute in "`api/v1/heatmap/readaccess`" API response at each node level including  bucket and volume.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8414

## How was this patch tested?

This patch is tested functionally using Junit test case assertion as well as verifying response of API through POSTMAN client where a new attribute "`path`" being added:

```
{
  "label": "root",
  "children": [
    {
      "label": "hivevolTest1",
      "children": [
        {
          "label": "hivebucketTest1",
          "children": [
            {
              "label": "enc_path/hive_tpcds/store_sales/test1.dat",
              "size": 1026,
              "path": "/hivevolTest1/hivebucketTest1/enc_path/hive_tpcds/store_sales/test1.dat",
              "accessCount": 155074,
              "color": 1
            },
            {
              "label": "enc_path/hive_tpcds/catalog_sales/test2",
              "size": 20,
              "path": "/hivevolTest1/hivebucketTest1/enc_path/hive_tpcds/catalog_sales/test2",
              "accessCount": 68567,
              "color": 0.56
            },
            {
              "label": "enc_path/hive_tpcds/web_sales/test3",
              "size": 2000,
              "path": "/hivevolTest1/hivebucketTest1/enc_path/hive_tpcds/web_sales/test3",
              "accessCount": 36114,
              "color": 0.45
            },
            {
              "label": "enc_path/hive_tpcds/test4",
              "size": 800,
              "path": "/hivevolTest1/hivebucketTest1/enc_path/hive_tpcds/test4",
              "accessCount": 9047,
              "color": 0.62
            },
            {
              "label": "enc_path/hive_tpcds/date_dim/test5",
              "size": 256,
              "path": "/hivevolTest1/hivebucketTest1/enc_path/hive_tpcds/date_dim/test5",
              "accessCount": 9044,
              "color": 0.78
            },
            {
              "label": "enc_path/hive_tpcds/store_sales",
              "size": 256,
              "path": "/hivevolTest1/hivebucketTest1/enc_path/hive_tpcds/store_sales",
              "accessCount": 6463,
              "color": 0.88
            }
          ],
          "size": 3584,
          **"path": "/hivevolTest1/hivebucketTest1",**
          "minAccessCount": 2924,
          "maxAccessCount": 155074
        }
      ],
      "size": 7168,
      **"path": "/hivevolTest1"**
    }
  ],
  "size": 25600,
  "minAccessCount": 2924,
  "maxAccessCount": 155074
}
```

### CODE REVIEW

**Comment by devmadhuu** [comment]
@sumitagrawl @dombizita  Pls review.

**Review by sumitagrawl — APPROVED** [review]
@devmadhuu Thanks for working on this, LGTM +1

**Comment by dombizita** [comment]
thanks for working on this @devmadhuu! overall it looks good, but based on the implementation shouldn't there be a `path` attribute for each children under bucket level (eg. in the childrens of `hivebucketTest1`) too? you set the path there too, here, right?
https://github.com/apache/ozone/blob/1ca40abf9819d1b97c27a3617a2814af87aa5396/hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/heatmap/HeatMapServiceImpl.java#L224
I can't see it in the examples that are in the description of the PR, neither in the javadoc of the changed methods. am I missing something here?

**Comment by devmadhuu** [comment]
> thanks for working on this @devmadhuu! overall it looks good, but based on the implementation shouldn't there be a `path` attribute for each children under bucket level (eg. in the childrens of `hivebucketTest1`) too? you set the path there too, here, right?
> 
> https://github.com/apache/ozone/blob/1ca40abf9819d1b97c27a3617a2814af87aa5396/hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/heatmap/HeatMapServiceImpl.java#L224
> 
> 
> I can't see it in the examples that are in the description of the PR, neither in the javadoc of the changed methods. am I missing something here?

@dombizita Thanks for review. No we don't need path attribute for bucket childrens as those are full paths as being treated as keys and listed as leaf level for read access counts and this path value is being used as an argument in API:`api/v1/heatmap/readaccess?startDate=90D&path=<path_value>&entityType=key`, when user will click on treemap box and box represents either bucket or volume. If User has already at leaf level, then no further childrens and no need to call for API again.

> thanks for working on this @devmadhuu! overall it looks good, but based on the implementation shouldn't there be a `path` attribute for each children under bucket level (eg. in the childrens of `hivebucketTest1`) too? you set the path there too, here, right?
> 
> https://github.com/apache/ozone/blob/1ca40abf9819d1b97c27a3617a2814af87aa5396/hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/heatmap/HeatMapServiceImpl.java#L224
> 
> 
> I can't see it in the examples that are in the description of the PR, neither in the javadoc of the changed methods. am I missing something here?

**Comment by devmadhuu** [comment]
@dombizita  - pls re-review.

**Review by dombizita — APPROVED** [review]
thanks for working on it @devmadhuu, it looks good to me!

**Pull request merged**
