### PR TITLE
HDDS-6505. TestContainerStateManagerIntegration consistently fails

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Fix TestContainerStateManagerIntegration:

 * Set pipeline limit, as the test assumes single pipeline per datanode (which used to be the default).
 * `testReplicaMap` had a consistent `fail()` call, which used to be part of a try-catch block where exception was expected before HDDS-5607.
 * Remove two test cases that were testing the same code path as others due to always passing an empty set of excluded container IDs.
 * Use a fixed thread pool for `testGetMatchingContainerMultipleThreads`.  It was failing in CI with `unable to create new native thread`, because [`supplyAsync` launches a new thread for each task when parallelism is 1](https://issues.apache.org/jira/browse/RATIS-1497?focusedCommentId=17480241&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17480241).
    ```
    java.lang.OutOfMemoryError: unable to create new native thread
      at java.lang.Thread.start0(Native Method)
      at java.lang.Thread.start(Thread.java:719)
      at java.util.concurrent.CompletableFuture$ThreadPerTaskExecutor.execute(CompletableFuture.java:405)
      at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1618)
      at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1827)
      at org.apache.hadoop.hdds.scm.container.TestContainerStateManagerIntegration.testGetMatchingContainerMultipleThreads(TestContainerStateManagerIntegration.java:294)
    ```

https://issues.apache.org/jira/browse/HDDS-6505

## How was this patch tested?

Repeated 50x without the flaky `testGetMatchingContainerMultipleThreads`:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2034074566

Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2034107910

### CODE REVIEW

**Review by kaijchen — APPROVED** [review]
LGTM, thanks for the fix.

**Comment by JacksonYao287** [comment]
@adoroszlai thanks for this work , the changes looks good to me! 
will merge this shortly!

**Review by JacksonYao287 — APPROVED** [review]
thanks @adoroszlai for the work and @kaijchen for the review. I have committed this patch to master branch

**Comment by adoroszlai** [comment]
Thanks @kaijchen for the review, @JacksonYao287 for reviewing and merging this.

**Pull request merged**
