### PR TITLE
HDDS-5393. Return latest version of key location for client on createKey/createFile

### PR DESCRIPTION
**Pull request by bharatviswa504**
## What changes were proposed in this pull request?

Use latestVersion config for createKey/createFile.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5393

## How was this patch tested?

Existing tests.  (Will add couple more tests)

### CODE REVIEW

**Comment by bharatviswa504** [comment]
@symious @ChenSammi @kuenishi Now we have HDDS-5472 is in, we can get this in.

**Comment by symious** [comment]
Sure, I think we can wait for a green sign?

**Comment by symious** [comment]
+1 LGTM

**Comment by ChenSammi** [comment]
Hey @bharatviswa504 , can you add a test in TestOmBlockVersioning for this create case?

**Comment by ChenSammi** [comment]
I revisted aws s3 documents, it seems that aws put object API only returns the latest object version-id when versioning is enabled(https://docs.aws.amazon.com/AmazonS3/latest/userguide/AddingObjectstoVersioningEnabledBuckets.html) , and return null or versioning is disabled. 
So I feel like we can make the " Return latest version of key location for client on createKey/createFile" a common logic, no need to depends on the getLatestVersionLocation. For getLatestVersionLocation is used for key retrieve under versioning case, like the listObject in https://docs.aws.amazon.com/AmazonS3/latest/userguide/manage-objects-versioned-bucket.html.

**Comment by ChenSammi** [comment]
I revisted aws s3 documents, it seems that aws put object API only returns the latest object version-id when versioning is enabled(https://docs.aws.amazon.com/AmazonS3/latest/userguide/AddingObjectstoVersioningEnabledBuckets.html) , and return null or versioning is disabled. 
So I feel like we can make the " Return latest version of key location for client on createKey/createFile" a common logic, no need to depends on the getLatestVersionLocation. For getLatestVersionLocation is used for key retrieve under versioning case, like the listObject in https://docs.aws.amazon.com/AmazonS3/latest/userguide/manage-objects-versioned-bucket.html.

**Comment by bharatviswa504** [comment]
I have added the test

**Comment by bharatviswa504** [comment]
> I revisted aws s3 documents, it seems that aws put object API only returns the latest object version-id when versioning is enabled(https://docs.aws.amazon.com/AmazonS3/latest/userguide/AddingObjectstoVersioningEnabledBuckets.html) , and return null when versioning is disabled.

I have used latestVersion boolean in code, and by default it is true, so in that perspective we should be good. And as we have this flag to be consistent in code using this flag should be okay. In this way, we don't remove the old behavior completely. 

What returns null? I have not understood that part, care to explain more.

> So I feel like we can make this " Return latest version of key location for client on createKey/createFile" a common logic, no need to depends on the getLatestVersionLocation value. It is more closer to the aws s3 behavior.

We have 2 code paths, in both places when returning from network returning latest version.

**Comment by bharatviswa504** [comment]
> OmBlockVersioning for this create case?

I have added test in new classes, TestOmBlockVersioning uses old write code path.

**Comment by ChenSammi** [comment]
> What returns null? I have not understood that part, care to explain more.
I means aws s3 put object doesn't return object version if buckt versioning is disabled. 

> I am okay to do change with out using flag, but I think we can remove this every where if it is not required in read path also, as get by default returns latest version. So, this can be addressed in new Jira
>
Yes, we can do it in an seperate JIRA.

**Comment by bharatviswa504** [comment]
@ChenSammi Added test, PTAL.

**Comment by ChenSammi** [comment]
> 
> 
> @ChenSammi Added test, PTAL.

The last path LGTM, + 1. 

Thanks @bharatviswa504 .

**Pull request merged**
