### PR TITLE
HDDS-6514. Cleanup constructors and builders in OM helpers

### PR DESCRIPTION
**Pull request by kaijchen**
## What changes were proposed in this pull request?

Use builder pattern to avoid constructor telescoping in OM helpers.
And reduce parameter numbers in constructors, thus removing the need of `@SuppressWarnings("checkstyle:ParameterNumber")`

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-6514

## How was this patch tested?

Unit test

### CODE REVIEW

**Comment by guihecheng** [comment]
We could combine HDDS-6513 and this into one since they are doing the same cleanups to source files under the same directory.

**Comment by kaijchen** [comment]
> We could combine [HDDS-6513](https://issues.apache.org/jira/browse/HDDS-6513) and this into one since they are doing the same cleanups to source files under the same directory.

There are many classes with the same problem, inside om.helpers or outside.
I prefer to keep the patch small and easy to review.

**Comment by guihecheng** [comment]
Oh if there are many(more than these 2) such problems and you've got a plan to fix them all, then we'd better have a base JIRA for "Avoid constructor for some submodule" and create sub-tasks under it, then we could know how many problems have fixed and how many left rather than randomly fix them one by one.

**Comment by kaijchen** [comment]
> Oh if there are many(more than these 2) such problems and you've got a plan to fix them all, then we'd better have a base JIRA for "Avoid constructor for some submodule" and create sub-tasks under it, then we could know how many problems have fixed and how many left rather than randomly fix them one by one.

Thanks for the advice. I have create HDDS-6518 to track them.

**Comment by kaijchen** [comment]
> There are many classes with the same problem, inside om.helpers or outside.
> I prefer to keep the patch small and easy to review.

I decided to group them to reduce the number of pull requests.

**Comment by kaijchen** [comment]
Rebased to master to solve the merge conflicts.

**Pull request closed without merging**
