### PR TITLE
HDDS-8656. Do not log zero byte object creation

### PR DESCRIPTION
**Pull request by kerneltime**
## What changes were proposed in this pull request?

 Do not log zero byte object creation

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-8656

## How was this patch tested?

Existing tests should cover this.

### CODE REVIEW

**Comment by kerneltime** [comment]
@tanvipenumudy can you please take a look ?

**Review by smengcl — APPROVED** [review]
lgtm

**Review by tanvipenumudy — APPROVED** [review]
LGTM, thanks

**Comment by adoroszlai** [comment]
@Xushaohong please take a look

**Review by kaijchen — APPROVED** [review]
LGTM

**Pull request merged**
