### PR TITLE
HDDS-8468. Fix Native JDK 11, 17 compile

### PR DESCRIPTION
**Pull request by swamirishi**
## What changes were proposed in this pull request?

Currently native header file compilation fails for jdk11 & jdk 17. 

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-8468

## How was this patch tested?
Local testing

### CODE REVIEW

**Comment by swamirishi** [comment]
@smengcl @adoroszlai Can you take a look at this?

**Comment by adoroszlai** [comment]
@swamirishi thanks for working on this.

Since native build is not included in regular CI, please:

1. create a test branch based on [HDDS-8468](https://github.com/swamirishi/ozone/tree/HDDS-8468)
2. make a temporary commit:
   * hard-code `-Drocks_tools_native` in `build.sh`
   * increase timeout of _build_ and _compile_ checks in `ci.yml` if necessary
3. push to your fork
4. link to the CI run of the test branch in the PR description

This will provide test coverage for the change.

**Comment by swamirishi** [comment]
Thank you attila for reviewing this:
Check https://github.com/swamirishi/ozone/actions/runs/4763117983/jobs/8466821254 for the ci run on test branch https://github.com/swamirishi/ozone/commit/05ed061c6c10956ceeee5f81d5b95929ff37e5fe

**Comment by adoroszlai** [comment]
Thanks @swamirishi for the test run, looks good.

**Comment by swamirishi** [comment]
@adoroszlai Can this be merged?

**Review by smengcl — APPROVED** [review]

**Pull request merged**
