### PR TITLE
HDDS-9148. OM to reject hsync if ozone.fs.hsync.enabled is false

### PR DESCRIPTION
**Pull request by jojochuang**
## What changes were proposed in this pull request?

1. OM rejects hsync request if ozone.fs.hsync.enabled is false (which is the default value).
2. Client hsync() actually calls flush() if ozone.fs.hsync.enabled is false. This is the original behavior prior to the hsync implementation.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-9148

## How was this patch tested?

Unit tests in client and OM side.

### CODE REVIEW

**Review by kerneltime — APPROVED** [review]

**Review by errose28 — APPROVED** [review]
Thanks for the fix @jojochuang. Functionally LGTM, but it would be nice to clean up the stream constructors in this PR or a follow up if possible. Some examples I've seen so far:
- `public OzoneOutputStream(OutputStream outputStream, Syncable syncable, boolean enableHsync)` is not intuitive. You can pass hsync=false but still need to pass a syncable object that is never used.
- `RpcClient#createSecureOutputStream(OpenKeySession openKey, OutputStream keyOutputStream, Syncable syncable)` is always invoked with `keyOutputStream` and `syncable` as the same object, or with `syncable` as null. This seems redundant overall.

I'm not sure what the better solution could be yet, and functionally this PR looks fine so I am ok with it for now,, but going forward we should try to integrate sync better with existing stream creation methods.

**Review by smengcl — APPROVED** [review]
lgtm.

If we want to fix the constructor, it should be done before 1.4.0.

**Comment by errose28** [comment]
> If we want to fix the constructor, it should be done before 1.4.0.

The constructor changes are new so they are already breaking changes in master right now. If we want to enforce this as a compatibility problem then a refactor of this area is required before 1.4.0 regardless of this or follow up patches.

**Comment by errose28** [comment]
@jojochuang The test is failing because other tests in the same cluster are already creating objects called "file". It will pass if changed to a unique name.

**Comment by smengcl** [comment]
Thanks @jojochuang for the patch. Thanks @kerneltime @errose28 for the reviews.

**Pull request merged**
