### PR TITLE
HDDS-9261. SCM Decommissioning Robot tests improvement

### PR DESCRIPTION
**Pull request by LZD-PratyushBhatt**
## What changes were proposed in this pull request?

Improving the SCM decommisioning robot tests. Refactoring the code and adding pre and post decommissioning data integrity check.

## What is the link to the Apache JIRA

[HDDS-9261](https://issues.apache.org/jira/browse/HDDS-9261)

## How was this patch tested?

Modifed the robot test.

### CODE REVIEW

**Comment by errose28** [comment]
@swamirishi would you like to review when this is out of draft?

**Comment by LZD-PratyushBhatt** [comment]
> @swamirishi would you like to review when this is out of draft?

Hi @errose28 @swamirishi ,Marked it ready for review.

**Comment by ChenSammi** [comment]
@LZD-PratyushBhatt , could you check the failed acceptance test. It's caused by the code change in patch.

**Comment by LZD-PratyushBhatt** [comment]
> @LZD-PratyushBhatt , could you check the failed acceptance test? It's caused by the code change in patch.

Hi @ChenSammi , Added a fix, please check. Thanks!
Ran CI on my fork, looks good now: https://github.com/LZD-PratyushBhatt/ozone/pull/2/checks?check_run_id=16864862995

**Comment by LZD-PratyushBhatt** [comment]
> @LZD-PratyushBhatt , could you check the failed acceptance test? It's caused by the code change in patch.

Hi Sammi, fixed the test. Failed splits are passing in my fork. https://github.com/LZD-PratyushBhatt/ozone/actions/runs/6224020946/job/16892248612

**Review by nandakumar131 — APPROVED** [review]

**Pull request merged**
