### PR TITLE
HDDS-10089. ManagedSecretKey.macInstances should not be ThreadLocal

### PR DESCRIPTION
**Pull request by sumitagrawl**
## What changes were proposed in this pull request?

There is possibility of ThreadLocal memory leak during rotation of key as thread local variable is never released, so for thread safety for mac instance, concurrent hash map with thread Id as key is used (Mac instance is not thread safe)

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-10089

## How was this patch tested?

- existing test case cover functionality

### CODE REVIEW

**Comment by adoroszlai** [comment]
@sumitagrawl I recommend resetting `master` branch in your fork from `apache/ozone` to avoid more and more `Merge branch 'apache:master' into master` commits in your PRs.  This can be done in Github UI (`Sync fork` drop-down button in https://github.com/sumitagrawl/ozone/tree/master, choose `Discard ... commits`), or via CLI.

Also, please wait with opening PR until a clean run in your fork is completed.

**Review by duongkame — COMMENTED** [review]
Thanks for making the issue notified @sumitagrawl. I think the problem with ThreadLocal is when threads come and go, e.g. as per ThreadPool policy, the associating value is not cleanup. This PR now doesn't do that kind cleanup as I understand.

Simply using `TerminatingThreadLocal` would ensure the thread local value is cleanup when threads exit.

**Comment by duongkame** [comment]
> There is possibility of ThreadLocal memory leak during rotation of key as thread local variable is never released
This is not necessary the case because when the `ThreadLocal` instance is unreachable, its slot in ThreadLocalMap will be replaced by the next call from the same Thread.

**Comment by sumitagrawl** [comment]
> Thanks for making the issue notified @sumitagrawl. I think the problem with ThreadLocal is when threads come and go, e.g. as per ThreadPool policy, the associating value is not cleanup. This PR now doesn't do that kind cleanup as I understand.
> 
> Simply using `TerminatingThreadLocal` would ensure the thread local value is cleanup when threads exit.

@duongkame Problem here is, we do not have kind of close resource where can do cleanup. Doing same in finalizer of java is not recommended. So I tried avoid using ThreadLocal itself.

ThreadLocal resource can be managed in static or singleton usecase, but with private member, its not recommended.

**Review by duongkame — APPROVED** [review]
Thanks for the explaination and the patch @sumitagrawl . LGTM.

**Pull request merged**
