### PR TITLE
HDDS-6723. Close Rocks objects properly in OzoneManager

### PR DESCRIPTION
**Pull request by jojochuang**
Change-Id: I5e2f906508d92c1c21555aa51d9b5c97744f26cd
(cherry picked from commit c1cda1d8e99555282b991f174d0bf597c0deb950)

## What changes were proposed in this pull request?

Close RocksDB objects when they are not used.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-6723

## How was this patch tested?

This is tested in an internal branch, ran a few workloads.
The RocksDB jar was replaced with a custom build which prints memory leak in stdout. This is the code: https://github.com/jojochuang/rocksdb/commits/debug_memory_leak

With this change, most of the leaks are now gone, except during OM initialization when load DB. Didn't care much about them as they account for very little memory usage.

### CODE REVIEW

**Comment by jojochuang** [comment]
[om_stdout.log](https://github.com/apache/ozone/files/8665431/om_stdout.log)
Sample stdout from OM after this PR.

**Comment by kerneltime** [comment]
The changes here are in the right direction but this will need to be updated post merge of https://github.com/apache/ozone/pull/3426

**Review by adoroszlai — COMMENTED** [review]
Thanks @jojochuang for working on this.

I found a few more unclosed table iterators in `KeyManagerImpl`:

https://github.com/apache/ozone/blob/a89da04bcc1b34625d3a1f376866ee4cbb3b3ac3/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java#L1553-L1554

https://github.com/apache/ozone/blob/a89da04bcc1b34625d3a1f376866ee4cbb3b3ac3/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java#L2010-L2011

https://github.com/apache/ozone/blob/a89da04bcc1b34625d3a1f376866ee4cbb3b3ac3/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java#L2397-L2398

**Review by adoroszlai — APPROVED** [review]
Thanks @jojochuang for updating the patch.

**Comment by adoroszlai** [comment]
@kerneltime would you like to take another look?

**Comment by adoroszlai** [comment]
Thanks @jojochuang for the patch, @kerneltime for the review.

**Pull request merged**
