### PR TITLE
HDDS-10854. Run full Ozone CI with specific Ratis commit

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Create a new workflow that runs full Ozone CI with any Ratis commit.  `ci-with-ratis` can be triggered manually, similar to `flaky-test-check`.

https://issues.apache.org/jira/browse/HDDS-10854

## How was this patch tested?

Manually triggered `ci-with-ratis` for the latest commit (https://github.com/apache/ratis/commit/de2e777e19d48bd67fcba1538007940abde87170) on [`branch-3.1.0`](https://github.com/apache/ratis/commits/branch-3.1.0):
https://github.com/adoroszlai/ozone/actions/runs/9545441575

Verified Ratis version in acceptance test logs.

```
$ grep -o 'ratis-[^:]*.jar' docker-ozone-om-1.log | sort -u         
ratis-client-3.1.0-de2e777-SNAPSHOT.jar
ratis-common-3.1.0-de2e777-SNAPSHOT.jar
ratis-grpc-3.1.0-de2e777-SNAPSHOT.jar
ratis-metrics-api-3.1.0-de2e777-SNAPSHOT.jar
ratis-metrics-dropwizard3-3.1.0-de2e777-SNAPSHOT.jar
ratis-netty-3.1.0-de2e777-SNAPSHOT.jar
ratis-proto-3.1.0-de2e777-SNAPSHOT.jar
ratis-server-3.1.0-de2e777-SNAPSHOT.jar
ratis-server-api-3.1.0-de2e777-SNAPSHOT.jar
ratis-thirdparty-misc-1.0.6.jar
```

Regular CI (triggered by `push` event):
https://github.com/adoroszlai/ozone/actions/runs/9545432869

### CODE REVIEW

**Comment by kerneltime** [comment]
@adoroszlai how can a developer try this out? Should we add a section to [CONTRIBUTING.md](https://github.com/apache/ozone/blob/master/CONTRIBUTING.md)

**Comment by adoroszlai** [comment]
> how can a developer try this out?

Developers should sync `master` in their fork (using CLI or GitHub UI) after this gets merged.  Afterwards they can trigger the `ci-with-ratis` workflow [manually](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow).

If you mean "try out" as in "verify the changes in this PR", fetch the branch from my remote and push it as `master` in your own fork.

> Should we add a section to CONTRIBUTING.md

The new website has a section for CI, it should be documented there.

**Comment by kerneltime** [comment]
> > how can a developer try this out?
> 
> Developers should sync `master` in their fork (using CLI or GitHub UI) after this gets merged. Afterwards they can trigger the `ci-with-ratis` workflow [manually](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow).
> 
We should include this some place in CI.md
> The new website has a section for CI, it should be documented there.
Should we have it part of CI.md?

**Comment by adoroszlai** [comment]
Thanks @kerneltime, @szetszwo for the review.

Documentation follow-up to be done in HDDS-11026.

**Comment by kerneltime** [comment]
> Thanks @kerneltime, @szetszwo for the review.
> 
> Documentation follow-up to be done in [HDDS-11026](https://issues.apache.org/jira/browse/HDDS-11026).

Thanks @adoroszlai

**Pull request merged**
