### PR TITLE
HDDS-9051. Change the log level when no nodes are available in NetworkTopologyImpl

### PR DESCRIPTION
**Pull request by Tejaskriya**
## What changes were proposed in this pull request?

We currently have a log message in NetworkTopologyImpl set at the WARN level for when no datanodes are available. It’ll usually show up with a bunch of other related, repeating logs. It is better to set it to DEBUG level, and relying on the INFO message at the end as a summary of what happened.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-9051

## How was this patch tested?

Only log level change. No testing required.

### CODE REVIEW

**Review by tanvipenumudy — COMMENTED** [review]
Thank you @Tejaskriya for the patch.

> It is better to set it to DEBUG level, and relying on the INFO message at the end as a summary of what happened

Can you please specify the `INFO` message which should suffice instead of the `WARN` messages?

**Comment by Tejaskriya** [comment]
> Can you please specify the `INFO` message which should suffice instead of the `WARN` messages?

The method chooseNodeInternal() in which this log is present is finally being called by `SCMContainerPlacementRackAware#chooseNode()` and `SCMContainerPlacementRackScatter#chooseNode()` . Both these methods have Log.info() messages to log "No satisfied datanode" being found after maxTries are hit. These INFO logs will serve the purpose of showing us the summary

**Review by siddhantsangwan — COMMENTED** [review]
@Tejaskriya The purpose here is to remove redundant information in the info logs. To do this, we need to ensure all classes using this method from `NetworkTopology` are providing a summary or similar information so that we can get rid of the repeated warnings from this class. `SCMContainerPlacementRackScatter` already does this. What about other classes?

**Comment by siddhantsangwan** [comment]
Thinking about it some more, it's actually hard to guarantee what a future user of the class will do, and the implementation details of this class cannot really rely on that. I think we're better off just bringing down the log level from WARN to INFO.

**Comment by Tejaskriya** [comment]
>  I think we're better off just bringing down the log level from WARN to INFO.

We want to bring it down from WARN to INFO and not DEBUG?

**Comment by siddhantsangwan** [comment]
> We want to bring it down from WARN to INFO and not DEBUG?

Yes

**Comment by Tejaskriya** [comment]
@siddhantsangwan thank you for the review! I have changed the log level to INFO now. Could you please approve the workflows if the patch is good to go?

**Review by adoroszlai — APPROVED** [review]

**Comment by adoroszlai** [comment]
Thanks @Tejaskriya for the patch, @siddhantsangwan, @tanvipenumudy for the review.

**Pull request merged**
