### PR TITLE
HDDS-7176. Sort the container replica according to the replica index

### PR DESCRIPTION
**Pull request by Xushaohong**
## What changes were proposed in this pull request?

Sort the container replica according to the replica index

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-7176

## How was this patch tested?
UT

### CODE REVIEW

**Review by sodonnel — COMMENTED** [review]
The changes here make sense to me. Any way you can add or modify a test to validate the ordering is now sorted by the replica index?

**Comment by Xushaohong** [comment]
> The changes here make sense to me. Any way you can add or modify a test to validate the ordering is now sorted by the replica index?

Hi @sodonnel , I have tested and posted the result in the above~ Is it enough?

**Comment by sodonnel** [comment]
It is better if we test it in one of the unit tests, otherwise someone may change something in the future that breaks it, and we will not catch it.

**Comment by Xushaohong** [comment]
> It is better if we test it in one of the unit tests, otherwise someone may change something in the future that breaks it, and we will not catch it.

Updated. PTAL

**Review by sodonnel — APPROVED** [review]

**Pull request merged**
