### PR TITLE
HDDS-4432. Update Ratis version to latest snapshot.

### PR DESCRIPTION
**Pull request by hanishakoneru**
## What changes were proposed in this pull request?

Update ozone with latest Ratis snapshot which has a critical fix for "Bootstrap new OM Node" feature - HDDS-4330.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4432

## How was this patch tested?

Not required.

### CODE REVIEW

**Comment by hanishakoneru** [comment]
@nandakumar131, @mukul1987, @lokeshj1703, TestNodeFailure#testPipelineFail is failing after Ratis version upgrade. Any idea what could be causing this regression? Was there any change in Ratis pipeline close logic?

**Comment by bshashikant** [comment]
Thanks @hanishakoneru for working on this. The test failure is related to the recent ratis change for config name (DatanodeRatisServerConfig rpcslowness.timeout. ----> rpc.slowness.timeout). I have also updated ratis to the latest snapshot created.

**Comment by adoroszlai** [comment]
Shouldn't Ratis be backward compatible now that it has reached 1.0?  Dropping existing API and renaming config keys without handling old ones look incompatible to me.  Maybe this is not the right place to discuss this, but the changes necessary in Ozone to upgrade Ratis highlights these issues.

**Comment by bshashikant** [comment]
> Shouldn't Ratis be backward compatible now that it has reached 1.0? Dropping existing API and renaming config keys without handling old ones look incompatible to me. Maybe this is not the right place to discuss this, but the changes necessary in Ozone to upgrade Ratis highlights these issues.

@adoroszlai , i agree with you. This needs better handling for upgrade cases. 
@avijayanhwx , any thoughts on this?

**Comment by hanishakoneru** [comment]
Thanks @bshashikant for debugging and fixing the issue.

Can we go ahead and merge this PR and discuss Ratis backward compatibility in dev list?
@adoroszlai, @avijayanhwx, do you see any issues with merging this PR?

**Comment by avijayanhwx** [comment]
It is quite possible that no existing cluster has overriden this config. But, it would be better to treat the old config key as deprecated (org.apache.hadoop.conf.Configuration.DeprecationDelta).

**Comment by adoroszlai** [comment]
> Can we go ahead and merge this PR and discuss Ratis backward compatibility in dev list?

Sure, I didn't want to block this PR.

**Comment by hanishakoneru** [comment]
Opened HDDS-4493 to handle deprecated configs.

**Review by avijayanhwx — APPROVED** [review]
LGTM +1.

Can we follow up these backward incompatible changes in the Ratis mailing group?

**Comment by hanishakoneru** [comment]
Thanks Aravindan.

> Can we follow up these backward incompatible changes in the Ratis mailing group?

Sure. I will start a discussion.

**Pull request merged**
