### PR TITLE
HDDS-6532. Enable READ audit log by default

### PR DESCRIPTION
**Pull request by symious**
## What changes were proposed in this pull request?

Currently, audit log only records WRITE operations, which is not convenient for cluster load  managing.

This ticket is to change the default configuration to also add READ operations.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-6532

## How was this patch tested?

unit test.

### CODE REVIEW

**Comment by symious** [comment]
@adoroszlai @ferhui Could you help to review this PR?

**Comment by adoroszlai** [comment]
@symious I don't think we should enable it by default.  Cluster admins can enable it via config if needed.

**Comment by symious** [comment]
@adoroszlai Thanks for the review.

As a HDFS user, I think it would be more conventional to have both READ and WRITE logs by default.

It seems a little strange to notice that only WRITE logs are recorded at first.

**Comment by ferhui** [comment]
@adoroszlai Could you please give your thoughts? I am also interested in why didn't enable audit for read

**Comment by adoroszlai** [comment]
> Could you please give your thoughts?

I already [did](https://github.com/apache/ozone/pull/3255#issuecomment-1083029499).

Can you start a discussion on the dev mailing list to get more opinions on changing the default?

> I am also interested in why didn't enable audit for read

I was not involved in the initial implementation (HDDS-98), so I cannot answer that.  That's why I asked @dineshchitlangia for review.  You can also ping other folks who reviewed audit logger feature back then.

**Comment by ferhui** [comment]
@adoroszlai Thanks for your comments.
@symious Can wait for other reviewers' opinions here. If no comments, can start the discussion thread through dev list as @adoroszlai said.

**Comment by symious** [comment]
Sure will do.

**Review by dineshchitlangia — COMMENTED** [review]
Thanks @adoroszlai for looping me.

The read audit log was disabled by default intentionally to avoid generating massive amount of log at scale. Many of the hadoop end customers we interacted with during my time at Cloudera they all had the same concern that they want only write logs by default and most of them would like to turn off default read audit.

Hence, we disable read audit log by default however, if someone specifically wants to audit reads, they can configure it that way. This is to avoid unintentionally audit log generation.

I suggest we skip this change as users can still configure it if needed, it doesn't block their ability to audit reads.

**Comment by symious** [comment]
@dineshchitlangia Thanks for the explaination.

We also concerned about the log flushing that might be caused by enabling READ audit logs. 

I've created another ticket to support the exclusion of operations on demand (https://issues.apache.org/jira/browse/HDDS-6562). With this feature, the log flushing should be resolved. 

IMHO, the original disable READ audit logs in fact doesn't resolve the issue, when users have the requirement to enable READ audit log, the log flushing would still annoy them. Only we are able to control what to log and not to log, the issue is really solved. At that time, enabling READ audit log should not be a problem.

**Comment by dineshchitlangia** [comment]
@symious Thank you for logging HDDS-6562 that is certainly a good feature to have.

I would still stick with default as disabled for Read audits. Even if you want to have it enabled and then use the exclusion settings, you would still end up with config change. On the other hand, if a user does not want read audits at all, they have no config change to make.

So, it is not a blocker if the read audits are disabled by default, at the time of cluster set up one can enable it. This combined with the feature you proposed should still serve the purpose if someone wants to enable it.

**Comment by symious** [comment]
The feature mentioned in https://issues.apache.org/jira/browse/HDDS-6562 was updated. Please have a check.

@dineshchitlangia The update config issue was indeed a concern. If a user want's to disable some log, he need to update the config and restart the service, which is not good.

So I added a new feature to let the users dynamically update the configuration, the first implementation is in https://github.com/symious/ozone/tree/dynamic_change. With this feature, users' habits might change. Users will first enable all the logs, then they can check which type of operations they don't like, update the config, and refresh the auditLog. So the update config issue should be solved.

Another thing is from the audit logs implemetation in HDFS,
1. From the commit in https://github.com/apache/hadoop/blob/trunk/hadoop-hdfs-project/hadoop-hdfs/src/main/resources/hdfs-default.xml#L3190, I think by default the configuration is empty.
2. In a releted ticket, https://issues.apache.org/jira/browse/HDFS-9828, It's also recommended not to disable READ audit logs.

**Review by dineshchitlangia — APPROVED** [review]
@symious In HDFS, it was not agreed to disable all read logs for a different reason.
Nevertheless, now that you have added the feature exclude specific operations via  https://issues.apache.org/jira/browse/HDDS-6562 , I am a +1 with the current proposal.

Pls resolve the conflicts with the trunk and I will merge it.

Thank you.

**Pull request merged**
