### PR TITLE
HDDS-8325. Consolidate and refine RocksDB metrics of services

### PR DESCRIPTION
**Pull request by ChenSammi**
https://issues.apache.org/jira/browse/HDDS-8325

## How was this patch tested?
1.
manual test the patch by checking the /jmx and /prom output of each service.  

Before the patch, for every rocksdb instance, there will be two metrics group in jmx, for example, SCM will have these two metrics group, 
```
"name" : "Hadoop:service=StorageContainerManager,name=Rocksdb_scm.db"
"name" : "Hadoop:service=Ozone,name=RocksDbStore,dbName=scm.db" 
```
After the patch, SCM will have one metrics group for rocksdb, 
```
"name" : "Hadoop:service=StorageContainerManager,name=Rocksdb_scm.db"
```
2.  blob_db related rocksdb metrics are  filtered.  Test by search with keyword BLOB_DB in /jmx and /prom output. 
3.  "estimated key count" in SCMMetadataStoreMetrics are consolidated. 

Before patch, 

image

After patch 
image

### CODE REVIEW

**Comment by ChenSammi** [comment]
The findbug issue is irrelevant.  File TestOzoneBlockTokenIdentifier is not updated in this patch.

**Comment by ChenSammi** [comment]
Hi @symious， could you help to review this patch at your convenient time？

**Comment by kerneltime** [comment]
cc @tanvipenumudy can you please take a look as well?

**Comment by symious** [comment]
LGTM.

I see the name of the metric is "Hadoop:service=StorageContainerManager,name=Rocksdb_scm.db", does that mean the metrics only have SCM db's metrics?

**Comment by ChenSammi** [comment]
> metrics

Yes, "Hadoop:service=StorageContainerManager,name=Rocksdb_scm.db" will have all exposed rocksdb metrics for SCM DB.

**Review by symious — APPROVED** [review]

**Comment by adoroszlai** [comment]
> The findbug issue is irrelevant. File TestOzoneBlockTokenIdentifier is not updated in this patch.

I don't understand why this findbugs issue is not flagged on other commits and PRs.  Fixing it in #4517.

**Comment by ChenSammi** [comment]
Thanks @symious and @tanvipenumudy for the code review.

**Pull request merged**
