### PR TITLE
HDDS-7536. Remove unused dependency declarations

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Some dependency declarations in Ozone root POM's `dependencyManagement` are leftover from Hadoop, unused, and can be removed.

https://issues.apache.org/jira/browse/HDDS-7536

## How was this patch tested?

No added or removed dependencies, verified by _dependency_ check in CI.

Also verified that dependency tree has not changed.  The only difference between Maven's output from `master` and the patch is in the Reactor Summary (time required to build each sub-module):

```
$ git checkout master
$ mvn -Dorg.slf4j.simpleLogger.showDateTime=false -B --no-transfer-progress dependency:tree > dep.master
$ git checkout HDDS-7536
$ mvn -Dorg.slf4j.simpleLogger.showDateTime=false -B --no-transfer-progress dependency:tree > dep.HDDS-7536
$ diff -uw dep.master dep.HDDS-7536
--- dep.master	2022-11-25 18:14:37.836905281 +0100
+++ dep.HDDS-7536	2022-11-25 18:14:20.081183954 +0100
@@ -5085,52 +5085,52 @@
 [INFO] ------------------------------------------------------------------------
 [INFO] Reactor Summary for Apache Ozone Main 1.3.0-SNAPSHOT:
 [INFO] 
-[INFO] Apache Ozone Main .................................. SUCCESS [  0.214 s]
-[INFO] Apache Ozone HDDS .................................. SUCCESS [  0.230 s]
+[INFO] Apache Ozone Main .................................. SUCCESS [  0.194 s]
+[INFO] Apache Ozone HDDS .................................. SUCCESS [  0.218 s]
...
```

Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3535439077

### CODE REVIEW

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by adoroszlai** [comment]
@jojochuang would you like to take a look?

**Review by jojochuang — APPROVED** [review]
LGTM. Although initially I thought you wanted to remove unused but declared dependencies in each modules. (Found a lot more when I ran mvn dependency:analysis tool)

**Comment by adoroszlai** [comment]
Thanks @ayushtkn, @jojochuang for the review.

> I thought you wanted to remove unused but declared dependencies in each modules

Yeah, that's another task.  We need to be more careful there, as some dependencies are only used at runtime e.g. when using Hadoop classes.

**Pull request merged**
