### PR TITLE
HDDS-11158. Improve Pipelines page UI

### PR DESCRIPTION
**Pull request by devabhishekpal**
## What changes were proposed in this pull request?
Improve Pipelines page UI.

Please describe your PR in detail:
* This PR adds a new Pipelines Page with improved layout and design.
* The new page would help to eventually improve the overall look and feel for Recon
* Currently the page is disabled to the user so as to not affect any existing functionality

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-11158

## How was this patch tested?
Patch was tested manually
Screenshot 2024-09-06 at 18 36 09
Screenshot 2024-09-06 at 18 36 31
Screenshot 2024-09-06 at 18 36 50
Screenshot 2024-09-06 at 18 37 40
Screenshot 2024-09-06 at 18 37 50

### CODE REVIEW

**Review by devmadhuu — COMMENTED** [review]
Thanks @devabhishekpal for the patch. Mostly looks good, but have few nits:

1. Please refrain PR description from copy paste from other PR. Write this manually as it is a very important part of PR and for reviewer who is reviewing the PR. Pls correct the PR description in detail.
2. This pipeline component handles multiple responsibilities, including API requests, table rendering, state management etc. Consider breaking the component into smaller, more focused components, such as:

- PipelinesTable: Handles table rendering.

- PipelinesSearch: Handles search functionality.

- usePipelinesData: A custom hook to encapsulate data fetching.

**Comment by devabhishekpal** [comment]
So the main reason this hasn't been broken down is because the state needs to be shared, and state can only go one way.
Even though we can have workarounds to share the state from child to parents, this is against the React code practices.
If we add something like Redux to share state, we can break this logic down to individual components.

For the dividing of data I think this is a good idea to have hook for each component.
However we need to rethink the logic for **autoReload**
AutoReload accepts a function/loader which it will call in intervals.
Currently this function is the function that we use to fetch data `loadData()` in this case.

But hooks can only be called in the component level and cannot be wrapped inside functions.
Hence we cannot do:
```
new AutoReloadHelper(usePipelinesData());
```

I'll think of a better implementation for AutoReloadHelper.

These two points are the major reason the current code is complex and is not broken up into components.
I had a few cleanup points as well which I wanted to tackle in the next phase by adding a state store like Redux to allow more pluggable components rather than having all logic in same place.

For the time being since we cannot avoid this, could you help take another look and let me know your inputs for other things?
Thanks

**Comment by devabhishekpal** [comment]
Hi @devmadhuu, I shifted the Table related logic to separate files for this PR.
Could you take another look?
For the others please refer to https://github.com/apache/ozone/pull/7171#issuecomment-2341729481 for reason.

**Review by ArafatKhan2198 — APPROVED** [review]
Thanks for the patch @devabhishekpal 
Changes LGTM +1

**Comment by ArafatKhan2198** [comment]
Thanks for the patch @devabhishekpal 
Thanks @devmadhuu for the review.

**Pull request merged**
