### PR TITLE
HDDS-6092. commitKey() to upload file checksum to OM.

### PR DESCRIPTION
**Pull request by jojochuang**
## What changes were proposed in this pull request?
When KeyOutputStream is closed, it sends a request to OM to commit the final change. Compute the file checksum at this point so that it can be uploaded to OM and be persisted.

The serialization of the KeyArgs is not yet implemented. That'll be completed in a follow-up jira.

## What is the link to the Apache JIRA
HDDS-6092

## How was this patch tested?

Existing UT

### CODE REVIEW

**Comment by ChenSammi** [comment]
Hey @jojochuang, could you rebase this PR?  I can help with the review.

**Comment by jojochuang** [comment]
This re-run passed precommit check
https://github.com/jojochuang/hadoop-ozone/actions/runs/2506622668

**Comment by JacksonYao287** [comment]
@jojochuang thanks for this patch , could you proceed this patch?

**Comment by kerneltime** [comment]
@jojochuang does this PR need to be revisited?

**Comment by swamirishi** [comment]
@jojochuang Is this PR still relevant?

**Pull request closed without merging**
