### PR TITLE
HDDS-4317. Copy UserVolumeInfo to PersistedUserVolumeInfo in interface-storage

### PR DESCRIPTION
**Pull request by amaliujia**
## What changes were proposed in this pull request?

Copy UserVolumeInfo to PersistedUserVolumeInfo in interface-storage

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4317

## How was this patch tested?

UT

### CODE REVIEW

**Comment by amaliujia** [comment]
R: @elek Can you take a look please?

BTW,  the next PR should be the last PR because of the complicated dependency issue. For all left migration, I will have to finish them all at once to make `interface-storage` only depends on a few (maybe just one) dependency so all other module can depend on  `interface-storage` when there is a need.

**Comment by amaliujia** [comment]
@elek friendly ping on this PR~

**Review by elek — APPROVED** [review]
+1 Thanks the patch @amaliujia 

(((Sorry for the late review, I was offline during the last 3 weeks, but coming back.)))

**Comment by amaliujia** [comment]
@elek   Thank you! and no problem!

**Pull request merged**
