### PR TITLE
HDDS-5327. EC: WritableEcContainerProvider should dynamically adjust the open container groups.

### PR DESCRIPTION
**Pull request by guihecheng**
## What changes were proposed in this pull request?

WritableEcContainerProvider should dynamically adjust the open container groups.
More details in the JIRA below.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-5327

## How was this patch tested?

Manual test for now for the number of open/total containers, for details please refer to:
https://docs.google.com/document/d/1drb7H0fAMrepMNkEFYZdMWpuRrAecRD-OSN0GVebgZM/edit?usp=sharing

### CODE REVIEW

**Comment by guihecheng** [comment]
Hi @sodonnel , I've got a solution for reviewing, but we could discuss about the details or other possible ways.

**Comment by guihecheng** [comment]
Thanks @sodonnel for your time to take a look at this, this PR is just a possible proposal for discussing, and we need more concerns on some of the problems.

It seems that there is another possible way proposed, and I've got some doubts below.

> I read through the doc and the change here, and I am not sure tracking space is the correct way to solve this. I know that EC files should be large, but they will not always be. Also a large cluster does not always need a lot of EC pipelines open. 

Well, I agree that we don't always need a lot of pipelines open, especially the IO load is low, but we need more often on large loads, because a larger cluster tends to serve larger loads. Assume EC 3:2, for 1 cluster of 100 nodes I think we may often need more open pipelines than a cluster of 5 nodes so as to utilize more DNs to carry IO loads(I've got a small test on a cluster of 30 DNs during the first discussion under the JIRA, more pipelines benefits performance before we drain the client bandwidth).
And we don't have to worry about too many pipelines, the original code has a minimum for open pipelines to bound the number of pipelines, and it is still there, only with larger value for a larger cluster.

> Sometimes, the main load may be from reads, or there is some rarely used EC policy (eg a tiny number of writes are using EC-3-2). That is why I think the "block allocation rate" is the best way to gauge the number of pipelines we need.

Actually EC read is often slower than replicated read, so EC tends to serve large cold data that is rarely read, hot data is often cached or converted to 2-way/3-way replicated. And we tends to use only a few EC policies in a single cluster.

> If we start with some sensible, but configurable minimum and some upper bound based on the registered nodes.

Sure, upper bound should be related to registered nodes.
But what is a "sensible" minimum in your mind then? Any possible contributing factors like the number of nodes in cluster, client bandwidth, or else?

> Then we keep track of the block allocation requests per time period in the ECWritableContainerProvider and per EC policy. We can guess the time it takes for a client to write a full block - it will always be approximate. We don't know how much of the block will be filled, or if the writer is a slow writer streaming events, or a fast writer. We know the max MB they can write, as it will be the `blockSize * Required_Nodes_For_EC_Policy`, for 6-3, that will be `256 * 9 = 2304MB`. The data is written mostly serially, so guess 150MB/s, it will take about 15 seconds to write that block. We we scale that number back by some factor as not all blocks will be filled. Eg assume it is 50% of that.
> 

Here I disagrees that we should use an experience-based value like "150MB/s" to do estimation, because it depends largely on the hardware we use, e.g. 10GE NIC would outperforms much than 1GE ones, and we have even faster cards(25GE, 40GE). And you could imagine that different disks will contribute to throughput in a similar way, even we don't tend to use SSDs for EC.
Other factors like client concurrency, other co-existing services sharing the resource of the client, complex network topology involves switches and racks all contributes to the IO speed.

> If we are seeing 10 block requests per second for an EC policy, and it takes 15 seconds to write the full block, perhaps we need 10 * 15 = 150 pipelines, or we can scale that by `block_fill_factor`. If the load drops to 1 request per second, we only need 10.
> 
> The other thing we need to consider, is that Ratis pipelines can have many open containers on a single pipeline, and each container is constrained to a single disk. An EC pipleline only has a single container and hence a single disk on a DN. So we need to consider the number of disks on the DNs as well as the number of nodes.

Here I raised the point in the doc that, we need to consider at least Disks and Network at the same time for a single DN, because performance of a single DN is bounded largely on these 2 factors at the same time, but ozone don't collect info on NICs and most storage systems doesn't.
On the ozone SCM side, most placement polices only considers nodes and let DN itself manages the disks.
So let's start with a configured limit as Ratis does, later we could introduces more calculation-based, reasonable values. 

> I am not sure how fine grained we would need to track the request rate, eg per second, per 10 seconds, per minute. Or should we have something like the Linux top command were it has the 1, 5 and 15 minute average, and if we did have that, how would we use it?

Yeah, exactly, there's hardly any rationale to track the request rate as a hint for resource allocation, right? 
Usually we only have request rates just as monitor metrics to let us understand the load of the system.

> I feel the existing close logic should handle containers filling OK without having to worry about it in the WriteableContainer provider. The DN triggers the close at some percentage full, expecting more blocks will continue to be written. For EC containers the problem is even less as the blocks are spread across the replicas more than with Ratis.

I agree with this point, and I don't touch the close logic in the PR, the allocatedSpace is only a hint for pre-allocating new pipelines, we don't force close the pipeline/container.

**Comment by sodonnel** [comment]
The formula I was suggesting is only a first guess. A lot of things can influence what the write speed will be, but the limiting factor is almost certainly the disk speed, rather than NIC speed. The NIC's will generally be much faster than the sustained disk speed.

We also cannot make broad assumptions such as "ec is only for cold data" or "ec will always be large files". People will do all sort of things we cannot expect. With modern hardware, it is reasonable on HDFS to have most data be EC provided the blocks are not small, and Ozone will likely be the same.

The number of open pipelines really should be a function of the write load, and the only was I can see SCM monitor that is by the rate of block requests. If the write load is very small, it doesn't matter how many pipelines are open - even one will do. We ideally want the containers to close after reaching their size limit relatively quickly. We also don't want to end up with 100 containers each with one block in them for a very slow write rate, as that could result in many small containers over time and currently we don't have a way to merge them.

I guess the space tracking is one way to track the allocation rate, but have a suspicion simply tracking allocation rate would be more accurate, even though we cannot be sure how long it will take to write the given block.

**Comment by guihecheng** [comment]
Thanks for your reply @sodonnel , so generally I'd say that the PR is using one way of tracking the "block allocation rate"
or "load", that is the allocated space, it is not accurate, but enough to be used as a hint for new pipelines.
This is a way that I could think of which has a simple and straight-forward method to define the 'trigger' to allocate new pipelines -- "The container is potentially full".

> The formula I was suggesting is only a first guess. A lot of things can influence what the write speed will be, but the limiting factor is almost certainly the disk speed, rather than NIC speed. The NIC's will generally be much faster than the sustained disk speed.

Here I disagrees that the NIC speed is not a limit, especially for EC, the client NIC speed is usually a bottleneck since a client has to transfer data concurrently to many DNs(think of EC 10:4, not just 3:2).
For the Ratis case, replication is done by the Ratis Leader to the Ratis Follower so Ratis uses inter-DN network bandwidth, but EC writes use purely the client output bandwidth.
Actually I've hitted the NIC speed limit of a 10GE NIC with an experimental Ozone deployment of only 30 simulated DNs in 3 physical servers, testing a load of 10 concurrent writes of 10 8GB files.

So if there are more convincing formula or calculation methods, you could raise it for discussion.

> We also cannot make broad assumptions such as "ec is only for cold data" or "ec will always be large files". People will do all sort of things we cannot expect. With modern hardware, it is reasonable on HDFS to have most data be EC provided the blocks are not small, and Ozone will likely be the same.

Well, this is only an observation that leads me to the idea of "tracking block allocation rate with allocated space", but it doesn't mean that it only works for "cold", "small" files. It could serve small files with the existing bound for open pipelines.
I mean even there are pure small files, we are bounded on the number of open pipelines.
And small files will get small number of pre-allocated blocks when they are created(We pre-allocate at most 64 blocks for big files, and at least 1 block for small files), so there won't be too much more "block allocated requests" or "loads".
I could do further tests on such scenarios with this approach.

> The number of open pipelines really should be a function of the write load, and the only was I can see SCM monitor that is by the rate of block requests. If the write load is very small, it doesn't matter how many pipelines are open - even one will do. We ideally want the containers to close after reaching their size limit relatively quickly. We also don't want to end up with 100 containers each with one block in them for a very slow write rate, as that could result in many small containers over time and currently we don't have a way to merge them.

Well, I can't agree more that we should keep the number of open containers under reasonable limit and we don't have too many small containers.

But I think we don't have to worry so much about that, Ozone and HDFS are long-running systems as backends for big data processing, we have large number of HDFS clusters busy running with all kinds of loads in our production environment.
So containers will be closed at last even we have all small writes, they will reach their size limit finally unless they are force closed due to other unpredictable events other than container full.

> I guess the space tracking is one way to track the allocation rate, but have a suspicion simply tracking allocation rate would be more accurate, even though we cannot be sure how long it will take to write the given block.

Yes, exactly, space tracking is similar to allocation rate tracking.
If you are suggesting other more accurate tracking approaches with certain explanations, I'm free to discuss.

At last, believe me, how long it takes to write the given block is never a problem anyone could easily answer.
We are doing all kinds of performance optimizations from time to time, right? You may got a bounded estimation today, but it is not guaranteed to apply tomorrow.

**Comment by guihecheng** [comment]
Updated with tests on small file writes in the doc together with the large file writes.
cc @sodonnel

**Pull request closed without merging**
